import GebLean.PolyBridge.WEquiv
import GebLean.Ramified.Algebras

/-!
# The free algebra on the vendored slice `W`-type

A second realization of the free algebra of a free-algebra signature
(`GebLean/Ramified/AlgSig.lean`), on the vendored `geb-mathlib` slice
`W`-type (`Geb.Mathlib.Data.PFunctor.Slice.W`) rather than this
development's `PolyFix`. `FreeAlg' A` is the fiber of
`(toSlice A.polyEndo).W` over the single index `PUnit.unit`
(`GebLean/PolyBridge/Slice.lean`); its generic constructor `FreeAlg'.mk` is
native, via the slice `W`-type's own constructor `SlicePFunctor.W.mk`, and
its recurrence `FreeAlg'.recurse` is a paramorphism realized natively by the
slice eliminator `SlicePFunctor.W.elim`, tupling each recursive result with
the reconstructed subterm so that the step functions see both, as the
legacy `FreeAlg.recurse` does. The bridge equivalence `freeAlgSliceEquiv`
(`GebLean/PolyBridge/WEquiv.lean`'s `polyFixSliceEquiv`, instantiated at the
one-sort domain) identifies `FreeAlg' A` with the legacy `FreeAlg A`, so the
numeric carrier of `natAlgSig` transports along it.

## Main definitions

* `FreeAlg'` — the free algebra on the slice `W`-type: the fiber of
  `(toSlice A.polyEndo).W` over `PUnit.unit`.
* `FreeAlg'.mk` — the generic constructor, native via `SlicePFunctor.W.mk`.
* `FreeAlg'.tupleFold` — the tupling fold underlying `FreeAlg'.recurse`: a
  `SlicePFunctor.W.elim` into `C × FreeAlg' A`, pairing each step's result
  with the reconstructed subterm.
* `FreeAlg'.recurse` — the recurrence over `FreeAlg'`, a paramorphism
  realized natively by `FreeAlg'.tupleFold`.
* `freeAlgSliceEquiv` — the bridge equivalence `FreeAlg' A ≃ FreeAlg A`,
  instantiating `polyFixSliceEquiv` at the one-sort domain.
* `natToFreeAlg'`, `freeAlgToNat'` — the numeric reading of the standard
  carrier `FreeAlg' natAlgSig`, native via `FreeAlg'.mk`/`FreeAlg'.recurse`.
* `natFreeAlgEquiv'` — the numeric reading packaged as a computable
  equivalence `FreeAlg' natAlgSig ≃ ℕ`, transported through
  `freeAlgSliceEquiv` from the legacy `natFreeAlgEquiv`.

## Main statements

* `FreeAlg'.tupleFold_snd` — the tupling fold's reconstructed subterm is the
  original subtree.
* `FreeAlg'.recurse_mk` — the reduction rule of the free-algebra recurrence
  at a constructor node.
* `freeAlgSliceEquiv_symm_mk`, `freeAlgSliceEquiv_mk` — `mk`-naturality
  across `freeAlgSliceEquiv`, in each direction.
* `freeAlgToNat'_natToFreeAlg'` — the numeric reading is a left inverse of
  the encoding.
* `freeAlgSliceEquiv_natToFreeAlg'`, `natFreeAlgEquiv'_natToFreeAlg'` — the
  native numeral encoding agrees with the legacy one across the bridge, and
  with the transported equivalence `natFreeAlgEquiv'`.
* `natFreeAlgEquiv'_slice` — `natFreeAlgEquiv'` is the composite of
  `freeAlgSliceEquiv` with the legacy `natFreeAlgEquiv`.

## References

The free algebra generated by a signature and its recurrence transcribe D.
Leivant, "Ramified recurrence and computational complexity III: Higher type
recurrence and elementary complexity", Annals of Pure and Applied Logic 96
(1999) 209-229, DOI `10.1016/S0168-0072(98)00040-2`, section 2.1.

## Tags

ramified recurrence, free algebra, W-type, paramorphism, polynomial functor
-/

namespace GebLean.Ramified.Polynomial

open GebLean.Ramified GebLean.PolyBridge

/-- The free algebra over `A`, realized on the vendored slice `W`-type: the
fiber of `(toSlice A.polyEndo).W` over the single index `PUnit.unit`. A
second realization of `FreeAlg A` (`GebLean/Ramified/AlgSig.lean`), related
to it by `freeAlgSliceEquiv`. -/
def FreeAlg' (A : AlgSig) : Type :=
  { w : (toSlice A.polyEndo).W // SlicePFunctor.wIndex (toSlice A.polyEndo) w = PUnit.unit }

/-- The generic constructor of `FreeAlg'`: a constructor label `b` together
with its subterms, native via the slice `W`-type's constructor
`SlicePFunctor.W.mk`. Every compatibility side condition is discharged by
`Subsingleton.elim`, since the single index type `PUnit` is a subsingleton. -/
def FreeAlg'.mk {A : AlgSig} (b : A.B) (subterms : Fin (A.ar b) → FreeAlg' A) : FreeAlg' A :=
  ⟨SlicePFunctor.W.mk ⟨⟨⟨PUnit.unit, b⟩, fun e => (subterms e).1⟩, Subsingleton.elim _ _⟩,
    Subsingleton.elim _ _⟩

/-- The tupling fold underlying `FreeAlg'.recurse`: a `SlicePFunctor.W.elim`
into `C × FreeAlg' A` at a fixed parameter `p`, whose algebra applies the
step function `g` to the parameter, the reconstructed subterms (the `.2`
components of the recursive tupled results), and the recursive results
themselves (the `.1` components), while independently reconstructing the
subterm via `FreeAlg'.mk` in the `.2` component. The pairing is what lets a
non-dependent fold (`SlicePFunctor.W.elim` is a catamorphism) realize a
paramorphism, whose step functions see the subterms as well as the
recursive results. -/
def FreeAlg'.tupleFold {A : AlgSig} {P C : Type}
    (g : (b : A.B) → P → (Fin (A.ar b) → FreeAlg' A) → (Fin (A.ar b) → C) → C)
    (p : P) : FreeAlg' A → C × FreeAlg' A :=
  fun t =>
    SlicePFunctor.W.elim (toSlice A.polyEndo) (C × FreeAlg' A) (fun _ => PUnit.unit)
      (fun node =>
        (g node.1.1.2 p (fun e => (node.1.2 e).2) (fun e => (node.1.2 e).1),
          FreeAlg'.mk node.1.1.2 (fun e => (node.1.2 e).2)))
      (Subsingleton.elim _ _)
      t.1

/-- The recurrence over `FreeAlg'` (Leivant III section 2.1, eq. (1)): one
step function per constructor label, seeing the parameter, the subterms of
the recurrence argument, and the recursive results. A paramorphism, native
via the tupling fold `FreeAlg'.tupleFold`, mirroring the legacy
`FreeAlg.recurse` (`GebLean/Ramified/AlgSig.lean`). -/
def FreeAlg'.recurse {A : AlgSig} {P C : Type}
    (g : (b : A.B) → P → (Fin (A.ar b) → FreeAlg' A) → (Fin (A.ar b) → C) → C) :
    P → FreeAlg' A → C :=
  fun p => Prod.fst ∘ FreeAlg'.tupleFold g p

/-- The tupling fold's reconstructed subterm (the `.2` component) is the
original subtree, for every parameter. By `SlicePFunctor.W.induction`: the
fold re-wraps each subtree through `FreeAlg'.mk`, so this is not
definitional. -/
theorem FreeAlg'.tupleFold_snd {A : AlgSig} {P C : Type}
    (g : (b : A.B) → P → (Fin (A.ar b) → FreeAlg' A) → (Fin (A.ar b) → C) → C)
    (p : P) (t : FreeAlg' A) : (FreeAlg'.tupleFold g p t).2 = t := by
  refine Subtype.ext ?_
  refine SlicePFunctor.W.induction (F := toSlice A.polyEndo)
    (motive := fun w =>
      (FreeAlg'.tupleFold g p ⟨w, Subsingleton.elim _ _⟩).2.1 = w) ?_ t.1
  intro node ih
  refine congrArg SlicePFunctor.W.mk (Subtype.ext (Sigma.ext rfl (heq_of_eq ?_)))
  funext e
  exact ih e

/-- The reduction rule of the free-algebra recurrence at a constructor node
(Leivant III section 2.1, eq. (1)): `FreeAlg'.recurse g p (FreeAlg'.mk b
sub)` unfolds to the step function `g` at `b` applied to the parameter `p`,
the subterms `sub`, and the recursive results on the subterms. From
`SlicePFunctor.W.elim_mk` together with `FreeAlg'.tupleFold_snd`, which
supplies the reconstructed-subterm identity that `elim_mk` alone does not. -/
theorem FreeAlg'.recurse_mk {A : AlgSig} {P C : Type}
    (g : (b : A.B) → P → (Fin (A.ar b) → FreeAlg' A) → (Fin (A.ar b) → C) → C)
    (p : P) (b : A.B) (sub : Fin (A.ar b) → FreeAlg' A) :
    FreeAlg'.recurse g p (FreeAlg'.mk b sub)
      = g b p sub (fun e => FreeAlg'.recurse g p (sub e)) := by
  have h : (fun e => (FreeAlg'.tupleFold g p (sub e)).2) = sub :=
    funext fun e => FreeAlg'.tupleFold_snd g p (sub e)
  change g b p (fun e => (FreeAlg'.tupleFold g p (sub e)).2)
           (fun e => FreeAlg'.recurse g p (sub e)) = _
  rw [h]

/-- The bridge equivalence between `FreeAlg' A` and the legacy `FreeAlg A`:
`polyFixSliceEquiv` (`GebLean/PolyBridge/WEquiv.lean`), instantiated at
`A.polyEndo` and the single index `PUnit.unit`, then inverted so that the
declared carrier `FreeAlg'` reads as the source. Typechecks by unfolding the
`def`s `FreeAlg` and `FreeAlg'`; `Equiv.symm` swaps no data, so no `Eq.rec`
transport is introduced. -/
def freeAlgSliceEquiv (A : AlgSig) : FreeAlg' A ≃ FreeAlg A :=
  (polyFixSliceEquiv A.polyEndo PUnit.unit).symm

/-- The inverse of `freeAlgSliceEquiv` carries a legacy `FreeAlg.mk` node to
the corresponding `FreeAlg'.mk` node whose subterms are the images of the
original subterms: `mk`-naturality in the direction that unfolds
definitionally, from `polyFixSliceEquiv_mk`. -/
theorem freeAlgSliceEquiv_symm_mk (A : AlgSig) (b : A.B) (subterms : Fin (A.ar b) → FreeAlg A) :
    (freeAlgSliceEquiv A).symm (FreeAlg.mk b subterms) =
      FreeAlg'.mk b (fun e => (freeAlgSliceEquiv A).symm (subterms e)) :=
  Subtype.ext (congrArg Subtype.val
    (polyFixSliceEquiv_mk A.polyEndo PUnit.unit b subterms))

/-- `freeAlgSliceEquiv` carries a `FreeAlg'.mk` node to the corresponding
legacy `FreeAlg.mk` node whose subterms are the images of the original
subterms: `mk`-naturality across the equiv, derived from
`freeAlgSliceEquiv_symm_mk` by the equivalence laws. -/
theorem freeAlgSliceEquiv_mk (A : AlgSig) (b : A.B) (sub : Fin (A.ar b) → FreeAlg' A) :
    freeAlgSliceEquiv A (FreeAlg'.mk b sub) =
      FreeAlg.mk b (fun e => freeAlgSliceEquiv A (sub e)) := by
  have h := freeAlgSliceEquiv_symm_mk A b (fun e => freeAlgSliceEquiv A (sub e))
  simp only [Equiv.symm_apply_apply] at h
  exact ((freeAlgSliceEquiv A).symm_apply_eq.mp h).symm

/-- A natural number as an element of the standard carrier
`FreeAlg' natAlgSig`, native via `FreeAlg'.mk`: `0` is the nullary
constructor and `n + 1` the unary constructor applied to `n`. Mirrors the
legacy `natToFreeAlg` (`GebLean/Ramified/AlgSig.lean`). -/
def natToFreeAlg' : Nat → FreeAlg' natAlgSig
  | 0 => FreeAlg'.mk false finZeroElim
  | n + 1 => FreeAlg'.mk true (fun _ => natToFreeAlg' n)

/-- An element of the standard carrier `FreeAlg' natAlgSig` as the natural
number counting its unary constructors, native via `FreeAlg'.recurse`.
Mirrors the legacy `freeAlgToNat` (`GebLean/Ramified/AlgSig.lean`). -/
def freeAlgToNat' (t : FreeAlg' natAlgSig) : Nat :=
  FreeAlg'.recurse (A := natAlgSig) (P := Unit)
    (fun b _ _sub rec => match b with
      | false => 0
      | true => rec ⟨0, Nat.zero_lt_one⟩ + 1) () t

/-- The numeric reading of the standard `natAlgSig` carrier is a left
inverse of the encoding, exercising the native fold `FreeAlg'.recurse`
through its reduction rule `FreeAlg'.recurse_mk`. -/
@[simp] theorem freeAlgToNat'_natToFreeAlg' (n : Nat) :
    freeAlgToNat' (natToFreeAlg' n) = n := by
  induction n with
  | zero =>
    simp only [natToFreeAlg', freeAlgToNat', FreeAlg'.recurse_mk]
  | succ n ih =>
    simp only [natToFreeAlg', freeAlgToNat', FreeAlg'.recurse_mk] at ih ⊢
    exact congrArg (· + 1) ih

/-- `freeAlgSliceEquiv` carries the native encoding `natToFreeAlg'` to the
legacy `natToFreeAlg`, by induction on the numeral using `freeAlgSliceEquiv_mk`. -/
@[simp] theorem freeAlgSliceEquiv_natToFreeAlg' (n : Nat) :
    freeAlgSliceEquiv natAlgSig (natToFreeAlg' n) = natToFreeAlg n := by
  induction n with
  | zero =>
    change freeAlgSliceEquiv natAlgSig (FreeAlg'.mk false finZeroElim) = natToFreeAlg 0
    rw [freeAlgSliceEquiv_mk]
    congr 1
    funext e
    exact e.elim0
  | succ n ih =>
    change freeAlgSliceEquiv natAlgSig (FreeAlg'.mk true (fun _ => natToFreeAlg' n))
      = natToFreeAlg (n + 1)
    rw [freeAlgSliceEquiv_mk]
    exact congrArg (FreeAlg.mk true) (funext fun _ => ih)

/-- The numeric reading of the standard `FreeAlg' natAlgSig` carrier as a
computable equivalence `FreeAlg' natAlgSig ≃ ℕ`, transporting the legacy
`natFreeAlgEquiv` (`GebLean/Ramified/Algebras.lean`) through the bridge
equivalence `freeAlgSliceEquiv`. -/
def natFreeAlgEquiv' : FreeAlg' natAlgSig ≃ ℕ :=
  (freeAlgSliceEquiv natAlgSig).trans natFreeAlgEquiv

/-- The transported equivalence `natFreeAlgEquiv'` is definitionally the
composite of the bridge equivalence `freeAlgSliceEquiv` with the legacy
`natFreeAlgEquiv`; names the fact for the `objToNat` correspondence. -/
theorem natFreeAlgEquiv'_slice :
    natFreeAlgEquiv' = (freeAlgSliceEquiv natAlgSig).trans natFreeAlgEquiv := rfl

/-- The transported equivalence `natFreeAlgEquiv'` agrees with the native
encoding `natToFreeAlg'` on the naturals, by `freeAlgSliceEquiv_natToFreeAlg'`
and the legacy round trip `freeAlgToNat_natToFreeAlg`. -/
@[simp] theorem natFreeAlgEquiv'_natToFreeAlg' (n : Nat) :
    natFreeAlgEquiv' (natToFreeAlg' n) = n := by
  simp [natFreeAlgEquiv']

end GebLean.Ramified.Polynomial
