name: markdown-lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd
        with:
          globs: '**/*.md'
          config: '.markdownlint-cli2.jsonc'
