import GebLeanTests.AcyclicCat
import GebLeanTests.Basic
import GebLeanTests.LayeredEquivalence
import GebLeanTests.TestTreeCalcMeta
import GebLeanTests.TestTreeCalcPrograms
import GebLeanTests.TestTreeCalcReduction
