import GebLeanTests.AcyclicCat
import GebLeanTests.Basic
import GebLeanTests.LawvereER
import GebLeanTests.LayeredEquivalence
import GebLeanTests.TestEqualizerCompletion
import GebLeanTests.TestTreeCalcMeta
import GebLeanTests.TestTreeCalcPrograms
import GebLeanTests.TestTreeCalcReduction
