name = "geb-lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["GebLean"]
testDriver = "GebLeanTests"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
pp.proofs = false
pp.showLetValues = false
pp.universes = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
backward.isDefEq.respectTransparency = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "GebLean"

# Test library
[[lean_lib]]
name = "GebLeanTests"
roots = ["GebLeanTests"]

[lean_lib.leanOptions]
linter.hashCommand = false
