name = "geb-lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["GebLean"]
testDriver = "test"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
pp.proofs = false
pp.showLetValues = false
pp.universes = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "GebLean"

# Test library
[[lean_lib]]
name = "test"
roots = ["test"]

[lean_lib.leanOptions]
linter.hashCommand = false
