import GebLean.Utilities.ComputableLimits
import Mathlib.Logic.Relation

/-!
# The Free Equalizer Completion

Defines the free equalizer completion of a category
with finite products, following the construction of
Pitts as reported in Bunge & Carboni, "The Symmetric
Topos" (JPAA 105, 1995, pp. 237--238).

Objects are coreflexive pairs in the base category.
Morphisms are equivalence classes of premorphisms
under the equivalence relation generated by the
coreflexive structure.
-/

namespace GebLean

open CategoryTheory

universe v u

variable (C : Type u) [Category.{v} C]

/-! ## Objects of the free equalizer completion -/

section CoreflexivePairObj

/--
An object of the free equalizer completion of C.
This consists of two objects `src` and `tgt` from C
together with two parallel morphisms `left` and
`right` from `src` to `tgt`, and a common retraction
`retract` from `tgt` to `src` satisfying
`left ≫ retract = 𝟙 src` and
`right ≫ retract = 𝟙 src`.
The object represents the formal equalizer of `left`
and `right`.
-/
@[ext]
structure CoreflexivePairObj where
  /-- The source object of the coreflexive pair. -/
  src : C
  /-- The target object of the coreflexive pair. -/
  tgt : C
  /-- The first (left) morphism of the pair. -/
  left : src ⟶ tgt
  /-- The second (right) morphism of the pair. -/
  right : src ⟶ tgt
  /-- The common retraction of the pair. -/
  retract : tgt ⟶ src
  /-- Left morphism followed by retraction is the
  identity. -/
  retract_left : left ≫ retract = 𝟙 src
  /-- Right morphism followed by retraction is the
  identity. -/
  retract_right : right ≫ retract = 𝟙 src

variable {C}

/--
Construct an object of `CoreflexivePairObj C` from
source, target, two parallel morphisms, a retraction,
and the two retraction proofs.
-/
@[simp]
def cpObjMk
    {src tgt : C}
    (left right : src ⟶ tgt)
    (retract : tgt ⟶ src)
    (rl : left ≫ retract = 𝟙 src)
    (rr : right ≫ retract = 𝟙 src)
    : CoreflexivePairObj C :=
  ⟨src, tgt, left, right, retract, rl, rr⟩

/-- Extract the source object from a coreflexive
pair. -/
@[simp]
def cpSrc
    (P : CoreflexivePairObj C) : C :=
  P.src

/-- Extract the target object from a coreflexive
pair. -/
@[simp]
def cpTgt
    (P : CoreflexivePairObj C) : C :=
  P.tgt

/-- Extract the left morphism from a coreflexive
pair. -/
@[simp]
def cpLeft
    (P : CoreflexivePairObj C)
    : cpSrc P ⟶ cpTgt P :=
  P.left

/-- Extract the right morphism from a coreflexive
pair. -/
@[simp]
def cpRight
    (P : CoreflexivePairObj C)
    : cpSrc P ⟶ cpTgt P :=
  P.right

/-- Extract the retraction from a coreflexive
pair. -/
@[simp]
def cpRetract
    (P : CoreflexivePairObj C)
    : cpTgt P ⟶ cpSrc P :=
  P.retract

@[simp]
lemma cpObjMk_src
    {src tgt : C}
    (left right : src ⟶ tgt)
    (retract : tgt ⟶ src)
    (rl : left ≫ retract = 𝟙 src)
    (rr : right ≫ retract = 𝟙 src)
    : cpSrc (cpObjMk left right retract rl rr)
      = src :=
  rfl

@[simp]
lemma cpObjMk_tgt
    {src tgt : C}
    (left right : src ⟶ tgt)
    (retract : tgt ⟶ src)
    (rl : left ≫ retract = 𝟙 src)
    (rr : right ≫ retract = 𝟙 src)
    : cpTgt (cpObjMk left right retract rl rr)
      = tgt :=
  rfl

@[simp]
lemma cpObjMk_left
    {src tgt : C}
    (left right : src ⟶ tgt)
    (retract : tgt ⟶ src)
    (rl : left ≫ retract = 𝟙 src)
    (rr : right ≫ retract = 𝟙 src)
    : cpLeft (cpObjMk left right retract rl rr)
      = left :=
  rfl

@[simp]
lemma cpObjMk_right
    {src tgt : C}
    (left right : src ⟶ tgt)
    (retract : tgt ⟶ src)
    (rl : left ≫ retract = 𝟙 src)
    (rr : right ≫ retract = 𝟙 src)
    : cpRight (cpObjMk left right retract rl rr)
      = right :=
  rfl

@[simp]
lemma cpObjMk_retract
    {src tgt : C}
    (left right : src ⟶ tgt)
    (retract : tgt ⟶ src)
    (rl : left ≫ retract = 𝟙 src)
    (rr : right ≫ retract = 𝟙 src)
    : cpRetract (cpObjMk left right retract rl rr)
      = retract :=
  rfl

/-- Reconstructing a coreflexive pair object from
its components. -/
@[simp]
lemma cpObjMk_eta
    (P : CoreflexivePairObj C)
    : cpObjMk (cpLeft P) (cpRight P) (cpRetract P)
        P.retract_left P.retract_right
      = P := by
  cases P; rfl

end CoreflexivePairObj

/-! ## Coreflexive equivalence relation -/

section CoreflexiveRelation

variable {C : Type u} [Category.{v} C]

/--
Two morphisms `f₀ f₁ : X.src ⟶ V` are one-step
related under the coreflexive structure of `X` if
there exists `h : X.tgt ⟶ V` such that
`X.left ≫ h = f₀` and `X.right ≫ h = f₁`.
-/
def CoreflexiveRelStep
    (X : CoreflexivePairObj C)
    {V : C}
    (f₀ f₁ : X.src ⟶ V) : Prop :=
  ∃ h : X.tgt ⟶ V,
    X.left ≫ h = f₀ ∧ X.right ≫ h = f₁

/--
The one-step coreflexive relation is reflexive.
The witness is `X.retract ≫ f`.
-/
theorem CoreflexiveRelStep.rfl_
    (X : CoreflexivePairObj C)
    {V : C}
    (f : X.src ⟶ V) :
    CoreflexiveRelStep X f f :=
  ⟨X.retract ≫ f,
    by rw [← Category.assoc, X.retract_left,
      Category.id_comp],
    by rw [← Category.assoc, X.retract_right,
      Category.id_comp]⟩

/--
The equivalence relation on `X.src ⟶ V` generated
by the one-step coreflexive relation of `X`.
-/
def CoreflexiveEqv
    (X : CoreflexivePairObj C)
    {V : C}
    (f₀ f₁ : X.src ⟶ V) : Prop :=
  Relation.EqvGen (CoreflexiveRelStep X) f₀ f₁

end CoreflexiveRelation

/-! ## Premorphisms -/

section Premorphism

variable {C : Type u} [Category.{v} C]

/--
A morphism `f : X.src ⟶ Y.src` is a premorphism
from `X` to `Y` if the two compositions
`f ≫ Y.left` and `f ≫ Y.right` are equivalent
under the coreflexive equivalence of `X`.
-/
def IsCPPremorphism
    (X Y : CoreflexivePairObj C)
    (f : X.src ⟶ Y.src) : Prop :=
  CoreflexiveEqv X
    (f ≫ Y.left) (f ≫ Y.right)

/--
The identity morphism `𝟙 X.src` is a premorphism
from `X` to `X`.  The witness for the one-step
relation is `𝟙 X.tgt`.
-/
theorem cpId_isPremorphism
    (X : CoreflexivePairObj C) :
    IsCPPremorphism X X (𝟙 X.src) := by
  unfold IsCPPremorphism CoreflexiveEqv
  rw [Category.id_comp, Category.id_comp]
  exact Relation.EqvGen.rel _ _
    ⟨𝟙 X.tgt,
      Category.comp_id X.left,
      Category.comp_id X.right⟩

/--
Post-composition preserves the one-step coreflexive
relation.  If `f₀` and `f₁` are one-step related
via `X`, then `f₀ ≫ g` and `f₁ ≫ g` are as well.
-/
theorem CoreflexiveRelStep_postcomp
    (X : CoreflexivePairObj C)
    {V W : C}
    {f₀ f₁ : X.src ⟶ V}
    (h : CoreflexiveRelStep X f₀ f₁)
    (g : V ⟶ W) :
    CoreflexiveRelStep X (f₀ ≫ g) (f₁ ≫ g) := by
  obtain ⟨w, hl, hr⟩ := h
  exact ⟨w ≫ g,
    by rw [← Category.assoc, hl],
    by rw [← Category.assoc, hr]⟩

/--
Post-composition preserves the generated coreflexive
equivalence relation.  If `f₀` and `f₁` are
equivalent under `X`, then `f₀ ≫ g` and `f₁ ≫ g`
are as well.
-/
theorem CoreflexiveEqv_postcomp
    (X : CoreflexivePairObj C)
    {V W : C}
    {f₀ f₁ : X.src ⟶ V}
    (h : CoreflexiveEqv X f₀ f₁)
    (g : V ⟶ W) :
    CoreflexiveEqv X (f₀ ≫ g) (f₁ ≫ g) := by
  unfold CoreflexiveEqv at h ⊢
  induction h with
  | rel _ _ hr =>
    exact Relation.EqvGen.rel _ _
      (CoreflexiveRelStep_postcomp X hr g)
  | refl _ => exact Relation.EqvGen.refl _
  | symm _ _ _ ih =>
    exact Relation.EqvGen.symm _ _ ih
  | trans _ _ _ _ _ ih1 ih2 =>
    exact Relation.EqvGen.trans _ _ _ ih1 ih2

/--
Pre-composition by a premorphism preserves the
one-step coreflexive relation.  If `a` and `b` are
one-step related under `Y`, and `f` is a premorphism
from `X` to `Y`, then `f ≫ a` and `f ≫ b` are
equivalent under `X`.
-/
theorem CoreflexiveEqv_precomp_step
    (X Y : CoreflexivePairObj C)
    {V : C}
    {a b : Y.src ⟶ V}
    (hab : CoreflexiveRelStep Y a b)
    (f : X.src ⟶ Y.src)
    (hf : IsCPPremorphism X Y f) :
    CoreflexiveEqv X (f ≫ a) (f ≫ b) := by
  obtain ⟨w, hl, hr⟩ := hab
  rw [← hl, ← hr]
  rw [← Category.assoc, ← Category.assoc]
  exact CoreflexiveEqv_postcomp X hf w

/--
Pre-composition by a premorphism preserves the
generated coreflexive equivalence relation.
If `a` and `b` are equivalent under `Y`, and `f`
is a premorphism from `X` to `Y`, then `f ≫ a`
and `f ≫ b` are equivalent under `X`.
-/
theorem CoreflexiveEqv_precomp_premorphism
    (X Y : CoreflexivePairObj C)
    {V : C}
    {a b : Y.src ⟶ V}
    (hab : CoreflexiveEqv Y a b)
    (f : X.src ⟶ Y.src)
    (hf : IsCPPremorphism X Y f) :
    CoreflexiveEqv X (f ≫ a) (f ≫ b) := by
  unfold CoreflexiveEqv at hab ⊢
  induction hab with
  | rel _ _ hr =>
    exact CoreflexiveEqv_precomp_step X Y hr f hf
  | refl _ => exact Relation.EqvGen.refl _
  | symm _ _ _ ih =>
    exact Relation.EqvGen.symm _ _ ih
  | trans _ _ _ _ _ ih1 ih2 =>
    exact Relation.EqvGen.trans _ _ _ ih1 ih2

/--
The composition of two premorphisms is a
premorphism.  Given premorphisms `f : X → Y`
and `g : Y → Z`, the composite `f ≫ g` is
a premorphism from `X` to `Z`.
-/
theorem cpComp_isPremorphism
    (X Y Z : CoreflexivePairObj C)
    (f : X.src ⟶ Y.src)
    (g : Y.src ⟶ Z.src)
    (hf : IsCPPremorphism X Y f)
    (hg : IsCPPremorphism Y Z g) :
    IsCPPremorphism X Z (f ≫ g) := by
  unfold IsCPPremorphism
  rw [Category.assoc, Category.assoc]
  exact CoreflexiveEqv_precomp_premorphism
    X Y hg f hf

/--
If `f₁` and `f₂` are equivalent under the
coreflexive structure of `X`, then for any
morphism `g : Y.src ⟶ V`, `f₁ ≫ g` and `f₂ ≫ g`
are equivalent under `X`.
This follows from `CoreflexiveEqv_postcomp`.
-/
theorem CoreflexiveEqv_comp_right
    (X : CoreflexivePairObj C)
    {V W : C}
    {f₁ f₂ : X.src ⟶ V}
    (h : CoreflexiveEqv X f₁ f₂)
    (g : V ⟶ W) :
    CoreflexiveEqv X (f₁ ≫ g) (f₂ ≫ g) :=
  CoreflexiveEqv_postcomp X h g

/--
If `g₁` and `g₂` are equivalent under the
coreflexive structure of `Y`, then for any
premorphism `f : X → Y`, `f ≫ g₁` and `f ≫ g₂`
are equivalent under `X`.
This follows from
`CoreflexiveEqv_precomp_premorphism`.
-/
theorem CoreflexiveEqv_comp_left
    (X Y : CoreflexivePairObj C)
    {V : C}
    {g₁ g₂ : Y.src ⟶ V}
    (h : CoreflexiveEqv Y g₁ g₂)
    (f : X.src ⟶ Y.src)
    (hf : IsCPPremorphism X Y f) :
    CoreflexiveEqv X (f ≫ g₁) (f ≫ g₂) :=
  CoreflexiveEqv_precomp_premorphism X Y h f hf

end Premorphism

/-! ## Quotient category structure -/

section QuotientCategory

variable {C : Type u} [Category.{v} C]

/-- The subtype of morphisms `X.src ⟶ Y.src` that
are premorphisms from `X` to `Y`. -/
def CPPreMor
    (X Y : CoreflexivePairObj C) :=
  { f : X.src ⟶ Y.src // IsCPPremorphism X Y f }

/-- The setoid on premorphisms from `X` to `Y`
induced by the coreflexive equivalence relation
on the underlying morphisms. -/
def cpPreMorSetoid
    (X Y : CoreflexivePairObj C) :
    Setoid (CPPreMor X Y) where
  r f g := CoreflexiveEqv X f.val g.val
  iseqv := {
    refl := fun f => Relation.EqvGen.refl f.val
    symm := fun h => Relation.EqvGen.symm _ _ h
    trans := fun h₁ h₂ =>
      Relation.EqvGen.trans _ _ _ h₁ h₂
  }

/-- The quotient morphism type for the free equalizer
completion: equivalence classes of premorphisms under
the coreflexive equivalence relation. -/
def CPMor
    (X Y : CoreflexivePairObj C) :=
  Quotient (cpPreMorSetoid X Y)

/-- The identity morphism in the quotient category:
the equivalence class of `𝟙 X.src`. -/
def cpId (X : CoreflexivePairObj C) :
    CPMor X X :=
  Quotient.mk (cpPreMorSetoid X X)
    ⟨𝟙 X.src, cpId_isPremorphism X⟩

/-- Composition of quotient morphisms, lifted from
composition of premorphisms via `Quotient.lift₂`.
Well-definedness follows from preservation of the
coreflexive equivalence under post-composition and
pre-composition by premorphisms. -/
def cpComp
    {X Y Z : CoreflexivePairObj C}
    (f : CPMor X Y) (g : CPMor Y Z) :
    CPMor X Z :=
  Quotient.lift₂
    (s₁ := cpPreMorSetoid X Y)
    (s₂ := cpPreMorSetoid Y Z)
    (fun f' g' =>
      Quotient.mk (cpPreMorSetoid X Z)
        ⟨f'.val ≫ g'.val,
         cpComp_isPremorphism X Y Z
           f'.val g'.val
           f'.property g'.property⟩)
    (fun f₁ g₁ f₂ g₂ hf hg => by
      apply Quotient.sound
        (s := cpPreMorSetoid X Z)
      change CoreflexiveEqv X
        (f₁.val ≫ g₁.val) (f₂.val ≫ g₂.val)
      exact Relation.EqvGen.trans _ _ _
        (CoreflexiveEqv_comp_right X hf g₁.val)
        (CoreflexiveEqv_comp_left X Y hg
          f₂.val f₂.property))
    f g

/-- Left identity: `cpComp (cpId X) f = f`. -/
theorem cpId_comp
    {X Y : CoreflexivePairObj C}
    (f : CPMor X Y) :
    cpComp (cpId X) f = f :=
  Quotient.ind
    (motive := fun f =>
      cpComp (cpId X) f = f)
    (fun f_raw => by
      change Quotient.mk _ ⟨𝟙 X.src ≫ f_raw.val,
        _⟩ = Quotient.mk _ f_raw
      congr 1
      exact Subtype.ext (Category.id_comp _))
    f

/-- Right identity: `cpComp f (cpId Y) = f`. -/
theorem cpComp_id
    {X Y : CoreflexivePairObj C}
    (f : CPMor X Y) :
    cpComp f (cpId Y) = f :=
  Quotient.ind
    (motive := fun f =>
      cpComp f (cpId Y) = f)
    (fun f_raw => by
      change Quotient.mk _ ⟨f_raw.val ≫ 𝟙 Y.src,
        _⟩ = Quotient.mk _ f_raw
      congr 1
      exact Subtype.ext (Category.comp_id _))
    f

/-- Associativity of composition in the quotient
category. -/
theorem cpComp_assoc
    {X Y Z W : CoreflexivePairObj C}
    (f : CPMor X Y)
    (g : CPMor Y Z)
    (h : CPMor Z W) :
    cpComp (cpComp f g) h =
      cpComp f (cpComp g h) :=
  Quotient.ind
    (motive := fun f =>
      ∀ (g : CPMor Y Z) (h : CPMor Z W),
        cpComp (cpComp f g) h =
          cpComp f (cpComp g h))
    (fun f_raw =>
      Quotient.ind
        (motive := fun g =>
          ∀ (h : CPMor Z W),
            cpComp (cpComp
              (Quotient.mk _ f_raw) g) h =
              cpComp (Quotient.mk _ f_raw)
                (cpComp g h))
        (fun g_raw =>
          Quotient.ind
            (motive := fun h =>
              cpComp (cpComp
                (Quotient.mk _ f_raw)
                (Quotient.mk _ g_raw)) h =
                cpComp (Quotient.mk _ f_raw)
                  (cpComp
                    (Quotient.mk _ g_raw) h))
            (fun h_raw => by
              apply congr_arg
                (Quotient.mk
                  (cpPreMorSetoid X W))
              exact Subtype.ext
                (Category.assoc _ _ _))))
    f g h

instance cpCategory :
    Category (CoreflexivePairObj C) where
  Hom := CPMor
  id := cpId
  comp := cpComp
  id_comp := cpId_comp
  comp_id := cpComp_id
  assoc := cpComp_assoc

end QuotientCategory

/-! ## Embedding functor -/

section EmbeddingFunctor

variable {C : Type u} [Category.{v} C]

/--
Embed an object of `C` as the trivial coreflexive
pair `(c, c, 𝟙, 𝟙, 𝟙)`.
-/
def cpEmbed
    (c : C) : CoreflexivePairObj C where
  src := c
  tgt := c
  left := 𝟙 c
  right := 𝟙 c
  retract := 𝟙 c
  retract_left := Category.id_comp _
  retract_right := Category.id_comp _

/--
Any morphism from a trivially-embedded object is a
premorphism.  For the trivial pair `cpEmbed c`, the
left and right morphisms are both `𝟙`, so the
premorphism condition `f ≫ 𝟙 ≈ f ≫ 𝟙` holds by
reflexivity.
-/
theorem cpEmbed_isPremorphism
    {c d : C} (f : c ⟶ d) :
    IsCPPremorphism (cpEmbed c) (cpEmbed d) f := by
  unfold IsCPPremorphism cpEmbed
  simp only [Category.comp_id]
  exact Relation.EqvGen.refl _

/--
On a trivially-embedded object, the one-step
coreflexive relation collapses to equality.
-/
theorem cpEmbed_relStep_eq
    {c V : C}
    {f g : c ⟶ V}
    (h : CoreflexiveRelStep (cpEmbed c) f g) :
    f = g := by
  obtain ⟨w, hl, hr⟩ := h
  change 𝟙 c ≫ w = f at hl
  change 𝟙 c ≫ w = g at hr
  rw [Category.id_comp] at hl hr
  rw [← hl, ← hr]

/--
On a trivially-embedded object, the coreflexive
equivalence relation coincides with equality.
-/
theorem cpEmbed_eqv_iff
    {c : C} {V : C}
    {f g : c ⟶ V} :
    CoreflexiveEqv (cpEmbed c) f g ↔ f = g := by
  constructor
  · intro h
    induction h with
    | rel _ _ hr => exact cpEmbed_relStep_eq hr
    | refl _ => rfl
    | symm _ _ _ ih => exact ih.symm
    | trans _ _ _ _ _ ih1 ih2 =>
      exact ih1.trans ih2
  · intro h
    subst h
    exact Relation.EqvGen.refl _

/--
The embedding functor `Δ : C → CoreflexivePairObj C`
that sends each object to its trivial coreflexive
pair and each morphism to its equivalence class.
-/
def cpEmbedding :
    C ⥤ CoreflexivePairObj C where
  obj := cpEmbed
  map {X Y} f :=
    Quotient.mk
      (cpPreMorSetoid (cpEmbed X) (cpEmbed Y))
      ⟨f, cpEmbed_isPremorphism f⟩
  map_id X := by
    apply Quotient.sound
      (s := cpPreMorSetoid
        (cpEmbed X) (cpEmbed X))
    exact Relation.EqvGen.refl _
  map_comp {X Y Z} f g := by
    apply Quotient.sound
      (s := cpPreMorSetoid
        (cpEmbed X) (cpEmbed Z))
    exact Relation.EqvGen.refl _

/--
The embedding functor is faithful: distinct morphisms
in `C` map to distinct morphisms in the completion.
-/
instance cpEmbedding_faithful :
    (cpEmbedding (C := C)).Faithful where
  map_injective {X Y f g} h := by
    have := Quotient.exact
      (s := cpPreMorSetoid
        (cpEmbed X) (cpEmbed Y)) h
    exact cpEmbed_eqv_iff.mp this

/--
The embedding functor is full: every morphism in the
completion between trivially-embedded objects is in
the image of the embedding.
-/
instance cpEmbedding_full :
    (cpEmbedding (C := C)).Full where
  map_surjective {X Y} f := by
    revert f
    apply Quotient.ind
    intro ⟨f_val, _⟩
    exact ⟨f_val, by
      apply Quotient.sound
        (s := cpPreMorSetoid
          (cpEmbed X) (cpEmbed Y))
      exact Relation.EqvGen.refl _⟩

end EmbeddingFunctor

end GebLean
