import GebLean.PLang.Syntax
import Mathlib.Data.Fin.Basic

/-!
# Lawvere Theory of Binary Trees

Defines the Lawvere (finite-product) theory of parameterized
binary tree objects (BTOs), analogous to the Lawvere theory
of parameterized natural numbers objects (which gives
primitive recursive arithmetic).

Objects are natural numbers `n`, representing the `n`-fold
product of the generating object `T`.

Morphisms `n → m` are `m`-tuples of primitive recursive
tree functions, each taking `n` inputs.

The morphisms are generated by:
- Projections (finite-product structure)
- `leaf` : the leaf constant (from the terminal object)
- `branch` : binary branching (`2 → 1`)
- `fold` : tree catamorphism with parameters (the universal
  property of the parameterized BTO)

The parameterized BTO structure follows the pattern of
parameterized NNOs
(https://ncatlab.org/nlab/show/natural+numbers+object#withparams):
an object `T` with morphisms `z : 1 → T` (leaf) and
`s : T × T → T` (branch), such that for any `f : A → X`
and `g : X × X → X`, there exists a unique
`φ : A × T → X` satisfying
`φ(a, z) = f(a)` and
`φ(a, s(t₁, t₂)) = g(φ(a, t₁), φ(a, t₂))`.

In the Lawvere theory, `A`, `X`, `T` are all powers of
the generating object, so `f : n → 1`, `g : (n+2) → 1`,
and `φ : (n+1) → 1`.

## References

* nLab, "Lawvere theory",
  https://ncatlab.org/nlab/show/Lawvere+theory
* nLab, "natural numbers object" (parameterized NNO),
  https://ncatlab.org/nlab/show/natural+numbers+object#withparams
-/

namespace GebLean

open CategoryTheory

universe u

/-! ## Binary tree object via polynomial machinery

The type of binary trees is the free monad of the product
polynomial (`polyProdFreeM`), evaluated at the terminal
object.  This gives the initial algebra of `X ↦ 1 + X × X`.

Constructors and the catamorphism are thin wrappers around
the `PolyFix` structure from `PolyAlg`.
-/

/-- Binary trees as the free monad of the product
polynomial at the terminal object. -/
abbrev BT : Type u :=
  PolyFreeM
    (overTerminal PUnit.{u + 1})
    polyProdType
    PUnit.unit

/-- The leaf tree (the unit `z : 1 → T` of the BTO). -/
def BT.leaf : BT.{u} :=
  PolyFix.mk PUnit.unit
    (Sum.inl ⟨PUnit.unit, rfl⟩)
    (fun e => PEmpty.elim e)

/-- A branching tree from two subtrees
(the operation `s : T × T → T` of the BTO). -/
def BT.node (l r : BT.{u}) : BT.{u} :=
  PolyFix.mk PUnit.unit
    (Sum.inr PUnit.unit)
    (fun e => match e with
      | Sum.inl _ => l
      | Sum.inr _ => r)

private def btFoldAux {α : Type u}
    (b : α) (s : α → α → α)
    {x : PUnit.{u + 1}}
    (t : PolyFix
      (polyTranslate
        (overTerminal PUnit.{u + 1})
        polyProdType) x) : α :=
  match t with
  | .mk _ (Sum.inl _) _ => b
  | .mk _ (Sum.inr _) ch =>
    s (btFoldAux b s (ch (Sum.inl PUnit.unit)))
      (btFoldAux b s (ch (Sum.inr PUnit.unit)))

/-- Catamorphism (fold) for binary trees (the universal
morphism `φ : A × T → X` of the parameterized BTO).
Given `b` for leaves and `s` for branches, folds a tree
to produce a result. -/
def BT.fold {α : Type u} (b : α) (s : α → α → α)
    (t : BT.{u}) : α :=
  btFoldAux b s t

/-! ## Morphisms of the Lawvere theory

A morphism `n → 1` is a term with `n` free variables,
built from variable references, the leaf constant, binary
branching, and fold (tree catamorphism with parameters).

Variables use de Bruijn indices: `proj i` refers to the
`i`-th input (where `i : Fin n`).

In the `fold` constructor:
- `base : BTMor1 n` gives the value at leaves, using the
  `n` context variables.
- `step : BTMor1 (n + 2)` gives the value at branches;
  variables `0` through `n - 1` are the same context,
  variable `n` is the left recursive result, and variable
  `n + 1` is the right recursive result.
- `tree : BTMor1 n` is the tree to fold over.
-/

/-- A morphism from the `n`-fold product of the generating
object to the generating object in the Lawvere theory of
binary trees. -/
inductive BTMor1 : ℕ → Type where
  /-- Projection: select the `i`-th input. -/
  | proj : {n : ℕ} → Fin n → BTMor1 n
  /-- Leaf constant. -/
  | leaf : {n : ℕ} → BTMor1 n
  /-- Branch: combine two subtree-valued expressions. -/
  | branch : {n : ℕ} →
    BTMor1 n → BTMor1 n → BTMor1 n
  /-- Fold (catamorphism) with parameters. -/
  | fold : {n : ℕ} →
    BTMor1 n →
    BTMor1 (n + 2) →
    BTMor1 n →
    BTMor1 n

/-! ## Renaming (variable permutation) -/

/-- Lift a variable renaming past two bound variables
(the recursive-result variables in a fold step).
Variables below `n` are renamed by `f`; variables `n`
and `n + 1` map to `m` and `m + 1`. -/
def liftRename {n m : ℕ}
    (f : Fin n → Fin m) :
    Fin (n + 2) → Fin (m + 2) :=
  fun i =>
    if h : i.val < n then
      ⟨(f ⟨i.val, h⟩).val, by omega⟩
    else
      ⟨m + (i.val - n), by omega⟩

/-- Apply a variable renaming to a morphism term. -/
def BTMor1.rename {n m : ℕ}
    (f : Fin n → Fin m) :
    BTMor1 n → BTMor1 m
  | .proj i => .proj (f i)
  | .leaf => .leaf
  | .branch t₁ t₂ =>
    .branch (t₁.rename f) (t₂.rename f)
  | .fold base step tree =>
    .fold (base.rename f)
      (step.rename (liftRename f))
      (tree.rename f)

/-! ## Shift and substitution -/

/-- Shift all variable indices up by `k`, embedding a
term from a context of size `n` into one of size
`n + k`. -/
def BTMor1.shift {n : ℕ} (k : ℕ) :
    BTMor1 n → BTMor1 (n + k) :=
  BTMor1.rename (fun i => ⟨i.val, by omega⟩)

/-- Lift a substitution past two bound variables.
Context variables (indices below `n`) are substituted
and shifted; the two recursive-result variables map to
fresh projections. -/
def liftSubst {n m : ℕ}
    (σ : Fin n → BTMor1 m) :
    Fin (n + 2) → BTMor1 (m + 2) :=
  fun i =>
    if h : i.val < n then
      (σ ⟨i.val, h⟩).shift 2
    else if _ : i.val = n then
      .proj ⟨m, by omega⟩
    else
      .proj ⟨m + 1, by omega⟩

/-- Simultaneous substitution: replace each free variable
in a term with a term from the substitution.  This is the
composition operation of the Lawvere theory. -/
def BTMor1.subst {n m : ℕ} :
    BTMor1 n → (Fin n → BTMor1 m) → BTMor1 m
  | .proj i, σ => σ i
  | .leaf, _ => .leaf
  | .branch t₁ t₂, σ =>
    .branch (t₁.subst σ) (t₂.subst σ)
  | .fold base step tree, σ =>
    .fold (base.subst σ)
      (step.subst (liftSubst σ))
      (tree.subst σ)

/-! ## Morphisms n → m -/

/-- A morphism from the `n`-fold product to the `m`-fold
product in the Lawvere theory of binary trees.  An
`m`-tuple of morphisms to the generating object. -/
def BTMorN (n m : ℕ) : Type :=
  Fin m → BTMor1 n

/-- The identity morphism: the tuple of projections. -/
def BTMorN.id (n : ℕ) : BTMorN n n :=
  fun i => .proj i

/-- Composition of morphisms via substitution. -/
def BTMorN.comp {n m k : ℕ}
    (g : BTMorN m k) (f : BTMorN n m) :
    BTMorN n k :=
  fun j => (g j).subst f

/-! ## Interpretation in `Type`

The generating object `1` maps to `BT`, and object `n`
maps to `Fin n → BT`. -/

/-- Extend a context of size `n` with two extra values
(for the recursive results in a fold step). -/
def extendCtx {n : ℕ} (ctx : Fin n → BT.{u})
    (r₁ r₂ : BT.{u}) :
    Fin (n + 2) → BT.{u} :=
  fun i =>
    if h : i.val < n then ctx ⟨i.val, h⟩
    else if i.val = n then r₁
    else r₂

/-- Interpret a morphism `n → 1` as a function from
`n`-tuples of binary trees to a binary tree. -/
def BTMor1.interp {n : ℕ} :
    BTMor1 n → (Fin n → BT.{u}) → BT.{u}
  | .proj i, ctx => ctx i
  | .leaf, _ => .leaf
  | .branch t₁ t₂, ctx =>
    .node (t₁.interp ctx) (t₂.interp ctx)
  | .fold base step tree, ctx =>
    (tree.interp ctx).fold
      (base.interp ctx)
      (fun r₁ r₂ =>
        step.interp (extendCtx ctx r₁ r₂))

/-- Interpret a morphism `n → m` as a function from
`n`-tuples to `m`-tuples of binary trees. -/
def BTMorN.interp {n m : ℕ}
    (f : BTMorN n m)
    (ctx : Fin n → BT.{u}) :
    Fin m → BT.{u} :=
  fun j => (f j).interp ctx

/-! ## Finite-product structure

The product of objects `n` and `m` is `n + m`
(concatenation of tuples).  The terminal object is `0`.
-/

/-- Terminal morphism: the unique morphism to the
terminal object (0-fold product). -/
def BTMorN.terminal (n : ℕ) : BTMorN n 0 :=
  fun i => i.elim0

/-- First projection from the product `n + m`. -/
def BTMorN.fst {n m : ℕ} : BTMorN (n + m) n :=
  fun i => .proj ⟨i.val, by omega⟩

/-- Second projection from the product `n + m`. -/
def BTMorN.snd {n m : ℕ} : BTMorN (n + m) m :=
  fun i => .proj ⟨n + i.val, by omega⟩

/-- Pairing: given morphisms to `n` and `m`, produce a
morphism to `n + m`. -/
def BTMorN.pair {k n m : ℕ}
    (f : BTMorN k n) (g : BTMorN k m) :
    BTMorN k (n + m) :=
  fun i =>
    if h : i.val < n then f ⟨i.val, h⟩
    else g ⟨i.val - n, by omega⟩

/-! ## Binary tree object structure

The parameterized BTO consists of the algebra structure
(`btLeaf`, `btBranch`) and the universal property
(`btFold`), following the parameterized NNO pattern from
https://ncatlab.org/nlab/show/natural+numbers+object#withparams
adapted to binary trees.
-/

/-- Leaf constructor: `0 → 1`.  The nullary operation
`z : 1 → T` producing the leaf tree (analogous to the
zero morphism of a parameterized NNO). -/
def btLeaf : BTMorN 0 1 :=
  fun _ => .leaf

/-- Branch constructor: `2 → 1`.  The binary operation
`s : T × T → T` combining two subtrees (analogous to
the successor morphism `s : N → N` of a parameterized
NNO, but binary rather than unary). -/
def btBranch : BTMorN 2 1 :=
  fun _ => .branch (.proj 0) (.proj 1)

/-- Fold (universal property of the parameterized BTO):
given `base : n → 1` (the morphism `f : A → X`)
and `step : (n + 2) → 1` (the morphism
`g : A × X × X → X`, where variables `n` and `n + 1`
are the recursive results), produces
`rec : (n + 1) → 1` (the unique `φ : A × T → X`).

The last input variable of `rec` is the tree to fold
over.

The base is lifted from arity `n` to `n + 1` (the tree
variable is unused).  The step is renamed from arity
`n + 2` to `n + 3` by shifting the recursive-result
variables past the tree variable. -/
def btFold {n : ℕ}
    (base : BTMorN n 1)
    (step : BTMorN (n + 2) 1) :
    BTMorN (n + 1) 1 :=
  fun _ =>
    let baseLifted : BTMor1 (n + 1) :=
      (base ⟨0, by omega⟩).shift 1
    let stepLifted : BTMor1 (n + 3) :=
      (step ⟨0, by omega⟩).rename
        (fun i =>
          if h : i.val < n then
            ⟨i.val, by omega⟩
          else
            ⟨i.val + 1, by omega⟩)
    .fold baseLifted stepLifted
      (.proj ⟨n, by omega⟩)

end GebLean
