import GebLean.LawvereER
import GebLean.Utilities.ZeroTestURM

/-!
# erToK: ER → K^sim_2 via zero-test URM simulation

The compiler half of the erToK construction: emit a
`URMProgram` from an `ERMor1 a` term such that running the
URM long enough produces `e.interp v` in the output
register.

## Main definitions

- `URMInstrRaw`: ℕ-indexed instruction intermediate used
  by compiler combinators before the final register-count
  is known.
- `URMInstrRaw.toBounded`: total conversion from a raw
  instruction to a `URMInstr r`, given a bound proof on
  every register index appearing in the raw instruction.
- `CompiledFragment`: a self-contained compiled URM
  fragment extending `URMProgram a` with a reserved-zero
  register convention used to encode unconditional
  `goto`.
- `CompiledFragment.toURMProgram`: auto-generated by the
  `extends URMProgram a` clause; forgets the reserved-zero
  fields and returns the underlying `URMProgram a`.

## References

- Tourlakis 2018 §0.1.0.37 (pp. 15–16): URM semantics.
- Tourlakis 2018 p. 19: worked URM examples (M template
  for `λx.x`, N template for `λx.x+1`, R^XY_Z template
  for `λxy.xy`).
- Tourlakis 2018 p. 20: Loop-to-URM translation template
  with per-Loop scratch register B.
- Tourlakis 2018 p. 21: bounded-recursion URM template.
- Tourlakis 2018 §0.1.0.42 (p. 18): `f ∈ E^n` is
  URM-computable within time bound in `E^n`.
- Spec §5 (ER → URM compiler):
  `docs/superpowers/specs/2026-05-16-er-to-k-via-cslib-urm-design.md`.

## Tags

URM, compiler, ER, Tourlakis, simulation
-/

namespace GebLean

namespace LawvereERKSim

open GebLean.ZeroTestURM

/-- Raw URM instruction with ℕ-indexed registers and
absolute PC labels. Compiler combinators emit raw
instructions during composition; the final
`CompiledFragment` constructs the `URMInstr numRegs`
array by converting each raw instruction through
`URMInstrRaw.toBounded` once `numRegs` is known.

The five constructors mirror `URMInstr` exactly except
register indices are plain ℕ instead of `Fin r`. Tourlakis
2018 §0.1.0.37 p. 16. -/
inductive URMInstrRaw : Type
  /-- `assignR i c` is Tourlakis's `V_i ← c`. -/
  | assignR (i c : ℕ) : URMInstrRaw
  /-- `incR i` is Tourlakis's `V_i ← V_i + 1`. -/
  | incR (i : ℕ) : URMInstrRaw
  /-- `decR i` is Tourlakis's `V_i ← V_i ∸ 1`. -/
  | decR (i : ℕ) : URMInstrRaw
  /-- `jumpZR i l₁ l₂` is Tourlakis's two-target
  zero-test jump. -/
  | jumpZR (i l₁ l₂ : ℕ) : URMInstrRaw
  /-- `stopR` is Tourlakis's halt. -/
  | stopR : URMInstrRaw
  deriving Repr, DecidableEq, Inhabited

/-- The maximum register index referenced by a raw
instruction, plus 1. Provides the lower bound on
`numRegs` needed to type the instruction as
`URMInstr numRegs`. -/
def URMInstrRaw.regBound : URMInstrRaw → ℕ
  | .assignR i _ => i + 1
  | .incR i => i + 1
  | .decR i => i + 1
  | .jumpZR i _ _ => i + 1
  | .stopR => 0

/-- Convert a raw instruction to a bounded `URMInstr r`,
given a bound proof on the raw instruction's register
index. Total function; the bound proof is consumed at the
`Fin r` construction site. -/
def URMInstrRaw.toBounded
    (r : ℕ) (instr : URMInstrRaw)
    (h : instr.regBound ≤ r) : URMInstr r :=
  match instr, h with
  | .assignR i c, h => .assign ⟨i, h⟩ c
  | .incR i, h => .inc ⟨i, h⟩
  | .decR i, h => .dec ⟨i, h⟩
  | .jumpZR i l₁ l₂, h => .jumpZ ⟨i, h⟩ l₁ l₂
  | .stopR, _ => .stop

/-- All raw instructions in a list have register bound
≤ `r`. -/
def URMInstrRaw.boundedBy (r : ℕ) (l : List URMInstrRaw) :
    Prop :=
  ∀ ins ∈ l, URMInstrRaw.regBound ins ≤ r

/-- Batch-convert a `URMInstrRaw.boundedBy r`-witnessed
list of raw instructions to an `Array (URMInstr r)`.
Uses `List.attach` to carry the membership proof
pointwise. -/
def URMInstrRaw.toBoundedArray (r : ℕ)
    (l : List URMInstrRaw)
    (h : URMInstrRaw.boundedBy r l) :
    Array (URMInstr r) :=
  (l.attach.map (fun ⟨ins, hmem⟩ =>
    URMInstrRaw.toBounded r ins (h ins hmem))).toArray

/-- A compiled URM fragment for a sub-expression of arity
`a`. Compositional building block: per-ER-constructor
combinators (`compileFrag_*`) glue sub-fragments into
larger fragments by register-index injection and
PC-shifting; the top-level `compileER` returns the
fragment's underlying `URMProgram a` via the
auto-generated `.toURMProgram`.

Extends `URMProgram a` (the arity-indexed URM kernel
program type, Task 0 refactor); adds the reserved-zero
convention used to encode unconditional `goto` via
`jumpZ V_z l l` per spec §5.1.

Convention: the reserved-zero register is `⟨0, …⟩` and
the first instruction in `instrs` is `assign ⟨0, …⟩ 0`,
defensively initialising it. -/
@[ext] structure CompiledFragment (a : ℕ)
    extends URMProgram a where
  /-- 0 < numRegs (the reserved-zero register exists). -/
  numRegs_pos : 0 < numRegs
  /-- Reserved-zero register `⟨0, numRegs_pos⟩` disjoint
  from all input registers. -/
  zeroReg_not_input : ∀ i, inputRegs i ≠ ⟨0, numRegs_pos⟩
  /-- Reserved-zero register disjoint from the output
  register. -/
  zeroReg_not_output : (⟨0, numRegs_pos⟩ : Fin numRegs)
    ≠ outputReg

/-- The reserved-zero register `⟨0, F.numRegs_pos⟩`. -/
def CompiledFragment.zeroReg {a : ℕ}
    (F : CompiledFragment a) : Fin F.numRegs :=
  ⟨0, F.numRegs_pos⟩

/-- Encode unconditional `goto l` as Tourlakis's
informal shorthand (p. 19): two-target zero-test jump on
the reserved-zero register `V_z` (= register 0). Both
branches go to `l`, so the jump is unconditional.

Returns a single raw instruction. -/
def URMRaw.goto (l : ℕ) : URMInstrRaw :=
  .jumpZR 0 l l

/-- Destructive transfer `V_dst ← V_dst + V_src;
V_src ← 0`. Body of Tourlakis 2018 p. 19's M program for
`λx.x`, generalised to arbitrary `src` and `dst` and
omitting the trailing `stop`. Emits exactly 4 raw
instructions starting at PC offset `pcBase`; exit PC is
`pcBase + 4`.

Returns the instruction list. The caller is responsible
for placing the returned instructions at `pcBase` in the
overall fragment. -/
def URMRaw.transferLoop (pcBase src dst : ℕ) :
    List URMInstrRaw :=
  [ .jumpZR src (pcBase + 4) (pcBase + 1),
    .decR src,
    .incR dst,
    URMRaw.goto pcBase ]

/-- Number of raw instructions emitted by
`transferLoop`. -/
def URMRaw.transferLoopLen : ℕ := 4

/-- Preserving transfer `V_dst ← V_dst + V_src;
V_src unchanged`. Two destructive-transfer loops via a
tmp register; spec §5.1 register-allocation discipline.
Emits exactly 9 raw instructions starting at PC offset
`pcBase`; exit PC is `pcBase + 9`. -/
def URMRaw.preservingTransfer
    (pcBase src dst tmp : ℕ) : List URMInstrRaw :=
  -- Loop 1: V_src consumed; V_dst, V_tmp accumulate.
  -- PCs pcBase..pcBase+4 (5 instructions):
  [ .jumpZR src (pcBase + 5) (pcBase + 1),  -- pcBase
    .decR src,                              -- pcBase+1
    .incR dst,                              -- pcBase+2
    .incR tmp,                              -- pcBase+3
    URMRaw.goto pcBase,                     -- pcBase+4
  -- Loop 2: V_tmp consumed; V_src restored.
  -- PCs pcBase+5..pcBase+8 (4 instructions):
    .jumpZR tmp (pcBase + 9) (pcBase + 6),  -- pcBase+5
    .decR tmp,                              -- pcBase+6
    .incR src,                              -- pcBase+7
    URMRaw.goto (pcBase + 5) ]              -- pcBase+8

/-- Number of raw instructions emitted by
`preservingTransfer`. -/
def URMRaw.preservingTransferLen : ℕ := 9

end LawvereERKSim

end GebLean
