import GebLean.PLang.Syntax
import GebLean.PolyAlgUMorph
import GebLean.Utilities.ComputableLimits
import Mathlib.Data.Fin.Basic

/-!
# Lawvere Theory of Binary Trees

Defines the Lawvere (finite-product) theory of parameterized
binary tree objects (BTOs), analogous to the Lawvere theory
of parameterized natural numbers objects (which gives
primitive recursive arithmetic).

Objects are natural numbers `n`, representing the `n`-fold
product of the generating object `T`.

Morphisms `n → m` are `m`-tuples of primitive recursive
tree functions, each taking `n` inputs.

The morphisms are generated by:
- Projections (finite-product structure)
- `leaf` : the leaf constant (from the terminal object)
- `branch` : binary branching (`2 → 1`)
- `fold` : tree catamorphism with parameters (the universal
  property of the parameterized BTO)

The parameterized BTO structure (`HasPBTO`) follows the
pattern of parameterized NNOs (`HasNNO`) from
https://ncatlab.org/nlab/show/natural+numbers+object#withparams
(the original, non-enhanced version):
an object `T` with morphisms `ℓ : 1 → T` (leaf) and
`β : T × T → T` (branch), such that for any `f : A → X`
and `g : X × X → X`, there exists a unique
`φ : A × T → X` satisfying
`φ(a, ℓ) = f(a)` and
`φ(a, β(t₁, t₂)) = g(φ(a, t₁), φ(a, t₂))`.

In the Lawvere theory, `A`, `X`, `T` are all powers of
the generating object.  With `A = n`, `T = 1`, `X = m`:
`f : n → m`, `g : (m + m) → m`, `φ : (n + 1) → m`.

## References

* nLab, "Lawvere theory",
  https://ncatlab.org/nlab/show/Lawvere+theory
* nLab, "natural numbers object" (parameterized NNO),
  https://ncatlab.org/nlab/show/natural+numbers+object#withparams
-/

namespace GebLean

open CategoryTheory

universe u v

/-! ## Parameterized natural numbers object

Transcription of the parameterized NNO from
https://ncatlab.org/nlab/show/natural+numbers+object#withparams
(the original, non-enhanced version).

In a category with finite products, a parameterized NNO
consists of `N` with `z : 𝟙_ C ⟶ N` and `s : N ⟶ N`
such that for any `A`, `X`, `f : A ⟶ X`, `g : X ⟶ X`,
there exists a unique `φ : A ⨯ N ⟶ X` satisfying
`φ ∘ ⟨id_A, z ∘ !_A⟩ = f` and
`φ ∘ (id_A ⨯ s) = g ∘ φ`.
-/

/-- A parameterized natural numbers object in a category
with chosen finite products.  Adapted from
https://ncatlab.org/nlab/show/natural+numbers+object#withparams. -/
class HasNNO (C : Type u) [Category.{v} C]
    [HasChosenFiniteProducts C] where
  /-- The natural numbers object. -/
  N : C
  /-- Zero: the initial element. -/
  z : cfpTerminal ⟶ N
  /-- Successor. -/
  s : N ⟶ N
  /-- The unique morphism given by the universal
  property: for `f : A ⟶ X` and `g : X ⟶ X`, the
  parameterized iterator `φ : A × N ⟶ X`. -/
  elim : ∀ {A X : C},
    (A ⟶ X) → (X ⟶ X) →
    (cfpProd A N ⟶ X)
  /-- Base case: `φ(a, z) = f(a)`. -/
  elim_z : ∀ {A X : C}
    (f : A ⟶ X) (g : X ⟶ X),
    cfpInsertSnd z A ≫ elim f g = f
  /-- Step case: `φ(a, s(n)) = g(φ(a, n))`. -/
  elim_s : ∀ {A X : C}
    (f : A ⟶ X) (g : X ⟶ X),
    cfpMap (𝟙 A) s ≫ elim f g =
      elim f g ≫ g
  /-- Uniqueness. -/
  elim_uniq : ∀ {A X : C}
    (f : A ⟶ X) (g : X ⟶ X)
    (φ : cfpProd A N ⟶ X),
    cfpInsertSnd z A ≫ φ = f →
    cfpMap (𝟙 A) s ≫ φ = φ ≫ g →
    φ = elim f g

/-! ## Parameterized binary tree object

The binary-tree analogue of the parameterized NNO.  An
object `T` with `ℓ : 𝟙_ C ⟶ T` (leaf) and
`β : T ⨯ T ⟶ T` (branch), such that for any `A`, `X`,
`f : A ⟶ X`, `g : X ⨯ X ⟶ X`, there exists a unique
`φ : A ⨯ T ⟶ X` satisfying
`φ ∘ ⟨id_A, ℓ ∘ !_A⟩ = f` and
`φ ∘ (id_A ⨯ β) = g ∘ (φ ⨯_A φ)`.

This is the direct adaptation of the parameterized NNO
with the unary successor `s : N ⟶ N` replaced by the
binary branching `β : T ⨯ T ⟶ T`, and the step
morphism `g : X ⟶ X` replaced by `g : X ⨯ X ⟶ X`.
-/

/-- A parameterized binary tree object in a category
with chosen finite products. -/
class HasPBTO (C : Type u) [Category.{v} C]
    [HasChosenFiniteProducts C] where
  /-- The binary tree object. -/
  T : C
  /-- Leaf: the initial element. -/
  ℓ : cfpTerminal ⟶ T
  /-- Branch: combines two subtrees. -/
  β : cfpProd T T ⟶ T
  /-- The unique morphism given by the universal
  property: for `f : A ⟶ X` and `g : X × X ⟶ X`,
  the parameterized catamorphism
  `φ : A × T ⟶ X`. -/
  elim : ∀ {A X : C},
    (A ⟶ X) → (cfpProd X X ⟶ X) →
    (cfpProd A T ⟶ X)
  /-- Base case: `φ(a, ℓ) = f(a)`. -/
  elim_ℓ : ∀ {A X : C}
    (f : A ⟶ X) (g : cfpProd X X ⟶ X),
    cfpInsertSnd ℓ A ≫ elim f g = f
  /-- Step case:
  `φ(a, β(t₁, t₂)) = g(φ(a, t₁), φ(a, t₂))`.
  From `A × (T × T)`, pairs `(a, t₁)` and
  `(a, t₂)` are extracted, `φ` is applied to each,
  and `g` combines the results. -/
  elim_β : ∀ {A X : C}
    (f : A ⟶ X) (g : cfpProd X X ⟶ X),
    cfpMap (𝟙 A) β ≫ elim f g =
      cfpLiftAssoc
        (elim f g) (elim f g) ≫ g
  /-- Uniqueness. -/
  elim_uniq : ∀ {A X : C}
    (f : A ⟶ X) (g : cfpProd X X ⟶ X)
    (φ : cfpProd A T ⟶ X),
    cfpInsertSnd ℓ A ≫ φ = f →
    cfpMap (𝟙 A) β ≫ φ =
      cfpLiftAssoc φ φ ≫ g →
    φ = elim f g

/-! ## Binary tree object via polynomial machinery

The type of binary trees is the free monad of the product
polynomial (`polyProdFreeM`), evaluated at the terminal
object.  This gives the initial algebra of `X ↦ 1 + X × X`.

Constructors and the catamorphism use universal morphisms
from `PolyAlg`:
- `polyFreeMPure` for leaf injection
- `polyFreeMStrFamily` for node injection
- `polyFreeCounitFoldAt` for the catamorphism (counit of
  the free-forgetful adjunction)
- `polyProdEvalOfPair` / `polyProdEvalToPair` for the
  pair interface on `polyProd` directions
-/

/-- Binary trees as the free monad of the product
polynomial at the terminal object. -/
abbrev BT : Type u :=
  PolyFreeM
    (overTerminal PUnit.{u + 1})
    polyProdType
    PUnit.unit

/-- The leaf tree (the unit `z : 1 → T` of the BTO).
Constructed via `polyFreeMPure` (the unit of the free
monad). -/
def BT.leaf : BT.{u} :=
  polyFreeMPure
    (overTerminal PUnit.{u + 1})
    polyProdType
    ⟨PUnit.unit, rfl⟩

/-- A branching tree from two subtrees
(the operation `s : T × T → T` of the BTO).
Constructed via `polyProdFreeMNode`. -/
def BT.node (l r : BT.{u}) : BT.{u} :=
  polyProdFreeMNode
    (overTerminal PUnit.{u + 1}) l r

/-- Catamorphism (fold) for binary trees (the universal
morphism `φ : A × T → X` of the parameterized BTO).
Given `b` for leaves and `s` for branches, folds a tree
to produce a result.
Constructed via `polyProdFreeMFoldAt`. -/
def BT.fold {α : Type u} (b : α) (s : α → α → α)
    (t : BT.{u}) : α :=
  polyProdFreeMFoldAt
    (overTerminal PUnit.{u + 1})
    (fun _ => b) s t

/-! ## Morphism polynomial: components

The morphism type `BTMor1 n` is the initial algebra of a
polynomial endofunctor on `Over ℕ`.  The polynomial is a
four-way coproduct, one summand per constructor:

- `btMorProjPoly`: projection (positions = `Fin n`, no
  children)
- `btMorLeafPoly`: leaf constant (one position, no
  children)
- `btMorBranchPoly`: binary branching (one position, two
  children at the same fiber) — this is `polyProd ℕ`
- `btMorFoldPoly`: fold (one position, three children at
  fibers `n`, `n + 2`, `n`)

The coproduct `btMorPoly` of these four is a "data types
a la carte" decomposition: each summand can be equipped
with algebras independently, and the coproduct algebra
combines them.
-/

/-- A polynomial endofunctor on `Over ℕ` representing a
single child whose fiber is shifted by `k` relative to
the parent.  At fiber `n`, there is one position and one
direction, and that direction maps to fiber `n + k`.

Evaluating at `Y : Over ℕ` gives `Y(n + k)` at each
fiber `n`: the child lives `k` fibers above the parent.

Used in `btMorFoldPoly` to represent the step child of
the fold constructor, which lives at fiber `n + 2` (the
context extended by two recursive-result variables). -/
def polyShift (k : ℕ) : PolyEndo ℕ :=
  polyEndoRepr
    (fun n => Over.mk (fun _ : PUnit.{1} => n + k))

/-- Projection component: at fiber `n`, positions are
`Fin n` with no children.  Uses `polyBetweenConst` with
`Over.mk Fin.val`. -/
def btMorProjPoly : PolyEndo ℕ :=
  polyBetweenConst
    (Over.mk (fun (p : Σ n, Fin n) => p.1))

/-- Leaf component: one position, no children.  Uses
`polyBetweenConst` with the terminal object. -/
def btMorLeafPoly : PolyEndo ℕ :=
  polyBetweenConst (overTerminal ℕ)

/-- Branch component: one position, two children at the
same fiber.  This is `polyProd ℕ`. -/
abbrev btMorBranchPoly : PolyEndo ℕ := polyProd ℕ

/-- Fold component: the full parameterized fold with
output dimension `m` and projection index `j : Fin m`.

At fiber `n`, positions are `(m : ℕ) × Fin m`, and
directions are `Fin (m + m + 1)` with fiber map:
- first `m` directions → fiber `n` (base children)
- next `m` directions → fiber `m + m` (step children)
- last direction → fiber `n` (tree child)

The semantics: `fold(m, j, f₀..f_{m-1}, g₀..g_{m-1},
tree)` evaluates to the `j`-th component of the mutual
fold of `tree` using base `f` and step `g`. -/
def btMorFoldPoly : PolyEndo ℕ :=
  fun n => ccrObjMk
    (fun (pos : Σ m, Fin m) =>
      let m := pos.1
      Over.mk (fun (d : Fin (m + m + 1)) =>
        if d.val < m then n
        else if d.val < m + m then m + m
        else n))

/-! ## Morphism polynomial: coproduct -/

/-- The four summands of the morphism polynomial,
indexed by `Fin 4`. -/
def btMorComponents : Fin 4 → PolyEndo ℕ :=
  fun i => match i with
    | 0 => btMorProjPoly
    | 1 => btMorLeafPoly
    | 2 => btMorBranchPoly
    | 3 => btMorFoldPoly

/-- The polynomial endofunctor on `Over ℕ` whose initial
algebra gives the morphism type of the Lawvere theory.
A four-way coproduct of projection, leaf, branch, and
fold components. -/
def btMorPoly : PolyEndo ℕ :=
  polyBetweenCoprod (Fin 4) btMorComponents

/-! ## Finitarity instances

Each component polynomial is finitary (finite
direction types), and finitarity is preserved by
coproducts.  The free monad inherits finitarity
via `polyFreeMPolyFinitary`. -/

/-- `PUnit.{u+1} ⊕ PUnit.{u+1}` is finite. -/
@[reducible] private def punitSumFintype :
    Fintype (PUnit.{u + 1} ⊕ PUnit.{u + 1}) :=
  ⟨{Sum.inl PUnit.unit, Sum.inr PUnit.unit},
    fun x => by cases x <;> simp⟩

instance polyProdTypeFinitary :
    PolyBetweenFinitary PUnit.{u + 1}
      PUnit.{u + 1} polyProdType where
  data := ⟨fun _ _ => punitSumFintype⟩

instance btMorProjPolyFinitary :
    PolyBetweenFinitary ℕ ℕ btMorProjPoly where
  data := ⟨fun _ _ => ⟨∅, fun x => x.elim⟩⟩

instance btMorLeafPolyFinitary :
    PolyBetweenFinitary ℕ ℕ btMorLeafPoly where
  data := ⟨fun _ _ => ⟨∅, fun x => x.elim⟩⟩

instance btMorBranchPolyFinitary :
    PolyBetweenFinitary ℕ ℕ btMorBranchPoly where
  data := ⟨fun _ _ => punitSumFintype⟩

instance btMorFoldPolyFinitary :
    PolyBetweenFinitary ℕ ℕ btMorFoldPoly where
  data := ⟨fun _ _ => Fin.fintype _⟩

instance btMorComponentsFinitary (i : Fin 4) :
    PolyBetweenFinitary ℕ ℕ
      (btMorComponents i) :=
  match i with
  | 0 => btMorProjPolyFinitary
  | 1 => btMorLeafPolyFinitary
  | 2 => btMorBranchPolyFinitary
  | 3 => btMorFoldPolyFinitary

instance btMorPolyFinitary :
    PolyBetweenFinitary ℕ ℕ btMorPoly where
  data := ⟨fun n ⟨i, p⟩ =>
    let inst := btMorComponentsFinitary i
    inst.data.familyFintype n p⟩

/-- The free monad of the binary tree polynomial
(`polyProdFreeM`) is finitary. -/
instance polyProdFreeMFinitary :
    PolyBetweenFinitary PUnit.{u + 1}
      PUnit.{u + 1}
      (polyProdFreeM PUnit.{u + 1}) :=
  polyFreeMPolyFinitary polyProdType

/-- The free monad of the morphism polynomial
(`polyFreeMPoly btMorPoly`) is finitary. -/
instance btMorFreeMFinitary :
    PolyBetweenFinitary ℕ ℕ
      (polyFreeMPoly btMorPoly) :=
  polyFreeMPolyFinitary btMorPoly

/-! ## Morphisms of the Lawvere theory

A morphism `n → 1` is the initial algebra of `btMorPoly`
at fiber `n`.  The four constructors correspond to the
four summands of the coproduct polynomial, injected via
`polyBetweenInj` and the initial algebra structure map.

Variables use de Bruijn indices: `proj i` refers to the
`i`-th input (where `i : Fin n`).

In the `fold` case:
- The base child is at fiber `n` (the context variables).
- The step child is at fiber `n + 2` (context plus two
  recursive-result variables).
- The tree child is at fiber `n` (the tree to fold over).
-/

/-- A morphism from the `n`-fold product of the generating
object to the generating object in the Lawvere theory of
binary trees.  Defined as `PolyFix btMorPoly n`. -/
abbrev BTMor1 (n : ℕ) : Type :=
  PolyFix btMorPoly n

/-! ## Morphism constructors

Each constructor injects component evaluation data into
the coproduct polynomial via `polyBetweenInj` and applies
the initial algebra structure map `polyFixStrFamily`.
-/

private abbrev btMorCarrier :=
  polyFixCarrier btMorPoly

private def btMorInject (j : Fin 4) {n : ℕ}
    (eval : polyBetweenEvalFamily ℕ ℕ
      (btMorComponents j) btMorCarrier n) :
    BTMor1 n :=
  polyFixStrFamily btMorPoly n
    (polyEndoMorphEvalAt
      (polyBetweenInj (Fin 4) btMorComponents j)
      btMorCarrier n eval)

/-- Projection: select the `i`-th input. -/
def BTMor1.proj {n : ℕ} (i : Fin n) :
    BTMor1 n :=
  btMorInject 0
    ⟨⟨⟨n, i⟩, rfl⟩,
      (overInitial_isInitial ℕ).to btMorCarrier⟩

/-- Leaf constant. -/
def BTMor1.leaf {n : ℕ} : BTMor1 n :=
  btMorInject 1
    ⟨⟨n, rfl⟩,
      (overInitial_isInitial ℕ).to btMorCarrier⟩

/-- Branch: combine two subtree-valued expressions. -/
def BTMor1.branch {n : ℕ}
    (l r : BTMor1 n) : BTMor1 n :=
  btMorInject 2
    (polyProdEvalOfPair btMorCarrier
      (⟨Sigma.mk n l, rfl⟩ :
        Over.Fiber btMorCarrier n)
      (⟨Sigma.mk n r, rfl⟩ :
        Over.Fiber btMorCarrier n))

/-- Fold: the full parameterized catamorphism.
Given output dimension `m`, base components
`f : Fin m → BTMor1 n`, step components
`g : Fin m → BTMor1 (m + m)`, tree `t : BTMor1 n`,
and projection index `j : Fin m`, produces a
`BTMor1 n` that evaluates to the `j`-th component
of the mutual fold of `t` using `f` and `g`. -/
def BTMor1.fold {n : ℕ}
    (m : ℕ) (f : Fin m → BTMor1 n)
    (g : Fin m → BTMor1 (m + m))
    (tree : BTMor1 n) (j : Fin m) :
    BTMor1 n :=
  btMorInject 3
    ⟨⟨m, j⟩, Over.homMk
      (fun (d : Fin (m + m + 1)) =>
        if hb : d.val < m then
          ⟨n, f ⟨d.val, hb⟩⟩
        else if hs : d.val < m + m then
          ⟨m + m, g ⟨d.val - m, by omega⟩⟩
        else
          ⟨n, tree⟩)
      (by funext d
          dsimp [btMorCarrier, btMorComponents,
            btMorFoldPoly, polyFixCarrier,
            familySliceForward,
            familySliceForwardObj,
            ccrObjMk, ccrFamily,
            types_comp_apply]
          split_ifs <;> rfl)⟩

/-! ## Interpretation via `polyFixFold`

The interpretation maps `BTMor1 n` to a function
`(Fin n → BT) → BT` using the universal fold
(`polyFixFoldAtWithProof`) with a `btMorPoly`-algebra
assembled via `algCoprodDesc` from four component
structure maps, one per constructor.
-/

/-- Extend a context of size `n` with two extra values
(for the recursive results in a fold step). -/
def extendCtx {n : ℕ} (ctx : Fin n → BT.{0})
    (r₁ r₂ : BT.{0}) :
    Fin (n + 2) → BT.{0} :=
  fun i =>
    if h : i.val < n then ctx ⟨i.val, h⟩
    else if i.val = n then r₁
    else r₂

/-- The carrier for the interpretation algebra.  Uses
`(ℕ → BT) → BT` uniformly at all fibers, avoiding
fiber-dependent type transport.  The restriction to
`Fin n` occurs at the public API. -/
private def interpCarrier : Over ℕ :=
  Over.mk
    (fun (p : ℕ × ((ℕ → BT.{0}) → BT.{0})) =>
      p.1)

/-- Extend a full context by placing `r₁` and `r₂` at
positions `n` and `n + 1`. -/
private def extendFullCtx
    (k : ℕ) (ctx : ℕ → BT.{0})
    (r₁ r₂ : BT.{0}) : ℕ → BT.{0} :=
  fun i =>
    if i = k then r₁
    else if i = k + 1 then r₂
    else ctx i

/-- Projection structure map: look up index `i`. -/
private def interpProjStr :
    (polyEndoFunctor ℕ btMorProjPoly).obj
      interpCarrier ⟶ interpCarrier :=
  Over.homMk
    (fun ⟨n, ⟨⟨⟨_, i⟩, rfl⟩, _⟩⟩ =>
      (n, fun ctx => ctx i.val))
    (by aesop_cat)

/-- Leaf structure map: return `BT.leaf`. -/
private def interpLeafStr :
    (polyEndoFunctor ℕ btMorLeafPoly).obj
      interpCarrier ⟶ interpCarrier :=
  Over.homMk
    (fun ⟨n, _⟩ => (n, fun _ => BT.leaf))
    (by aesop_cat)

/-- Branch structure map: apply `BT.node` to the two
recursive results.  Uses `polyProdAlgStr`. -/
private def interpBranchStr :
    (polyEndoFunctor ℕ btMorBranchPoly).obj
      interpCarrier ⟶ interpCarrier :=
  polyProdAlgStr interpCarrier
    (fun a₁ a₂ =>
      ⟨(a₁.val.1, fun ctx =>
        BT.node (a₁.val.2 ctx) (a₂.val.2 ctx)),
        a₁.property⟩)

/-- Fold structure map: combine base, step, tree.
Extracts `m` base children, `m` step children, and
one tree child.  Folds the tree with carrier
`Fin m → BT`, then extracts the `j`-th component. -/
private def interpFoldStr :
    (polyEndoFunctor ℕ btMorFoldPoly).obj
      interpCarrier ⟶ interpCarrier :=
  Over.homMk
    (fun ⟨n, ⟨pos, childMor⟩⟩ =>
      let pm := pos.1
      let pj := pos.2
      let treeChild :=
        (childMor.left
          ⟨pm + pm, by omega⟩).2
      (n, fun ctx =>
        let baseVals : Fin pm → BT.{0} :=
          fun i =>
            (childMor.left
              ⟨i.val, by omega⟩).2 ctx
        (treeChild ctx).fold
          baseVals
          (fun leftAll rightAll =>
            fun j =>
              let stepCtx : ℕ → BT.{0} :=
                fun i =>
                  if h : i < pm then
                    leftAll ⟨i, h⟩
                  else if h2 :
                      i - pm < pm then
                    rightAll
                      ⟨i - pm, h2⟩
                  else BT.leaf
              (childMor.left
                ⟨pm + j.val, by omega⟩).2
                  stepCtx)
          pj))
    (by aesop_cat)

/-- The four component structure maps. -/
private def interpComponentStrs :
    ∀ (i : Fin 4),
      (polyEndoFunctor ℕ (btMorComponents i)).obj
        interpCarrier ⟶ interpCarrier :=
  fun i => match i with
    | 0 => interpProjStr
    | 1 => interpLeafStr
    | 2 => interpBranchStr
    | 3 => interpFoldStr

/-- The `btMorPoly`-algebra for interpretation,
assembled via `algCoprodDesc`. -/
private def interpAlg : PolyAlg btMorPoly :=
  algCoprodDesc interpCarrier interpComponentStrs

/-- Interpret a morphism `n → 1` as a function from
`n`-tuples of binary trees to a binary tree.

Defined via `polyFixFoldAtWithProof` with the
interpretation algebra.  The carrier uses
`(ℕ → BT) → BT` uniformly; the restriction to
`Fin n` occurs here. -/
def BTMor1.interp {n : ℕ}
    (t : BTMor1 n)
    (ctx : Fin n → BT.{0}) : BT.{0} :=
  let fullCtx : ℕ → BT.{0} :=
    fun i =>
      if h : i < n then ctx ⟨i, h⟩
      else BT.leaf
  (polyFixFoldAtWithProof btMorPoly interpAlg
    n t).val.2 fullCtx

/-! ## Morphisms n → m -/

/-- A morphism from the `n`-fold product to the `m`-fold
product in the Lawvere theory of binary trees.  An
`m`-tuple of morphisms to the generating object. -/
def BTMorN (n m : ℕ) : Type :=
  Fin m → BTMor1 n

/-- The identity morphism: the tuple of projections. -/
def BTMorN.id (n : ℕ) : BTMorN n n :=
  fun i => BTMor1.proj i

/-- Interpret a morphism `n → m` as a function from
`n`-tuples to `m`-tuples of binary trees. -/
def BTMorN.interp {n m : ℕ}
    (f : BTMorN n m)
    (ctx : Fin n → BT.{0}) :
    Fin m → BT.{0} :=
  fun j => (f j).interp ctx

/-! ## Finite-product structure

The product of objects `n` and `m` is `n + m`
(concatenation of tuples).  The terminal object is `0`.
-/

/-- Terminal morphism: the unique morphism to the
terminal object (0-fold product). -/
def BTMorN.terminal (n : ℕ) : BTMorN n 0 :=
  fun i => i.elim0

/-- First projection from the product `n + m`. -/
def BTMorN.fst {n m : ℕ} : BTMorN (n + m) n :=
  fun i => BTMor1.proj ⟨i.val, by omega⟩

/-- Second projection from the product `n + m`. -/
def BTMorN.snd {n m : ℕ} : BTMorN (n + m) m :=
  fun i => BTMor1.proj ⟨n + i.val, by omega⟩

/-- Pairing: given morphisms to `n` and `m`, produce a
morphism to `n + m`. -/
def BTMorN.pair {k n m : ℕ}
    (f : BTMorN k n) (g : BTMorN k m) :
    BTMorN k (n + m) :=
  fun i =>
    if h : i.val < n then f ⟨i.val, h⟩
    else g ⟨i.val - n, by omega⟩

/-! ## Binary tree object structure

The parameterized BTO consists of the algebra structure
(`btLeaf`, `btBranch`) and the universal property
(`btFoldFull`), following `HasPBTO`.
-/

/-- Leaf constructor: `0 → 1`. -/
def btLeaf : BTMorN 0 1 :=
  fun _ => BTMor1.leaf

/-- Branch constructor: `2 → 1`. -/
def btBranch : BTMorN 2 1 :=
  fun _ =>
    BTMor1.branch (BTMor1.proj 0) (BTMor1.proj 1)

/-! ## Rename via `polyFixFold`

`rename` changes the fiber (from `n` to `m`), so the
fold carrier stores `(ℕ → ℕ) → Σ m, BTMor1 m`: a
function from a "total renaming" to a renamed term with
its output fiber.  The total renaming derived from
`f : Fin n → Fin m` is
`fun i => if i < n then (f i).val else m + (i - n)`,
which works uniformly at all fibers (including nested
fold step children at `n + 2`, `n + 4`, ...).
-/

private abbrev renameCarrier : Over ℕ :=
  Over.mk
    (fun (p : ℕ ×
      ((ℕ → ℕ) → Σ k, BTMor1 k)) => p.1)

private def renameProjStr :
    (polyEndoFunctor ℕ btMorProjPoly).obj
      renameCarrier ⟶ renameCarrier :=
  Over.homMk
    (fun ⟨k, ⟨⟨⟨_, i⟩, rfl⟩, _⟩⟩ =>
      (k, fun ren =>
        let tgt := ren k
        if h : ren i.val < tgt then
          ⟨tgt, BTMor1.proj ⟨ren i.val, h⟩⟩
        else ⟨tgt, BTMor1.leaf⟩))
    (by aesop_cat)

private def renameLeafStr :
    (polyEndoFunctor ℕ btMorLeafPoly).obj
      renameCarrier ⟶ renameCarrier :=
  Over.homMk
    (fun ⟨k, _⟩ =>
      (k, fun ren => ⟨ren k, BTMor1.leaf⟩))
    (by aesop_cat)

private def renameBranchStr :
    (polyEndoFunctor ℕ btMorBranchPoly).obj
      renameCarrier ⟶ renameCarrier :=
  polyProdAlgStr renameCarrier
    (fun a₁ a₂ =>
      ⟨(a₁.val.1, fun ren =>
        let ⟨m₁, t₁⟩ := a₁.val.2 ren
        let ⟨m₂, t₂⟩ := a₂.val.2 ren
        if h : m₂ = m₁ then
          ⟨m₁, BTMor1.branch t₁ (h ▸ t₂)⟩
        else ⟨m₁, t₁⟩), a₁.property⟩)

private def renameFoldStr :
    (polyEndoFunctor ℕ btMorFoldPoly).obj
      renameCarrier ⟶ renameCarrier :=
  Over.homMk
    (fun ⟨k, ⟨pos, childMor⟩⟩ =>
      let pm := pos.1
      let pj := pos.2
      have hpm : 0 < pm :=
        Nat.lt_of_le_of_lt
          (Nat.zero_le _) pj.isLt
      (k, fun ren =>
        let bases :
            Fin pm → Σ j, BTMor1 j :=
          fun i =>
            (childMor.left
              ⟨i.val, by omega⟩).2 ren
        let steps :
            Fin pm → Σ j, BTMor1 j :=
          fun i =>
            (childMor.left
              ⟨pm + i.val, by omega⟩).2
                ren
        let treeR :=
          (childMor.left
            ⟨pm + pm, by omega⟩).2 ren
        let mB := (bases ⟨0, hpm⟩).1
        let allBasesOk :=
          ∀ i, (bases i).1 = mB
        if hOk : allBasesOk then
          let baseFns :
              Fin pm → BTMor1 mB :=
            fun i =>
              let h := hOk i
              h ▸ (bases i).2
          let stepFns :
              Fin pm → BTMor1 (pm + pm) :=
            fun i =>
              let ⟨ms, s⟩ := steps i
              if hs : ms = pm + pm then
                hs ▸ s
              else BTMor1.leaf
          let ⟨mT, tree⟩ := treeR
          if hT : mT = mB then
            ⟨mB, BTMor1.fold pm
              baseFns stepFns
              (hT ▸ tree) pj⟩
          else ⟨mB, (baseFns pj)⟩
        else
          ⟨(bases ⟨0, hpm⟩).1,
            (bases ⟨0, hpm⟩).2⟩))
    (by aesop_cat)

private def renameComponentStrs :
    ∀ (i : Fin 4),
      (polyEndoFunctor ℕ (btMorComponents i)).obj
        renameCarrier ⟶ renameCarrier :=
  fun i => match i with
    | 0 => renameProjStr
    | 1 => renameLeafStr
    | 2 => renameBranchStr
    | 3 => renameFoldStr

private def renameAlg : PolyAlg btMorPoly :=
  algCoprodDesc renameCarrier renameComponentStrs

/-- The total renaming derived from `f : Fin n → Fin m`.
Maps context variables via `f` and shifts additional
variables (recursive-result positions) by `m - n`. -/
def totalRenaming {n m : ℕ}
    (f : Fin n → Fin m) : ℕ → ℕ :=
  fun i =>
    if h : i < n then (f ⟨i, h⟩).val
    else m + (i - n)

/-- Apply a variable renaming to a morphism term.
Defined via `polyFixFoldAtWithProof` with the rename
algebra. -/
def BTMor1.rename {n m : ℕ}
    (f : Fin n → Fin m)
    (t : BTMor1 n) : BTMor1 m :=
  let result :=
    (polyFixFoldAtWithProof btMorPoly
      renameAlg n t).val.2 (totalRenaming f)
  if h : result.1 = m then h ▸ result.2
  else BTMor1.leaf

/-- Shift all variable indices up by `k`. -/
def BTMor1.shift {n : ℕ} (k : ℕ)
    (t : BTMor1 n) : BTMor1 (n + k) :=
  BTMor1.rename
    (fun i => ⟨i.val, by omega⟩) t

/-! ## Substitution via `polyFixFold` -/

/-- Lift a variable renaming past two bound variables
(the recursive-result variables in a fold step). -/
def liftRename {n m : ℕ}
    (f : Fin n → Fin m) :
    Fin (n + 2) → Fin (m + 2) :=
  fun i =>
    if h : i.val < n then
      ⟨(f ⟨i.val, h⟩).val, by omega⟩
    else
      ⟨m + (i.val - n), by omega⟩

/-- Lift a substitution past two bound variables. -/
def liftSubst {n m : ℕ}
    (σ : Fin n → BTMor1 m) :
    Fin (n + 2) → BTMor1 (m + 2) :=
  fun i =>
    if h : i.val < n then
      (σ ⟨i.val, h⟩).shift 2
    else if _ : i.val = n then
      BTMor1.proj ⟨m, by omega⟩
    else
      BTMor1.proj ⟨m + 1, by omega⟩

private abbrev substCarrier : Over ℕ :=
  Over.mk
    (fun (p : ℕ ×
      ((ℕ → Σ k, BTMor1 k) →
        Σ k, BTMor1 k)) => p.1)

private def substProjStr :
    (polyEndoFunctor ℕ btMorProjPoly).obj
      substCarrier ⟶ substCarrier :=
  Over.homMk
    (fun ⟨k, ⟨⟨⟨_, i⟩, rfl⟩, _⟩⟩ =>
      (k, fun σ => σ i.val))
    (by aesop_cat)

private def substLeafStr :
    (polyEndoFunctor ℕ btMorLeafPoly).obj
      substCarrier ⟶ substCarrier :=
  Over.homMk
    (fun ⟨k, _⟩ =>
      (k, fun _ => ⟨k, BTMor1.leaf⟩))
    (by aesop_cat)

private def substBranchStr :
    (polyEndoFunctor ℕ btMorBranchPoly).obj
      substCarrier ⟶ substCarrier :=
  polyProdAlgStr substCarrier
    (fun a₁ a₂ =>
      ⟨(a₁.val.1, fun σ =>
        let ⟨m₁, t₁⟩ := a₁.val.2 σ
        let ⟨m₂, t₂⟩ := a₂.val.2 σ
        if h : m₂ = m₁ then
          ⟨m₁, BTMor1.branch t₁ (h ▸ t₂)⟩
        else ⟨m₁, t₁⟩), a₁.property⟩)

private def substFoldStr :
    (polyEndoFunctor ℕ btMorFoldPoly).obj
      substCarrier ⟶ substCarrier :=
  Over.homMk
    (fun ⟨k, ⟨pos, childMor⟩⟩ =>
      let pm := pos.1
      let pj := pos.2
      have hpm : 0 < pm :=
        Nat.lt_of_le_of_lt
          (Nat.zero_le _) pj.isLt
      (k, fun σ =>
        let bases :
            Fin pm → Σ j, BTMor1 j :=
          fun i =>
            (childMor.left
              ⟨i.val, by omega⟩).2 σ
        let steps :
            Fin pm → Σ j, BTMor1 j :=
          fun i =>
            (childMor.left
              ⟨pm + i.val, by omega⟩).2
                σ
        let treeR :=
          (childMor.left
            ⟨pm + pm, by omega⟩).2 σ
        let mB := (bases ⟨0, hpm⟩).1
        let allBasesOk :=
          ∀ i, (bases i).1 = mB
        if hOk : allBasesOk then
          let baseFns :
              Fin pm → BTMor1 mB :=
            fun i =>
              let h := hOk i
              h ▸ (bases i).2
          let stepFns :
              Fin pm → BTMor1 (pm + pm) :=
            fun i =>
              let ⟨ms, s⟩ := steps i
              if hs : ms = pm + pm then
                hs ▸ s
              else BTMor1.leaf
          let ⟨mT, tree⟩ := treeR
          if hT : mT = mB then
            ⟨mB, BTMor1.fold pm
              baseFns stepFns
              (hT ▸ tree) pj⟩
          else ⟨mB, (baseFns pj)⟩
        else
          ⟨(bases ⟨0, hpm⟩).1,
            (bases ⟨0, hpm⟩).2⟩))
    (by aesop_cat)

private def substComponentStrs :
    ∀ (i : Fin 4),
      (polyEndoFunctor ℕ (btMorComponents i)).obj
        substCarrier ⟶ substCarrier :=
  fun i => match i with
    | 0 => substProjStr
    | 1 => substLeafStr
    | 2 => substBranchStr
    | 3 => substFoldStr

private def substAlg : PolyAlg btMorPoly :=
  algCoprodDesc substCarrier substComponentStrs

/-- The total substitution derived from
`σ : Fin n → BTMor1 m`. -/
def totalSubst {n m : ℕ}
    (σ : Fin n → BTMor1 m) :
    ℕ → Σ k, BTMor1 k :=
  fun i =>
    if h : i < n then ⟨m, σ ⟨i, h⟩⟩
    else if hm : 0 < m then
      ⟨m + (i - n),
        BTMor1.proj ⟨i - n, by omega⟩⟩
    else ⟨i - n, BTMor1.leaf⟩

/-- Simultaneous substitution: replace each free
variable in a term with a term from the substitution.
Defined via `polyFixFoldAtWithProof` with the
substitution algebra. -/
def BTMor1.subst {n m : ℕ}
    (t : BTMor1 n)
    (σ : Fin n → BTMor1 m) : BTMor1 m :=
  let result :=
    (polyFixFoldAtWithProof btMorPoly
      substAlg n t).val.2 (totalSubst σ)
  if h : result.1 = m then h ▸ result.2
  else BTMor1.leaf

/-! ## Morphism operations -/

/-- Composition of morphisms via substitution. -/
def BTMorN.comp {n m k : ℕ}
    (f : BTMorN n m) (g : BTMorN m k) :
    BTMorN n k :=
  fun j => (g j).subst f

/-! ## Full fold (universal property of the
parameterized BTO)

The full universal property of the parameterized
binary tree object with arbitrary target dimension:
given `f : n → m` and `g : (m + m) → m`, produce
`φ : (n + 1) → m`.

The fold uses `BT.fold` with carrier `Fin m → BT`
so that all `m` output components are computed
simultaneously in a single pass over the tree.
At each leaf, the `m` outputs are computed by `f`
applied to the `n` context variables.  At each
branch, the `m` outputs are computed by `g` applied
to the concatenation of the `m` left results and `m`
right results.

The `BTMor1.fold` constructor's step child has two
recursive-result variables, which suffices for
`m = 1` but not for coupled mutual recursion with
`m > 1`.  The definition `btFoldFull` works for all
`m` by folding BT values directly with carrier
`Fin m → BT.{0}`.  The syntactic version `btFold`
(for `m = 1`) constructs a `BTMor1.fold` term.
-/

/-- Concatenate two `Fin`-indexed tuples into a
single tuple indexed by `Fin (a + b)`. -/
def finAppend {a b : ℕ} {α : Type}
    (l : Fin a → α) (r : Fin b → α) :
    Fin (a + b) → α :=
  fun i =>
    if h : i.val < a then l ⟨i.val, h⟩
    else r ⟨i.val - a, by omega⟩

/-- The full universal property of the parameterized
BTO: given `f : n → m` (base) and `g : (m + m) → m`
(step), produce a morphism `(n + 1) → m` as a
function on BT contexts.

The last element of the `(n + 1)`-tuple is the tree
being folded.  Uses `BT.fold` with carrier
`Fin m → BT.{0}` to compute all `m` outputs in a
single pass. -/
def btFoldFull {n m : ℕ}
    (f : BTMorN n m) (g : BTMorN (m + m) m)
    (ctx : Fin (n + 1) → BT.{0}) :
    Fin m → BT.{0} :=
  let baseCtx : Fin n → BT.{0} :=
    fun i => ctx ⟨i.val, by omega⟩
  let tree : BT.{0} := ctx ⟨n, by omega⟩
  tree.fold
    (f.interp baseCtx)
    (fun leftAll rightAll =>
      g.interp (finAppend leftAll rightAll))

/-- Fold (the simple universal property with
`X = 1`): given `f : n → 1` and `g : 2 → 1`,
produces `φ : (n + 1) → 1` as a syntactic
`BTMor1.fold` term.

The last variable of `φ` is the tree being folded.
The base case `f` gives the value at leaves (using
the `n` context variables).  The step case `g`
combines two recursive results (no access to the
context). -/
def btFold {n : ℕ}
    (f : BTMorN n 1) (g : BTMorN 2 1) :
    BTMorN (n + 1) 1 :=
  fun _ =>
    BTMor1.fold 1
      (fun _ =>
        (f ⟨0, by omega⟩).shift 1)
      (fun _ => g ⟨0, by omega⟩)
      (BTMor1.proj ⟨n, by omega⟩)
      ⟨0, by omega⟩

/-- The enhanced universal property of the
parameterized BTO: given `f : n → m` (base) and
`g : (n + m + m) → m` (step with context access),
produce `φ : (n + 1) → m` as a function on BT
contexts.

Derived from `btFoldFull` by folding into the
product `A × X` (with `A = n`, `X = m`), so
`btFoldFull` operates on `(n + m)`-tuples.

The construction follows the nLab derivation of the
enhanced parameterized NNO from the original one:
define `f' : n → (n + m)` and
`g' : (n + m + n + m) → (n + m)` that thread the
context through the fold, then extract the last `m`
components. -/
def btFoldEnhanced {n m : ℕ}
    (f : BTMorN n m)
    (g : BTMorN (n + m + m) m)
    (ctx : Fin (n + 1) → BT.{0}) :
    Fin m → BT.{0} :=
  let f' : BTMorN n (n + m) :=
    BTMorN.pair (BTMorN.id n) f
  let g' : BTMorN ((n + m) + (n + m)) (n + m) :=
    BTMorN.pair
      (fun j => BTMor1.proj ⟨j.val, by omega⟩)
      (fun j => (g j).rename (fun i =>
        if h₁ : i.val < n then
          ⟨i.val, by omega⟩
        else if h₂ : i.val < n + m then
          ⟨i.val, by omega⟩
        else
          ⟨(n + m) + n + (i.val - n - m),
            by omega⟩))
  let result := btFoldFull f' g' ctx
  fun j => result ⟨n + j.val, by omega⟩

/-! ## Proof schemes for BTMor1

Proof principles for `BTMor1 = PolyFix btMorPoly`
that mirror the computation schemes.  Just as
`polyFixFold` provides elimination without explicit
recursion, these provide induction and uniqueness
without explicit recursion on the polynomial
structure.
-/

/-- Induction principle for `BTMor1`.  To prove
`P n t` for all `t : BTMor1 n`, provide:
- `hProj`: `P` holds for `proj i`
- `hLeaf`: `P` holds for `leaf`
- `hBranch`: `P` holds for `branch l r` given
  `P` for `l` and `r`
- `hFold`: `P` holds for `fold m f g tree j`
  given `P` for each `f i`, each `g i`, and
  `tree` -/
def BTMor1.ind
    (P : ∀ {n : ℕ}, BTMor1 n → Prop)
    (hProj : ∀ {n : ℕ} (i : Fin n),
      P (BTMor1.proj i))
    (hLeaf : ∀ {n : ℕ},
      P (BTMor1.leaf (n := n)))
    (hBranch : ∀ {n : ℕ}
      (l r : BTMor1 n),
      P l → P r → P (BTMor1.branch l r))
    (hFold : ∀ {n : ℕ} (m : ℕ)
      (f : Fin m → BTMor1 n)
      (g : Fin m → BTMor1 (m + m))
      (tree : BTMor1 n) (j : Fin m),
      (∀ i, P (f i)) →
      (∀ i, P (g i)) →
      P tree →
      P (BTMor1.fold m f g tree j))
    {n : ℕ} (t : BTMor1 n) : P t := by
  exact _

/-- The identity substitution: substituting
projections into a term returns the original term. -/
theorem BTMor1.subst_id {n : ℕ}
    (t : BTMor1 n) :
    t.subst (fun i => BTMor1.proj i) = t := by
  exact _

/-- Substitution composition: substituting twice
equals substituting with the composed
substitution. -/
theorem BTMor1.subst_comp {n m k : ℕ}
    (t : BTMor1 n)
    (σ : Fin n → BTMor1 m)
    (τ : Fin m → BTMor1 k) :
    (t.subst σ).subst τ =
      t.subst (fun i => (σ i).subst τ) := by
  exact _

end GebLean
