import GebLean.LawvereER
import GebLean.Utilities.ZeroTestURM
import Mathlib.Data.Fintype.Basic
import Mathlib.Tactic.FinCases

/-!
# erToK: ER → K^sim_2 via zero-test URM simulation

The compiler half of the erToK construction: emit a
`URMProgram` from an `ERMor1 a` term such that running the
URM long enough produces `e.interp v` in the output
register.

## Main definitions

- `URMInstrRaw`: ℕ-indexed instruction intermediate used
  by compiler combinators before the final register-count
  is known.
- `URMInstrRaw.toBounded`: total conversion from a raw
  instruction to a `URMInstr r`, given a bound proof on
  every register index appearing in the raw instruction.
- `CompiledFragment`: a self-contained compiled URM
  fragment extending `URMProgram a` with a reserved-zero
  register convention used to encode unconditional
  `goto`.
- `CompiledFragment.toURMProgram`: auto-generated by the
  `extends URMProgram a` clause; forgets the reserved-zero
  fields and returns the underlying `URMProgram a`.
- `compileFrag_zero`, `compileFrag_succ`,
  `compileFrag_proj`, `compileFrag_sub`: atomic
  per-ER-constructor fragment combinators (no
  sub-fragment composition).
- `compileFrag_comp`: compositional combinator for
  `ERMor1.comp f gs` — glues sub-fragments via raw-level
  register-space injection and PC-shifting (fused into
  `URMInstrRaw.reindexShift`) and destructive output→input
  transfer between sub-fragments.
- `compileFrag_bsum`: compositional combinator for
  `ERMor1.bsum f` — outer loop on the bound register
  with per-iteration prologue re-cloning outer
  parameters and accumulator update via transferLoop.
- `compileFrag_bprod`: compositional combinator for
  `ERMor1.bprod f` — mirrors `compileFrag_bsum` with a
  multiplicative accumulator (initial value 1) updated
  via Tourlakis 2018 p. 19's R^XY_Z nested-loop
  template.
- `compileER`: the top-level recursive driver
  `{a : ℕ} → ERMor1 a → URMProgram a`. Dispatches to
  the per-constructor combinators via `compileERFrag`
  and forgets the reserved-zero convention via
  `.toURMProgram`.
- `compileER_runtime`: ℕ-valued runtime witness defined
  by structural recursion on `e`; sufficient step count
  for `URMState.runFor (compileER e) v` to halt with
  output register holding `e.interp v`.

## References

- Tourlakis 2018 §0.1.0.37 (pp. 15–16): URM semantics.
- Tourlakis 2018 p. 19: worked URM examples (M template
  for `λx.x`, N template for `λx.x+1`, R^XY_Z template
  for `λxy.xy`).
- Tourlakis 2018 p. 20: Loop-to-URM translation template
  with per-Loop scratch register B.
- Tourlakis 2018 p. 21: bounded-recursion URM template.
- Tourlakis 2018 §0.1.0.42 (p. 18): `f ∈ E^n` is
  URM-computable within time bound in `E^n`.
- Spec §5 (ER → URM compiler):
  `docs/superpowers/specs/2026-05-16-er-to-k-via-cslib-urm-design.md`.

## Tags

URM, compiler, ER, Tourlakis, simulation
-/

namespace GebLean

namespace LawvereERKSim

open GebLean.ZeroTestURM

/-- Raw URM instruction with ℕ-indexed registers and
absolute PC labels. Compiler combinators emit raw
instructions during composition; the final
`CompiledFragment` constructs the `URMInstr numRegs`
array by converting each raw instruction through
`URMInstrRaw.toBounded` once `numRegs` is known.

The five constructors mirror `URMInstr` exactly except
register indices are plain ℕ instead of `Fin r`. Tourlakis
2018 §0.1.0.37 p. 16. -/
inductive URMInstrRaw : Type
  /-- `assignR i c` is Tourlakis's `V_i ← c`. -/
  | assignR (i c : ℕ) : URMInstrRaw
  /-- `incR i` is Tourlakis's `V_i ← V_i + 1`. -/
  | incR (i : ℕ) : URMInstrRaw
  /-- `decR i` is Tourlakis's `V_i ← V_i ∸ 1`. -/
  | decR (i : ℕ) : URMInstrRaw
  /-- `jumpZR i l₁ l₂` is Tourlakis's two-target
  zero-test jump. -/
  | jumpZR (i l₁ l₂ : ℕ) : URMInstrRaw
  /-- `stopR` is Tourlakis's halt. -/
  | stopR : URMInstrRaw
  deriving Repr, DecidableEq, Inhabited

/-- The maximum register index referenced by a raw
instruction, plus 1. Provides the lower bound on
`numRegs` needed to type the instruction as
`URMInstr numRegs`. -/
def URMInstrRaw.regBound : URMInstrRaw → ℕ
  | .assignR i _ => i + 1
  | .incR i => i + 1
  | .decR i => i + 1
  | .jumpZR i _ _ => i + 1
  | .stopR => 0

/-- Convert a raw instruction to a bounded `URMInstr r`,
given a bound proof on the raw instruction's register
index. Total function; the bound proof is consumed at the
`Fin r` construction site. -/
def URMInstrRaw.toBounded
    (r : ℕ) (instr : URMInstrRaw)
    (h : instr.regBound ≤ r) : URMInstr r :=
  match instr, h with
  | .assignR i c, h => .assign ⟨i, h⟩ c
  | .incR i, h => .inc ⟨i, h⟩
  | .decR i, h => .dec ⟨i, h⟩
  | .jumpZR i l₁ l₂, h => .jumpZ ⟨i, h⟩ l₁ l₂
  | .stopR, _ => .stop

/-- All raw instructions in a list have register bound
≤ `r`. -/
def URMInstrRaw.boundedBy (r : ℕ) (l : List URMInstrRaw) :
    Prop :=
  ∀ ins ∈ l, URMInstrRaw.regBound ins ≤ r

/-- Batch-convert a `URMInstrRaw.boundedBy r`-witnessed
list of raw instructions to an `Array (URMInstr r)`.
Uses `List.attach` to carry the membership proof
pointwise. -/
def URMInstrRaw.toBoundedArray (r : ℕ)
    (l : List URMInstrRaw)
    (h : URMInstrRaw.boundedBy r l) :
    Array (URMInstr r) :=
  (l.attach.map (fun ⟨ins, hmem⟩ =>
    URMInstrRaw.toBounded r ins (h ins hmem))).toArray

/-- If a raw instruction list ends with `.stopR`, then its
bounded-array form ends with `.stop`. Used by combinators
to discharge `CompiledFragment.lastInstr_isStop`. -/
private theorem URMInstrRaw.toBoundedArray_back?_of_last_stopR
    {r : ℕ} {l : List URMInstrRaw}
    (h : URMInstrRaw.boundedBy r l)
    (hl : l.getLast? = some .stopR) :
    (URMInstrRaw.toBoundedArray r l h).back? = some .stop := by
  rw [List.getLast?_eq_some_iff] at hl
  obtain ⟨l', hl'⟩ := hl
  subst hl'
  unfold URMInstrRaw.toBoundedArray
  rw [List.back?_toArray, List.attach_append]
  simp only [List.map_append, List.map_cons, List.map_nil,
    List.attach_cons, List.attach_nil, List.getLast?_concat]
  rfl

/-- The size of `toBoundedArray r l h` equals `l.length`. -/
private theorem URMInstrRaw.toBoundedArray_size
    (r : ℕ) (l : List URMInstrRaw)
    (h : URMInstrRaw.boundedBy r l) :
    (URMInstrRaw.toBoundedArray r l h).size = l.length := by
  unfold URMInstrRaw.toBoundedArray
  rw [List.size_toArray, List.length_map, List.length_attach]

/-- Indexing `toBoundedArray r l h` at `i < l.length`
yields `toBounded` applied to the `i`-th raw element. -/
private theorem URMInstrRaw.toBoundedArray_getElem
    (r : ℕ) (l : List URMInstrRaw)
    (h : URMInstrRaw.boundedBy r l)
    (i : ℕ) (hi : i < (URMInstrRaw.toBoundedArray r l h).size) :
    (URMInstrRaw.toBoundedArray r l h)[i] =
      URMInstrRaw.toBounded r (l[i]'(by
        rw [URMInstrRaw.toBoundedArray_size] at hi; exact hi))
        (h _ (List.getElem_mem (by
          rw [URMInstrRaw.toBoundedArray_size] at hi; exact hi))) := by
  unfold URMInstrRaw.toBoundedArray
  rw [List.getElem_toArray, List.getElem_map,
    List.getElem_attach]

/-- `getElem?` form of `toBoundedArray_getElem`: at any
`i < l.length`, the bounded array yields
`some (toBounded …)`. -/
private theorem URMInstrRaw.toBoundedArray_getElem?
    (r : ℕ) (l : List URMInstrRaw)
    (h : URMInstrRaw.boundedBy r l)
    (i : ℕ) (hi : i < l.length) :
    (URMInstrRaw.toBoundedArray r l h)[i]? =
      some (URMInstrRaw.toBounded r (l[i]'hi)
        (h _ (List.getElem_mem hi))) := by
  have hsize : i < (URMInstrRaw.toBoundedArray r l h).size := by
    rw [URMInstrRaw.toBoundedArray_size]; exact hi
  rw [Array.getElem?_eq_getElem hsize,
    URMInstrRaw.toBoundedArray_getElem]

/-- A compiled URM fragment for a sub-expression of arity
`a`. Compositional building block: per-ER-constructor
combinators (`compileFrag_*`) glue sub-fragments into
larger fragments by register-index injection and
PC-shifting; the top-level `compileER` returns the
fragment's underlying `URMProgram a` via the
auto-generated `.toURMProgram`.

Extends `URMProgram a` (the arity-indexed URM kernel
program type, Task 0 refactor); adds the reserved-zero
convention used to encode unconditional `goto` via
`jumpZ V_z l l` per spec §5.1.

Convention: the reserved-zero register is `⟨0, …⟩` and
the first instruction in `instrs` is `assign ⟨0, …⟩ 0`,
defensively initialising it. -/
@[ext] structure CompiledFragment (a : ℕ)
    extends URMProgram a where
  /-- 0 < numRegs (the reserved-zero register exists). -/
  numRegs_pos : 0 < numRegs
  /-- Reserved-zero register `⟨0, numRegs_pos⟩` disjoint
  from all input registers. -/
  zeroReg_not_input : ∀ i, inputRegs i ≠ ⟨0, numRegs_pos⟩
  /-- Reserved-zero register disjoint from the output
  register. -/
  zeroReg_not_output : (⟨0, numRegs_pos⟩ : Fin numRegs)
    ≠ outputReg
  /-- The last instruction is the halt instruction. Used
  by combinators that drop a trailing `.stop` to splice
  sub-fragments together. -/
  lastInstr_isStop : instrs.back? = some .stop

/-- The reserved-zero register `⟨0, F.numRegs_pos⟩`. -/
def CompiledFragment.zeroReg {a : ℕ}
    (F : CompiledFragment a) : Fin F.numRegs :=
  ⟨0, F.numRegs_pos⟩

/-- Encode unconditional `goto l` as Tourlakis's
informal shorthand (p. 19): two-target zero-test jump on
the reserved-zero register `V_z` (= register 0). Both
branches go to `l`, so the jump is unconditional.

Returns a single raw instruction. -/
def URMRaw.goto (l : ℕ) : URMInstrRaw :=
  .jumpZR 0 l l

/-- Destructive transfer `V_dst ← V_dst + V_src;
V_src ← 0`. Body of Tourlakis 2018 p. 19's M program for
`λx.x`, generalised to arbitrary `src` and `dst` and
omitting the trailing `stop`. Emits exactly 4 raw
instructions starting at PC offset `pcBase`; exit PC is
`pcBase + 4`.

Returns the instruction list. The caller is responsible
for placing the returned instructions at `pcBase` in the
overall fragment. -/
def URMRaw.transferLoop (pcBase src dst : ℕ) :
    List URMInstrRaw :=
  [ .jumpZR src (pcBase + 4) (pcBase + 1),
    .decR src,
    .incR dst,
    URMRaw.goto pcBase ]

/-- Number of raw instructions emitted by
`transferLoop`. -/
def URMRaw.transferLoopLen : ℕ := 4

/-- Preserving transfer `V_dst ← V_dst + V_src;
V_src unchanged`. Two destructive-transfer loops via a
tmp register; spec §5.1 register-allocation discipline.
Emits exactly 9 raw instructions starting at PC offset
`pcBase`; exit PC is `pcBase + 9`. -/
def URMRaw.preservingTransfer
    (pcBase src dst tmp : ℕ) : List URMInstrRaw :=
  -- Loop 1: V_src consumed; V_dst, V_tmp accumulate.
  -- PCs pcBase..pcBase+4 (5 instructions):
  [ .jumpZR src (pcBase + 5) (pcBase + 1),  -- pcBase
    .decR src,                              -- pcBase+1
    .incR dst,                              -- pcBase+2
    .incR tmp,                              -- pcBase+3
    URMRaw.goto pcBase,                     -- pcBase+4
  -- Loop 2: V_tmp consumed; V_src restored.
  -- PCs pcBase+5..pcBase+8 (4 instructions):
    .jumpZR tmp (pcBase + 9) (pcBase + 6),  -- pcBase+5
    .decR tmp,                              -- pcBase+6
    .incR src,                              -- pcBase+7
    URMRaw.goto (pcBase + 5) ]              -- pcBase+8

/-- Number of raw instructions emitted by
`preservingTransfer`. -/
def URMRaw.preservingTransferLen : ℕ := 9

/-- Fragment for `ERMor1.zero`. Tourlakis 2018 §0.1.0.37
p. 16 instruction set; spec §5.1 zero template. Output is
the constant 0; emits `assign V_z 0; assign V_out 0;
stop`. -/
def compileFrag_zero : CompiledFragment 0 where
  numRegs := 2
  numRegs_pos := by decide
  inputRegs := Fin.elim0
  outputReg := ⟨1, by decide⟩
  instrs := #[
    .assign ⟨0, by decide⟩ 0,
    .assign ⟨1, by decide⟩ 0,
    .stop ]
  inputRegs_inj := by
    intro a _ _
    exact Fin.elim0 a
  outputReg_not_input := by
    intro i _
    exact Fin.elim0 i
  zeroReg_not_input := by
    intro i _
    exact Fin.elim0 i
  zeroReg_not_output := by decide
  lastInstr_isStop := by decide

/-- Fragment for `ERMor1.succ`. Tourlakis 2018 p. 19
N-template (M plus one increment); spec §5.1 succ
template. Copies the single input to the output
non-destructively, then increments. -/
def compileFrag_succ : CompiledFragment 1 :=
  let rawList : List URMInstrRaw :=
    (.assignR 0 0)
      :: (URMRaw.preservingTransfer 1 2 1 3
          ++ [.incR 1, .stopR])
  have hBound : URMInstrRaw.boundedBy 4 rawList := by
    change ∀ ins ∈ rawList, _
    simp only [rawList, URMRaw.preservingTransfer,
      URMRaw.goto, List.forall_mem_cons,
      List.forall_mem_append, List.not_mem_nil,
      IsEmpty.forall_iff, forall_const]
    decide
  { numRegs := 4
    numRegs_pos := by decide
    inputRegs := fun _ => ⟨2, by decide⟩
    outputReg := ⟨1, by decide⟩
    instrs := URMInstrRaw.toBoundedArray 4 rawList hBound
    inputRegs_inj := by
      intro i j _
      exact Subsingleton.elim _ _
    outputReg_not_input := by
      intro _ h
      exact absurd (congrArg Fin.val h) (by decide)
    zeroReg_not_input := by
      intro _ h
      exact absurd (congrArg Fin.val h) (by decide)
    zeroReg_not_output := by decide
    lastInstr_isStop :=
      URMInstrRaw.toBoundedArray_back?_of_last_stopR hBound
        (by simp [rawList, URMRaw.preservingTransfer,
          URMRaw.goto]) }

/-- Fragment for `ERMor1.proj i`. Spec §5.1 proj
template. Preserving-transfer from input slot `i`'s
register to the output. -/
def compileFrag_proj {k : ℕ} (i : Fin k) :
    CompiledFragment k :=
  let rawList : List URMInstrRaw :=
    (.assignR 0 0)
      :: ((URMRaw.preservingTransfer 1 (2 + i.val) 1 (2 + k))
          ++ [.stopR])
  have hBound : URMInstrRaw.boundedBy (k + 3) rawList := by
    have hi : i.val < k := i.isLt
    intro ins hmem
    -- Decompose membership via simp; rewrite `ins` from
    -- each equality and discharge per disjunct with
    -- `omega` (which sees `hi`).
    simp only [rawList, URMRaw.preservingTransfer,
      URMRaw.goto, List.mem_cons, List.mem_append,
      List.not_mem_nil, or_false] at hmem
    rcases hmem with h | h | h
    · rw [h]; simp only [URMInstrRaw.regBound]; omega
    · rcases h with h | h | h | h | h | h | h | h | h <;>
        (rw [h]; simp only [URMInstrRaw.regBound]; omega)
    · rw [h]; simp only [URMInstrRaw.regBound]; omega
  { numRegs := k + 3
    numRegs_pos := by omega
    inputRegs := fun j => ⟨2 + j.val, by omega⟩
    outputReg := ⟨1, by omega⟩
    instrs := URMInstrRaw.toBoundedArray (k + 3) rawList hBound
    inputRegs_inj := by
      intro p q hpq
      apply Fin.ext
      have h : (2 + p.val : ℕ) = (2 + q.val : ℕ) :=
        congrArg Fin.val hpq
      omega
    outputReg_not_input := by
      intro p hp
      have h : (2 + p.val : ℕ) = (1 : ℕ) :=
        congrArg Fin.val hp
      omega
    zeroReg_not_input := by
      intro p hp
      have h : (2 + p.val : ℕ) = (0 : ℕ) :=
        congrArg Fin.val hp
      omega
    zeroReg_not_output := by
      intro h
      have h' : (0 : ℕ) = (1 : ℕ) := congrArg Fin.val h
      omega
    lastInstr_isStop :=
      URMInstrRaw.toBoundedArray_back?_of_last_stopR hBound
        (by simp [rawList, URMRaw.preservingTransfer,
          URMRaw.goto]) }

/-- Input register assignment for `compileFrag_sub`:
slot 0 → register 2, slot 1 → register 3. Built via
`Fin.cases` over the two-element `Fin 2`. -/
def compileFrag_sub_inputRegs : Fin 2 → Fin 6 :=
  Fin.cases (⟨2, by decide⟩) (fun _ => ⟨3, by decide⟩)

/-- `compileFrag_sub_inputRegs` on slot 0. -/
@[simp] theorem compileFrag_sub_inputRegs_zero :
    compileFrag_sub_inputRegs 0 = ⟨2, by decide⟩ := rfl

/-- `compileFrag_sub_inputRegs` on slot 1. -/
@[simp] theorem compileFrag_sub_inputRegs_one :
    compileFrag_sub_inputRegs 1 = ⟨3, by decide⟩ := rfl

/-- Fragment for `ERMor1.sub`. Spec §5.1 sub template:
preserving-transfer X to output; destructive copy of Y
to scratch; outer loop decrementing both output and
scratch. Tourlakis 2018 p. 19 M-template plus
Loop-to-URM expansion (p. 20). -/
def compileFrag_sub : CompiledFragment 2 :=
  let rawList : List URMInstrRaw :=
    (.assignR 0 0)
      :: ((URMRaw.preservingTransfer 1 2 1 4)
          ++ (URMRaw.transferLoop 10 3 5)
          ++ [ .jumpZR 5 18 15,
               .decR 5,
               .decR 1,
               URMRaw.goto 14,
               .stopR ])
  have hBound : URMInstrRaw.boundedBy 6 rawList := by
    change ∀ ins ∈ rawList, _
    simp only [rawList, URMRaw.preservingTransfer,
      URMRaw.transferLoop, URMRaw.goto,
      List.forall_mem_cons, List.forall_mem_append,
      List.not_mem_nil, IsEmpty.forall_iff, forall_const]
    decide
  { numRegs := 6
    numRegs_pos := by decide
    inputRegs := compileFrag_sub_inputRegs
    outputReg := ⟨1, by decide⟩
    instrs := URMInstrRaw.toBoundedArray 6 rawList hBound
    inputRegs_inj := by
      intro p q hpq
      -- `p, q : Fin 2` each lie in {0, 1}; the slot-to-
      -- register function is injective on those values.
      -- Use `Fin.cases` (Lean-core eliminator) for a
      -- constructive case-split avoiding mathlib's
      -- `fin_cases` (which pulls in `Classical.choice`).
      apply Fin.ext
      have h := congrArg Fin.val hpq
      revert h
      refine Fin.cases ?_
        (fun i => Fin.cases ?_ (fun j => j.elim0) i) p <;>
        refine Fin.cases ?_
          (fun i => Fin.cases ?_ (fun j => j.elim0) i) q <;>
        intro h <;>
        (first | rfl | (exfalso; revert h; decide))
    outputReg_not_input := by
      intro p hp
      have h := congrArg Fin.val hp
      revert h
      refine Fin.cases ?_
        (fun i => Fin.cases ?_ (fun j => j.elim0) i) p <;>
        intro h <;> revert h <;> decide
    zeroReg_not_input := by
      intro p hp
      have h := congrArg Fin.val hp
      revert h
      refine Fin.cases ?_
        (fun i => Fin.cases ?_ (fun j => j.elim0) i) p <;>
        intro h <;> revert h <;> decide
    zeroReg_not_output := by decide
    lastInstr_isStop :=
      URMInstrRaw.toBoundedArray_back?_of_last_stopR hBound
        (by simp [rawList, URMRaw.preservingTransfer,
          URMRaw.transferLoop, URMRaw.goto]) }

/-- Convert a typed `URMInstr r` to its raw form,
discarding the bound proof on register indices. Used by
`compileFrag_comp` to splice sub-fragment instructions
into the raw-list emission pipeline. -/
def toRawOfBounded {r : ℕ} : URMInstr r → URMInstrRaw
  | .assign i c => .assignR i.val c
  | .inc i => .incR i.val
  | .dec i => .decR i.val
  | .jumpZ i l₁ l₂ => .jumpZR i.val l₁ l₂
  | .stop => .stopR

/-- Register bound of `toRawOfBounded ins` is at most
`r` — every register index in `ins` is a `Fin r`, so its
`Nat`-form `+1` is at most `r`-bounded by the `Fin` proof.
We state the bound as `≤ r` (so callers can chain). -/
theorem regBound_toRawOfBounded_le {r : ℕ} (ins : URMInstr r) :
    (toRawOfBounded ins).regBound ≤ r := by
  cases ins
  · exact Fin.isLt _
  · exact Fin.isLt _
  · exact Fin.isLt _
  · exact Fin.isLt _
  · exact Nat.zero_le _

/-- Reindex and PC-shift a sub-fragment's instructions in
one go at the raw level: emit a `URMInstrRaw` with
register indices shifted by `regOffset` and PC labels
shifted by `pcShift`. -/
def URMInstrRaw.reindexShift (regOffset pcShift : ℕ) :
    URMInstrRaw → URMInstrRaw
  | .assignR i c => .assignR (regOffset + i) c
  | .incR i => .incR (regOffset + i)
  | .decR i => .decR (regOffset + i)
  | .jumpZR i l₁ l₂ =>
      .jumpZR (regOffset + i) (pcShift + l₁) (pcShift + l₂)
  | .stopR => .stopR

/-- Cumulative register count of the first `n`
sub-fragments. Used by `compileFrag_comp` to lay out
disjoint register blocks. -/
private def gsPrefixSum {k a : ℕ}
    (frag_gs : Fin k → CompiledFragment a) :
    ℕ → ℕ
  | 0 => 0
  | n + 1 =>
    gsPrefixSum frag_gs n
      + (if h : n < k then (frag_gs ⟨n, h⟩).numRegs else 0)

/-- The block size contributed by `frag_gs i` to the
prefix sum equals `(frag_gs i).numRegs`. -/
private theorem gsPrefixSum_succ_eq {k a : ℕ}
    (frag_gs : Fin k → CompiledFragment a) (i : Fin k) :
    gsPrefixSum frag_gs (i.val + 1)
      = gsPrefixSum frag_gs i.val + (frag_gs i).numRegs := by
  change gsPrefixSum frag_gs i.val
      + (if h : i.val < k then (frag_gs ⟨i.val, h⟩).numRegs else 0)
    = gsPrefixSum frag_gs i.val + (frag_gs i).numRegs
  simp only [i.isLt, dite_true, Fin.eta]

/-- `gsPrefixSum` is monotone. -/
private theorem gsPrefixSum_mono {k a : ℕ}
    (frag_gs : Fin k → CompiledFragment a) {n m : ℕ}
    (h : n ≤ m) :
    gsPrefixSum frag_gs n ≤ gsPrefixSum frag_gs m := by
  induction h with
  | refl => exact Nat.le_refl _
  | step _ ih =>
    refine Nat.le_trans ih ?_
    change gsPrefixSum frag_gs _
      ≤ gsPrefixSum frag_gs _ + (if h : _ < k then _ else 0)
    split <;> omega

/-- Boundedness lemma for `preservingTransfer`: every
emitted raw instruction has register bound at most
`max(src, dst, tmp) + 1`. -/
theorem boundedBy_preservingTransfer (r pcBase src dst tmp : ℕ)
    (hsrc : src + 1 ≤ r) (hdst : dst + 1 ≤ r)
    (htmp : tmp + 1 ≤ r) :
    URMInstrRaw.boundedBy r
      (URMRaw.preservingTransfer pcBase src dst tmp) := by
  intro ins hmem
  simp only [URMRaw.preservingTransfer, URMRaw.goto,
    List.mem_cons, List.not_mem_nil,
    or_false] at hmem
  rcases hmem with h | h | h | h | h | h | h | h | h <;>
    (rw [h]; simp only [URMInstrRaw.regBound]; omega)

/-- Boundedness lemma for `transferLoop`. -/
theorem boundedBy_transferLoop (r pcBase src dst : ℕ)
    (hsrc : src + 1 ≤ r) (hdst : dst + 1 ≤ r) :
    URMInstrRaw.boundedBy r
      (URMRaw.transferLoop pcBase src dst) := by
  intro ins hmem
  simp only [URMRaw.transferLoop, URMRaw.goto,
    List.mem_cons, List.not_mem_nil,
    or_false] at hmem
  rcases hmem with h | h | h | h <;>
    (rw [h]; simp only [URMInstrRaw.regBound]; omega)

/-- Bound on `URMInstrRaw.reindexShift`. -/
theorem regBound_reindexShift_le_offset_add
    (regOffset pcShift bound : ℕ)
    (ins : URMInstrRaw) (h : ins.regBound ≤ bound) :
    (URMInstrRaw.reindexShift regOffset pcShift ins).regBound
      ≤ regOffset + bound := by
  cases ins <;>
    simp only [URMInstrRaw.reindexShift, URMInstrRaw.regBound] <;>
    (revert h; simp only [URMInstrRaw.regBound]; omega)

/-- Block at offset `pcBase` for sub-fragment `i`:
input-wiring preamble (`a` copies of `preservingTransfer`
moving outer input `j` into the reindexed slot of
`(frag_gs i).inputRegs j`), then `gs i`'s instructions
(minus trailing stop) reindexed and PC-shifted, then a
destructive `transferLoop` wiring `gs i`'s output into
`f`'s `i`-th input slot. -/
private def compileFrag_comp_subBlock {k a : ℕ}
    (frag_f : CompiledFragment k)
    (frag_gs : Fin k → CompiledFragment a)
    (gsBase fBase tmpReg : ℕ) (i : Fin k) (pcBase : ℕ) :
    List URMInstrRaw :=
  let bodyBase : ℕ := pcBase + 9 * a
  let trBase : ℕ :=
    bodyBase + ((frag_gs i).instrs.size - 1)
  let inputCopies : List URMInstrRaw :=
    (List.finRange a).flatMap fun j =>
      URMRaw.preservingTransfer
        (pcBase + 9 * j.val)
        (2 + j.val)
        (gsBase + ((frag_gs i).inputRegs j).val)
        tmpReg
  let body : List URMInstrRaw :=
    (frag_gs i).instrs.pop.toList.map fun ins =>
      URMInstrRaw.reindexShift gsBase bodyBase (toRawOfBounded ins)
  let transfer : List URMInstrRaw :=
    URMRaw.transferLoop trBase
      (gsBase + ((frag_gs i).outputReg).val)
      (fBase + (frag_f.inputRegs i).val)
  inputCopies ++ body ++ transfer

/-- Boundedness lemma for `compileFrag_comp_subBlock`:
each emitted raw instruction has register bound at most
`nR`, given arithmetic bounds linking `gsBase`, `fBase`,
`tmpReg`, the sub-fragment's register count, and `f`'s
register count. -/
private theorem boundedBy_compileFrag_comp_subBlock {k a : ℕ}
    (frag_f : CompiledFragment k)
    (frag_gs : Fin k → CompiledFragment a)
    (gsBase fBase tmpReg nR : ℕ) (i : Fin k) (pcBase : ℕ)
    (hGsBlock : gsBase + (frag_gs i).numRegs ≤ fBase)
    (hFBlock : fBase + frag_f.numRegs = tmpReg)
    (hTmp : tmpReg < nR) (ha : a ≤ fBase) :
    URMInstrRaw.boundedBy nR
      (compileFrag_comp_subBlock frag_f frag_gs
        gsBase fBase tmpReg i pcBase) := by
  unfold compileFrag_comp_subBlock
  -- bound facts shared across all three sub-lists
  have hOut : gsBase + ((frag_gs i).outputReg).val + 1 ≤ nR := by
    have hO : ((frag_gs i).outputReg).val < (frag_gs i).numRegs :=
      (frag_gs i).outputReg.isLt
    omega
  have hFIn : fBase + (frag_f.inputRegs i).val + 1 ≤ nR := by
    have hI : (frag_f.inputRegs i).val < frag_f.numRegs :=
      (frag_f.inputRegs i).isLt
    omega
  have hTmpR : tmpReg + 1 ≤ nR := by omega
  intro ins hmem
  simp only [List.mem_append, List.mem_flatMap,
    List.mem_map] at hmem
  rcases hmem with ((⟨j, _, hj⟩) | ⟨ins', _, heq⟩) | hT
  · -- inputCopies branch
    have hJa : j.val + 1 ≤ a := j.isLt
    have hSrc : (2 + j.val) + 1 ≤ nR := by omega
    have hDst : (gsBase + ((frag_gs i).inputRegs j).val) + 1 ≤ nR := by
      have hI : ((frag_gs i).inputRegs j).val < (frag_gs i).numRegs :=
        ((frag_gs i).inputRegs j).isLt
      omega
    exact boundedBy_preservingTransfer nR _ _ _ _ hSrc hDst hTmpR ins hj
  · -- body branch
    rw [← heq]
    have hb : (toRawOfBounded ins').regBound ≤ (frag_gs i).numRegs :=
      regBound_toRawOfBounded_le ins'
    have hr := regBound_reindexShift_le_offset_add gsBase
      (pcBase + 9 * a) (frag_gs i).numRegs (toRawOfBounded ins') hb
    omega
  · -- transfer branch
    exact boundedBy_transferLoop nR _ _ _ hOut hFIn ins hT

/-- Fragment for `ERMor1.comp f gs`. Spec §5.1.2:
sequentially run each sub-URM `gs i` (after a
preserving-transfer preamble that copies outer inputs into
`gs i`'s input slots), destructively transfer its output
into `f`'s `i`-th input slot via `transferLoop`, then run
`f`'s URM (whose own trailing `stop` becomes the outer
fragment's halt instruction). Tourlakis 2018 p. 21
"concatenate M_g and M_f".

Design choice: each sub-fragment is allocated a disjoint
register block of size `(frag_gs i).numRegs` (so its
internal zero register, distinct from the outer zero
register, is initialised by its own first-instruction
`assign 0 0` once reindexed). One shared scratch register
at slot `numRegs - 1` services every `preservingTransfer`
input-wiring step. `f`'s block sits immediately after the
last `gs i` block. -/
def compileFrag_comp {k a : ℕ}
    (frag_f : CompiledFragment k)
    (frag_gs : Fin k → CompiledFragment a) :
    CompiledFragment a :=
  let totalGsRegs : ℕ := gsPrefixSum frag_gs k
  let fBase : ℕ := 2 + a + totalGsRegs
  let tmpReg : ℕ := fBase + frag_f.numRegs
  let nR : ℕ := tmpReg + 1
  let gsBase : Fin k → ℕ :=
    fun i => 2 + a + gsPrefixSum frag_gs i.val
  -- Cumulative PC offset before block `i`. The whole
  -- emission begins with one `assign 0 0` at PC 0, so
  -- block `i`'s base PC is `1 + Σ_{j < i} (per-block
  -- length)`; this is encoded inline by threading
  -- `pcBase` through a `List.foldl` rather than as a
  -- separate prefix-sum function.
  let blockLen : Fin k → ℕ := fun i =>
    9 * a + ((frag_gs i).instrs.size - 1) + 4
  let pcBase : Fin k → ℕ := fun i =>
    1 + ((List.finRange k).filter
        (fun j => decide (j.val < i.val))).foldr
      (fun j acc => acc + blockLen j) 0
  let subBlocks : List URMInstrRaw :=
    (List.finRange k).flatMap fun i =>
      compileFrag_comp_subBlock frag_f frag_gs
        (gsBase i) fBase tmpReg i (pcBase i)
  let fPcBase : ℕ :=
    1 + (List.finRange k).foldr
      (fun j acc => acc + blockLen j) 0
  let fBody : List URMInstrRaw :=
    frag_f.instrs.toList.map fun ins =>
      URMInstrRaw.reindexShift fBase fPcBase (toRawOfBounded ins)
  let rawList : List URMInstrRaw :=
    (.assignR 0 0) :: (subBlocks ++ fBody)
  -- Shared arithmetic bounds.
  have hTmpLt : tmpReg < nR := by simp only [nR]; omega
  have hFBlockEq : fBase + frag_f.numRegs = tmpReg := by
    simp only [tmpReg]
  have ha_le : a ≤ fBase := by
    simp only [fBase]; omega
  have hGsBlock : ∀ i : Fin k,
      gsBase i + (frag_gs i).numRegs ≤ fBase := by
    intro i
    have hmono : gsPrefixSum frag_gs (i.val + 1)
        ≤ gsPrefixSum frag_gs k :=
      gsPrefixSum_mono frag_gs i.isLt
    have hsucc :
        gsPrefixSum frag_gs (i.val + 1)
          = gsPrefixSum frag_gs i.val + (frag_gs i).numRegs :=
      gsPrefixSum_succ_eq frag_gs i
    simp only [gsBase, fBase, totalGsRegs]
    omega
  have hBound : URMInstrRaw.boundedBy nR rawList := by
    intro ins hmem
    have hmem' : ins = (.assignR 0 0 : URMInstrRaw)
        ∨ ins ∈ subBlocks ++ fBody := List.mem_cons.mp hmem
    rcases hmem' with hAssign | hmem
    · -- `assignR 0 0` (head of rawList)
      rw [hAssign]; simp only [URMInstrRaw.regBound]
      simp only [nR, tmpReg, fBase]; omega
    rcases List.mem_append.mp hmem with hSub | hF
    · -- sub-block branch
      rcases List.mem_flatMap.mp hSub with ⟨i, _, hi⟩
      exact boundedBy_compileFrag_comp_subBlock frag_f frag_gs
        (gsBase i) fBase tmpReg nR i (pcBase i)
        (hGsBlock i) hFBlockEq hTmpLt ha_le ins hi
    · -- f-body branch
      rcases List.mem_map.mp hF with ⟨ins', _, heq⟩
      rw [← heq]
      have hb : (toRawOfBounded ins').regBound ≤ frag_f.numRegs :=
        regBound_toRawOfBounded_le ins'
      have hr := regBound_reindexShift_le_offset_add fBase
        fPcBase frag_f.numRegs (toRawOfBounded ins') hb
      omega
  have hFInstrsLast : frag_f.instrs.toList.getLast?
      = some (URMInstr.stop : URMInstr frag_f.numRegs) := by
    rw [Array.getLast?_toList]; exact frag_f.lastInstr_isStop
  have hFBodyLast : fBody.getLast? = some .stopR := by
    simp only [fBody, List.getLast?_map, hFInstrsLast,
      Option.map_some]
    rfl
  have hFBodyNe : fBody ≠ [] := by
    intro he; rw [he] at hFBodyLast; simp at hFBodyLast
  have hLastStopR : rawList.getLast? = some .stopR := by
    have hSubFLast :
        (subBlocks ++ fBody).getLast? = some .stopR :=
      List.getLast?_append_of_ne_nil _ hFBodyNe ▸ hFBodyLast
    simp only [rawList, List.getLast?_cons, hSubFLast,
      Option.getD_some]
  { numRegs := nR
    numRegs_pos := by
      simp only [nR]; omega
    inputRegs := fun j => ⟨2 + j.val, by
      have : j.val < a := j.isLt
      simp only [nR, tmpReg, fBase]; omega⟩
    outputReg := ⟨fBase + frag_f.outputReg.val, by
      have hO : frag_f.outputReg.val < frag_f.numRegs :=
        frag_f.outputReg.isLt
      simp only [nR, tmpReg]; omega⟩
    instrs := URMInstrRaw.toBoundedArray nR rawList hBound
    inputRegs_inj := by
      intro p q hpq
      apply Fin.ext
      have h : (2 + p.val : ℕ) = (2 + q.val : ℕ) :=
        congrArg Fin.val hpq
      omega
    outputReg_not_input := by
      intro p hp
      have hp_lt : p.val < a := p.isLt
      have h : (2 + p.val : ℕ) = (fBase + frag_f.outputReg.val : ℕ) :=
        congrArg Fin.val hp
      simp only [fBase] at h
      omega
    zeroReg_not_input := by
      intro p hp
      have h : (2 + p.val : ℕ) = (0 : ℕ) :=
        congrArg Fin.val hp
      omega
    zeroReg_not_output := by
      intro h
      have h' : (0 : ℕ) = (fBase + frag_f.outputReg.val : ℕ) :=
        congrArg Fin.val h
      simp only [fBase] at h'
      omega
    lastInstr_isStop :=
      URMInstrRaw.toBoundedArray_back?_of_last_stopR hBound
        hLastStopR }

/-- Source register for the per-iteration prologue at
slot `s : Fin (k + 1)`. Slot 0 receives the iteration
index `V_i` (located at register `k + 4`); slots `1..k`
receive the outer parameter at register `s.val + 2`. -/
private def bsum_prologueSrc (k : ℕ) (s : Fin (k + 1)) : ℕ :=
  if s.val = 0 then k + 4 else s.val + 2

/-- Per-slot block of the `compileFrag_bsum` per-iteration
prologue: copy the outer register at `bsum_prologueSrc k s`
into f's `s`-th input register (reindexed by `fBase`),
using `tmp1` as scratch. Each iteration's prologue is
preceded by a zero-sweep over all of f's reindexed registers
(`bsum_zeroSweep` below), so `preservingTransfer`'s additive
write produces the current iteration's source value rather
than accumulating across iterations; the zero-sweep also
flushes any internal scratches that nested combinators
inside `frag_f` may have left in f's register block.
Emitted at PC offset `prologueBase + 9 * s.val`; emits
exactly 9 raw instructions. -/
private def bsum_prologueBlock {k : ℕ}
    (frag_f : CompiledFragment (k + 1))
    (fBase tmp1 prologueBase : ℕ) (s : Fin (k + 1)) :
    List URMInstrRaw :=
  URMRaw.preservingTransfer
    (prologueBase + 9 * s.val)
    (bsum_prologueSrc k s)
    (fBase + (frag_f.inputRegs s).val)
    tmp1

/-- Boundedness lemma for `bsum_prologueBlock`: every
emitted raw instruction has register bound at most `nR`,
given arithmetic facts placing `bsum_prologueSrc k s`,
`fBase + (frag_f.inputRegs s).val`, and `tmp1` inside
`nR`. -/
private theorem boundedBy_bsum_prologueBlock {k : ℕ}
    (frag_f : CompiledFragment (k + 1))
    (fBase tmp1 prologueBase nR : ℕ) (s : Fin (k + 1))
    (hSrc : bsum_prologueSrc k s + 1 ≤ nR)
    (hDst : fBase + (frag_f.inputRegs s).val + 1 ≤ nR)
    (hTmp : tmp1 + 1 ≤ nR) :
    URMInstrRaw.boundedBy nR
      (bsum_prologueBlock frag_f fBase tmp1 prologueBase s) := by
  intro ins hpT
  simp only [bsum_prologueBlock] at hpT
  exact boundedBy_preservingTransfer nR _ _ _ _ hSrc hDst hTmp ins hpT

/-- Zero-sweep over all of f's reindexed registers
(`frag_f.numRegs` `assignR` instructions emitting
`assignR (fBase + r) 0` for `r ∈ [0, frag_f.numRegs)`).
Run at the start of each `compileFrag_bsum` iteration's
prologue to flush f's entire register block; this ensures
nested combinators inside `frag_f` whose internal scratches
accumulate additively (e.g. `compileFrag_comp`'s gs-input
slots) start each iteration from zero. -/
private def bsum_zeroSweep {k : ℕ}
    (frag_f : CompiledFragment (k + 1)) (fBase : ℕ) :
    List URMInstrRaw :=
  (List.finRange frag_f.numRegs).map fun r =>
    (.assignR (fBase + r.val) 0 : URMInstrRaw)

/-- Boundedness lemma for `bsum_zeroSweep`: every emitted
instruction targets a register inside `nR`, given
`fBase + frag_f.numRegs ≤ nR`. -/
private theorem boundedBy_bsum_zeroSweep {k : ℕ}
    (frag_f : CompiledFragment (k + 1)) (fBase nR : ℕ)
    (hBlock : fBase + frag_f.numRegs ≤ nR) :
    URMInstrRaw.boundedBy nR (bsum_zeroSweep frag_f fBase) := by
  intro ins hmem
  simp only [bsum_zeroSweep, List.mem_map] at hmem
  rcases hmem with ⟨r, _, heq⟩
  rw [← heq]
  simp only [URMInstrRaw.regBound]
  have hr : r.val < frag_f.numRegs := r.isLt
  omega

/-- Fragment for `ERMor1.bsum f`. Spec §5.1, §5.1.1.
Outer Loop with iteration-counter register `V_i`
incrementing each iteration and bound register `V_x`
decrementing each iteration. Per-iteration prologue
re-clones outer parameters and writes `V_i` to f's
slot-0 scratch. Inner body invokes `frag_f`'s URM
(reindexed and PC-shifted) and `transferLoop`-adds
f's output into the bsum's output register.
Tourlakis 2018 p. 21 bounded-recursion template. -/
def compileFrag_bsum {k : ℕ}
    (frag_f : CompiledFragment (k + 1)) :
    CompiledFragment (k + 1) :=
  -- Register layout (outer):
  --   0     : V_z (reserved zero)
  --   1     : V_acc (accumulator / outputReg)
  --   2     : V_bound_in (outer input slot 0)
  --   3..k+2: V_param_j (outer input slots 1..k)
  --   k + 3 : V_x  (destructive clone of V_bound_in)
  --   k + 4 : V_i  (iteration index)
  --   k + 5 : tmp1 (scratch for preservingTransfer)
  --   k + 6 : tmp2 (scratch for cloning bound into V_x)
  --   k+7.. : f's reindexed registers (block size = frag_f.numRegs)
  let vAcc : ℕ := 1
  let vBoundIn : ℕ := 2
  let vX : ℕ := k + 3
  let vI : ℕ := k + 4
  let tmp1 : ℕ := k + 5
  let tmp2 : ℕ := k + 6
  let fBase : ℕ := k + 7
  let nR : ℕ := fBase + frag_f.numRegs
  -- PC layout (offsets are absolute):
  --   0  : assignR 0 0     (V_z ← 0)
  --   1  : assignR vAcc 0
  --   2  : assignR vX 0
  --   3  : assignR vI 0
  --   4..12 : preservingTransfer 4 vBoundIn vX tmp2  (9 instrs)
  --   13 : jumpZR vX exitPC bodyStartPC          (loop top)
  --   14 : decR vX                                (body start)
  --   15..(15 + frag_f.numRegs - 1) : zero-sweep over f's block
  --     (`frag_f.numRegs` `assignR (fBase + r) 0` instructions);
  --     flushes f's reindexed register block at the start of each
  --     iteration so internal scratches of nested combinators
  --     inside f do not accumulate across iterations.
  --   (15 + frag_f.numRegs)..(bodyPCBase - 1) : per-iter prologue,
  --     k+1 blocks of `preservingTransfer` (9 instrs each)
  --     copying outer sources into f's input slots.
  --   bodyPCBase = 15 + frag_f.numRegs + 9 * (k + 1) :
  --     f's body (frag_f.instrs.size - 1 instrs, reindexed and PC-shifted)
  --   bodyPCBase + fBodyLen .. + 3 : transferLoop f-out → vAcc (4 instrs)
  --   bodyPCBase + fBodyLen + 4 : incR vI
  --   bodyPCBase + fBodyLen + 5 : goto topPC
  --   exitPC = bodyPCBase + fBodyLen + 6 : stopR
  let topPC : ℕ := 13
  let bodyStartPC : ℕ := 14
  let zeroSweepBase : ℕ := 15
  let prologueBase : ℕ := 15 + frag_f.numRegs
  let bodyPCBase : ℕ := 15 + frag_f.numRegs + 9 * (k + 1)
  let fBodyLen : ℕ := frag_f.instrs.size - 1
  let trBase : ℕ := bodyPCBase + fBodyLen
  let incIPC : ℕ := trBase + 4
  let gotoTopPC : ℕ := trBase + 5
  let exitPC : ℕ := trBase + 6
  let prelude : List URMInstrRaw :=
    [ .assignR 0 0,
      .assignR vAcc 0,
      .assignR vX 0,
      .assignR vI 0 ]
        ++ URMRaw.preservingTransfer 4 vBoundIn vX tmp2
  let loopTop : List URMInstrRaw :=
    [ .jumpZR vX exitPC bodyStartPC,
      .decR vX ]
  let zeroSweep : List URMInstrRaw :=
    bsum_zeroSweep frag_f fBase
  let prologue : List URMInstrRaw :=
    (List.finRange (k + 1)).flatMap fun s =>
      bsum_prologueBlock frag_f fBase tmp1 prologueBase s
  let fBody : List URMInstrRaw :=
    frag_f.instrs.pop.toList.map fun ins =>
      URMInstrRaw.reindexShift fBase bodyPCBase (toRawOfBounded ins)
  let accUpdate : List URMInstrRaw :=
    URMRaw.transferLoop trBase
      (fBase + frag_f.outputReg.val) vAcc
  let epilogue : List URMInstrRaw :=
    [ .incR vI, URMRaw.goto topPC, .stopR ]
  let rawList : List URMInstrRaw :=
    prelude ++ loopTop ++ zeroSweep ++ prologue ++ fBody
      ++ accUpdate ++ epilogue
  -- Shared boundedness facts.
  have hAcc : vAcc + 1 ≤ nR := by
    simp only [vAcc, nR, fBase]; omega
  have hBoundIn : vBoundIn + 1 ≤ nR := by
    simp only [vBoundIn, nR, fBase]; omega
  have hVX : vX + 1 ≤ nR := by
    simp only [vX, nR, fBase]; omega
  have hVI : vI + 1 ≤ nR := by
    simp only [vI, nR, fBase]; omega
  have hTmp1 : tmp1 + 1 ≤ nR := by
    simp only [tmp1, nR, fBase]; omega
  have hTmp2 : tmp2 + 1 ≤ nR := by
    simp only [tmp2, nR, fBase]; omega
  have hFOut : fBase + frag_f.outputReg.val + 1 ≤ nR := by
    have : frag_f.outputReg.val < frag_f.numRegs :=
      frag_f.outputReg.isLt
    simp only [nR]; omega
  have hPrologueSrc : ∀ s : Fin (k + 1),
      bsum_prologueSrc k s + 1 ≤ nR := by
    intro s
    have hs : s.val < k + 1 := s.isLt
    simp only [bsum_prologueSrc, nR, fBase]
    split <;> omega
  have hFIn : ∀ s : Fin (k + 1),
      fBase + (frag_f.inputRegs s).val + 1 ≤ nR := by
    intro s
    have : (frag_f.inputRegs s).val < frag_f.numRegs :=
      (frag_f.inputRegs s).isLt
    simp only [nR]; omega
  -- Boundedness of every block.
  have hPreludeBound : URMInstrRaw.boundedBy nR prelude := by
    intro ins hmem
    simp only [prelude, List.mem_append, List.mem_cons,
      List.not_mem_nil, or_false] at hmem
    rcases hmem with (h | h | h | h) | hpT
    · rw [h]; simp only [URMInstrRaw.regBound]; omega
    · rw [h]; simp only [URMInstrRaw.regBound]; exact hAcc
    · rw [h]; simp only [URMInstrRaw.regBound]; exact hVX
    · rw [h]; simp only [URMInstrRaw.regBound]; exact hVI
    · exact boundedBy_preservingTransfer nR _ _ _ _
        hBoundIn hVX hTmp2 ins hpT
  have hLoopTopBound : URMInstrRaw.boundedBy nR loopTop := by
    intro ins hmem
    simp only [loopTop, List.mem_cons, List.not_mem_nil,
      or_false] at hmem
    rcases hmem with h | h <;>
      (rw [h]; simp only [URMInstrRaw.regBound]; exact hVX)
  have hPrologueBound : URMInstrRaw.boundedBy nR prologue := by
    intro ins hmem
    simp only [prologue, List.mem_flatMap] at hmem
    rcases hmem with ⟨s, _, hs⟩
    exact boundedBy_bsum_prologueBlock frag_f fBase tmp1
      prologueBase nR s (hPrologueSrc s) (hFIn s) hTmp1 ins hs
  have hFBodyBound : URMInstrRaw.boundedBy nR fBody := by
    intro ins hmem
    simp only [fBody, List.mem_map] at hmem
    rcases hmem with ⟨ins', _, heq⟩
    rw [← heq]
    have hb : (toRawOfBounded ins').regBound ≤ frag_f.numRegs :=
      regBound_toRawOfBounded_le ins'
    have hr := regBound_reindexShift_le_offset_add fBase
      bodyPCBase frag_f.numRegs (toRawOfBounded ins') hb
    simp only [nR]; omega
  have hAccUpdateBound : URMInstrRaw.boundedBy nR accUpdate :=
    boundedBy_transferLoop nR _ _ _ hFOut hAcc
  have hEpilogueBound : URMInstrRaw.boundedBy nR epilogue := by
    intro ins hmem
    simp only [epilogue, URMRaw.goto, List.mem_cons,
      List.not_mem_nil, or_false] at hmem
    rcases hmem with h | h | h
    · rw [h]; simp only [URMInstrRaw.regBound]; exact hVI
    · rw [h]; simp only [URMInstrRaw.regBound]; omega
    · rw [h]; simp only [URMInstrRaw.regBound]; omega
  have hZeroSweepBound : URMInstrRaw.boundedBy nR zeroSweep := by
    have hBlock : fBase + frag_f.numRegs ≤ nR := by
      simp only [nR]; omega
    exact boundedBy_bsum_zeroSweep frag_f fBase nR hBlock
  have hBound : URMInstrRaw.boundedBy nR rawList := by
    intro ins hmem
    simp only [rawList, List.mem_append] at hmem
    rcases hmem with
      (((((hP | hL) | hZ) | hPr) | hF) | hA) | hE
    · exact hPreludeBound ins hP
    · exact hLoopTopBound ins hL
    · exact hZeroSweepBound ins hZ
    · exact hPrologueBound ins hPr
    · exact hFBodyBound ins hF
    · exact hAccUpdateBound ins hA
    · exact hEpilogueBound ins hE
  -- Last raw instruction is `.stopR` (rightmost element
  -- of `epilogue`).
  have hEpiNeNil : epilogue ≠ [] := by
    simp only [epilogue, ne_eq, reduceCtorEq, not_false_eq_true]
  have hEpiLast : epilogue.getLast? = some .stopR := by
    simp only [epilogue]; rfl
  have hLastStopR : rawList.getLast? = some .stopR := by
    simp only [rawList]
    rw [List.getLast?_append_of_ne_nil _ hEpiNeNil]
    exact hEpiLast
  { numRegs := nR
    numRegs_pos := by simp only [nR, fBase]; omega
    inputRegs := fun j => ⟨2 + j.val, by
      have : j.val < k + 1 := j.isLt
      simp only [nR, fBase]; omega⟩
    outputReg := ⟨1, by simp only [nR, fBase]; omega⟩
    instrs := URMInstrRaw.toBoundedArray nR rawList hBound
    inputRegs_inj := by
      intro p q hpq
      apply Fin.ext
      have h : (2 + p.val : ℕ) = (2 + q.val : ℕ) :=
        congrArg Fin.val hpq
      omega
    outputReg_not_input := by
      intro p hp
      have h : (2 + p.val : ℕ) = (1 : ℕ) :=
        congrArg Fin.val hp
      omega
    zeroReg_not_input := by
      intro p hp
      have h : (2 + p.val : ℕ) = (0 : ℕ) :=
        congrArg Fin.val hp
      omega
    zeroReg_not_output := by
      intro h
      have h' : (0 : ℕ) = (1 : ℕ) := congrArg Fin.val h
      omega
    lastInstr_isStop :=
      URMInstrRaw.toBoundedArray_back?_of_last_stopR hBound
        hLastStopR }

/-- Fragment for `ERMor1.bprod f`. Spec §5.1, §5.1.1.
Mirrors `compileFrag_bsum` with a multiplicative
accumulator; initial value 1 (empty product).
Multiplication accumulator update emits Tourlakis 2018
p. 19's R^XY_Z nested-loop template. -/
def compileFrag_bprod {k : ℕ}
    (frag_f : CompiledFragment (k + 1)) :
    CompiledFragment (k + 1) :=
  -- Register layout (outer):
  --   0     : V_z (reserved zero)
  --   1     : V_acc (accumulator / outputReg)
  --   2     : V_bound_in (outer input slot 0)
  --   3..k+2: V_param_j (outer input slots 1..k)
  --   k + 3 : V_x  (destructive clone of V_bound_in)
  --   k + 4 : V_i  (iteration index)
  --   k + 5 : tmp1 (scratch for prologue preservingTransfer)
  --   k + 6 : tmp2 (scratch for cloning bound into V_x)
  --   k + 7 : V_acc_clone (multiplicative scratch:
  --           destructive copy of V_acc)
  --   k + 8 : V_factor    (destructive copy of V_f_out)
  --   k + 9 : V_mul_tmp   (preservingTransfer scratch
  --           used inside the inner add of the
  --           R^XY_Z multiplication template)
  --   k+10..: f's reindexed registers (block size = frag_f.numRegs)
  let vAcc : ℕ := 1
  let vBoundIn : ℕ := 2
  let vX : ℕ := k + 3
  let vI : ℕ := k + 4
  let tmp1 : ℕ := k + 5
  let tmp2 : ℕ := k + 6
  let vAccClone : ℕ := k + 7
  let vFactor : ℕ := k + 8
  let vMulTmp : ℕ := k + 9
  let fBase : ℕ := k + 10
  let nR : ℕ := fBase + frag_f.numRegs
  -- PC layout (offsets are absolute):
  --   0  : assignR 0 0     (V_z ← 0)
  --   1  : assignR vAcc 0
  --   2  : assignR vX 0
  --   3  : assignR vI 0
  --   4..12 : preservingTransfer 4 vBoundIn vX tmp2 (9 instrs)
  --   13 : incR vAcc       (V_acc ← 1; empty product)
  --   14 : jumpZR vX exitPC bodyStartPC (loop top)
  --   15 : decR vX                            (body start)
  --   16..(16 + frag_f.numRegs - 1) : zero-sweep over f's block
  --     (`frag_f.numRegs` `assignR (fBase + r) 0` instructions).
  --   (16 + frag_f.numRegs)..(bodyPCBase - 1) : per-iter prologue,
  --     `k + 1` blocks of `preservingTransfer` (9 instrs each).
  --   bodyPCBase = 16 + frag_f.numRegs + 9 * (k + 1) :
  --     f's body (frag_f.instrs.size - 1 instrs, reindexed/PC-shifted)
  --   trBase = bodyPCBase + fBodyLen :
  --     accumulator-update block (21 instrs)
  --     trBase..trBase+3   : transferLoop V_acc → V_acc_clone
  --     trBase+4..trBase+7 : transferLoop V_f_out → V_factor
  --     trBase+8           : jumpZR V_factor (trBase+20) (trBase+9)
  --     trBase+9           : decR V_factor
  --     trBase+10..+18     : preservingTransfer
  --                          V_acc_clone → V_acc (9 instrs)
  --     trBase+19          : goto (trBase+8)
  --     trBase+20          : assignR V_acc_clone 0 (reset clone)
  --   trBase+21 : incR vI
  --   trBase+22 : goto topPC
  --   exitPC = trBase + 23 : stopR
  let topPC : ℕ := 14
  let bodyStartPC : ℕ := 15
  let prologueBase : ℕ := 16 + frag_f.numRegs
  let bodyPCBase : ℕ := 16 + frag_f.numRegs + 9 * (k + 1)
  let fBodyLen : ℕ := frag_f.instrs.size - 1
  let trBase : ℕ := bodyPCBase + fBodyLen
  let exitPC : ℕ := trBase + 23
  let prelude : List URMInstrRaw :=
    [ .assignR 0 0,
      .assignR vAcc 0,
      .assignR vX 0,
      .assignR vI 0 ]
        ++ URMRaw.preservingTransfer 4 vBoundIn vX tmp2
        ++ [ .incR vAcc ]
  let loopTop : List URMInstrRaw :=
    [ .jumpZR vX exitPC bodyStartPC,
      .decR vX ]
  let zeroSweep : List URMInstrRaw :=
    bsum_zeroSweep frag_f fBase
  let prologue : List URMInstrRaw :=
    (List.finRange (k + 1)).flatMap fun s =>
      bsum_prologueBlock frag_f fBase tmp1 prologueBase s
  let fBody : List URMInstrRaw :=
    frag_f.instrs.pop.toList.map fun ins =>
      URMInstrRaw.reindexShift fBase bodyPCBase (toRawOfBounded ins)
  let accUpdate : List URMInstrRaw :=
    URMRaw.transferLoop trBase vAcc vAccClone
      ++ URMRaw.transferLoop (trBase + 4)
          (fBase + frag_f.outputReg.val) vFactor
      ++ [ .jumpZR vFactor (trBase + 20) (trBase + 9),
           .decR vFactor ]
      ++ URMRaw.preservingTransfer (trBase + 10)
          vAccClone vAcc vMulTmp
      ++ [ URMRaw.goto (trBase + 8),
           .assignR vAccClone 0 ]
  let epilogue : List URMInstrRaw :=
    [ .incR vI, URMRaw.goto topPC, .stopR ]
  let rawList : List URMInstrRaw :=
    prelude ++ loopTop ++ zeroSweep ++ prologue ++ fBody
      ++ accUpdate ++ epilogue
  -- Shared boundedness facts.
  have hAcc : vAcc + 1 ≤ nR := by
    simp only [vAcc, nR, fBase]; omega
  have hBoundIn : vBoundIn + 1 ≤ nR := by
    simp only [vBoundIn, nR, fBase]; omega
  have hVX : vX + 1 ≤ nR := by
    simp only [vX, nR, fBase]; omega
  have hVI : vI + 1 ≤ nR := by
    simp only [vI, nR, fBase]; omega
  have hTmp1 : tmp1 + 1 ≤ nR := by
    simp only [tmp1, nR, fBase]; omega
  have hTmp2 : tmp2 + 1 ≤ nR := by
    simp only [tmp2, nR, fBase]; omega
  have hAccClone : vAccClone + 1 ≤ nR := by
    simp only [vAccClone, nR, fBase]; omega
  have hFactor : vFactor + 1 ≤ nR := by
    simp only [vFactor, nR, fBase]; omega
  have hMulTmp : vMulTmp + 1 ≤ nR := by
    simp only [vMulTmp, nR, fBase]; omega
  have hFOut : fBase + frag_f.outputReg.val + 1 ≤ nR := by
    have : frag_f.outputReg.val < frag_f.numRegs :=
      frag_f.outputReg.isLt
    simp only [nR]; omega
  have hPrologueSrc : ∀ s : Fin (k + 1),
      bsum_prologueSrc k s + 1 ≤ nR := by
    intro s
    have hs : s.val < k + 1 := s.isLt
    simp only [bsum_prologueSrc, nR, fBase]
    split <;> omega
  have hFIn : ∀ s : Fin (k + 1),
      fBase + (frag_f.inputRegs s).val + 1 ≤ nR := by
    intro s
    have : (frag_f.inputRegs s).val < frag_f.numRegs :=
      (frag_f.inputRegs s).isLt
    simp only [nR]; omega
  -- Boundedness of every block.
  have hPreludeBound : URMInstrRaw.boundedBy nR prelude := by
    intro ins hmem
    simp only [prelude, List.mem_append, List.mem_cons,
      List.not_mem_nil, or_false] at hmem
    rcases hmem with ((h | h | h | h) | hpT) | h
    · rw [h]; simp only [URMInstrRaw.regBound]; omega
    · rw [h]; simp only [URMInstrRaw.regBound]; exact hAcc
    · rw [h]; simp only [URMInstrRaw.regBound]; exact hVX
    · rw [h]; simp only [URMInstrRaw.regBound]; exact hVI
    · exact boundedBy_preservingTransfer nR _ _ _ _
        hBoundIn hVX hTmp2 ins hpT
    · rw [h]; simp only [URMInstrRaw.regBound]; exact hAcc
  have hLoopTopBound : URMInstrRaw.boundedBy nR loopTop := by
    intro ins hmem
    simp only [loopTop, List.mem_cons, List.not_mem_nil,
      or_false] at hmem
    rcases hmem with h | h <;>
      (rw [h]; simp only [URMInstrRaw.regBound]; exact hVX)
  have hPrologueBound : URMInstrRaw.boundedBy nR prologue := by
    intro ins hmem
    simp only [prologue, List.mem_flatMap] at hmem
    rcases hmem with ⟨s, _, hs⟩
    exact boundedBy_bsum_prologueBlock frag_f fBase tmp1
      prologueBase nR s (hPrologueSrc s) (hFIn s) hTmp1 ins hs
  have hFBodyBound : URMInstrRaw.boundedBy nR fBody := by
    intro ins hmem
    simp only [fBody, List.mem_map] at hmem
    rcases hmem with ⟨ins', _, heq⟩
    rw [← heq]
    have hb : (toRawOfBounded ins').regBound ≤ frag_f.numRegs :=
      regBound_toRawOfBounded_le ins'
    have hr := regBound_reindexShift_le_offset_add fBase
      bodyPCBase frag_f.numRegs (toRawOfBounded ins') hb
    simp only [nR]; omega
  have hAccUpdateBound : URMInstrRaw.boundedBy nR accUpdate := by
    intro ins hmem
    simp only [accUpdate, List.mem_append, List.mem_cons,
      List.not_mem_nil, or_false] at hmem
    rcases hmem with
      ((((hTr1 | hTr2) | hOuter) | hInner) | hTail)
    · exact boundedBy_transferLoop nR _ _ _
        hAcc hAccClone ins hTr1
    · exact boundedBy_transferLoop nR _ _ _
        hFOut hFactor ins hTr2
    · rcases hOuter with h | h
      · rw [h]; simp only [URMInstrRaw.regBound]; exact hFactor
      · rw [h]; simp only [URMInstrRaw.regBound]; exact hFactor
    · exact boundedBy_preservingTransfer nR _ _ _ _
        hAccClone hAcc hMulTmp ins hInner
    · rcases hTail with h | h
      · rw [h]; simp only [URMRaw.goto, URMInstrRaw.regBound]
        omega
      · rw [h]; simp only [URMInstrRaw.regBound]; exact hAccClone
  have hEpilogueBound : URMInstrRaw.boundedBy nR epilogue := by
    intro ins hmem
    simp only [epilogue, URMRaw.goto, List.mem_cons,
      List.not_mem_nil, or_false] at hmem
    rcases hmem with h | h | h
    · rw [h]; simp only [URMInstrRaw.regBound]; exact hVI
    · rw [h]; simp only [URMInstrRaw.regBound]; omega
    · rw [h]; simp only [URMInstrRaw.regBound]; omega
  have hZeroSweepBound : URMInstrRaw.boundedBy nR zeroSweep := by
    have hBlock : fBase + frag_f.numRegs ≤ nR := by
      simp only [nR]; omega
    exact boundedBy_bsum_zeroSweep frag_f fBase nR hBlock
  have hBound : URMInstrRaw.boundedBy nR rawList := by
    intro ins hmem
    simp only [rawList, List.mem_append] at hmem
    rcases hmem with
      (((((hP | hL) | hZ) | hPr) | hF) | hA) | hE
    · exact hPreludeBound ins hP
    · exact hLoopTopBound ins hL
    · exact hZeroSweepBound ins hZ
    · exact hPrologueBound ins hPr
    · exact hFBodyBound ins hF
    · exact hAccUpdateBound ins hA
    · exact hEpilogueBound ins hE
  -- Last raw instruction is `.stopR` (rightmost element
  -- of `epilogue`).
  have hEpiNeNil : epilogue ≠ [] := by
    simp only [epilogue, ne_eq, reduceCtorEq, not_false_eq_true]
  have hEpiLast : epilogue.getLast? = some .stopR := by
    simp only [epilogue]; rfl
  have hLastStopR : rawList.getLast? = some .stopR := by
    simp only [rawList]
    rw [List.getLast?_append_of_ne_nil _ hEpiNeNil]
    exact hEpiLast
  { numRegs := nR
    numRegs_pos := by simp only [nR, fBase]; omega
    inputRegs := fun j => ⟨2 + j.val, by
      have : j.val < k + 1 := j.isLt
      simp only [nR, fBase]; omega⟩
    outputReg := ⟨1, by simp only [nR, fBase]; omega⟩
    instrs := URMInstrRaw.toBoundedArray nR rawList hBound
    inputRegs_inj := by
      intro p q hpq
      apply Fin.ext
      have h : (2 + p.val : ℕ) = (2 + q.val : ℕ) :=
        congrArg Fin.val hpq
      omega
    outputReg_not_input := by
      intro p hp
      have h : (2 + p.val : ℕ) = (1 : ℕ) :=
        congrArg Fin.val hp
      omega
    zeroReg_not_input := by
      intro p hp
      have h : (2 + p.val : ℕ) = (0 : ℕ) :=
        congrArg Fin.val hp
      omega
    zeroReg_not_output := by
      intro h
      have h' : (0 : ℕ) = (1 : ℕ) := congrArg Fin.val h
      omega
    lastInstr_isStop :=
      URMInstrRaw.toBoundedArray_back?_of_last_stopR hBound
        hLastStopR }

/-- Recursive driver: emit a `CompiledFragment a` for
each `ERMor1 a` constructor by dispatching to the
per-constructor combinators. -/
def compileERFrag : {a : ℕ} → ERMor1 a → CompiledFragment a
  | _, .zero => compileFrag_zero
  | _, .succ => compileFrag_succ
  | _, .proj i => compileFrag_proj i
  | _, .sub => compileFrag_sub
  | _, .comp f gs =>
      compileFrag_comp (compileERFrag f)
        (fun i => compileERFrag (gs i))
  | _, .bsum f => compileFrag_bsum (compileERFrag f)
  | _, .bprod f => compileFrag_bprod (compileERFrag f)

/-- The top-level ER → URM compiler. Returns a
`URMProgram a` (arity-indexed per Task 0's refactor)
whose execution on input `v : Fin a → ℕ` produces
`e.interp v` in the output register. Spec §5; Tourlakis
2018 §0.1.0.37 (pp. 15–16) URM semantics; Tourlakis
2018 pp. 19–21 per-template constructions. -/
def compileER {a : ℕ} (e : ERMor1 a) : URMProgram a :=
  (compileERFrag e).toURMProgram

/-- Runtime witness: a step count sufficient for
`URMState.runFor (compileER e) v` to reach a state where
the output register holds `e.interp v`. Structural
recursion on `e`; per-template costs match the spec §5.2
shape. Tourlakis 2018 §0.1.0.42 (p. 18) `f ∈ E^n` is
URM-computable within time `t ∈ E^n`. -/
def compileER_runtime : {a : ℕ} → ERMor1 a →
    (Fin a → ℕ) → ℕ
  | _, .zero, _ => 3
  | _, .succ, v => 12 + 10 * v 0
  | _, .proj i, v => 11 + 10 * v i
  | _, .sub, v => 20 + 10 * v 0 + 10 * v 1
  | _, .comp (k := k) f gs, v =>
      let inner : Fin k → ℕ := fun i => (gs i).interp v
      let glue : ℕ :=
        ((List.finRange k).map
          (fun i => compileER_runtime (gs i) v
            + 4 + 5 * inner i)).foldl (· + ·) 0
      glue + compileER_runtime f inner + 2
  | _, .bsum (k := k) f, v =>
      let bound : ℕ := v 0
      let perIter : ℕ → ℕ := fun i =>
        let ctx_f : Fin (k + 1) → ℕ :=
          Fin.cons i (Fin.tail v)
        let outerSum : ℕ :=
          ((List.finRange k).map (Fin.tail v)).foldl
            (· + ·) 0
        compileER_runtime f ctx_f
        + 50 + 10 * (i + outerSum)
        + 5 * f.interp ctx_f
      30 + 10 * bound +
        ((List.range bound).map perIter).foldl (· + ·) 0
  | _, .bprod (k := k) f, v =>
      let bound : ℕ := v 0
      let perIter : ℕ → ℕ := fun i =>
        let ctx_f : Fin (k + 1) → ℕ :=
          Fin.cons i (Fin.tail v)
        let outerSum : ℕ :=
          ((List.finRange k).map (Fin.tail v)).foldl
            (· + ·) 0
        compileER_runtime f ctx_f
        + 60 + 10 * (i + outerSum)
        + 5 * f.interp ctx_f
      40 + 10 * bound +
        ((List.range bound).map perIter).foldl (· + ·) 0

/-- Convert a `getElem?` equality to an indexed `getElem`
plus the corresponding bound proof. Used to feed the
`step` function's `dif_pos`/`match` form from a hypothesis
stated with `[…]?`. -/
private theorem getElem_of_getElem?_some {α : Type*}
    (xs : Array α) (k : ℕ) (a : α)
    (h : xs[k]? = some a) :
    ∃ hk : k < xs.size, xs[k]'hk = a := by
  by_cases hk : k < xs.size
  · refine ⟨hk, ?_⟩
    rw [Array.getElem?_eq_getElem hk] at h
    exact Option.some.inj h
  · rw [Array.getElem?_eq_none (Nat.le_of_not_lt hk)] at h
    exact absurd h (by simp)

/-- One step from a state at PC `pcBase + k` whose
instruction lookup is hypothesised via `[…]?`. Used to
absorb each instruction in a `preservingTransfer` block
without unfolding the literal program. -/
private theorem URMState.step_of_getElem?_jumpZ {a : ℕ}
    (P : URMProgram a) (s : URMState P) (k : ℕ)
    (i : Fin P.numRegs) (l₁ l₂ : ℕ)
    (h_pc : s.pc = k)
    (h_instr : P.instrs[k]? = some (.jumpZ i l₁ l₂)) :
    URMState.step P s =
      { pc := if s.regs i = 0 then l₁ else l₂
        regs := s.regs } := by
  obtain ⟨hk, h_eq⟩ := getElem_of_getElem?_some P.instrs k _ h_instr
  simp only [URMState.step, h_pc, dif_pos hk, h_eq]

private theorem URMState.step_of_getElem?_dec {a : ℕ}
    (P : URMProgram a) (s : URMState P) (k : ℕ)
    (i : Fin P.numRegs)
    (h_pc : s.pc = k)
    (h_instr : P.instrs[k]? = some (.dec i)) :
    URMState.step P s =
      { pc := s.pc + 1
        regs := Function.update s.regs i (s.regs i - 1) } := by
  obtain ⟨hk, h_eq⟩ := getElem_of_getElem?_some P.instrs k _ h_instr
  simp only [URMState.step, h_pc, dif_pos hk, h_eq]

private theorem URMState.step_of_getElem?_inc {a : ℕ}
    (P : URMProgram a) (s : URMState P) (k : ℕ)
    (i : Fin P.numRegs)
    (h_pc : s.pc = k)
    (h_instr : P.instrs[k]? = some (.inc i)) :
    URMState.step P s =
      { pc := s.pc + 1
        regs := Function.update s.regs i (s.regs i + 1) } := by
  obtain ⟨hk, h_eq⟩ := getElem_of_getElem?_some P.instrs k _ h_instr
  simp only [URMState.step, h_pc, dif_pos hk, h_eq]

/-- Hypothesis bundle for `preservingTransfer_correct`:
the nine instruction-lookup equalities at PCs `pcBase..pcBase+8`
matching the raw layout of `URMRaw.preservingTransfer`. The
`zReg` parameter holds the reserved-zero register used by
`URMRaw.goto`; `h_zReg` asserts its value is 0 so the
`goto` jumps fire unconditionally. -/
private structure preservingTransferInstrs {a : ℕ}
    (P : URMProgram a) (pcBase : ℕ)
    (src dst tmp zReg : Fin P.numRegs) : Prop where
  h0 : P.instrs[pcBase]? =
    some (.jumpZ src (pcBase + 5) (pcBase + 1))
  h1 : P.instrs[pcBase + 1]? = some (.dec src)
  h2 : P.instrs[pcBase + 2]? = some (.inc dst)
  h3 : P.instrs[pcBase + 3]? = some (.inc tmp)
  h4 : P.instrs[pcBase + 4]? = some (.jumpZ zReg pcBase pcBase)
  h5 : P.instrs[pcBase + 5]? =
    some (.jumpZ tmp (pcBase + 9) (pcBase + 6))
  h6 : P.instrs[pcBase + 6]? = some (.dec tmp)
  h7 : P.instrs[pcBase + 7]? = some (.inc src)
  h8 : P.instrs[pcBase + 8]? =
    some (.jumpZ zReg (pcBase + 5) (pcBase + 5))

/-- Inner loop 1 of `URMRaw.preservingTransfer`: while
`V_src > 0`, body decrements `V_src` and increments
`V_dst`, `V_tmp`. After `5 * m + 1` steps starting from
`pc = pcBase` and `V_src = m`, the state has
`pc = pcBase + 5`, `V_src = 0`, `V_dst += m`, `V_tmp += m`,
and all other registers unchanged. -/
private theorem preservingTransfer_loop1 {a : ℕ}
    (P : URMProgram a) (pcBase : ℕ)
    (src dst tmp zReg : Fin P.numRegs)
    (h_disj_sd : src ≠ dst) (h_disj_st : src ≠ tmp)
    (h_disj_dt : dst ≠ tmp) (h_disj_zs : zReg ≠ src)
    (h_disj_zd : zReg ≠ dst) (h_disj_zt : zReg ≠ tmp)
    (H : preservingTransferInstrs P pcBase src dst tmp zReg)
    (s : URMState P) (h_pc : s.pc = pcBase)
    (h_z : s.regs zReg = 0)
    (m : ℕ) (h_src : s.regs src = m) :
    let s' := URMState.runFor P s (5 * m + 1)
    s'.pc = pcBase + 5 ∧
    s'.regs src = 0 ∧
    s'.regs dst = s.regs dst + m ∧
    s'.regs tmp = s.regs tmp + m ∧
    s'.regs zReg = 0 ∧
    ∀ r, r ≠ src → r ≠ dst → r ≠ tmp → s'.regs r = s.regs r := by
  -- Move the let-binder into the conclusion explicitly.
  simp only []
  induction m generalizing s with
  | zero =>
    -- 1 step: jumpZR src (pcBase+5) (pcBase+1).  V_src = 0,
    -- so PC → pcBase+5.
    have hstep : (5 * 0 + 1 : ℕ) = 0 + 1 := rfl
    rw [hstep, URMState.runFor_succ, URMState.runFor_zero]
    rw [URMState.step_of_getElem?_jumpZ P s pcBase src
      (pcBase + 5) (pcBase + 1) h_pc H.h0]
    have hsrc_eq : s.regs src = 0 := h_src
    simp only [hsrc_eq, ↓reduceIte]
    refine ⟨trivial, trivial, ?_, ?_, h_z, fun _ _ _ _ => trivial⟩
    · show s.regs dst = s.regs dst + 0
      omega
    · show s.regs tmp = s.regs tmp + 0
      omega
  | succ m ih =>
    -- Peel 5 steps: jumpZ (to pcBase+1), dec src, inc dst,
    -- inc tmp, goto pcBase.  Then apply ih on the resulting
    -- state with V_src = m.
    have h5n : 5 * (m + 1) + 1 = 5 + (5 * m + 1) := by omega
    rw [h5n, URMState.runFor_add]
    -- Compute the state after the first 5 steps via a local lemma.
    -- The 5 steps execute: jumpZ src (taken to pcBase+1), dec src,
    -- inc dst, inc tmp, goto pcBase.
    set s5 : URMState P :=
      { pc := pcBase
        regs := Function.update
          (Function.update
            (Function.update s.regs src (s.regs src - 1))
            dst ((Function.update s.regs src (s.regs src - 1)) dst + 1))
          tmp ((Function.update
            (Function.update s.regs src (s.regs src - 1))
            dst ((Function.update s.regs src (s.regs src - 1)) dst + 1))
            tmp + 1) } with hs5_def
    have h_src_ne : s.regs src ≠ 0 := by rw [h_src]; omega
    have h_five : URMState.runFor P s 5 = s5 := by
      -- Peel 5 steps.
      change URMState.runFor P s (4 + 1) = _
      rw [URMState.runFor_succ]
      rw [URMState.step_of_getElem?_jumpZ P s pcBase src
        (pcBase + 5) (pcBase + 1) h_pc H.h0]
      simp only [h_src_ne, ↓reduceIte]
      set s1 : URMState P :=
        { pc := pcBase + 1, regs := s.regs } with hs1_def
      have hs1_pc : s1.pc = pcBase + 1 := rfl
      change URMState.runFor P s1 (3 + 1) = _
      rw [URMState.runFor_succ,
        URMState.step_of_getElem?_dec P s1 (pcBase + 1) src hs1_pc H.h1]
      set s2 : URMState P :=
        { pc := s1.pc + 1
          regs := Function.update s1.regs src (s1.regs src - 1) } with hs2_def
      have hs2_pc : s2.pc = pcBase + 2 := by
        change s1.pc + 1 = pcBase + 2; rw [hs1_pc]
      change URMState.runFor P s2 (2 + 1) = _
      rw [URMState.runFor_succ,
        URMState.step_of_getElem?_inc P s2 (pcBase + 2) dst hs2_pc H.h2]
      set s3 : URMState P :=
        { pc := s2.pc + 1
          regs := Function.update s2.regs dst (s2.regs dst + 1) } with hs3_def
      have hs3_pc : s3.pc = pcBase + 3 := by
        change s2.pc + 1 = pcBase + 3; rw [hs2_pc]
      change URMState.runFor P s3 (1 + 1) = _
      rw [URMState.runFor_succ,
        URMState.step_of_getElem?_inc P s3 (pcBase + 3) tmp hs3_pc H.h3]
      set s4 : URMState P :=
        { pc := s3.pc + 1
          regs := Function.update s3.regs tmp (s3.regs tmp + 1) } with hs4_def
      have hs4_pc : s4.pc = pcBase + 4 := by
        change s3.pc + 1 = pcBase + 4; rw [hs3_pc]
      change URMState.runFor P s4 (0 + 1) = _
      rw [URMState.runFor_succ, URMState.runFor_zero,
        URMState.step_of_getElem?_jumpZ P s4 (pcBase + 4) zReg
          pcBase pcBase hs4_pc H.h4]
      -- Compute s4.regs zReg = 0.
      have hs4_z : s4.regs zReg = 0 := by
        change Function.update s3.regs tmp _ zReg = 0
        rw [Function.update_of_ne h_disj_zt]
        change Function.update s2.regs dst _ zReg = 0
        rw [Function.update_of_ne h_disj_zd]
        change Function.update s1.regs src _ zReg = 0
        rw [Function.update_of_ne h_disj_zs]
        exact h_z
      simp only [hs4_z, ↓reduceIte]
      -- Goal now: { pc := pcBase, regs := s4.regs } = s5
      rfl
    rw [h_five]
    -- Compute s5's register values via Function.update reasoning.
    have hs5_pc : s5.pc = pcBase := rfl
    -- Compute s5.regs values via Function.update reasoning.
    -- For Function.update_of_ne (h : a ≠ a') : update f a' v a = f a.
    -- We rewrite `Function.update _ X _ Y` where Y ≠ X.
    -- Generic helper: register r ≠ src gives `f0 r = s.regs r`.
    set f0 : Fin P.numRegs → ℕ :=
      Function.update s.regs src (s.regs src - 1) with hf0
    set f1 : Fin P.numRegs → ℕ :=
      Function.update f0 dst (f0 dst + 1) with hf1
    -- f0 reasoning.
    have hf0_dst : f0 dst = s.regs dst :=
      Function.update_of_ne h_disj_sd.symm _ s.regs
    have hf0_tmp : f0 tmp = s.regs tmp :=
      Function.update_of_ne h_disj_st.symm _ s.regs
    have hf0_z : f0 zReg = s.regs zReg :=
      Function.update_of_ne h_disj_zs _ s.regs
    have hf0_other : ∀ r, r ≠ src → f0 r = s.regs r := fun r hrs =>
      Function.update_of_ne hrs _ s.regs
    -- f1 reasoning.
    have hf1_dst : f1 dst = s.regs dst + 1 := by
      change Function.update f0 dst (f0 dst + 1) dst = _
      rw [Function.update_self, hf0_dst]
    have hf1_tmp : f1 tmp = s.regs tmp := by
      change Function.update f0 dst (f0 dst + 1) tmp = _
      rw [Function.update_of_ne h_disj_dt.symm, hf0_tmp]
    have hf1_z : f1 zReg = s.regs zReg := by
      change Function.update f0 dst (f0 dst + 1) zReg = _
      rw [Function.update_of_ne h_disj_zd, hf0_z]
    have hf1_src : f1 src = s.regs src - 1 := by
      change Function.update f0 dst (f0 dst + 1) src = _
      rw [Function.update_of_ne h_disj_sd, hf0]
      change Function.update s.regs src (s.regs src - 1) src = _
      rw [Function.update_self]
    have hf1_other : ∀ r, r ≠ src → r ≠ dst → f1 r = s.regs r := by
      intro r hrs hrd
      change Function.update f0 dst (f0 dst + 1) r = _
      rw [Function.update_of_ne hrd]
      exact hf0_other r hrs
    -- s5 reasoning. s5.regs = update f1 tmp (f1 tmp + 1).
    have hs5_z : s5.regs zReg = 0 := by
      change Function.update f1 tmp (f1 tmp + 1) zReg = 0
      rw [Function.update_of_ne h_disj_zt, hf1_z, h_z]
    have hs5_src : s5.regs src = m := by
      change Function.update f1 tmp (f1 tmp + 1) src = m
      rw [Function.update_of_ne h_disj_st, hf1_src]
      omega
    have hs5_dst : s5.regs dst = s.regs dst + 1 := by
      change Function.update f1 tmp (f1 tmp + 1) dst = _
      rw [Function.update_of_ne h_disj_dt]
      exact hf1_dst
    have hs5_tmp : s5.regs tmp = s.regs tmp + 1 := by
      change Function.update f1 tmp (f1 tmp + 1) tmp = _
      rw [Function.update_self, hf1_tmp]
    have hs5_other : ∀ r, r ≠ src → r ≠ dst → r ≠ tmp →
        s5.regs r = s.regs r := by
      intro r hrs hrd hrt
      change Function.update f1 tmp (f1 tmp + 1) r = _
      rw [Function.update_of_ne hrt]
      exact hf1_other r hrs hrd
    obtain ⟨ih_pc, ih_src, ih_dst, ih_tmp, ih_z, ih_oth⟩ :=
      ih s5 hs5_pc hs5_z hs5_src
    refine ⟨ih_pc, ih_src, ?_, ?_, ih_z, ?_⟩
    · rw [ih_dst, hs5_dst]; omega
    · rw [ih_tmp, hs5_tmp]; omega
    · intro r hrs hrd hrt
      rw [ih_oth r hrs hrd hrt, hs5_other r hrs hrd hrt]

/-- Inner loop 2 of `URMRaw.preservingTransfer`: while
`V_tmp > 0`, body decrements `V_tmp` and increments
`V_src`. After `4 * m + 1` steps starting from
`pc = pcBase + 5` and `V_tmp = m`, the state has
`pc = pcBase + 9`, `V_tmp = 0`, `V_src += m`, and all
other registers unchanged. -/
private theorem preservingTransfer_loop2 {a : ℕ}
    (P : URMProgram a) (pcBase : ℕ)
    (src dst tmp zReg : Fin P.numRegs)
    (h_disj_st : src ≠ tmp)
    (h_disj_zs : zReg ≠ src) (h_disj_zt : zReg ≠ tmp)
    (H : preservingTransferInstrs P pcBase src dst tmp zReg)
    (s : URMState P) (h_pc : s.pc = pcBase + 5)
    (h_z : s.regs zReg = 0)
    (m : ℕ) (h_tmp : s.regs tmp = m) :
    let s' := URMState.runFor P s (4 * m + 1)
    s'.pc = pcBase + 9 ∧
    s'.regs tmp = 0 ∧
    s'.regs src = s.regs src + m ∧
    s'.regs zReg = 0 ∧
    ∀ r, r ≠ src → r ≠ tmp → s'.regs r = s.regs r := by
  simp only []
  induction m generalizing s with
  | zero =>
    have hstep : (4 * 0 + 1 : ℕ) = 0 + 1 := rfl
    rw [hstep, URMState.runFor_succ, URMState.runFor_zero,
      URMState.step_of_getElem?_jumpZ P s (pcBase + 5) tmp
        (pcBase + 9) (pcBase + 6) h_pc H.h5]
    have htmp_eq : s.regs tmp = 0 := h_tmp
    simp only [htmp_eq, ↓reduceIte]
    -- Goal: True (pc) ∧ True (tmp) ∧ src = src + 0 ∧ True (zReg) ∧ ∀, True.
    refine ⟨trivial, trivial, ?_, h_z, fun _ _ _ => trivial⟩
    show s.regs src = s.regs src + 0
    omega
  | succ m ih =>
    have h4n : 4 * (m + 1) + 1 = 4 + (4 * m + 1) := by omega
    rw [h4n, URMState.runFor_add]
    set s4 : URMState P :=
      { pc := pcBase + 5
        regs := Function.update
          (Function.update s.regs tmp (s.regs tmp - 1))
          src ((Function.update s.regs tmp (s.regs tmp - 1)) src + 1) }
      with hs4_def
    have h_tmp_ne : s.regs tmp ≠ 0 := by rw [h_tmp]; omega
    have h_four : URMState.runFor P s 4 = s4 := by
      change URMState.runFor P s (3 + 1) = _
      rw [URMState.runFor_succ,
        URMState.step_of_getElem?_jumpZ P s (pcBase + 5) tmp
          (pcBase + 9) (pcBase + 6) h_pc H.h5]
      simp only [h_tmp_ne, ↓reduceIte]
      set s1 : URMState P :=
        { pc := pcBase + 6, regs := s.regs } with hs1_def
      have hs1_pc : s1.pc = pcBase + 6 := rfl
      change URMState.runFor P s1 (2 + 1) = _
      rw [URMState.runFor_succ,
        URMState.step_of_getElem?_dec P s1 (pcBase + 6) tmp hs1_pc H.h6]
      set s2 : URMState P :=
        { pc := s1.pc + 1
          regs := Function.update s1.regs tmp (s1.regs tmp - 1) } with hs2_def
      have hs2_pc : s2.pc = pcBase + 7 := by
        change s1.pc + 1 = pcBase + 7; rw [hs1_pc]
      change URMState.runFor P s2 (1 + 1) = _
      rw [URMState.runFor_succ,
        URMState.step_of_getElem?_inc P s2 (pcBase + 7) src hs2_pc H.h7]
      set s3 : URMState P :=
        { pc := s2.pc + 1
          regs := Function.update s2.regs src (s2.regs src + 1) } with hs3_def
      have hs3_pc : s3.pc = pcBase + 8 := by
        change s2.pc + 1 = pcBase + 8; rw [hs2_pc]
      change URMState.runFor P s3 (0 + 1) = _
      rw [URMState.runFor_succ, URMState.runFor_zero,
        URMState.step_of_getElem?_jumpZ P s3 (pcBase + 8) zReg
          (pcBase + 5) (pcBase + 5) hs3_pc H.h8]
      have hs3_z : s3.regs zReg = 0 := by
        change Function.update s2.regs src _ zReg = 0
        rw [Function.update_of_ne h_disj_zs]
        change Function.update s1.regs tmp _ zReg = 0
        rw [Function.update_of_ne h_disj_zt]
        exact h_z
      simp only [hs3_z, ↓reduceIte]
      rfl
    rw [h_four]
    have hs4_pc : s4.pc = pcBase + 5 := rfl
    have hs4_z : s4.regs zReg = 0 := by
      change Function.update (Function.update s.regs tmp
        (s.regs tmp - 1)) src _ zReg = 0
      rw [Function.update_of_ne h_disj_zs]
      rw [Function.update_of_ne h_disj_zt]
      exact h_z
    have hs4_tmp : s4.regs tmp = m := by
      change Function.update (Function.update s.regs tmp
        (s.regs tmp - 1)) src _ tmp = m
      rw [Function.update_of_ne h_disj_st.symm]
      rw [Function.update_self]
      omega
    have hs4_src : s4.regs src = s.regs src + 1 := by
      change Function.update (Function.update s.regs tmp
        (s.regs tmp - 1)) src _ src = _
      rw [Function.update_self]
      rw [Function.update_of_ne h_disj_st]
    have hs4_other : ∀ r, r ≠ src → r ≠ tmp →
        s4.regs r = s.regs r := by
      intro r hrs hrt
      change Function.update (Function.update s.regs tmp
        (s.regs tmp - 1)) src _ r = _
      rw [Function.update_of_ne hrs]
      rw [Function.update_of_ne hrt]
    obtain ⟨ih_pc, ih_tmp', ih_src, ih_z, ih_oth⟩ :=
      ih s4 hs4_pc hs4_z hs4_tmp
    refine ⟨ih_pc, ih_tmp', ?_, ih_z, ?_⟩
    · rw [ih_src, hs4_src]; omega
    · intro r hrs hrt
      rw [ih_oth r hrs hrt, hs4_other r hrs hrt]

/-- Correctness of the `URMRaw.preservingTransfer` 9-instruction
block. Running for `9 * n + 2` steps from a state with
`pc = pcBase`, `V_src = n`, `V_tmp = 0`, and the reserved-zero
register `V_zReg = 0` yields a state with `pc = pcBase + 9`,
`V_dst += n`, `V_src = n` (preserved), `V_tmp = 0` (restored
after loop 2 consumes the loop-1 deposit), `V_zReg = 0`, and
all other registers unchanged. The instruction-presence
hypothesis bundles the 9 lookup equalities at offsets `0..8`.

The `V_tmp = 0` precondition reflects the spec's
register-allocation discipline: `tmp` is a fragment-local
scratch zeroed before each `preservingTransfer` invocation
(e.g. by `bsum_zeroSweep` in bsum's outer iteration). -/
private theorem preservingTransfer_correct {a : ℕ}
    (P : URMProgram a) (pcBase : ℕ)
    (src dst tmp zReg : Fin P.numRegs)
    (h_disj_sd : src ≠ dst) (h_disj_st : src ≠ tmp)
    (h_disj_dt : dst ≠ tmp) (h_disj_zs : zReg ≠ src)
    (h_disj_zd : zReg ≠ dst) (h_disj_zt : zReg ≠ tmp)
    (H : preservingTransferInstrs P pcBase src dst tmp zReg)
    (s : URMState P) (h_pc : s.pc = pcBase)
    (h_z : s.regs zReg = 0) (h_tmp0 : s.regs tmp = 0)
    (n : ℕ) (h_src : s.regs src = n) :
    let s' := URMState.runFor P s (9 * n + 2)
    s'.pc = pcBase + 9 ∧
    s'.regs dst = s.regs dst + n ∧
    s'.regs src = n ∧
    s'.regs tmp = 0 ∧
    s'.regs zReg = 0 ∧
    ∀ r, r ≠ dst → s'.regs r = s.regs r := by
  -- 9n + 2 = (5n + 1) + (4n + 1).
  have hsum : 9 * n + 2 = (5 * n + 1) + (4 * n + 1) := by omega
  rw [hsum, URMState.runFor_add]
  obtain ⟨l1_pc, l1_src, l1_dst, l1_tmp, l1_z, l1_oth⟩ :=
    preservingTransfer_loop1 P pcBase src dst tmp zReg
      h_disj_sd h_disj_st h_disj_dt h_disj_zs h_disj_zd h_disj_zt
      H s h_pc h_z n h_src
  set s1 : URMState P := URMState.runFor P s (5 * n + 1)
  -- s1.regs tmp = s.regs tmp + n = 0 + n = n.
  have h_s1_tmp : s1.regs tmp = n := by rw [l1_tmp, h_tmp0]; omega
  obtain ⟨l2_pc, l2_tmp, l2_src, l2_z, l2_oth⟩ :=
    preservingTransfer_loop2 P pcBase src dst tmp zReg
      h_disj_st h_disj_zs h_disj_zt
      H s1 l1_pc l1_z n h_s1_tmp
  refine ⟨l2_pc, ?_, ?_, l2_tmp, l2_z, ?_⟩
  · -- s'.regs dst = s.regs dst + n.
    -- l2_oth: ∀ r, r ≠ src → r ≠ tmp → final_dst = s1.regs dst
    rw [l2_oth dst h_disj_sd.symm h_disj_dt, l1_dst]
  · -- s'.regs src = n.
    -- l2_src: final_src = s1.regs src + n.  s1.regs src = 0.
    rw [l2_src, l1_src, Nat.zero_add]
  · -- For r ≠ dst, also r ≠ src means we go through l1_oth
    -- (preserving src too).  But here we have only r ≠ dst.
    -- Need to handle r = src and r = tmp separately.
    intro r hrd
    by_cases hrs : r = src
    · subst hrs
      rw [l2_src, l1_src, h_src]; omega
    · by_cases hrt : r = tmp
      · subst hrt
        rw [l2_tmp, h_tmp0]
      · rw [l2_oth r hrs hrt, l1_oth r hrs hrd hrt]

/-- Hypothesis bundle for `transferLoop_correct`: the four
instruction-lookup equalities at PCs `pcBase..pcBase+3`
matching the raw layout of `URMRaw.transferLoop`. The
`zReg` parameter holds the reserved-zero register used by
`URMRaw.goto`; it is required to be the register at index
`0` so the trailing `goto` compiles to a zero-test on
`zReg`. -/
private structure transferLoopInstrs {a : ℕ}
    (P : URMProgram a) (pcBase : ℕ)
    (src dst zReg : Fin P.numRegs) : Prop where
  h0 : P.instrs[pcBase]? =
    some (.jumpZ src (pcBase + 4) (pcBase + 1))
  h1 : P.instrs[pcBase + 1]? = some (.dec src)
  h2 : P.instrs[pcBase + 2]? = some (.inc dst)
  h3 : P.instrs[pcBase + 3]? = some (.jumpZ zReg pcBase pcBase)

/-- Correctness of the `URMRaw.transferLoop` 4-instruction
block. Running for `4 * n + 1` steps from a state with
`pc = pcBase`, `V_src = n`, and the reserved-zero register
`V_zReg = 0` yields a state with `pc = pcBase + 4`,
`V_dst += n`, `V_src = 0` (destructively consumed),
`V_zReg = 0`, and all other registers unchanged. The
instruction-presence hypothesis bundles the four lookup
equalities at offsets `0..3`. -/
private theorem transferLoop_correct {a : ℕ}
    (P : URMProgram a) (pcBase : ℕ)
    (src dst zReg : Fin P.numRegs)
    (h_disj_sd : src ≠ dst) (h_disj_zs : zReg ≠ src)
    (h_disj_zd : zReg ≠ dst)
    (H : transferLoopInstrs P pcBase src dst zReg)
    (s : URMState P) (h_pc : s.pc = pcBase)
    (h_z : s.regs zReg = 0)
    (n : ℕ) (h_src : s.regs src = n) :
    let s' := URMState.runFor P s (4 * n + 1)
    s'.pc = pcBase + 4 ∧
    s'.regs dst = s.regs dst + n ∧
    s'.regs src = 0 ∧
    s'.regs zReg = 0 ∧
    ∀ r, r ≠ dst → r ≠ src → r ≠ zReg →
      s'.regs r = s.regs r := by
  simp only []
  induction n generalizing s with
  | zero =>
    -- 1 step: jumpZ src (pcBase+4) (pcBase+1).  V_src = 0,
    -- so PC → pcBase+4.
    have hstep : (4 * 0 + 1 : ℕ) = 0 + 1 := rfl
    rw [hstep, URMState.runFor_succ, URMState.runFor_zero,
      URMState.step_of_getElem?_jumpZ P s pcBase src
        (pcBase + 4) (pcBase + 1) h_pc H.h0]
    have hsrc_eq : s.regs src = 0 := h_src
    simp only [hsrc_eq, ↓reduceIte]
    refine ⟨trivial, ?_, trivial, h_z, fun _ _ _ _ => trivial⟩
    show s.regs dst = s.regs dst + 0
    omega
  | succ n ih =>
    -- Peel 4 steps: jumpZ (to pcBase+1), dec src, inc dst,
    -- goto pcBase.  Then apply ih on the resulting state
    -- with V_src = n.
    have h4n : 4 * (n + 1) + 1 = 4 + (4 * n + 1) := by omega
    rw [h4n, URMState.runFor_add]
    set s4 : URMState P :=
      { pc := pcBase
        regs := Function.update
          (Function.update s.regs src (s.regs src - 1))
          dst ((Function.update s.regs src (s.regs src - 1)) dst + 1) }
      with hs4_def
    have h_src_ne : s.regs src ≠ 0 := by rw [h_src]; omega
    have h_four : URMState.runFor P s 4 = s4 := by
      change URMState.runFor P s (3 + 1) = _
      rw [URMState.runFor_succ,
        URMState.step_of_getElem?_jumpZ P s pcBase src
          (pcBase + 4) (pcBase + 1) h_pc H.h0]
      simp only [h_src_ne, ↓reduceIte]
      set s1 : URMState P :=
        { pc := pcBase + 1, regs := s.regs } with hs1_def
      have hs1_pc : s1.pc = pcBase + 1 := rfl
      change URMState.runFor P s1 (2 + 1) = _
      rw [URMState.runFor_succ,
        URMState.step_of_getElem?_dec P s1 (pcBase + 1) src hs1_pc H.h1]
      set s2 : URMState P :=
        { pc := s1.pc + 1
          regs := Function.update s1.regs src (s1.regs src - 1) } with hs2_def
      have hs2_pc : s2.pc = pcBase + 2 := by
        change s1.pc + 1 = pcBase + 2; rw [hs1_pc]
      change URMState.runFor P s2 (1 + 1) = _
      rw [URMState.runFor_succ,
        URMState.step_of_getElem?_inc P s2 (pcBase + 2) dst hs2_pc H.h2]
      set s3 : URMState P :=
        { pc := s2.pc + 1
          regs := Function.update s2.regs dst (s2.regs dst + 1) } with hs3_def
      have hs3_pc : s3.pc = pcBase + 3 := by
        change s2.pc + 1 = pcBase + 3; rw [hs2_pc]
      change URMState.runFor P s3 (0 + 1) = _
      rw [URMState.runFor_succ, URMState.runFor_zero,
        URMState.step_of_getElem?_jumpZ P s3 (pcBase + 3) zReg
          pcBase pcBase hs3_pc H.h3]
      have hs3_z : s3.regs zReg = 0 := by
        change Function.update s2.regs dst _ zReg = 0
        rw [Function.update_of_ne h_disj_zd]
        change Function.update s1.regs src _ zReg = 0
        rw [Function.update_of_ne h_disj_zs]
        exact h_z
      simp only [hs3_z, ↓reduceIte]
      rfl
    rw [h_four]
    have hs4_pc : s4.pc = pcBase := rfl
    have hs4_z : s4.regs zReg = 0 := by
      change Function.update (Function.update s.regs src
        (s.regs src - 1)) dst _ zReg = 0
      rw [Function.update_of_ne h_disj_zd]
      rw [Function.update_of_ne h_disj_zs]
      exact h_z
    have hs4_src : s4.regs src = n := by
      change Function.update (Function.update s.regs src
        (s.regs src - 1)) dst _ src = n
      rw [Function.update_of_ne h_disj_sd]
      rw [Function.update_self]
      omega
    have hs4_dst : s4.regs dst = s.regs dst + 1 := by
      change Function.update (Function.update s.regs src
        (s.regs src - 1)) dst _ dst = _
      rw [Function.update_self]
      rw [Function.update_of_ne h_disj_sd.symm]
    have hs4_other : ∀ r, r ≠ dst → r ≠ src →
        s4.regs r = s.regs r := by
      intro r hrd hrs
      change Function.update (Function.update s.regs src
        (s.regs src - 1)) dst _ r = _
      rw [Function.update_of_ne hrd]
      rw [Function.update_of_ne hrs]
    obtain ⟨ih_pc, ih_dst, ih_src, ih_z, ih_oth⟩ :=
      ih s4 hs4_pc hs4_z hs4_src
    refine ⟨ih_pc, ?_, ih_src, ih_z, ?_⟩
    · rw [ih_dst, hs4_dst]; omega
    · intro r hrd hrs hrz
      rw [ih_oth r hrd hrs hrz, hs4_other r hrd hrs]

/-- Correctness of `compileER` on `.zero`: running for at
least 3 steps from `init` produces output register = 0. -/
private theorem compileER_runFor_zero
    (v : Fin 0 → ℕ) (t' : ℕ)
    (ht' : compileER_runtime (.zero : ERMor1 0) v ≤ t') :
    (URMState.runFor (compileER ERMor1.zero)
        (URMState.init (compileER ERMor1.zero) v) t').regs
        (compileER ERMor1.zero).outputReg
      = ERMor1.zero.interp v := by
  -- runtime = 3; write t' = 3 + (t' - 3).
  have h3 : 3 ≤ t' := ht'
  obtain ⟨sl, rfl⟩ : ∃ sl, t' = 3 + sl :=
    ⟨t' - 3, by omega⟩
  -- Split runFor (3 + sl) = runFor sl after 3 steps.
  rw [URMState.runFor_add]
  -- Compute the state after 3 steps by unfolding step
  -- three times.  All three instruction lookups discharge
  -- by `decide`, since the program is a literal #[…]
  -- array.
  set P : URMProgram 0 := compileER ERMor1.zero
  set s0 : URMState P := URMState.init P v
  -- Step 1: assign ⟨0, _⟩ 0.
  have hs1 : URMState.step P s0 =
      { pc := 1, regs := Function.update s0.regs ⟨0, by decide⟩ 0 } := by
    simp only [URMState.step, s0, URMState.init,
      P, compileER, compileERFrag, compileFrag_zero]
    rfl
  -- Run for sl steps after 3 hops via runFor_stop, since
  -- the third instruction is `.stop`.
  -- Build the state after 3 hops directly.
  set s3 : URMState P :=
    { pc := 2
      regs := Function.update
        (Function.update s0.regs ⟨0, by decide⟩ 0)
        ⟨1, by decide⟩ 0 }
  have h_three :
      URMState.runFor P s0 3 = s3 := by
    rw [show (3 : ℕ) = 2 + 1 from rfl, URMState.runFor_add,
      show (2 : ℕ) = 1 + 1 from rfl, URMState.runFor_add]
    -- Now have runFor P (runFor P (runFor P s0 1) 1) 1
    -- Each individual step computes by `rfl`-like simp.
    simp only [URMState.runFor_succ, URMState.runFor_zero]
    -- Step 1
    rw [show URMState.step P s0 =
        { pc := 1, regs :=
            Function.update s0.regs ⟨0, by decide⟩ 0 } from hs1]
    -- Step 2: assign ⟨1, _⟩ 0.
    have hs2 :
        URMState.step P
          { pc := 1
            regs := Function.update s0.regs ⟨0, by decide⟩ 0 } =
        { pc := 2
          regs := Function.update
            (Function.update s0.regs ⟨0, by decide⟩ 0)
            ⟨1, by decide⟩ 0 } := by
      simp only [URMState.step, P, compileER, compileERFrag,
        compileFrag_zero]
      rfl
    rw [hs2]
    -- Step 3: stop at PC 2.
    change URMState.step P
        { pc := 2
          regs := Function.update
            (Function.update s0.regs ⟨0, by decide⟩ 0)
            ⟨1, by decide⟩ 0 } = s3
    simp only [URMState.step, P, compileER, compileERFrag,
      compileFrag_zero, s3]
    rfl
  rw [h_three]
  -- Slack steps from s3 (PC = 2 = stop instruction) are
  -- absorbed by `runFor_stop`.
  have h_pc : s3.pc < P.instrs.size := by
    change 2 < P.instrs.size
    simp only [P, compileER, compileERFrag, compileFrag_zero]
    decide
  have h_stop : P.instrs[s3.pc]'h_pc = URMInstr.stop := by
    change P.instrs[(2 : ℕ)]'h_pc = URMInstr.stop
    simp only [P, compileER, compileERFrag, compileFrag_zero]
    rfl
  rw [URMState.runFor_stop P s3 sl h_pc h_stop]
  -- Read off register 1 = output reg.
  change s3.regs (compileER ERMor1.zero).outputReg = _
  -- outputReg = ⟨1, _⟩, and regs ⟨1, _⟩ = 0 via the
  -- second Function.update.
  change Function.update (Function.update s0.regs ⟨0, by decide⟩ 0)
      ⟨1, by decide⟩ 0 (compileER ERMor1.zero).outputReg = _
  simp only [P, compileER, compileERFrag, compileFrag_zero]
  rfl

/-- Correctness of `compileER` on `.succ`: running for at
least `12 + 10 * v 0` steps from `init` produces output
register = `(v 0).succ`. Traces the 12-instruction
`compileFrag_succ` program: assignR zeroReg, then 9-step
`preservingTransfer` of input into output, then incR
output, then stopR. -/
private theorem compileER_runFor_succ
    (v : Fin 1 → ℕ) (t' : ℕ)
    (ht' : compileER_runtime (.succ : ERMor1 1) v ≤ t') :
    (URMState.runFor (compileER ERMor1.succ)
        (URMState.init (compileER ERMor1.succ) v) t').regs
        (compileER ERMor1.succ).outputReg
      = ERMor1.succ.interp v := by
  -- Abbreviations for the program and register Fins.
  set P : URMProgram 1 := compileER ERMor1.succ with hP
  set s0 : URMState P := URMState.init P v with hs0
  -- The runtime is 12 + 10 * v 0; the actual trace uses
  -- 9 * v 0 + 5 steps (1 assign + (9 * v 0 + 2) transfer
  -- + 1 inc + 1 stop).  Slack = t' - (9 * v 0 + 5).
  have hrt : compileER_runtime (.succ : ERMor1 1) v = 12 + 10 * v 0 :=
    rfl
  obtain ⟨slack, rfl⟩ : ∃ sl, t' = (9 * v 0 + 5) + sl :=
    ⟨t' - (9 * v 0 + 5), by rw [hrt] at ht'; omega⟩
  -- Five Fins of `P.numRegs = 4`.
  set zReg : Fin P.numRegs := ⟨0, by decide⟩ with hzReg
  set dst  : Fin P.numRegs := ⟨1, by decide⟩ with hdst
  set src  : Fin P.numRegs := ⟨2, by decide⟩ with hsrc
  set tmp  : Fin P.numRegs := ⟨3, by decide⟩ with htmp
  -- Inputs.
  have h_inputReg : P.inputRegs 0 = src := rfl
  -- s0.regs values.
  have hs0_src : s0.regs src = v 0 := by
    -- (List.finRange 1).find? returns some 0 since
    -- inputRegs 0 = src.
    change (URMState.init P v).regs src = v 0
    rfl
  have hs0_zReg : s0.regs zReg = 0 := by
    change (URMState.init P v).regs zReg = 0
    rfl
  have hs0_dst : s0.regs dst = 0 := by
    change (URMState.init P v).regs dst = 0
    rfl
  have hs0_tmp : s0.regs tmp = 0 := by
    change (URMState.init P v).regs tmp = 0
    rfl
  have hs0_pc : s0.pc = 0 := rfl
  -- Disjointness of the four Fins.
  have h_disj_sd : src ≠ dst := by
    intro h; exact absurd (congrArg Fin.val h) (by decide)
  have h_disj_st : src ≠ tmp := by
    intro h; exact absurd (congrArg Fin.val h) (by decide)
  have h_disj_dt : dst ≠ tmp := by
    intro h; exact absurd (congrArg Fin.val h) (by decide)
  have h_disj_zs : zReg ≠ src := by
    intro h; exact absurd (congrArg Fin.val h) (by decide)
  have h_disj_zd : zReg ≠ dst := by
    intro h; exact absurd (congrArg Fin.val h) (by decide)
  have h_disj_zt : zReg ≠ tmp := by
    intro h; exact absurd (congrArg Fin.val h) (by decide)
  -- Instruction-presence hypotheses for preservingTransfer
  -- at PCs 1..9; each one is a literal-array `getElem?`
  -- equality that reduces by `rfl`.
  have H : preservingTransferInstrs P 1 src dst tmp zReg := by
    refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> rfl
  -- t' = (9 * v 0 + 5) + slack.
  --   = 1 + (9 * v 0 + 2) + 1 + 1 + slack.
  -- Step 1 (PC 0): assignR 0 0; s0 → s1 with PC = 1 and
  -- regs zReg = 0 (no change).
  have h_split : 9 * v 0 + 5 + slack
      = 1 + ((9 * v 0 + 2) + (1 + (1 + slack))) := by omega
  rw [h_split, URMState.runFor_add]
  -- Compute the first step.
  have h_step0 : URMState.step P s0 =
      { pc := 1
        regs := Function.update s0.regs zReg 0 } := by
    have h_pc : (0 : ℕ) < P.instrs.size := by decide
    have h_eq : P.instrs[(0 : ℕ)]'h_pc = .assign zReg 0 := rfl
    simp only [URMState.step, hs0_pc, dif_pos h_pc, h_eq]
  set s1 : URMState P :=
      { pc := 1
        regs := Function.update s0.regs zReg 0 } with hs1
  have h_first : URMState.runFor P s0 1 = s1 := by
    change URMState.runFor P (URMState.step P s0) 0 = _
    rw [URMState.runFor_zero, h_step0]
  rw [h_first]
  -- s1's register values.
  have hs1_pc : s1.pc = 1 := rfl
  have hs1_zReg : s1.regs zReg = 0 := by
    change Function.update s0.regs zReg 0 zReg = 0
    rw [Function.update_self]
  have hs1_src : s1.regs src = v 0 := by
    change Function.update s0.regs zReg 0 src = v 0
    rw [Function.update_of_ne (Ne.symm h_disj_zs), hs0_src]
  have hs1_dst : s1.regs dst = 0 := by
    change Function.update s0.regs zReg 0 dst = 0
    rw [Function.update_of_ne (Ne.symm h_disj_zd), hs0_dst]
  have hs1_tmp : s1.regs tmp = 0 := by
    change Function.update s0.regs zReg 0 tmp = 0
    rw [Function.update_of_ne (Ne.symm h_disj_zt), hs0_tmp]
  -- Step 2: preservingTransfer block for `9 * v 0 + 2`
  -- steps.
  rw [URMState.runFor_add]
  obtain ⟨pt_pc, pt_dst, pt_src, pt_tmp, pt_z, pt_oth⟩ :=
    preservingTransfer_correct P 1 src dst tmp zReg
      h_disj_sd h_disj_st h_disj_dt h_disj_zs h_disj_zd h_disj_zt
      H s1 hs1_pc hs1_zReg hs1_tmp (v 0) hs1_src
  set s2 : URMState P := URMState.runFor P s1 (9 * v 0 + 2)
    with hs2
  -- s2's values.
  have hs2_pc : s2.pc = 10 := by
    have h10 : (1 : ℕ) + 9 = 10 := by omega
    rw [← h10]; exact pt_pc
  have hs2_dst : s2.regs dst = v 0 := by
    rw [pt_dst, hs1_dst]; omega
  -- Step 3: incR dst at PC 10.
  rw [URMState.runFor_add]
  have h_step2 : URMState.step P s2 =
      { pc := 11
        regs := Function.update s2.regs dst (s2.regs dst + 1) } := by
    have h_pc : (10 : ℕ) < P.instrs.size := by decide
    have h_eq : P.instrs[(10 : ℕ)]'h_pc = .inc dst := rfl
    simp only [URMState.step, hs2_pc, dif_pos h_pc, h_eq]
  set s3 : URMState P :=
      { pc := 11
        regs := Function.update s2.regs dst (s2.regs dst + 1) }
    with hs3
  have h_third : URMState.runFor P s2 1 = s3 := by
    change URMState.runFor P (URMState.step P s2) 0 = _
    rw [URMState.runFor_zero, h_step2]
  rw [h_third]
  have hs3_pc : s3.pc = 11 := rfl
  have hs3_dst : s3.regs dst = v 0 + 1 := by
    change Function.update s2.regs dst (s2.regs dst + 1) dst = v 0 + 1
    rw [Function.update_self, hs2_dst]
  -- Step 4: stopR at PC 11.  The remaining `1 + slack`
  -- steps are absorbed by `runFor_stop`.
  have h_pc11 : s3.pc < P.instrs.size := by
    rw [hs3_pc]; decide
  have h_stop : P.instrs[s3.pc]'h_pc11 = URMInstr.stop := by
    change P.instrs[(11 : ℕ)]'(hs3_pc ▸ h_pc11) = URMInstr.stop
    rfl
  rw [URMState.runFor_stop P s3 (1 + slack) h_pc11 h_stop]
  -- Read off output register.
  change s3.regs dst = _
  rw [hs3_dst, ERMor1.interp_succ]

/-- Auxiliary: `(List.finRange a).find?` over an injective
predicate keyed by `inputRegs` returns the input slot whose
register matches. Phrased over a generic injective `f` to
keep the induction clean. Constructive: built bottom-up from
`List.finRange_succ` and `List.find?_cons`. -/
private theorem List.find?_finRange_inputRegs
    {a : ℕ} {β : Type*} [DecidableEq β]
    (f : Fin a → β) (hf : Function.Injective f) (i : Fin a) :
    (List.finRange a).find? (fun j => decide (f j = f i)) = some i := by
  induction a with
  | zero => exact i.elim0
  | succ a' ih =>
    rw [List.finRange_succ, List.find?_cons]
    by_cases h0 : i = 0
    · subst h0
      simp
    · -- i is some Fin.succ i'.
      have h_dec :
          decide (f 0 = f i) = false := by
        simp only [decide_eq_false_iff_not]
        intro heq; exact h0 (hf heq).symm
      rw [h_dec]
      -- Recurse on `(List.finRange a').map Fin.succ`.
      obtain ⟨i', rfl⟩ : ∃ i', i = Fin.succ i' := ⟨i.pred h0, (i.succ_pred h0).symm⟩
      rw [List.find?_map]
      have h_rec :
          (List.finRange a').find?
              ((fun j => decide (f j = f i'.succ)) ∘ Fin.succ) = some i' := by
        have := ih (f ∘ Fin.succ)
          (fun x y hxy => Fin.succ_injective _ (hf hxy)) i'
        simp only [Function.comp] at this ⊢
        exact this
      rw [h_rec]
      rfl

/-- The `init` register at any input slot's image returns
the corresponding input value. Generalises the single-slot
`rfl` reduction used in `compileER_runFor_succ` to programs
with more than one input. Constructive. -/
private theorem URMState.init_regs_inputRegs {a : ℕ}
    (P : URMProgram a) (v : Fin a → ℕ) (i : Fin a) :
    (URMState.init P v).regs (P.inputRegs i) = v i := by
  change
    (match (List.finRange a).find?
        (fun j => decide (P.inputRegs j = P.inputRegs i)) with
      | some j => v j
      | none   => 0) = v i
  rw [List.find?_finRange_inputRegs P.inputRegs P.inputRegs_inj i]

/-- Correctness of `compileER` on `.proj i`: running for at
least `11 + 10 * v i` steps from `init` produces output
register = `v i`. Traces the 11-instruction
`compileFrag_proj i` program: assignR zeroReg, then 9-step
`preservingTransfer` of input slot `i` into output, then
stopR. -/
private theorem compileER_runFor_proj {k : ℕ} (i : Fin k)
    (v : Fin k → ℕ) (t' : ℕ)
    (ht' : compileER_runtime (.proj i : ERMor1 k) v ≤ t') :
    (URMState.runFor (compileER (ERMor1.proj i))
        (URMState.init (compileER (ERMor1.proj i)) v) t').regs
        (compileER (ERMor1.proj i)).outputReg
      = (ERMor1.proj i).interp v := by
  -- Abbreviations for the program and register Fins.
  set P : URMProgram k := compileER (ERMor1.proj i) with hP
  set s0 : URMState P := URMState.init P v with hs0
  -- The runtime is 11 + 10 * v i; the actual trace uses
  -- 9 * v i + 3 steps (1 assign + (9 * v i + 2) transfer
  -- + 1 stop).  Slack = t' - (9 * v i + 3).
  have hrt : compileER_runtime (.proj i : ERMor1 k) v = 11 + 10 * v i :=
    rfl
  obtain ⟨slack, rfl⟩ : ∃ sl, t' = (9 * v i + 3) + sl :=
    ⟨t' - (9 * v i + 3), by rw [hrt] at ht'; omega⟩
  -- Four Fins of `P.numRegs = k + 3`.
  have hi : i.val < k := i.isLt
  set zReg : Fin P.numRegs := ⟨0, by change 0 < k + 3; omega⟩ with hzReg
  set dst  : Fin P.numRegs := ⟨1, by change 1 < k + 3; omega⟩ with hdst
  set src  : Fin P.numRegs := ⟨2 + i.val, by change 2 + i.val < k + 3; omega⟩
    with hsrc
  set tmp  : Fin P.numRegs := ⟨2 + k, by change 2 + k < k + 3; omega⟩ with htmp
  -- Inputs.
  have h_inputReg : P.inputRegs i = src := rfl
  -- s0.regs values.
  have hs0_src : s0.regs src = v i := by
    change (URMState.init P v).regs (P.inputRegs i) = v i
    exact URMState.init_regs_inputRegs P v i
  have hs0_zReg : s0.regs zReg = 0 := by
    change (URMState.init P v).regs zReg = 0
    -- zReg is not in the image of inputRegs; find? returns none.
    change (match (List.finRange k).find?
        (fun j => decide (P.inputRegs j = zReg)) with
      | some j => v j
      | none   => 0) = 0
    have h_none : (List.finRange k).find?
        (fun j => decide (P.inputRegs j = zReg)) = none := by
      apply List.find?_eq_none.mpr
      intro j _
      simp only [Bool.not_eq_true, decide_eq_false_iff_not]
      intro h
      have : (2 + j.val : ℕ) = 0 := congrArg Fin.val h
      omega
    rw [h_none]
  have hs0_dst : s0.regs dst = 0 := by
    change (URMState.init P v).regs dst = 0
    change (match (List.finRange k).find?
        (fun j => decide (P.inputRegs j = dst)) with
      | some j => v j
      | none   => 0) = 0
    have h_none : (List.finRange k).find?
        (fun j => decide (P.inputRegs j = dst)) = none := by
      apply List.find?_eq_none.mpr
      intro j _
      simp only [Bool.not_eq_true, decide_eq_false_iff_not]
      intro h
      have : (2 + j.val : ℕ) = 1 := congrArg Fin.val h
      omega
    rw [h_none]
  have hs0_tmp : s0.regs tmp = 0 := by
    change (URMState.init P v).regs tmp = 0
    change (match (List.finRange k).find?
        (fun j => decide (P.inputRegs j = tmp)) with
      | some j => v j
      | none   => 0) = 0
    have h_none : (List.finRange k).find?
        (fun j => decide (P.inputRegs j = tmp)) = none := by
      apply List.find?_eq_none.mpr
      intro j hj
      simp only [Bool.not_eq_true, decide_eq_false_iff_not]
      intro h
      have : (2 + j.val : ℕ) = 2 + k := congrArg Fin.val h
      have hjlt : j.val < k := j.isLt
      omega
    rw [h_none]
  have hs0_pc : s0.pc = 0 := rfl
  -- Disjointness of the four Fins.
  have h_disj_sd : src ≠ dst := by
    intro h
    have : (2 + i.val : ℕ) = 1 := congrArg Fin.val h
    omega
  have h_disj_st : src ≠ tmp := by
    intro h
    have : (2 + i.val : ℕ) = 2 + k := congrArg Fin.val h
    omega
  have h_disj_dt : dst ≠ tmp := by
    intro h
    have : (1 : ℕ) = 2 + k := congrArg Fin.val h
    omega
  have h_disj_zs : zReg ≠ src := by
    intro h
    have : (0 : ℕ) = 2 + i.val := congrArg Fin.val h
    omega
  have h_disj_zd : zReg ≠ dst := by
    intro h
    have : (0 : ℕ) = 1 := congrArg Fin.val h
    omega
  have h_disj_zt : zReg ≠ tmp := by
    intro h
    have : (0 : ℕ) = 2 + k := congrArg Fin.val h
    omega
  -- Instruction-presence hypotheses for preservingTransfer
  -- at PCs 1..9; each one is a literal-array `getElem?`
  -- equality that reduces by `rfl`.
  have H : preservingTransferInstrs P 1 src dst tmp zReg := by
    refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> rfl
  -- t' = (9 * v i + 3) + slack.
  --   = 1 + ((9 * v i + 2) + slack).  The trailing `slack`
  -- includes the final `stop` step at PC 10 and absorbs
  -- via `runFor_stop`.
  have h_split : 9 * v i + 3 + slack
      = 1 + ((9 * v i + 2) + slack) := by omega
  rw [h_split, URMState.runFor_add]
  -- Program size is 11 (independent of i).
  have h_size : P.instrs.size = 11 := rfl
  -- Step 1 (PC 0): assignR 0 0; s0 → s1 with PC = 1 and
  -- regs zReg = 0 (no change).
  have h_step0 : URMState.step P s0 =
      { pc := 1
        regs := Function.update s0.regs zReg 0 } := by
    have h_pc : (0 : ℕ) < P.instrs.size := by rw [h_size]; decide
    have h_eq : P.instrs[(0 : ℕ)]'h_pc = .assign zReg 0 := rfl
    simp only [URMState.step, hs0_pc, dif_pos h_pc, h_eq]
  set s1 : URMState P :=
      { pc := 1
        regs := Function.update s0.regs zReg 0 } with hs1
  have h_first : URMState.runFor P s0 1 = s1 := by
    change URMState.runFor P (URMState.step P s0) 0 = _
    rw [URMState.runFor_zero, h_step0]
  rw [h_first]
  -- s1's register values.
  have hs1_pc : s1.pc = 1 := rfl
  have hs1_zReg : s1.regs zReg = 0 := by
    change Function.update s0.regs zReg 0 zReg = 0
    rw [Function.update_self]
  have hs1_src : s1.regs src = v i := by
    change Function.update s0.regs zReg 0 src = v i
    rw [Function.update_of_ne (Ne.symm h_disj_zs), hs0_src]
  have hs1_dst : s1.regs dst = 0 := by
    change Function.update s0.regs zReg 0 dst = 0
    rw [Function.update_of_ne (Ne.symm h_disj_zd), hs0_dst]
  have hs1_tmp : s1.regs tmp = 0 := by
    change Function.update s0.regs zReg 0 tmp = 0
    rw [Function.update_of_ne (Ne.symm h_disj_zt), hs0_tmp]
  -- Step 2: preservingTransfer block for `9 * v i + 2` steps.
  rw [URMState.runFor_add]
  obtain ⟨pt_pc, pt_dst, _pt_src, _pt_tmp, _pt_z, _pt_oth⟩ :=
    preservingTransfer_correct P 1 src dst tmp zReg
      h_disj_sd h_disj_st h_disj_dt h_disj_zs h_disj_zd h_disj_zt
      H s1 hs1_pc hs1_zReg hs1_tmp (v i) hs1_src
  set s2 : URMState P := URMState.runFor P s1 (9 * v i + 2)
    with hs2
  -- s2's values.
  have hs2_pc : s2.pc = 10 := by
    have h10 : (1 : ℕ) + 9 = 10 := by omega
    rw [← h10]; exact pt_pc
  have hs2_dst : s2.regs dst = v i := by
    rw [pt_dst, hs1_dst]; omega
  -- Step 3: stopR at PC 10.  The remaining `slack` steps
  -- are absorbed by `runFor_stop`.
  have h_pc10 : s2.pc < P.instrs.size := by
    rw [hs2_pc, h_size]; decide
  have h_stop : P.instrs[s2.pc]'h_pc10 = URMInstr.stop := by
    -- `s2.pc = 10`; transport along this to read off the
    -- stop instruction at PC 10.
    revert h_pc10
    rw [hs2_pc]
    intro _; rfl
  rw [URMState.runFor_stop P s2 slack h_pc10 h_stop]
  -- Read off output register.
  change s2.regs dst = _
  rw [hs2_dst, ERMor1.interp_proj]

end LawvereERKSim

end GebLean
