import GebLean.PshRelEdgeInclusion
import GebLean.PshRelEdgeExp
import Mathlib.CategoryTheory.Monoidal.Cartesian.Basic

/-!
# PshRelEdge C as separated presheaves

This file constructs the equivalence between
`PshRelEdge C` and the full subcategory of
`WalkingSpan ⥤ PSh(C)` on separated spans:
those where the pairing map
`F(.none) → F(.left) × F(.right)` is a
monomorphism (i.e., the two span projections
are jointly monic).

This is the separated-presheaf characterization
`PshRelEdge C ≅ Sep_J(C × I^op)` where `J` is
the Grothendieck topology on `C × I^op`
generated by covering each span apex with
its two projections.

## Main definitions

* `IsSeparatedSpan`: predicate on
  `WalkingSpan ⥤ PSh(C)` for joint monicity
  of span projections
* `pshRelEdge_isSeparatedSpan`: every edge
  in the image of the inclusion is separated
* `separatedSpanToEdge`: build an edge from a
  separated span
* `pshRelEdgeSepEquiv`: the category
  equivalence
-/

open CategoryTheory Limits

namespace GebLean

universe u v w

variable {C : Type u} [Category.{v} C]

/-- A span `F : WalkingSpan ⥤ PSh(C)` is
**separated** when the two span projections
`F.map fst` and `F.map snd` are jointly
injective at each stage: if two elements
`r₁, r₂ ∈ F(.none)(c)` have the same images
under both projections, then `r₁ = r₂`.

This is equivalent to the pairing map
`F(.none) → F(.left) × F(.right)` being a
monomorphism (in `Type`-valued presheaf
categories, monomorphisms are pointwise
injective). This is the separation condition
for the Grothendieck topology on `C × I^op`
generated by covering each span apex with its
two projections.

For edges in the image of
`pshRelEdgeInclusionFunctor`, this holds
because the relation `R` is a subfunctor of
`P × Q`, so the inclusion `R.ι` is monic. -/
def IsSeparatedSpan
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w)) :
    Prop :=
  ∀ (c : Cᵒᵖ)
    (r₁ r₂ : (F.obj .none).obj c),
    (F.map WalkingSpan.Hom.fst).app c r₁ =
      (F.map WalkingSpan.Hom.fst).app c r₂ →
    (F.map WalkingSpan.Hom.snd).app c r₁ =
      (F.map WalkingSpan.Hom.snd).app c r₂ →
    r₁ = r₂

/-- Every edge in the image of the inclusion
functor is separated. The pairing map is
`R.ι : R.toFunctor ⟶ pshProdPresheaf P Q`,
which is monic because `R` is a subfunctor. -/
theorem pshRelEdge_isSeparatedSpan
    (E : PshRelEdge.{u, v, w} C) :
    IsSeparatedSpan
      (pshRelEdgeSpan (C := C) E) := by
  intro c r₁ r₂ hfst hsnd
  dsimp [pshRelEdgeSpan, span,
    WidePushoutShape.mkCocone,
    pshRelFstProj,
    pshRelSndProj] at hfst hsnd
  exact Subtype.ext (Prod.ext hfst hsnd)

/-- Build a presheaf relation from a separated
span by taking the image of the pairing map
`(F.map fst, F.map snd) :
F(.none) → F(.left) × F(.right)`.

The relation at stage `c` consists of pairs
`(p, q) ∈ F(.left)(c) × F(.right)(c)` such
that there exists `r ∈ F(.none)(c)` with
`F.map(fst)(r) = p` and `F.map(snd)(r) = q`.

When the span is separated, the pairing map
is injective, so each pair `(p, q)` in the
relation has a unique witness `r`. -/
def separatedSpanRel
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w)) :
    PshRel (F.obj (.some .left))
      (F.obj (.some .right)) where
  obj c :=
    { pq |
      ∃ r : F.obj .none |>.obj c,
        (F.map WalkingSpan.Hom.fst).app c r =
          pq.1 ∧
        (F.map WalkingSpan.Hom.snd).app c r =
          pq.2 }
  map {c d} f := by
    rintro ⟨p, q⟩ ⟨r, hrp, hrq⟩
    refine ⟨F.obj .none |>.map f r, ?_, ?_⟩
    · have nat := congr_fun
        ((F.map WalkingSpan.Hom.fst).naturality
          f) r
      simp only [types_comp_apply] at nat
      rw [nat, hrp]; rfl
    · have nat := congr_fun
        ((F.map WalkingSpan.Hom.snd).naturality
          f) r
      simp only [types_comp_apply] at nat
      rw [nat, hrq]; rfl

/-- Build an edge from a span by taking
the image relation. -/
def separatedSpanToEdge
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w)) :
    PshRelEdge.{u, v, w} C :=
  { src := F.obj (.some .left)
    tgt := F.obj (.some .right)
    edge := separatedSpanRel (C := C) F }

/-- The image relation of the inclusion span
equals the original relation: the image of a
subfunctor inclusion `R.ι` is `R` itself. -/
theorem separatedSpanRel_of_inclusion
    (E : PshRelEdge.{u, v, w} C) :
    separatedSpanRel (pshRelEdgeSpan E) =
    E.edge := by
  apply Subfunctor.ext
  funext c
  ext ⟨p, q⟩
  simp only [separatedSpanRel,
    pshRelEdgeSpan, span,
    pshRelFstProj, pshRelSndProj,
    Set.mem_setOf_eq]
  constructor
  · rintro ⟨r, hrp, hrq⟩
    have : (p, q) = r.val := Prod.ext
      hrp.symm hrq.symm
    rw [this]
    exact r.prop
  · intro hpq
    exact ⟨⟨(p, q), hpq⟩, rfl, rfl⟩

/-- Round-trip: `separatedSpanToEdge` applied
to the inclusion span of an edge recovers the
original edge. -/
theorem separatedSpanToEdge_inclusion
    (E : PshRelEdge.{u, v, w} C) :
    separatedSpanToEdge
      (pshRelEdgeSpan (C := C) E) = E := by
  simp only [separatedSpanToEdge,
    pshRelEdgeSpan, span]
  exact congrArg (VertEdge.mk E.src E.tgt)
    (separatedSpanRel_of_inclusion E)

/-- The pairing map from the span apex to
the image relation's total presheaf. Sends
`r ∈ F(.none)(c)` to
`((F.map fst)(r), (F.map snd)(r))` with the
witness `r` itself. -/
def separatedSpanPairingMap
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w)) :
    F.obj .none ⟶
    (separatedSpanRel (C := C) F).toFunctor
    where
  app c r :=
    ⟨((F.map WalkingSpan.Hom.fst).app c r,
      (F.map WalkingSpan.Hom.snd).app c r),
     ⟨r, rfl, rfl⟩⟩
  naturality c d f := by
    ext r
    apply Subtype.ext
    apply Prod.ext
    · exact congr_fun
        ((F.map WalkingSpan.Hom.fst).naturality
          f) r
    · exact congr_fun
        ((F.map WalkingSpan.Hom.snd).naturality
          f) r

/-- For a separated span, the pairing map is
injective at each stage: if two elements have
the same image under both projections, they
are equal. -/
theorem separatedSpanPairingMap_injective
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w))
    (hF : IsSeparatedSpan (C := C) F)
    (c : Cᵒᵖ) :
    Function.Injective
      ((separatedSpanPairingMap F).app c) := by
  intro r₁ r₂ heq
  have heq' := congr_arg Subtype.val heq
  exact hF c r₁ r₂
    (congr_arg Prod.fst heq')
    (congr_arg Prod.snd heq')

/-- The pairing map is surjective: every element
of the image relation has a preimage in the
span apex (by definition of the image). -/
theorem separatedSpanPairingMap_surjective
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w))
    (c : Cᵒᵖ)
    (x : (separatedSpanRel (C := C) F).toFunctor.obj
      c) :
    ∃ r : (F.obj .none).obj c,
      (separatedSpanPairingMap F).app c r =
        x := by
  obtain ⟨⟨p, q⟩, ⟨r, hrp, hrq⟩⟩ := x
  exact ⟨r, Subtype.ext
    (Prod.ext hrp hrq)⟩

/-- The separation reflector `pshRelEdgeSepObj`
applied to an inclusion span gives back the
original edge: the image of a subfunctor
inclusion is the subfunctor itself. -/
theorem pshRelEdgeSepObj_inclusion
    (E : PshRelEdge.{u, v, w} C) :
    pshRelEdgeSepObj (C := C)
      (pshRelEdgeSpan E) = E := by
  simp only [pshRelEdgeSepObj,
    pshRelEdgeSpan, span]
  congr 1
  apply Subfunctor.ext; funext c; ext ⟨p, q⟩
  simp only [Subfunctor.range, Set.mem_range,
    pshProdLift, FunctorToTypes.prod.lift]
  constructor
  · rintro ⟨r, hr⟩
    have hp := congr_arg Prod.fst hr
    have hq := congr_arg Prod.snd hr
    dsimp at hp hq
    rw [← hp, ← hq]
    exact r.prop
  · intro hpq
    exact ⟨⟨(p, q), hpq⟩, rfl⟩

/-- Separated spans map to themselves under the
separation reflector: the reflector unit is a
pointwise injection at the apex, and every pair
in the image has a witness.

The separation condition is equivalent to the
pairing map `F(.none) → F(.left) × F(.right)`
being monic. The reflector replaces the apex
with the image of this map; when the map is
monic, the image is isomorphic to the original
apex (though constructing the inverse requires
extracting witnesses from `Set.range`, which
stores them propositionally).

The reflector `pshRelEdgeSepFunctor` together
with the fully faithful inclusion and
`pshRelEdgeSepObj_inclusion` establishes
`PshRelEdge C` as the reflective subcategory
of separated spans in `WalkingSpan ⥤ PSh(C)`.
-/
theorem separatedSpan_unit_injective
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w))
    (hF : IsSeparatedSpan (C := C) F)
    (c : Cᵒᵖ) :
    Function.Injective
      ((pshRelEdgeSepUnit F).app .none
        |>.app c) := by
  intro r₁ r₂ heq
  have heq' := congr_arg Subtype.val heq
  simp only [pshRelEdgeSepUnit, spanHomMk,
    pshProdLift,
    FunctorToTypes.prod.lift] at heq'
  exact hF c r₁ r₂
    (congr_arg Prod.fst heq')
    (congr_arg Prod.snd heq')

section BarrAdjunctionAgreement

/-- The functor `P ↦ P + B` for a fixed
presheaf `B`, as a covariant endofunctor. -/
def pshCoprodRightFunctor
    (B : Cᵒᵖ ⥤ Type w) :
    (Cᵒᵖ ⥤ Type w) ⥤ (Cᵒᵖ ⥤ Type w) where
  obj P := pshCoprodPresheaf P B
  map {P₁ P₂} f :=
    pshCoprodDesc
      (f ≫ pshCoprodInl P₂ B)
      (pshCoprodInr P₂ B)
  map_id P := by
    ext c x; match x with
    | Sum.inl _ => rfl
    | Sum.inr _ => rfl
  map_comp f g := by
    ext c x; match x with
    | Sum.inl _ => rfl
    | Sum.inr _ => rfl

/-- The Barr lift of the coproduct functor
`(- + B)` at a relation `R` equals the
coproduct relation `pshRelCoprod R (pshRelId B)`.

This shows that the Barr lift agrees with
the adjunction lift (which produces
`pshRelEdgeCoprod`) when the fixed argument
carries the identity relation. -/
theorem pshBarrLiftRel_coprodRight
    {P Q B : Cᵒᵖ ⥤ Type w}
    (R : PshRel P Q) :
    pshBarrLiftRel
      (pshCoprodRightFunctor (C := C) B)
      R =
    pshRelCoprod R (pshRelId B) := by
  apply Subfunctor.ext; funext c
  ext ⟨pq₁, pq₂⟩
  simp only [pshBarrLiftRel, pshBarrLift,
    pshProdOverToRel, Subfunctor.range,
    Set.mem_range, Over.mk_hom,
    FunctorToTypes.prod.lift,
    pshCoprodRightFunctor,
    pshRelCoprod, pshRelId,
    Set.mem_setOf_eq]
  constructor
  · rintro ⟨r, hr⟩
    have h₁ := congr_arg Prod.fst hr
    have h₂ := congr_arg Prod.snd hr
    dsimp [pshCoprodPresheaf] at h₁ h₂
    match r with
    | Sum.inl r' =>
      rw [← h₁, ← h₂]; exact r'.prop
    | Sum.inr b =>
      rw [← h₁, ← h₂]; rfl
  · intro h
    match pq₁, pq₂, h with
    | Sum.inl p, Sum.inl q, h =>
      exact ⟨Sum.inl ⟨(p, q), h⟩, rfl⟩
    | Sum.inr b₁, Sum.inr b₂, h =>
      exact ⟨Sum.inr b₁,
        congr_arg (fun x => (Sum.inr b₁,
          Sum.inr x)) h⟩

end BarrAdjunctionAgreement

section CartesianClosedInstances

variable {C : Type u} [Category.{v} C]

/-- The exponential right adjoint functor for
a fixed edge `A`: sends `B` to
`pshRelEdgeExp A B` and morphisms to the
appropriate induced maps via post-composition
currying. The universe `w = max u v` is
required for the exponential structure. -/
def pshRelEdgeIhom
    (A : PshRelEdge.{u, v, max u v} C) :
    PshRelEdge.{u, v, max u v} C ⥤
    PshRelEdge.{u, v, max u v} C where
  obj B := pshRelEdgeExp A B
  map f := pshRelEdgeCurry
    (pshRelEdgeEval A _ ≫ f)
  map_id B := by
    change pshRelEdgeCurry
      (pshRelEdgeEval A B ≫
        𝟙 (B : PshRelEdge.{u, v, max u v} C)) =
      𝟙 _
    rw [Category.comp_id]
    change pshRelEdgeCurry
      (pshRelEdgeUncurry
        (𝟙 (pshRelEdgeExp A B))) =
      𝟙 (pshRelEdgeExp A B)
    exact pshRelEdgeCurry_uncurry _
  map_comp {B₁ B₂ B₃} f g := by
    have inj : ∀ {X Y : PshRelEdge.{u, v,
        max u v} C}
        (a b : X ⟶ pshRelEdgeExp A Y),
        pshRelEdgeUncurry a =
          pshRelEdgeUncurry b → a = b :=
      fun a b h =>
        (pshRelEdgeCurry_uncurry a).symm.trans
          (congrArg pshRelEdgeCurry h
            |>.trans
            (pshRelEdgeCurry_uncurry b))
    apply inj
    rw [pshRelEdgeUncurry_curry,
      pshRelEdgeUncurry_curry_comp,
      Category.assoc]

instance pshRelEdgeBraided
    (C : Type u) [Category.{v} C] :
    BraidedCategory
      (PshRelEdge.{u, v, w} C) :=
  BraidedCategory.ofCartesianMonoidalCategory

instance pshRelEdgeSymmetric
    (C : Type u) [Category.{v} C] :
    SymmetricCategory
      (PshRelEdge.{u, v, w} C) :=
  CartesianMonoidalCategory.toSymmetricCategory

open MonoidalCategory in
/-- Each edge `A` in `PshRelEdge C` is closed:
`tensorLeft A` has `pshRelEdgeIhom A` as
right adjoint. The adjunction uses the
braiding `A ⊗ B ≅ B ⊗ A` to match the
`tensorLeft` convention with our curry
convention `pshRelEdgeProd B A ⟶ C ↔
B ⟶ pshRelEdgeExp A C`. -/
instance pshRelEdgeClosed
    (A : PshRelEdge.{u, v, max u v} C) :
    Closed A where
  rightAdj := pshRelEdgeIhom A
  adj := Adjunction.mkOfHomEquiv
    { homEquiv := fun B D =>
        { toFun := fun (f : A ⊗ B ⟶ D) =>
            pshRelEdgeCurry (C := C)
              ((β_ B A).hom ≫ f)
          invFun := fun g =>
            (β_ B A).inv ≫
              pshRelEdgeUncurry g
          left_inv := fun f => by
            simp only [Iso.inv_hom_id_assoc,
              pshRelEdgeUncurry_curry]
          right_inv := fun g => by
            dsimp only []
            rw [Iso.hom_inv_id_assoc]
            exact pshRelEdgeCurry_uncurry g }
      homEquiv_naturality_right := by
        intro X Y Y' f g
        simp only [Equiv.coe_fn_mk]
        symm
        have inj := fun
            (a b : X ⟶ pshRelEdgeExp A Y') =>
          fun (h : pshRelEdgeUncurry a =
            pshRelEdgeUncurry b) =>
          (pshRelEdgeCurry_uncurry a).symm.trans
            (congrArg pshRelEdgeCurry h
              |>.trans
              (pshRelEdgeCurry_uncurry b))
        apply inj
        change pshRelEdgeUncurry
          (pshRelEdgeCurry ((β_ X A).hom ≫ f) ≫
            pshRelEdgeCurry
              (pshRelEdgeEval A Y ≫ g)) = _
        rw [pshRelEdgeUncurry_curry_comp,
          pshRelEdgeUncurry_curry,
          Category.assoc] }

/-- `PshRelEdge C` is monoidal closed (at
universe `w = max u v`): every object is
closed. -/
instance pshRelEdgeMonoidalClosed
    (C : Type u) [Category.{v} C] :
    MonoidalClosed
      (PshRelEdge.{u, v, max u v} C) where
  closed A := pshRelEdgeClosed A

open MonoidalClosed MonoidalCategory in
/-- The internal hom object `[A, B]` in
`PshRelEdge C`, via mathlib's `ihom` from the
`MonoidalClosed` instance. -/
abbrev pshRelEdgeInternalHom
    (A B : PshRelEdge.{u, v, max u v} C) :
    PshRelEdge.{u, v, max u v} C :=
  (ihom A).obj B

open MonoidalClosed MonoidalCategory in
/-- The internal hom functor `[A, -]` in
`PshRelEdge C`, via mathlib's `ihom`. -/
abbrev pshRelEdgeInternalHomFunctor
    (A : PshRelEdge.{u, v, max u v} C) :
    PshRelEdge.{u, v, max u v} C ⥤
    PshRelEdge.{u, v, max u v} C :=
  ihom A

open MonoidalClosed MonoidalCategory in
/-- The adjunction `- ⊗ A ⊣ [A, -]` in
`PshRelEdge C`, from mathlib's `ihom`. -/
abbrev pshRelEdgeIhomAdjunction
    (A : PshRelEdge.{u, v, max u v} C) :
    tensorLeft A ⊣ ihom A :=
  ihom.adjunction A

open MonoidalClosed MonoidalCategory in
/-- The global-element correspondence: the
internal hom from the terminal edge to any
edge `A` is isomorphic to `A` itself.
`Hom(⊤, [⊤, A]) ≅ Hom(⊤, A)`, which by
Yoneda means `[⊤, A] ≅ A`. -/
abbrev pshRelEdgeUnitIsoSelf
    (A : PshRelEdge.{u, v, max u v} C) :
    ((𝟙_ (PshRelEdge.{u, v, max u v} C))
      ⟶[PshRelEdge.{u, v, max u v} C] A) ≅
    A :=
  unitIsoSelf (X := A)

open MonoidalClosed MonoidalCategory in
/-- Global elements of the internal hom
biject with morphisms:
`Hom(⊤, [A, B]) ≃ Hom(A, B)`.
This is the CCC correspondence that connects
`ParametricCone` (global elements of a limit)
to natural transformations between
endofunctors.

The equivalence is the adjunction hom-equiv
`Hom(A ⊗ ⊤, B) ≅ Hom(⊤, [A, B])` composed
with the right unitor `A ⊗ ⊤ ≅ A`. -/
def pshRelEdgeGlobalElementEquiv
    (A B : PshRelEdge.{u, v, max u v} C) :
    (pshRelEdgeTerminal C ⟶
      pshRelEdgeInternalHom A B) ≃
    (A ⟶ B) :=
  ((ihom.adjunction A).homEquiv
    (pshRelEdgeTerminal C) B).symm.trans
    (Iso.homCongr (ρ_ A) (Iso.refl B))

open MonoidalClosed MonoidalCategory in
/-- Mathlib's curry for `PshRelEdge C`:
given `f : A ⊗ B ⟶ D`, produce
`B ⟶ [A, D]`. -/
abbrev pshRelEdgeMathCurry
    {A B D : PshRelEdge.{u, v, max u v} C}
    [inst : Closed A]
    (f : A ⊗ B ⟶ D) : B ⟶ (ihom A).obj D :=
  MonoidalClosed.curry f

open MonoidalClosed MonoidalCategory in
/-- Mathlib's uncurry for `PshRelEdge C`:
given `g : B ⟶ [A, D]`, produce
`A ⊗ B ⟶ D`. -/
abbrev pshRelEdgeMathUncurry
    {A B D : PshRelEdge.{u, v, max u v} C}
    [inst : Closed A]
    (g : B ⟶ (ihom A).obj D) :
    A ⊗ B ⟶ D :=
  MonoidalClosed.uncurry g

open MonoidalClosed MonoidalCategory in
/-- Internalize a morphism as a global element
of the internal hom: given `f : A ⟶ B`,
produce `⊤ ⟶ [A, B]`. -/
abbrev pshRelEdgeInternalize
    {A B : PshRelEdge.{u, v, max u v} C}
    (f : A ⟶ B) :
    pshRelEdgeTerminal C ⟶
      pshRelEdgeInternalHom A B :=
  (pshRelEdgeGlobalElementEquiv A B).symm f

end CartesianClosedInstances

section YonedaExtFullFaithfulness

variable (C : Type u) [Category.{v} C]

/-- Post-composition with `uliftFunctor` is
fully faithful (it is an equivalence). -/
def whiskerRightULiftFullyFaithful :
    ((Functor.whiskeringRight Cᵒᵖ
      (Type v) (Type (max u v))).obj
      uliftFunctor.{u}).FullyFaithful where
  preimage {P Q} α :=
    { app := fun c p =>
        (α.app c (ULift.up p)).down
      naturality := fun {c d} f => by
        ext p
        have h := congr_fun
          (α.naturality f) (ULift.up p)
        exact congrArg ULift.down h }
  map_preimage {P Q} α := by
    ext c ⟨p⟩; rfl
  preimage_map {P Q} f := by
    ext c p; rfl

/-- `yonedaLarge C` is fully faithful, as
the composition of fully faithful `yoneda`
with fully faithful post-composition by
`uliftFunctor`. -/
def yonedaLargeFullyFaithful :
    (yonedaLarge C).FullyFaithful :=
  Yoneda.fullyFaithful.comp
    (whiskerRightULiftFullyFaithful C)

/-- Extract a morphism `F.obj X ⟶ G.obj X`
from a natural transformation
`α : yonedaExt F ⟶ yonedaExt G` by
restricting to the representable
`yonedaULift X` and conjugating with the
representable isomorphism. -/
def yonedaExtPreimageApp
    {F G : C ⥤ C}
    (α : yonedaExt F ⟶ yonedaExt G)
    (X : C) : F.obj X ⟶ G.obj X :=
  Yoneda.fullyFaithful.preimage
    (Functor.FullyFaithful.preimage
      (whiskerRightULiftFullyFaithful C)
      ((yonedaExtRepresentableULiftIso F X).inv
        ≫ α.app (yonedaULift X)
        ≫ (yonedaExtRepresentableULiftIso
            G X).hom))

/-- The representable isomorphism is natural
in `X`: the family
`yonedaExtRepresentableULiftIso F X` assembles
into a natural isomorphism
`F ⋙ yonedaLarge C ≅
(yonedaLarge C) ⋙ yonedaExt F`.

This says: applying `F` then embedding via
`yonedaLarge` is naturally isomorphic to
embedding via `yonedaLarge` then extending
via `yonedaExt F`. -/
def yonedaExtRepresentableNatIso
    (F : C ⥤ C) :
    F ⋙ yonedaLarge C ≅
      yonedaLarge C ⋙ yonedaExt F :=
  NatIso.ofComponents
    (fun X => {
      hom := (yonedaExtRepresentableULiftIso F X).inv
      inv := (yonedaExtRepresentableULiftIso F X).hom
      hom_inv_id :=
        (yonedaExtRepresentableULiftIso F X).inv_hom_id
      inv_hom_id :=
        (yonedaExtRepresentableULiftIso F X).hom_inv_id
    })
    (fun {X Y} f => by
      ext T ⟨t⟩
      simp only [Functor.comp_obj,
        Functor.comp_map, NatTrans.comp_app,
        types_comp_apply]
      -- LHS: iso(F,Y).inv applied to
      --   (yonedaLarge.map(F.map f))(t)
      -- = iso(F,Y).inv applied to
      --   (t ≫ F.map f)
      -- = Quot.mk(Y, 𝟙 Y, t ≫ F.map f)
      -- RHS: (yonedaExt F).map(yonedaLarge.map f)
      --   applied to iso(F,X).inv(t)
      -- = (yonedaExt F).map(yonedaLarge.map f)
      --   applied to Quot.mk(X, 𝟙 X, t)
      -- = Quot.mk(X, f, t)
      -- (by the yonedaExt map definition)
      -- These are equal in the quotient:
      -- (X, f, t) ~ (Y, 𝟙 Y, t ≫ F.map f)
      -- via the step (Y, f, 𝟙 Y).
      dsimp [yonedaExtRepresentableULiftIso,
        yonedaExtUnitULift, yonedaLarge,
        yonedaULift, yonedaExt, yonedaExtObj,
        yonedaExtSigmaMap]
      apply Quot.sound
      exact ⟨f,
        by dsimp [yonedaExtSigmaMapNat]; simp,
        by dsimp [yonedaExtSigmaMapNat]⟩)

/-- Abbreviation for the ulift-yoneda-level
composition used in the preimage: the
iso conjugation of `α` at a given object. -/
abbrev yonedaExtPreimageULift
    {F G : C ⥤ C}
    (α : yonedaExt F ⟶ yonedaExt G)
    (X : C) :
    yonedaULift (F.obj X) ⟶
      yonedaULift (G.obj X) :=
  (yonedaExtRepresentableULiftIso F X).inv ≫
    α.app (yonedaULift X) ≫
    (yonedaExtRepresentableULiftIso G X).hom

/-- The ulift-level preimage satisfies
naturality: `yUL(F.map f) ≫ preimageULift(Y)
= preimageULift(X) ≫ yUL(G.map f)`.
This follows from naturality of
`yonedaExtRepresentableNatIso` and
naturality of `α`. -/
theorem yonedaExtPreimageULift_naturality
    {F G : C ⥤ C}
    (α : yonedaExt F ⟶ yonedaExt G)
    {X Y : C} (f : X ⟶ Y) :
    (yonedaLarge C).map (F.map f) ≫
      yonedaExtPreimageULift (C := C) α Y =
    yonedaExtPreimageULift (C := C) α X ≫
      (yonedaLarge C).map (G.map f) := by
  -- The proof chains three naturality
  -- results at the ulift-yoneda level.
  -- Use the NatIso naturality we proved
  -- in `yonedaExtRepresentableNatIso` and
  -- the naturality of `α`.
  simp only [yonedaExtPreimageULift,
    Category.assoc]
  -- Factor: state the naturality of the
  -- NatIso as a separate lemma about
  -- yonedaExtRepresentableULiftIso components.
  have natIsoF_nat :
      (yonedaLarge C).map (F.map f) ≫
        (yonedaExtRepresentableULiftIso F Y).inv
      =
      (yonedaExtRepresentableULiftIso F X).inv ≫
        (yonedaExt F).map
          ((yonedaLarge C).map f) := by
    have h := Iso.hom
      (yonedaExtRepresentableNatIso C F)
      |>.naturality f
    simp only [Functor.comp_map] at h
    exact h
  have natIsoG_nat :
      (yonedaExt G).map
          ((yonedaLarge C).map f) ≫
        (yonedaExtRepresentableULiftIso G Y).hom
      =
      (yonedaExtRepresentableULiftIso G X).hom ≫
        (yonedaLarge C).map (G.map f) := by
    have h := Iso.inv
      (yonedaExtRepresentableNatIso C G)
      |>.naturality f
    simp only [Functor.comp_map] at h
    exact h
  -- Reassociate to expose the pattern
  -- for natIsoF_nat on the LHS.
  rw [show (yonedaLarge C).map (F.map f) ≫
    (yonedaExtRepresentableULiftIso F Y).inv ≫
    α.app (yonedaULift Y) ≫
    (yonedaExtRepresentableULiftIso G Y).hom =
    ((yonedaLarge C).map (F.map f) ≫
      (yonedaExtRepresentableULiftIso F Y).inv)
    ≫ α.app (yonedaULift Y) ≫
    (yonedaExtRepresentableULiftIso G Y).hom
    from by simp only [Category.assoc],
    natIsoF_nat]
  simp only [Category.assoc]
  -- Now LHS: iso_X.inv ≫ yExt_F(yL.map f) ≫
  --   α(yUL Y) ≫ iso_G_Y.hom
  -- Cancel common prefix iso_F_X.inv.
  -- Convert yonedaULift to yonedaLarge.obj.
  change
    (yonedaExtRepresentableULiftIso F X).inv ≫
      (yonedaExt F).map ((yonedaLarge C).map f) ≫
      α.app ((yonedaLarge C).obj Y) ≫
      (yonedaExtRepresentableULiftIso G Y).hom =
    (yonedaExtRepresentableULiftIso F X).inv ≫
      α.app ((yonedaLarge C).obj X) ≫
      (yonedaExtRepresentableULiftIso G X).hom ≫
      (yonedaLarge C).map (G.map f)
  calc (yonedaExtRepresentableULiftIso F X).inv
      ≫ (yonedaExt F).map
        ((yonedaLarge C).map f) ≫
      α.app ((yonedaLarge C).obj Y) ≫
      (yonedaExtRepresentableULiftIso G Y).hom
    _ = (yonedaExtRepresentableULiftIso F X).inv
      ≫ (α.app ((yonedaLarge C).obj X) ≫
      (yonedaExt G).map
        ((yonedaLarge C).map f)) ≫
      (yonedaExtRepresentableULiftIso G Y).hom
      := by
        simp only [Category.assoc]
        congr 1
        rw [← Category.assoc,
          α.naturality
            ((yonedaLarge C).map f),
          Category.assoc]
    _ = (yonedaExtRepresentableULiftIso F X).inv
      ≫ α.app ((yonedaLarge C).obj X) ≫
      (yonedaExtRepresentableULiftIso G X).hom ≫
      (yonedaLarge C).map (G.map f)
      := by simp only [Category.assoc,
        natIsoG_nat]

/-- Naturality of `yonedaExtPreimageApp`:
`F.map f ≫ preimageApp(Y) =
preimageApp(X) ≫ G.map f`.
Follows from `yonedaExtPreimageULift_naturality`
by reflecting through `yoneda` and `ulift`
full faithfulness. -/
theorem yonedaExtPreimageApp_naturality
    {F G : C ⥤ C}
    (α : yonedaExt F ⟶ yonedaExt G)
    {X Y : C} (f : X ⟶ Y) :
    F.map f ≫
      yonedaExtPreimageApp (C := C) α Y =
    yonedaExtPreimageApp (C := C) α X ≫
      G.map f := by
  -- First check: does unfold work?
  simp only [yonedaExtPreimageApp]
  rw [← Yoneda.fullyFaithful.preimage_map
    (F.map f),
    ← Yoneda.fullyFaithful.preimage_comp,
    ← Yoneda.fullyFaithful.preimage_map
    (G.map f)]
  conv_rhs =>
    rw [← Yoneda.fullyFaithful.preimage_comp]
  congr 1
  -- Inject through wFF to get to ULift level.
  apply Functor.FullyFaithful.map_injective
    (whiskerRightULiftFullyFaithful C)
  rw [Functor.map_comp, Functor.map_comp,
    Functor.FullyFaithful.map_preimage
      (whiskerRightULiftFullyFaithful C),
    Functor.FullyFaithful.map_preimage
      (whiskerRightULiftFullyFaithful C)]
  -- Now at ULift level.
  exact @yonedaExtPreimageULift_naturality
    C _ _ _ α _ _ f

/-- The preimage as a natural transformation:
given `α : yonedaExt F ⟶ yonedaExt G`,
produce `F ⟶ G`. -/
def yonedaExtFunctorPreimage
    {F G : C ⥤ C}
    (α : yonedaExt F ⟶ yonedaExt G) :
    F ⟶ G where
  app X := yonedaExtPreimageApp (C := C) α X
  naturality _ _ f :=
    yonedaExtPreimageApp_naturality C α f


/-- Every element `Quot.mk ⟨S, g, t⟩` of
`(yonedaExt F).obj P` at stage `T` equals
`((yonedaExt F).obj P).map t.op
(Quot.mk ⟨S, g, 𝟙⟩)`: the element at the
representable stage `op(F.obj S)` transported
along `t`. -/
theorem yonedaExtElement_decompose
    {F : C ⥤ C}
    (P : Cᵒᵖ ⥤ Type (max u v))
    (T : Cᵒᵖ) (S : C)
    (g : P.obj (Opposite.op S))
    (t : T.unop ⟶ F.obj S) :
    Quot.mk (YonedaExtStep F P T)
      ⟨S, g, t⟩ =
    ((yonedaExt F).obj P).map t.op
      (Quot.mk
        (YonedaExtStep F P
          (Opposite.op (F.obj S)))
        ⟨S, g, 𝟙 (F.obj S)⟩) := by
  change _ = Quot.mk _
    (yonedaExtSigmaMap F P t.op _)
  dsimp [yonedaExtSigmaMap]
  simp

/-- At the representable stage (where
`t = 𝟙`), `yonedaExtFunctor.map(preimage α)`
agrees with `α` for any presheaf `P`. -/
theorem yonedaExtFunctor_map_preimage_id
    {F G : C ⥤ C}
    (α : yonedaExt F ⟶ yonedaExt G)
    (P : Cᵒᵖ ⥤ Type (max u v))
    (S : C) (g : P.obj (Opposite.op S)) :
    (NatTrans.app
      (yonedaExtFunctor.map
        (yonedaExtFunctorPreimage (C := C) α))
      P).app (Opposite.op (F.obj S))
      (Quot.mk _
        ⟨S, g, 𝟙 (F.obj S)⟩) =
    (α.app P).app (Opposite.op (F.obj S))
      (Quot.mk _
        ⟨S, g, 𝟙 (F.obj S)⟩) := by
  -- LHS: Quot.mk(G-step)(yonedaExtSigmaAlpha
  --   (preimage α) P (op(F.obj S))
  --   ⟨S, g, 𝟙⟩)
  -- = Quot.mk(G-step)
  --   ⟨S, g, 𝟙 ≫ preimage(α).app S⟩
  -- = Quot.mk(G-step)
  --   ⟨S, g, preimage(α).app S⟩
  -- RHS: α.app P . app (op(F.obj S))
  --   (Quot.mk(F-step) ⟨S, g, 𝟙⟩)
  -- Use naturality of α at the presheaf
  -- morphism P → yonedaULift S induced by g.
  -- Factor: first rewrite LHS via
  -- yonedaExtSigmaAlpha unfolding.
  change Quot.mk _ _ = _
  dsimp [yonedaExtFunctor,
    yonedaExtFunctorPreimage,
    yonedaExtPreimageApp,
    yonedaExtPreimageULift,
    whiskerRightULiftFullyFaithful,
    yonedaExtRepresentableULiftIso,
    yonedaExtCounitULift,
    yonedaExtUnitULift,
    yonedaExtSigmaAlpha,
    Yoneda.fullyFaithful]
  simp only [Category.id_comp]
  -- Now: Quot.mk(G-step)
  --   ⟨S, g, Quot.lift(...)(α(yUL S)(op(F.obj S))
  --     (Quot.mk ⟨S, ⟨𝟙, 𝟙⟩⟩)).down⟩
  -- = α.app P . app (op(F.obj S))
  --   (Quot.mk ⟨S, g, 𝟙⟩)
  -- Step 1: write ⟨S, g, 𝟙⟩ as
  -- (yonedaExtPresheafUnit F P).app(op S)(g).
  -- Step 2: use naturality of α at
  -- yonedaExtPresheafUnit F P to factor
  -- through the representable.
  -- Step 3: at the representable, both sides
  -- reduce to the preimage construction.
  --
  -- Direct: use the presheaf unit to connect
  -- P-level elements to representable-level
  -- elements, then α's naturality at the unit.
  -- Define η_g : yonedaULift S ⟶ P.
  let η_g : yonedaULift (C := C) S ⟶ P :=
    { app := fun T x =>
        P.map (Quiver.Hom.op x.down) g
      naturality := fun {T₁ T₂} k => by
        ext ⟨f⟩
        simp only [types_comp_apply,
          yonedaULift]
        exact congr_fun (P.map_comp _ _) g }
  -- Use α.naturality at η_g.
  have natα := congr_fun (congr_app
    (α.naturality η_g)
    (Opposite.op (F.obj S)))
    (Quot.mk _
      ⟨S, (ULift.up (𝟙 S),
        𝟙 (F.obj S))⟩)
  -- natα has form:
  -- (yonedaExt(F).map(η_g) ≫ α.app(P))(...)(q₀)
  -- = (α.app(yUL S) ≫ yonedaExt(G).map(η_g))(...)(q₀)
  -- Unfold the ≫ to get function application.
  simp only [NatTrans.comp_app,
    types_comp_apply] at natα
  -- Now natα is pointwise.
  -- RHS of goal = α(P)(...)(⟨S,g,𝟙⟩)
  -- = α(P)(...)(yonedaExt(F).map(η_g)(q₀))
  -- [because yonedaExt(F).map(η_g)(q₀) = ⟨S,g,𝟙⟩]
  -- = natα LHS
  -- = natα RHS
  -- = yonedaExt(G).map(η_g)(α(yUL S)(q₀))
  -- = LHS of goal
  -- [because yonedaExt(G).map(η_g) sends
  -- the ULift component to g via η_g]
  -- Step A: RHS = α(P)(...)(yonedaExt(F).map(η_g)(q₀))
  conv_rhs =>
    rw [show Quot.mk
        (YonedaExtStep F P
          (Opposite.op (F.obj S)))
        ⟨S, (g, 𝟙 (F.obj S))⟩ =
      ((yonedaExt F).map η_g).app
        (Opposite.op (F.obj S))
        (Quot.mk _
          ⟨S, (ULift.up (𝟙 S),
            𝟙 (F.obj S))⟩)
      from by
        change Quot.mk _ _ = Quot.mk _ _
        congr 1
        dsimp [yonedaExtSigmaMapNat, η_g]
        simp only [P.map_id,
          types_id_apply]]
  -- Use natα to rewrite RHS. After step A,
  -- RHS = natα LHS. Rewrite to natα RHS.
  rw [natα]
  -- Now both sides involve
  -- (yonedaExt G).map(η_g)(α(yUL S)(q₀)).
  -- LHS = Quot.mk ⟨S, g, Quot.lift(...)(αq).down⟩
  -- RHS = (yonedaExt G).map(η_g)(αq)
  -- These agree by Quot.inductionOn on αq.
  set αq := (α.app (yonedaULift S)).app
    (Opposite.op (F.obj S))
    (Quot.mk _
      ⟨S, (ULift.up (𝟙 S),
        𝟙 (F.obj S))⟩)
  induction αq using Quot.inductionOn with
  | h x =>
    obtain ⟨W, ⟨h_w⟩, t⟩ := x
    -- RHS = Quot.mk ⟨W, (P.map(h_w.op)(g), t)⟩
    -- LHS = Quot.mk ⟨S, (g, t ≫ G.map h_w)⟩
    -- Related by quotient step h_w.
    -- Unfold the RHS directly.
    -- RHS = Quot.mk ⟨W, (P.map(h_w.op)(g), t)⟩
    -- (after unfolding yonedaExt.map(η_g)).
    -- LHS = Quot.mk ⟨S, (g, t ≫ G.map h_w)⟩
    -- These are related by step h_w:
    -- ⟨S, (g, t ≫ G.map h_w)⟩ ~
    -- ⟨W, (P.map(h_w.op)(g), t)⟩.
    conv_rhs =>
      dsimp [yonedaExt, yonedaExtObj,
        yonedaExtMap, yonedaExtSigmaMap, η_g]
    apply Quot.sound
    exact ⟨h_w,
      by dsimp [yonedaExtSigmaMapNat],
      by dsimp [yonedaExtSigmaMapNat]⟩

/-- The map-preimage roundtrip for a single
quotient representative `⟨S, g, t⟩`. -/
theorem yonedaExtFunctor_map_preimage_triple
    {F G : C ⥤ C}
    (α : yonedaExt F ⟶ yonedaExt G)
    (P : Cᵒᵖ ⥤ Type (max u v))
    (T : Cᵒᵖ)
    (S : C)
    (g : P.obj (Opposite.op S))
    (t : T.unop ⟶ F.obj S) :
    (NatTrans.app
      (yonedaExtFunctor.map
        (yonedaExtFunctorPreimage (C := C) α))
      P).app T
      (Quot.mk _ ⟨S, g, t⟩) =
    (α.app P).app T
      (Quot.mk _ ⟨S, g, t⟩) := by
  -- Both LHS and RHS are nat trans apps.
  -- Decompose and chain.
  let lhs := NatTrans.app
    (yonedaExtFunctor.map
      (yonedaExtFunctorPreimage (C := C) α)) P
  let rhs := α.app P
  -- Decompose on both sides.
  -- yonedaExtFunctor.obj F = yonedaExt F
  -- definitionally.
  change lhs.app T (Quot.mk _ ⟨S, g, t⟩) =
    rhs.app T (Quot.mk _ ⟨S, g, t⟩)
  conv_lhs =>
    rw [yonedaExtElement_decompose (C := C) P T S g t]
  conv_rhs =>
    rw [yonedaExtElement_decompose (C := C) P T S g t]
  -- Both sides apply nat trans (lhs/rhs) to
  -- the SAME element: map(t.op)(q₀).
  -- Use congrArg to reduce to the id lemma.
  have base := yonedaExtFunctor_map_preimage_id
    C α P S g
  -- base : lhs.app(op(F.obj S))(q₀) =
  --   rhs.app(op(F.obj S))(q₀)
  -- Apply ((yonedaExt G).obj P).map(t.op).
  -- lhs.app T (F.map(t.op) q₀)
  -- = G.map(t.op) (lhs.app(op(F.obj S)) q₀)
  -- by naturality of lhs.
  have nat_lhs := congr_fun
    (lhs.naturality t.op)
    (Quot.mk _ ⟨S, g, 𝟙 (F.obj S)⟩)
  -- rhs.app T (F.map(t.op) q₀)
  -- = G.map(t.op) (rhs.app(op(F.obj S)) q₀)
  -- by naturality of rhs.
  have nat_rhs := congr_fun
    (rhs.naturality t.op)
    (Quot.mk _ ⟨S, g, 𝟙 (F.obj S)⟩)
  simp only [types_comp_apply,
    Opposite.op_unop] at nat_lhs nat_rhs
  -- nat_lhs uses yonedaExtFunctor.obj F =
  -- yonedaExt F (definitionally equal).
  exact nat_lhs.trans
    (congrArg _ base |>.trans nat_rhs.symm)

/-- `yonedaExtFunctor.map(preimage α) = α`:
the map-preimage roundtrip. -/
theorem yonedaExtFunctor_map_preimage
    {F G : C ⥤ C}
    (α : yonedaExt F ⟶ yonedaExt G) :
    yonedaExtFunctor.map
      (yonedaExtFunctorPreimage (C := C) α) =
    α := by
  ext P T x
  induction x using Quot.inductionOn with
  | h x =>
    obtain ⟨S, g, t⟩ := x
    exact yonedaExtFunctor_map_preimage_triple
      (C := C) α P T S g t

/-- `yonedaExtFunctor` is fully faithful:
natural transformations between endofunctors
`F ⟶ G` biject with natural transformations
between their Yoneda extensions
`yonedaExt F ⟶ yonedaExt G`. -/
def yonedaExtFunctorFullyFaithful :
    Functor.FullyFaithful
      (yonedaExtFunctor :
        (C ⥤ C) ⥤
        ((Cᵒᵖ ⥤ Type (max u v)) ⥤
          (Cᵒᵖ ⥤ Type (max u v)))) where
  preimage {F G} α :=
    yonedaExtFunctorPreimage (C := C) α
  map_preimage {F G} α :=
    @yonedaExtFunctor_map_preimage
      C _ _ _ α
  preimage_map {F G} σ := by
    ext X
    -- preimage(yonedaExtFunctor.map σ).app X
    -- = yFF.preimage(wFF.preimage(
    --   iso_X.inv ≫ (yonedaExt σ).app(yUL X)
    --   ≫ iso_X.hom))
    -- The iso conjugation with yonedaExt σ
    -- gives yoneda.map(σ.app X) ⋙ ulift.
    -- Reflecting through wFF gives
    -- yoneda.map(σ.app X), then through yFF
    -- gives σ.app X.
    dsimp [yonedaExtFunctorPreimage,
      yonedaExtPreimageApp,
      yonedaExtPreimageULift,
      whiskerRightULiftFullyFaithful,
      yonedaExtRepresentableULiftIso,
      yonedaExtCounitULift,
      yonedaExtUnitULift,
      yonedaExtFunctor,
      yonedaExt, yonedaExtObj,
      yonedaExtSigmaAlpha,
      yonedaExtSigmaMapNat,
      Yoneda.fullyFaithful]
    change (𝟙 (F.obj X) ≫ σ.app X) ≫
      G.map (𝟙 X) = σ.app X
    simp only [G.map_id, Category.id_comp,
      Category.comp_id]

end YonedaExtFullFaithfulness

end GebLean
