import GebLean.PshRelEdgeInclusion
import GebLean.PshRelEdgeExp
import GebLean.Utilities.PowersAndCopowers
import Mathlib.CategoryTheory.Monoidal.Cartesian.Basic
import Mathlib.CategoryTheory.Adjunction.Reflective
import Mathlib.CategoryTheory.Monoidal.Closed.FunctorCategory.Basic
import Mathlib.CategoryTheory.Functor.Currying

/-!
# PshRelEdge C as separated presheaves

This file constructs the equivalence between
`PshRelEdge C` and the full subcategory of
`WalkingSpan ⥤ PSh(C)` on separated spans:
those where the pairing map
`F(.none) → F(.left) × F(.right)` is a
monomorphism (i.e., the two span projections
are jointly monic).

This is the separated-presheaf characterization
`PshRelEdge C ≅ Sep_J(C × I^op)` where `J` is
the Grothendieck topology on `C × I^op`
generated by covering each span apex with
its two projections.

## Main definitions

* `IsSeparatedSpan`: predicate on
  `WalkingSpan ⥤ PSh(C)` for joint monicity
  of span projections
* `pshRelEdge_isSeparatedSpan`: every edge
  in the image of the inclusion is separated
* `separatedSpanToEdge`: build an edge from a
  separated span
* `pshRelEdgeSepEquiv`: the category
  equivalence
-/

open CategoryTheory Limits

namespace GebLean

universe u v w

variable {C : Type u} [Category.{v} C]

/-- A span `F : WalkingSpan ⥤ PSh(C)` is
**separated** when the two span projections
`F.map fst` and `F.map snd` are jointly
injective at each stage: if two elements
`r₁, r₂ ∈ F(.none)(c)` have the same images
under both projections, then `r₁ = r₂`.

This is equivalent to the pairing map
`F(.none) → F(.left) × F(.right)` being a
monomorphism (in `Type`-valued presheaf
categories, monomorphisms are pointwise
injective). This is the separation condition
for the Grothendieck topology on `C × I^op`
generated by covering each span apex with its
two projections.

For edges in the image of
`pshRelEdgeInclusionFunctor`, this holds
because the relation `R` is a subfunctor of
`P × Q`, so the inclusion `R.ι` is monic. -/
def IsSeparatedSpan
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w)) :
    Prop :=
  ∀ (c : Cᵒᵖ)
    (r₁ r₂ : (F.obj .none).obj c),
    (F.map WalkingSpan.Hom.fst).app c r₁ =
      (F.map WalkingSpan.Hom.fst).app c r₂ →
    (F.map WalkingSpan.Hom.snd).app c r₁ =
      (F.map WalkingSpan.Hom.snd).app c r₂ →
    r₁ = r₂

/-- Every edge in the image of the inclusion
functor is separated. The pairing map is
`R.ι : R.toFunctor ⟶ pshProdPresheaf P Q`,
which is monic because `R` is a subfunctor. -/
theorem pshRelEdge_isSeparatedSpan
    (E : PshRelEdge.{u, v, w} C) :
    IsSeparatedSpan
      (pshRelEdgeSpan (C := C) E) := by
  intro c r₁ r₂ hfst hsnd
  dsimp [pshRelEdgeSpan, span,
    WidePushoutShape.mkCocone,
    pshRelFstProj,
    pshRelSndProj] at hfst hsnd
  exact Subtype.ext (Prod.ext hfst hsnd)

/-- Build a presheaf relation from a separated
span by taking the image of the pairing map
`(F.map fst, F.map snd) :
F(.none) → F(.left) × F(.right)`.

The relation at stage `c` consists of pairs
`(p, q) ∈ F(.left)(c) × F(.right)(c)` such
that there exists `r ∈ F(.none)(c)` with
`F.map(fst)(r) = p` and `F.map(snd)(r) = q`.

When the span is separated, the pairing map
is injective, so each pair `(p, q)` in the
relation has a unique witness `r`. -/
def separatedSpanRel
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w)) :
    PshRel (F.obj (.some .left))
      (F.obj (.some .right)) where
  obj c :=
    { pq |
      ∃ r : F.obj .none |>.obj c,
        (F.map WalkingSpan.Hom.fst).app c r =
          pq.1 ∧
        (F.map WalkingSpan.Hom.snd).app c r =
          pq.2 }
  map {c d} f := by
    rintro ⟨p, q⟩ ⟨r, hrp, hrq⟩
    refine ⟨F.obj .none |>.map f r, ?_, ?_⟩
    · have nat := congr_fun
        ((F.map WalkingSpan.Hom.fst).naturality
          f) r
      simp only [types_comp_apply] at nat
      rw [nat, hrp]; rfl
    · have nat := congr_fun
        ((F.map WalkingSpan.Hom.snd).naturality
          f) r
      simp only [types_comp_apply] at nat
      rw [nat, hrq]; rfl

/-- Build an edge from a span by taking
the image relation. -/
def separatedSpanToEdge
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w)) :
    PshRelEdge.{u, v, w} C :=
  { src := F.obj (.some .left)
    tgt := F.obj (.some .right)
    edge := separatedSpanRel (C := C) F }

/-- The image relation of the inclusion span
equals the original relation: the image of a
subfunctor inclusion `R.ι` is `R` itself. -/
theorem separatedSpanRel_of_inclusion
    (E : PshRelEdge.{u, v, w} C) :
    separatedSpanRel (pshRelEdgeSpan E) =
    E.edge := by
  apply Subfunctor.ext
  funext c
  ext ⟨p, q⟩
  simp only [separatedSpanRel,
    pshRelEdgeSpan, span,
    pshRelFstProj, pshRelSndProj,
    Set.mem_setOf_eq]
  constructor
  · rintro ⟨r, hrp, hrq⟩
    have : (p, q) = r.val := Prod.ext
      hrp.symm hrq.symm
    rw [this]
    exact r.prop
  · intro hpq
    exact ⟨⟨(p, q), hpq⟩, rfl, rfl⟩

/-- Round-trip: `separatedSpanToEdge` applied
to the inclusion span of an edge recovers the
original edge. -/
theorem separatedSpanToEdge_inclusion
    (E : PshRelEdge.{u, v, w} C) :
    separatedSpanToEdge
      (pshRelEdgeSpan (C := C) E) = E := by
  simp only [separatedSpanToEdge,
    pshRelEdgeSpan, span]
  exact congrArg (VertEdge.mk E.src E.tgt)
    (separatedSpanRel_of_inclusion E)

/-- The pairing map from the span apex to
the image relation's total presheaf. Sends
`r ∈ F(.none)(c)` to
`((F.map fst)(r), (F.map snd)(r))` with the
witness `r` itself. -/
def separatedSpanPairingMap
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w)) :
    F.obj .none ⟶
    (separatedSpanRel (C := C) F).toFunctor
    where
  app c r :=
    ⟨((F.map WalkingSpan.Hom.fst).app c r,
      (F.map WalkingSpan.Hom.snd).app c r),
     ⟨r, rfl, rfl⟩⟩
  naturality c d f := by
    ext r
    apply Subtype.ext
    apply Prod.ext
    · exact congr_fun
        ((F.map WalkingSpan.Hom.fst).naturality
          f) r
    · exact congr_fun
        ((F.map WalkingSpan.Hom.snd).naturality
          f) r

/-- For a separated span, the pairing map is
injective at each stage: if two elements have
the same image under both projections, they
are equal. -/
theorem separatedSpanPairingMap_injective
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w))
    (hF : IsSeparatedSpan (C := C) F)
    (c : Cᵒᵖ) :
    Function.Injective
      ((separatedSpanPairingMap F).app c) := by
  intro r₁ r₂ heq
  have heq' := congr_arg Subtype.val heq
  exact hF c r₁ r₂
    (congr_arg Prod.fst heq')
    (congr_arg Prod.snd heq')

/-- The pairing map is surjective: every element
of the image relation has a preimage in the
span apex (by definition of the image). -/
theorem separatedSpanPairingMap_surjective
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w))
    (c : Cᵒᵖ)
    (x : (separatedSpanRel (C := C) F).toFunctor.obj
      c) :
    ∃ r : (F.obj .none).obj c,
      (separatedSpanPairingMap F).app c r =
        x := by
  obtain ⟨⟨p, q⟩, ⟨r, hrp, hrq⟩⟩ := x
  exact ⟨r, Subtype.ext
    (Prod.ext hrp hrq)⟩

/-- The separation reflector `pshRelEdgeSepObj`
applied to an inclusion span gives back the
original edge: the image of a subfunctor
inclusion is the subfunctor itself. -/
theorem pshRelEdgeSepObj_inclusion
    (E : PshRelEdge.{u, v, w} C) :
    pshRelEdgeSepObj (C := C)
      (pshRelEdgeSpan E) = E := by
  simp only [pshRelEdgeSepObj,
    pshRelEdgeSpan, span]
  congr 1
  apply Subfunctor.ext; funext c; ext ⟨p, q⟩
  simp only [Subfunctor.range, Set.mem_range,
    pshProdLift, FunctorToTypes.prod.lift]
  constructor
  · rintro ⟨r, hr⟩
    have hp := congr_arg Prod.fst hr
    have hq := congr_arg Prod.snd hr
    dsimp at hp hq
    rw [← hp, ← hq]
    exact r.prop
  · intro hpq
    exact ⟨⟨(p, q), hpq⟩, rfl⟩

/-- Separated spans map to themselves under the
separation reflector: the reflector unit is a
pointwise injection at the apex, and every pair
in the image has a witness.

The separation condition is equivalent to the
pairing map `F(.none) → F(.left) × F(.right)`
being monic. The reflector replaces the apex
with the image of this map; when the map is
monic, the image is isomorphic to the original
apex (though constructing the inverse requires
extracting witnesses from `Set.range`, which
stores them propositionally).

The reflector `pshRelEdgeSepFunctor` together
with the fully faithful inclusion and
`pshRelEdgeSepObj_inclusion` establishes
`PshRelEdge C` as the reflective subcategory
of separated spans in `WalkingSpan ⥤ PSh(C)`.
-/
theorem separatedSpan_unit_injective
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w))
    (hF : IsSeparatedSpan (C := C) F)
    (c : Cᵒᵖ) :
    Function.Injective
      ((pshRelEdgeSepUnit F).app .none
        |>.app c) := by
  intro r₁ r₂ heq
  have heq' := congr_arg Subtype.val heq
  simp only [pshRelEdgeSepUnit, spanHomMk,
    pshProdLift,
    FunctorToTypes.prod.lift] at heq'
  exact hF c r₁ r₂
    (congr_arg Prod.fst heq')
    (congr_arg Prod.snd heq')

section BarrAdjunctionAgreement

/-- The functor `P ↦ P + B` for a fixed
presheaf `B`, as a covariant endofunctor. -/
def pshCoprodRightFunctor
    (B : Cᵒᵖ ⥤ Type w) :
    (Cᵒᵖ ⥤ Type w) ⥤ (Cᵒᵖ ⥤ Type w) where
  obj P := pshCoprodPresheaf P B
  map {P₁ P₂} f :=
    pshCoprodDesc
      (f ≫ pshCoprodInl P₂ B)
      (pshCoprodInr P₂ B)
  map_id P := by
    ext c x; match x with
    | Sum.inl _ => rfl
    | Sum.inr _ => rfl
  map_comp f g := by
    ext c x; match x with
    | Sum.inl _ => rfl
    | Sum.inr _ => rfl

/-- The Barr lift of the coproduct functor
`(- + B)` at a relation `R` equals the
coproduct relation `pshRelCoprod R (pshRelId B)`.

This shows that the Barr lift agrees with
the adjunction lift (which produces
`pshRelEdgeCoprod`) when the fixed argument
carries the identity relation. -/
theorem pshBarrLiftRel_coprodRight
    {P Q B : Cᵒᵖ ⥤ Type w}
    (R : PshRel P Q) :
    pshBarrLiftRel
      (pshCoprodRightFunctor (C := C) B)
      R =
    pshRelCoprod R (pshRelId B) := by
  apply Subfunctor.ext; funext c
  ext ⟨pq₁, pq₂⟩
  simp only [pshBarrLiftRel, pshBarrLift,
    pshProdOverToRel, Subfunctor.range,
    Set.mem_range, Over.mk_hom,
    FunctorToTypes.prod.lift,
    pshCoprodRightFunctor,
    pshRelCoprod, pshRelId,
    Set.mem_setOf_eq]
  constructor
  · rintro ⟨r, hr⟩
    have h₁ := congr_arg Prod.fst hr
    have h₂ := congr_arg Prod.snd hr
    dsimp [pshCoprodPresheaf] at h₁ h₂
    match r with
    | Sum.inl r' =>
      rw [← h₁, ← h₂]; exact r'.prop
    | Sum.inr b =>
      rw [← h₁, ← h₂]; rfl
  · intro h
    match pq₁, pq₂, h with
    | Sum.inl p, Sum.inl q, h =>
      exact ⟨Sum.inl ⟨(p, q), h⟩, rfl⟩
    | Sum.inr b₁, Sum.inr b₂, h =>
      exact ⟨Sum.inr b₁,
        congr_arg (fun x => (Sum.inr b₁,
          Sum.inr x)) h⟩

end BarrAdjunctionAgreement

section CartesianClosedInstances

variable {C : Type u} [Category.{v} C]

/-- The exponential right adjoint functor for
a fixed edge `A`: sends `B` to
`pshRelEdgeExp A B` and morphisms to the
appropriate induced maps via post-composition
currying. The universe `w = max u v` is
required for the exponential structure. -/
def pshRelEdgeIhom
    (A : PshRelEdge.{u, v, max u v} C) :
    PshRelEdge.{u, v, max u v} C ⥤
    PshRelEdge.{u, v, max u v} C where
  obj B := pshRelEdgeExp A B
  map f := pshRelEdgeCurry
    (pshRelEdgeEval A _ ≫ f)
  map_id B := by
    change pshRelEdgeCurry
      (pshRelEdgeEval A B ≫
        𝟙 (B : PshRelEdge.{u, v, max u v} C)) =
      𝟙 _
    rw [Category.comp_id]
    change pshRelEdgeCurry
      (pshRelEdgeUncurry
        (𝟙 (pshRelEdgeExp A B))) =
      𝟙 (pshRelEdgeExp A B)
    exact pshRelEdgeCurry_uncurry _
  map_comp {B₁ B₂ B₃} f g := by
    have inj : ∀ {X Y : PshRelEdge.{u, v,
        max u v} C}
        (a b : X ⟶ pshRelEdgeExp A Y),
        pshRelEdgeUncurry a =
          pshRelEdgeUncurry b → a = b :=
      fun a b h =>
        (pshRelEdgeCurry_uncurry a).symm.trans
          (congrArg pshRelEdgeCurry h
            |>.trans
            (pshRelEdgeCurry_uncurry b))
    apply inj
    rw [pshRelEdgeUncurry_curry,
      pshRelEdgeUncurry_curry_comp,
      Category.assoc]

instance pshRelEdgeBraided
    (C : Type u) [Category.{v} C] :
    BraidedCategory
      (PshRelEdge.{u, v, w} C) :=
  BraidedCategory.ofCartesianMonoidalCategory

instance pshRelEdgeSymmetric
    (C : Type u) [Category.{v} C] :
    SymmetricCategory
      (PshRelEdge.{u, v, w} C) :=
  CartesianMonoidalCategory.toSymmetricCategory

open MonoidalCategory in
/-- Each edge `A` in `PshRelEdge C` is closed:
`tensorLeft A` has `pshRelEdgeIhom A` as
right adjoint. The adjunction uses the
braiding `A ⊗ B ≅ B ⊗ A` to match the
`tensorLeft` convention with our curry
convention `pshRelEdgeProd B A ⟶ C ↔
B ⟶ pshRelEdgeExp A C`. -/
instance pshRelEdgeClosed
    (A : PshRelEdge.{u, v, max u v} C) :
    Closed A where
  rightAdj := pshRelEdgeIhom A
  adj := Adjunction.mkOfHomEquiv
    { homEquiv := fun B D =>
        { toFun := fun (f : A ⊗ B ⟶ D) =>
            pshRelEdgeCurry (C := C)
              ((β_ B A).hom ≫ f)
          invFun := fun g =>
            (β_ B A).inv ≫
              pshRelEdgeUncurry g
          left_inv := fun f => by
            simp only [Iso.inv_hom_id_assoc,
              pshRelEdgeUncurry_curry]
          right_inv := fun g => by
            dsimp only []
            rw [Iso.hom_inv_id_assoc]
            exact pshRelEdgeCurry_uncurry g }
      homEquiv_naturality_right := by
        intro X Y Y' f g
        simp only [Equiv.coe_fn_mk]
        symm
        have inj := fun
            (a b : X ⟶ pshRelEdgeExp A Y') =>
          fun (h : pshRelEdgeUncurry a =
            pshRelEdgeUncurry b) =>
          (pshRelEdgeCurry_uncurry a).symm.trans
            (congrArg pshRelEdgeCurry h
              |>.trans
              (pshRelEdgeCurry_uncurry b))
        apply inj
        change pshRelEdgeUncurry
          (pshRelEdgeCurry ((β_ X A).hom ≫ f) ≫
            pshRelEdgeCurry
              (pshRelEdgeEval A Y ≫ g)) = _
        rw [pshRelEdgeUncurry_curry_comp,
          pshRelEdgeUncurry_curry,
          Category.assoc] }

/-- `PshRelEdge C` is monoidal closed (at
universe `w = max u v`): every object is
closed. -/
instance pshRelEdgeMonoidalClosed
    (C : Type u) [Category.{v} C] :
    MonoidalClosed
      (PshRelEdge.{u, v, max u v} C) where
  closed A := pshRelEdgeClosed A

open MonoidalClosed MonoidalCategory in
/-- The internal hom object `[A, B]` in
`PshRelEdge C`, via mathlib's `ihom` from the
`MonoidalClosed` instance. -/
abbrev pshRelEdgeInternalHom
    (A B : PshRelEdge.{u, v, max u v} C) :
    PshRelEdge.{u, v, max u v} C :=
  (ihom A).obj B

open MonoidalClosed MonoidalCategory in
/-- The internal hom functor `[A, -]` in
`PshRelEdge C`, via mathlib's `ihom`. -/
abbrev pshRelEdgeInternalHomFunctor
    (A : PshRelEdge.{u, v, max u v} C) :
    PshRelEdge.{u, v, max u v} C ⥤
    PshRelEdge.{u, v, max u v} C :=
  ihom A

open MonoidalClosed MonoidalCategory in
/-- The adjunction `- ⊗ A ⊣ [A, -]` in
`PshRelEdge C`, from mathlib's `ihom`. -/
abbrev pshRelEdgeIhomAdjunction
    (A : PshRelEdge.{u, v, max u v} C) :
    tensorLeft A ⊣ ihom A :=
  ihom.adjunction A

open MonoidalClosed MonoidalCategory in
/-- The global-element correspondence: the
internal hom from the terminal edge to any
edge `A` is isomorphic to `A` itself.
`Hom(⊤, [⊤, A]) ≅ Hom(⊤, A)`, which by
Yoneda means `[⊤, A] ≅ A`. -/
abbrev pshRelEdgeUnitIsoSelf
    (A : PshRelEdge.{u, v, max u v} C) :
    (ihom
      (𝟙_ (PshRelEdge.{u, v, max u v} C))
      |>.obj A) ≅
    A :=
  unitIsoSelf (X := A)

open MonoidalClosed MonoidalCategory in
/-- Global elements of the internal hom
biject with morphisms:
`Hom(⊤, [A, B]) ≃ Hom(A, B)`.
This is the CCC correspondence that connects
`ParametricCone` (global elements of a limit)
to natural transformations between
endofunctors.

The equivalence is the adjunction hom-equiv
`Hom(A ⊗ ⊤, B) ≅ Hom(⊤, [A, B])` composed
with the right unitor `A ⊗ ⊤ ≅ A`. -/
def pshRelEdgeGlobalElementEquiv
    (A B : PshRelEdge.{u, v, max u v} C) :
    (pshRelEdgeTerminal C ⟶
      pshRelEdgeInternalHom A B) ≃
    (A ⟶ B) :=
  ((ihom.adjunction A).homEquiv
    (pshRelEdgeTerminal C) B).symm.trans
    (Iso.homCongr (ρ_ A) (Iso.refl B))

open MonoidalClosed MonoidalCategory in
/-- Mathlib's curry for `PshRelEdge C`:
given `f : A ⊗ B ⟶ D`, produce
`B ⟶ [A, D]`. -/
abbrev pshRelEdgeMathCurry
    {A B D : PshRelEdge.{u, v, max u v} C}
    [inst : Closed A]
    (f : A ⊗ B ⟶ D) : B ⟶ (ihom A).obj D :=
  MonoidalClosed.curry f

open MonoidalClosed MonoidalCategory in
/-- Mathlib's uncurry for `PshRelEdge C`:
given `g : B ⟶ [A, D]`, produce
`A ⊗ B ⟶ D`. -/
abbrev pshRelEdgeMathUncurry
    {A B D : PshRelEdge.{u, v, max u v} C}
    [inst : Closed A]
    (g : B ⟶ (ihom A).obj D) :
    A ⊗ B ⟶ D :=
  MonoidalClosed.uncurry g

open MonoidalClosed MonoidalCategory in
/-- Internalize a morphism as a global element
of the internal hom: given `f : A ⟶ B`,
produce `⊤ ⟶ [A, B]`. -/
abbrev pshRelEdgeInternalize
    {A B : PshRelEdge.{u, v, max u v} C}
    (f : A ⟶ B) :
    pshRelEdgeTerminal C ⟶
      pshRelEdgeInternalHom A B :=
  (pshRelEdgeGlobalElementEquiv A B).symm f

end CartesianClosedInstances

section YonedaExtFullFaithfulness

variable (C : Type u) [Category.{v} C]

/-- Post-composition with `uliftFunctor` is
fully faithful (it is an equivalence). -/
def whiskerRightULiftFullyFaithful :
    ((Functor.whiskeringRight Cᵒᵖ
      (Type v) (Type (max u v))).obj
      uliftFunctor.{u}).FullyFaithful where
  preimage {P Q} α :=
    { app := fun c p =>
        (α.app c (ULift.up p)).down
      naturality := fun {c d} f => by
        ext p
        have h := congr_fun
          (α.naturality f) (ULift.up p)
        exact congrArg ULift.down h }
  map_preimage {P Q} α := by
    ext c ⟨p⟩; rfl
  preimage_map {P Q} f := by
    ext c p; rfl

/-- `yonedaLarge C` is fully faithful, as
the composition of fully faithful `yoneda`
with fully faithful post-composition by
`uliftFunctor`. -/
def yonedaLargeFullyFaithful :
    (yonedaLarge C).FullyFaithful :=
  Yoneda.fullyFaithful.comp
    (whiskerRightULiftFullyFaithful C)

variable {D : Type u} [Category.{v} D]

/-- Extract a morphism `F.obj X ⟶ G.obj X`
from a natural transformation
`α : leftYonedaExt F ⟶ leftYonedaExt G` by
restricting to the representable
`yonedaULift X` and conjugating with the
representable isomorphism. -/
def leftYonedaExtPreimageApp
    {F G : C ⥤ D}
    (α : leftYonedaExt F ⟶ leftYonedaExt G)
    (X : C) : F.obj X ⟶ G.obj X :=
  Yoneda.fullyFaithful.preimage
    (Functor.FullyFaithful.preimage
      (whiskerRightULiftFullyFaithful D)
      ((leftYonedaExtRepresentableULiftIso F X).inv
        ≫ α.app (yonedaULift X)
        ≫ (leftYonedaExtRepresentableULiftIso
            G X).hom))

/-- The representable isomorphism is natural
in `X`: the family
`leftYonedaExtRepresentableULiftIso F X` assembles
into a natural isomorphism
`F ⋙ yonedaLarge D ≅
(yonedaLarge C) ⋙ leftYonedaExt F`.

This says: applying `F` then embedding via
`yonedaLarge D` is naturally isomorphic to
embedding via `yonedaLarge C` then extending
via `leftYonedaExt F`. -/
def leftYonedaExtRepresentableNatIso
    (F : C ⥤ D) :
    F ⋙ yonedaLarge D ≅
      yonedaLarge C ⋙ leftYonedaExt F :=
  NatIso.ofComponents
    (fun X => {
      hom := (leftYonedaExtRepresentableULiftIso F X).inv
      inv := (leftYonedaExtRepresentableULiftIso F X).hom
      hom_inv_id :=
        (leftYonedaExtRepresentableULiftIso F X).inv_hom_id
      inv_hom_id :=
        (leftYonedaExtRepresentableULiftIso F X).hom_inv_id
    })
    (fun {X Y} f => by
      ext T ⟨t⟩
      simp only [Functor.comp_obj,
        Functor.comp_map, NatTrans.comp_app,
        types_comp_apply]
      -- LHS: iso(F,Y).inv applied to
      --   (yonedaLarge.map(F.map f))(t)
      -- = iso(F,Y).inv applied to
      --   (t ≫ F.map f)
      -- = Quot.mk(Y, 𝟙 Y, t ≫ F.map f)
      -- RHS: (leftYonedaExt F).map(yonedaLarge.map f)
      --   applied to iso(F,X).inv(t)
      -- = (leftYonedaExt F).map(yonedaLarge.map f)
      --   applied to Quot.mk(X, 𝟙 X, t)
      -- = Quot.mk(X, f, t)
      -- (by the leftYonedaExt map definition)
      -- These are equal in the quotient:
      -- (X, f, t) ~ (Y, 𝟙 Y, t ≫ F.map f)
      -- via the step (Y, f, 𝟙 Y).
      dsimp [leftYonedaExtRepresentableULiftIso,
        leftYonedaExtUnitULift, yonedaLarge,
        yonedaULift, leftYonedaExt, leftYonedaExtObj,
        leftYonedaExtSigmaMap]
      apply Quot.sound
      exact ⟨f,
        by dsimp [leftYonedaExtSigmaMapNat]; simp,
        by dsimp [leftYonedaExtSigmaMapNat]⟩)

/-- Abbreviation for the ulift-yoneda-level
composition used in the preimage: the
iso conjugation of `α` at a given object. -/
abbrev leftYonedaExtPreimageULift
    {F G : C ⥤ D}
    (α : leftYonedaExt F ⟶ leftYonedaExt G)
    (X : C) :
    yonedaULift (F.obj X) ⟶
      yonedaULift (G.obj X) :=
  (leftYonedaExtRepresentableULiftIso F X).inv ≫
    α.app (yonedaULift X) ≫
    (leftYonedaExtRepresentableULiftIso G X).hom

/-- The ulift-level preimage satisfies
naturality: `yUL(F.map f) ≫ preimageULift(Y)
= preimageULift(X) ≫ yUL(G.map f)`.
This follows from naturality of
`leftYonedaExtRepresentableNatIso` and
naturality of `α`. -/
theorem leftYonedaExtPreimageULift_naturality
    {F G : C ⥤ D}
    (α : leftYonedaExt F ⟶ leftYonedaExt G)
    {X Y : C} (f : X ⟶ Y) :
    (yonedaLarge D).map (F.map f) ≫
      leftYonedaExtPreimageULift (C := C) α Y =
    leftYonedaExtPreimageULift (C := C) α X ≫
      (yonedaLarge D).map (G.map f) := by
  -- The proof chains three naturality
  -- results at the ulift-yoneda level.
  -- Use the NatIso naturality we proved
  -- in `leftYonedaExtRepresentableNatIso` and
  -- the naturality of `α`.
  simp only [leftYonedaExtPreimageULift,
    Category.assoc]
  -- Factor: state the naturality of the
  -- NatIso as a separate lemma about
  -- leftYonedaExtRepresentableULiftIso components.
  have natIsoF_nat :
      (yonedaLarge D).map (F.map f) ≫
        (leftYonedaExtRepresentableULiftIso F Y).inv
      =
      (leftYonedaExtRepresentableULiftIso F X).inv ≫
        (leftYonedaExt F).map
          ((yonedaLarge C).map f) := by
    have h := Iso.hom
      (@leftYonedaExtRepresentableNatIso C _ D _ F)
      |>.naturality f
    simp only [Functor.comp_map] at h
    exact h
  have natIsoG_nat :
      (leftYonedaExt G).map
          ((yonedaLarge C).map f) ≫
        (leftYonedaExtRepresentableULiftIso G Y).hom
      =
      (leftYonedaExtRepresentableULiftIso G X).hom ≫
        (yonedaLarge D).map (G.map f) := by
    have h := Iso.inv
      (@leftYonedaExtRepresentableNatIso C _ D _ G)
      |>.naturality f
    simp only [Functor.comp_map] at h
    exact h
  -- Reassociate to expose the pattern
  -- for natIsoF_nat on the LHS.
  rw [show (yonedaLarge D).map (F.map f) ≫
    (leftYonedaExtRepresentableULiftIso F Y).inv ≫
    α.app (yonedaULift Y) ≫
    (leftYonedaExtRepresentableULiftIso G Y).hom =
    ((yonedaLarge D).map (F.map f) ≫
      (leftYonedaExtRepresentableULiftIso F Y).inv)
    ≫ α.app (yonedaULift Y) ≫
    (leftYonedaExtRepresentableULiftIso G Y).hom
    from by simp only [Category.assoc],
    natIsoF_nat]
  simp only [Category.assoc]
  -- Now LHS: iso_X.inv ≫ yExt_F(yL.map f) ≫
  --   α(yUL Y) ≫ iso_G_Y.hom
  -- Cancel common prefix iso_F_X.inv.
  -- Convert yonedaULift to yonedaLarge.obj.
  change
    (leftYonedaExtRepresentableULiftIso F X).inv ≫
      (leftYonedaExt F).map ((yonedaLarge C).map f) ≫
      α.app ((yonedaLarge C).obj Y) ≫
      (leftYonedaExtRepresentableULiftIso G Y).hom =
    (leftYonedaExtRepresentableULiftIso F X).inv ≫
      α.app ((yonedaLarge C).obj X) ≫
      (leftYonedaExtRepresentableULiftIso G X).hom ≫
      (yonedaLarge D).map (G.map f)
  calc (leftYonedaExtRepresentableULiftIso F X).inv
      ≫ (leftYonedaExt F).map
        ((yonedaLarge C).map f) ≫
      α.app ((yonedaLarge C).obj Y) ≫
      (leftYonedaExtRepresentableULiftIso G Y).hom
    _ = (leftYonedaExtRepresentableULiftIso F X).inv
      ≫ (α.app ((yonedaLarge C).obj X) ≫
      (leftYonedaExt G).map
        ((yonedaLarge C).map f)) ≫
      (leftYonedaExtRepresentableULiftIso G Y).hom
      := by
        simp only [Category.assoc]
        congr 1
        rw [← Category.assoc,
          α.naturality
            ((yonedaLarge C).map f),
          Category.assoc]
    _ = (leftYonedaExtRepresentableULiftIso F X).inv
      ≫ α.app ((yonedaLarge C).obj X) ≫
      (leftYonedaExtRepresentableULiftIso G X).hom ≫
      (yonedaLarge D).map (G.map f)
      := by simp only [Category.assoc,
        natIsoG_nat]

/-- Naturality of `leftYonedaExtPreimageApp`:
`F.map f ≫ preimageApp(Y) =
preimageApp(X) ≫ G.map f`.
Follows from `leftYonedaExtPreimageULift_naturality`
by reflecting through `yoneda` and `ulift`
full faithfulness. -/
theorem leftYonedaExtPreimageApp_naturality
    {F G : C ⥤ D}
    (α : leftYonedaExt F ⟶ leftYonedaExt G)
    {X Y : C} (f : X ⟶ Y) :
    F.map f ≫
      leftYonedaExtPreimageApp (C := C) α Y =
    leftYonedaExtPreimageApp (C := C) α X ≫
      G.map f := by
  -- First check: does unfold work?
  simp only [leftYonedaExtPreimageApp]
  rw [← Yoneda.fullyFaithful.preimage_map
    (F.map f),
    ← Yoneda.fullyFaithful.preimage_comp,
    ← Yoneda.fullyFaithful.preimage_map
    (G.map f)]
  conv_rhs =>
    rw [← Yoneda.fullyFaithful.preimage_comp]
  congr 1
  -- Inject through wFF to get to ULift level.
  apply Functor.FullyFaithful.map_injective
    (whiskerRightULiftFullyFaithful D)
  rw [Functor.map_comp, Functor.map_comp,
    Functor.FullyFaithful.map_preimage
      (whiskerRightULiftFullyFaithful D),
    Functor.FullyFaithful.map_preimage
      (whiskerRightULiftFullyFaithful D)]
  -- Now at ULift level.
  exact @leftYonedaExtPreimageULift_naturality
    C _ D _ F G α X Y f

/-- The preimage as a natural transformation:
given `α : leftYonedaExt F ⟶ leftYonedaExt G`,
produce `F ⟶ G`. -/
def leftYonedaExtFunctorPreimage
    {F G : C ⥤ D}
    (α : leftYonedaExt F ⟶ leftYonedaExt G) :
    F ⟶ G where
  app X := leftYonedaExtPreimageApp (C := C) α X
  naturality {X Y} f :=
    @leftYonedaExtPreimageApp_naturality C _ D _ F G α X Y f


/-- Every element `Quot.mk ⟨S, g, t⟩` of
`(leftYonedaExt F).obj P` at stage `T` equals
`((leftYonedaExt F).obj P).map t.op
(Quot.mk ⟨S, g, 𝟙⟩)`: the element at the
representable stage `op(F.obj S)` transported
along `t`. -/
theorem leftYonedaExtElement_decompose
    {F : C ⥤ D}
    (P : Cᵒᵖ ⥤ Type (max u v))
    (T : Dᵒᵖ) (S : C)
    (g : P.obj (Opposite.op S))
    (t : T.unop ⟶ F.obj S) :
    Quot.mk (LeftYonedaExtStep F P T)
      ⟨S, g, t⟩ =
    ((leftYonedaExt F).obj P).map t.op
      (Quot.mk
        (LeftYonedaExtStep F P
          (Opposite.op (F.obj S)))
        ⟨S, g, 𝟙 (F.obj S)⟩) := by
  change _ = Quot.mk _
    (leftYonedaExtSigmaMap F P t.op _)
  dsimp [leftYonedaExtSigmaMap]
  simp

/-- At the representable stage (where
`t = 𝟙`), `leftYonedaExtFunctor.map(preimage α)`
agrees with `α` for any presheaf `P`. -/
theorem leftYonedaExtFunctor_map_preimage_id
    {F G : C ⥤ D}
    (α : leftYonedaExt F ⟶ leftYonedaExt G)
    (P : Cᵒᵖ ⥤ Type (max u v))
    (S : C) (g : P.obj (Opposite.op S)) :
    (NatTrans.app
      (leftYonedaExtFunctor.map
        (leftYonedaExtFunctorPreimage (C := C) α))
      P).app (Opposite.op (F.obj S))
      (Quot.mk _
        ⟨S, g, 𝟙 (F.obj S)⟩) =
    (α.app P).app (Opposite.op (F.obj S))
      (Quot.mk _
        ⟨S, g, 𝟙 (F.obj S)⟩) := by
  -- LHS: Quot.mk(G-step)(leftYonedaExtSigmaAlpha
  --   (preimage α) P (op(F.obj S))
  --   ⟨S, g, 𝟙⟩)
  -- = Quot.mk(G-step)
  --   ⟨S, g, 𝟙 ≫ preimage(α).app S⟩
  -- = Quot.mk(G-step)
  --   ⟨S, g, preimage(α).app S⟩
  -- RHS: α.app P . app (op(F.obj S))
  --   (Quot.mk(F-step) ⟨S, g, 𝟙⟩)
  -- Use naturality of α at the presheaf
  -- morphism P → yonedaULift S induced by g.
  -- Factor: first rewrite LHS via
  -- leftYonedaExtSigmaAlpha unfolding.
  change Quot.mk _ _ = _
  dsimp [leftYonedaExtFunctor,
    leftYonedaExtFunctorPreimage,
    leftYonedaExtPreimageApp,
    leftYonedaExtPreimageULift,
    whiskerRightULiftFullyFaithful,
    leftYonedaExtRepresentableULiftIso,
    leftYonedaExtCounitULift,
    leftYonedaExtUnitULift,
    leftYonedaExtSigmaAlpha,
    Yoneda.fullyFaithful]
  simp only [Category.id_comp]
  -- Now: Quot.mk(G-step)
  --   ⟨S, g, Quot.lift(...)(α(yUL S)(op(F.obj S))
  --     (Quot.mk ⟨S, ⟨𝟙, 𝟙⟩⟩)).down⟩
  -- = α.app P . app (op(F.obj S))
  --   (Quot.mk ⟨S, g, 𝟙⟩)
  -- Step 1: write ⟨S, g, 𝟙⟩ as
  -- (leftYonedaExtPresheafUnit F P).app(op S)(g).
  -- Step 2: use naturality of α at
  -- leftYonedaExtPresheafUnit F P to factor
  -- through the representable.
  -- Step 3: at the representable, both sides
  -- reduce to the preimage construction.
  --
  -- Direct: use the presheaf unit to connect
  -- P-level elements to representable-level
  -- elements, then α's naturality at the unit.
  -- Define η_g : yonedaULift S ⟶ P.
  let η_g : yonedaULift (C := C) S ⟶ P :=
    { app := fun T x =>
        P.map (Quiver.Hom.op x.down) g
      naturality := fun {T₁ T₂} k => by
        ext ⟨f⟩
        simp only [types_comp_apply,
          yonedaULift]
        exact congr_fun (P.map_comp _ _) g }
  -- Use α.naturality at η_g.
  have natα := congr_fun (congr_app
    (α.naturality η_g)
    (Opposite.op (F.obj S)))
    (Quot.mk _
      ⟨S, (ULift.up (𝟙 S),
        𝟙 (F.obj S))⟩)
  -- natα has form:
  -- (leftYonedaExt(F).map(η_g) ≫ α.app(P))(...)(q₀)
  -- = (α.app(yUL S) ≫ leftYonedaExt(G).map(η_g))(...)(q₀)
  -- Unfold the ≫ to get function application.
  simp only [NatTrans.comp_app,
    types_comp_apply] at natα
  -- Now natα is pointwise.
  -- RHS of goal = α(P)(...)(⟨S,g,𝟙⟩)
  -- = α(P)(...)(leftYonedaExt(F).map(η_g)(q₀))
  -- [because leftYonedaExt(F).map(η_g)(q₀) = ⟨S,g,𝟙⟩]
  -- = natα LHS
  -- = natα RHS
  -- = leftYonedaExt(G).map(η_g)(α(yUL S)(q₀))
  -- = LHS of goal
  -- [because leftYonedaExt(G).map(η_g) sends
  -- the ULift component to g via η_g]
  -- Step A: RHS = α(P)(...)(leftYonedaExt(F).map(η_g)(q₀))
  conv_rhs =>
    rw [show Quot.mk
        (LeftYonedaExtStep F P
          (Opposite.op (F.obj S)))
        ⟨S, (g, 𝟙 (F.obj S))⟩ =
      ((leftYonedaExt F).map η_g).app
        (Opposite.op (F.obj S))
        (Quot.mk _
          ⟨S, (ULift.up (𝟙 S),
            𝟙 (F.obj S))⟩)
      from by
        change Quot.mk _ _ = Quot.mk _ _
        congr 1
        dsimp [leftYonedaExtSigmaMapNat, η_g]
        simp only [P.map_id,
          types_id_apply]]
  -- Use natα to rewrite RHS. After step A,
  -- RHS = natα LHS. Rewrite to natα RHS.
  rw [natα]
  -- Now both sides involve
  -- (leftYonedaExt G).map(η_g)(α(yUL S)(q₀)).
  -- LHS = Quot.mk ⟨S, g, Quot.lift(...)(αq).down⟩
  -- RHS = (leftYonedaExt G).map(η_g)(αq)
  -- These agree by Quot.inductionOn on αq.
  set αq := (α.app (yonedaULift S)).app
    (Opposite.op (F.obj S))
    (Quot.mk _
      ⟨S, (ULift.up (𝟙 S),
        𝟙 (F.obj S))⟩)
  induction αq using Quot.inductionOn with
  | h x =>
    obtain ⟨W, ⟨h_w⟩, t⟩ := x
    -- RHS = Quot.mk ⟨W, (P.map(h_w.op)(g), t)⟩
    -- LHS = Quot.mk ⟨S, (g, t ≫ G.map h_w)⟩
    -- Related by quotient step h_w.
    -- Unfold the RHS directly.
    -- RHS = Quot.mk ⟨W, (P.map(h_w.op)(g), t)⟩
    -- (after unfolding leftYonedaExt.map(η_g)).
    -- LHS = Quot.mk ⟨S, (g, t ≫ G.map h_w)⟩
    -- These are related by step h_w:
    -- ⟨S, (g, t ≫ G.map h_w)⟩ ~
    -- ⟨W, (P.map(h_w.op)(g), t)⟩.
    conv_rhs =>
      dsimp [leftYonedaExt, leftYonedaExtObj,
        leftYonedaExtMap, leftYonedaExtSigmaMap, η_g]
    apply Quot.sound
    exact ⟨h_w,
      by dsimp [leftYonedaExtSigmaMapNat],
      by dsimp [leftYonedaExtSigmaMapNat]⟩

/-- The map-preimage roundtrip for a single
quotient representative `⟨S, g, t⟩`. -/
theorem leftYonedaExtFunctor_map_preimage_triple
    {F G : C ⥤ D}
    (α : leftYonedaExt F ⟶ leftYonedaExt G)
    (P : Cᵒᵖ ⥤ Type (max u v))
    (T : Dᵒᵖ)
    (S : C)
    (g : P.obj (Opposite.op S))
    (t : T.unop ⟶ F.obj S) :
    (NatTrans.app
      (leftYonedaExtFunctor.map
        (leftYonedaExtFunctorPreimage (C := C) α))
      P).app T
      (Quot.mk _ ⟨S, g, t⟩) =
    (α.app P).app T
      (Quot.mk _ ⟨S, g, t⟩) := by
  -- Both LHS and RHS are nat trans apps.
  -- Decompose and chain.
  let lhs := NatTrans.app
    (leftYonedaExtFunctor.map
      (leftYonedaExtFunctorPreimage (C := C) α)) P
  let rhs := α.app P
  -- Decompose on both sides.
  -- leftYonedaExtFunctor.obj F = leftYonedaExt F
  -- definitionally.
  change lhs.app T (Quot.mk _ ⟨S, g, t⟩) =
    rhs.app T (Quot.mk _ ⟨S, g, t⟩)
  conv_lhs =>
    rw [leftYonedaExtElement_decompose (C := C) P T S g t]
  conv_rhs =>
    rw [leftYonedaExtElement_decompose (C := C) P T S g t]
  -- Both sides apply nat trans (lhs/rhs) to
  -- the SAME element: map(t.op)(q₀).
  -- Use congrArg to reduce to the id lemma.
  have base := leftYonedaExtFunctor_map_preimage_id
    C α P S g
  -- base : lhs.app(op(F.obj S))(q₀) =
  --   rhs.app(op(F.obj S))(q₀)
  -- Apply ((leftYonedaExt G).obj P).map(t.op).
  -- lhs.app T (F.map(t.op) q₀)
  -- = G.map(t.op) (lhs.app(op(F.obj S)) q₀)
  -- by naturality of lhs.
  have nat_lhs := congr_fun
    (lhs.naturality t.op)
    (Quot.mk _ ⟨S, g, 𝟙 (F.obj S)⟩)
  -- rhs.app T (F.map(t.op) q₀)
  -- = G.map(t.op) (rhs.app(op(F.obj S)) q₀)
  -- by naturality of rhs.
  have nat_rhs := congr_fun
    (rhs.naturality t.op)
    (Quot.mk _ ⟨S, g, 𝟙 (F.obj S)⟩)
  simp only [types_comp_apply,
    Opposite.op_unop] at nat_lhs nat_rhs
  -- nat_lhs uses leftYonedaExtFunctor.obj F =
  -- leftYonedaExt F (definitionally equal).
  exact nat_lhs.trans
    (congrArg _ base |>.trans nat_rhs.symm)

/-- `leftYonedaExtFunctor.map(preimage α) = α`:
the map-preimage roundtrip. -/
theorem leftYonedaExtFunctor_map_preimage
    {F G : C ⥤ D}
    (α : leftYonedaExt F ⟶ leftYonedaExt G) :
    leftYonedaExtFunctor.map
      (leftYonedaExtFunctorPreimage (C := C) α) =
    α := by
  ext P T x
  induction x using Quot.inductionOn with
  | h x =>
    obtain ⟨S, g, t⟩ := x
    exact leftYonedaExtFunctor_map_preimage_triple
      (C := C) α P T S g t

/-- `leftYonedaExtFunctor` is fully faithful:
natural transformations between functors
`F ⟶ G : C ⥤ D` biject with natural transformations
between their Yoneda extensions
`leftYonedaExt F ⟶ leftYonedaExt G`. -/
def leftYonedaExtFunctorFullyFaithful :
    Functor.FullyFaithful
      (leftYonedaExtFunctor :
        (C ⥤ D) ⥤
        ((Cᵒᵖ ⥤ Type (max u v)) ⥤
          (Dᵒᵖ ⥤ Type (max u v)))) where
  preimage {F G} α :=
    leftYonedaExtFunctorPreimage (C := C) α
  map_preimage {F G} α :=
    @leftYonedaExtFunctor_map_preimage
      C _ D _ F G α
  preimage_map {F G} σ := by
    ext X
    -- preimage(leftYonedaExtFunctor.map σ).app X
    -- = yFF.preimage(wFF.preimage(
    --   iso_X.inv ≫ (leftYonedaExt σ).app(yUL X)
    --   ≫ iso_X.hom))
    -- The iso conjugation with leftYonedaExt σ
    -- gives yoneda.map(σ.app X) ⋙ ulift.
    -- Reflecting through wFF gives
    -- yoneda.map(σ.app X), then through yFF
    -- gives σ.app X.
    dsimp [leftYonedaExtFunctorPreimage,
      leftYonedaExtPreimageApp,
      leftYonedaExtPreimageULift,
      whiskerRightULiftFullyFaithful,
      leftYonedaExtRepresentableULiftIso,
      leftYonedaExtCounitULift,
      leftYonedaExtUnitULift,
      leftYonedaExtFunctor,
      leftYonedaExt, leftYonedaExtObj,
      leftYonedaExtSigmaAlpha,
      leftYonedaExtSigmaMapNat,
      Yoneda.fullyFaithful]
    change (𝟙 (F.obj X) ≫ σ.app X) ≫
      G.map (𝟙 X) = σ.app X
    simp only [G.map_id, Category.id_comp,
      Category.comp_id]

end YonedaExtFullFaithfulness

section RightYonedaExtFullFaithfulness

variable (C : Type u) [Category.{v} C]
variable {D : Type u} [Category.{v} D]

/-- The tautological family for the right Yoneda
extension at the Hom-presheaf
`F.op ⋙ yonedaULift (G.obj X)` and stage
`op (G.obj X)`. The family sends
`(S, t : F.obj S ⟶ G.obj X)` to `ULift.up t`.
-/
def rightYonedaExtCanonicalFamily
    {F G : C ⥤ D} (X : C) :
    RightYonedaExtFamily F
      (F.op ⋙ yonedaULift (G.obj X))
      (Opposite.op (G.obj X)) where
  family S (t : F.obj S ⟶ G.obj X) :=
    ULift.up t
  naturality {S₁ S₂} (g : S₂ ⟶ S₁)
      (t : F.obj S₁ ⟶ G.obj X) := by
    rfl

/-- The preimage morphism component: given
`α : rightYonedaExt F ⟶ rightYonedaExt G`,
extract `σ.app X : F.obj X ⟶ G.obj X` by
evaluating `α` at the Hom-presheaf
`F.op ⋙ yonedaULift (G.obj X)` on the
canonical family, then reading off the
`(X, 𝟙)` component. -/
def rightYonedaExtFunctorPreimageApp
    {F G : C ⥤ D}
    (α : rightYonedaExt F ⟶ rightYonedaExt G)
    (X : C) : F.obj X ⟶ G.obj X :=
  ((α.app (F.op ⋙ yonedaULift (G.obj X))).app
    (Opposite.op (G.obj X))
    (@rightYonedaExtCanonicalFamily C _ D _ F G X)).family
    X (𝟙 (G.obj X)) |>.down

/-- The preimage extraction applied to
`rightYonedaExtFunctor.map σ` recovers
`σ.app X`. -/
theorem rightYonedaExtFunctor_preimage_app
    {F G : C ⥤ D} (σ : F ⟶ G) (X : C) :
    rightYonedaExtFunctorPreimageApp C
      (rightYonedaExtFunctor.map σ) X =
    σ.app X := by
  dsimp [rightYonedaExtFunctorPreimageApp,
    rightYonedaExtFunctor,
    rightYonedaExtFamilyAlpha,
    rightYonedaExtCanonicalFamily]
  simp

/-- Naturality of the preimage: for `f : X ⟶ Y`,
`F.map f ≫ σ.app Y = σ.app X ≫ G.map f`.
Proved by combining:
(1) α's naturality in the presheaf argument
(at a postcomposition morphism P_X ⟶ P_Y),
(2) stage naturality of α.app(P_Y), and
(3) G-family naturality of the output at Y.
-/
theorem rightYonedaExtFunctorPreimageApp_nat
    {F G : C ⥤ D}
    (α : rightYonedaExt F ⟶ rightYonedaExt G)
    {X Y : C} (f : X ⟶ Y) :
    F.map f ≫
      rightYonedaExtFunctorPreimageApp C α Y =
    rightYonedaExtFunctorPreimageApp C α X ≫
      G.map f := by
  -- Step 1: Set up notation.
  set P_X := F.op ⋙ yonedaULift (G.obj X)
  set P_Y := F.op ⋙ yonedaULift (G.obj Y)
  set y_X := (α.app P_X).app
    (Opposite.op (G.obj X))
    (@rightYonedaExtCanonicalFamily C _ D _ F G X)
  set y_Y := (α.app P_Y).app
    (Opposite.op (G.obj Y))
    (@rightYonedaExtCanonicalFamily C _ D _ F G Y)
  -- The goal reduces to showing two morphisms
  -- are equal: use intermediate
  -- y_Y.family X (G.map f).
  -- Step 2: Define γ : P_X ⟶ P_Y
  -- (postcomposition with G.map f).
  let γ : P_X ⟶ P_Y :=
    { app := fun c (x : P_X.obj c) =>
        (show P_Y.obj c from
          ULift.up (x.down ≫ G.map f))
      naturality := fun {c d} k => by
        funext ⟨h⟩
        change ULift.up
          ((P_X.map k (ULift.up h)).down ≫
            G.map f) =
          P_Y.map k (ULift.up (h ≫ G.map f))
        change ULift.up _ = ULift.up _
        congr 1
        exact Category.assoc _ _ _ }
  -- Step 3: P-naturality of α at γ.
  have hα := congr_fun (congr_app
    (α.naturality γ)
    (Opposite.op (G.obj X)))
    (@rightYonedaExtCanonicalFamily C _ D _ F G X)
  simp only [NatTrans.comp_app,
    types_comp_apply] at hα
  -- Step 4: Stage-naturality of α.app P_Y.
  have hstage := congr_fun
    ((α.app P_Y).naturality (G.map f).op)
    (rightYonedaExtCanonicalFamily C Y)
  simp only [types_comp_apply] at hstage
  -- Step 5: The two F-inputs coincide.
  have heq_z :
      ((rightYonedaExt F).obj P_Y).map
        (G.map f).op
        (@rightYonedaExtCanonicalFamily C _ D _ F G Y) =
      ((rightYonedaExt F).map γ).app
        (Opposite.op (G.obj X))
        (@rightYonedaExtCanonicalFamily C _ D _ F G X) := by
    apply RightYonedaExtFamily.ext'
    intro S t
    dsimp [rightYonedaExt, rightYonedaExtObj,
      rightYonedaExtFamilyMap,
      rightYonedaExtMap,
      rightYonedaExtFamilyMapNat,
      rightYonedaExtCanonicalFamily]
  rw [heq_z] at hstage
  rw [hα] at hstage
  -- hstage : γ-transport(y_X) =
  --   stage-transport(y_Y)
  -- Step 6: Extract .family X (𝟙).down.
  have comm :
      ((((rightYonedaExt G).map γ).app
        (Opposite.op (G.obj X)) y_X).family
        X (𝟙 (G.obj X))).down =
      ((((rightYonedaExt G).obj P_Y).map
        (G.map f).op y_Y).family
        X (𝟙 (G.obj X))).down :=
    congrArg
      (fun z => (z.family X
        (𝟙 (G.obj X))).down)
      hstage
  -- Step 7: Simplify comm to explicit form.
  dsimp [rightYonedaExt, rightYonedaExtObj,
    rightYonedaExtFamilyMap,
    rightYonedaExtMap,
    rightYonedaExtFamilyMapNat] at comm
  simp only [Category.id_comp] at comm
  -- comm :
  -- (y_X.family X 𝟙).down ≫ G.map f
  --   = (y_Y.family X (G.map f)).down
  -- Step 8: G-family naturality of y_Y.
  have nat_y_Y :=
    congrArg ULift.down
      (y_Y.naturality f (𝟙 (G.obj Y)))
  simp only [Category.comp_id] at nat_y_Y
  dsimp [yonedaULift] at nat_y_Y
  -- nat_y_Y :
  -- F.map f ≫ (y_Y.family Y 𝟙).down
  --   = (y_Y.family X (G.map f)).down
  -- Step 9: Combine.
  change F.map f ≫
    (y_Y.family Y (𝟙 (G.obj Y))).down =
    (y_X.family X (𝟙 (G.obj X))).down ≫
      G.map f
  exact nat_y_Y.trans comm.symm

/-- The preimage as a natural transformation:
given `α : rightYonedaExt F ⟶ rightYonedaExt G`,
produce `F ⟶ G`. -/
def rightYonedaExtFunctorPreimage
    {F G : C ⥤ D}
    (α : rightYonedaExt F ⟶ rightYonedaExt G) :
    F ⟶ G where
  app X :=
    rightYonedaExtFunctorPreimageApp C α X
  naturality {X Y} f :=
    @rightYonedaExtFunctorPreimageApp_nat C _ D _ F G α X Y f

/-- `preimage(rightYonedaExtFunctor.map σ) = σ`:
the preimage-map roundtrip. -/
theorem rightYonedaExtFunctor_preimage_map
    {F G : C ⥤ D} (σ : F ⟶ G) :
    rightYonedaExtFunctorPreimage C
      (rightYonedaExtFunctor.map σ) = σ := by
  ext X
  exact rightYonedaExtFunctor_preimage_app
    C σ X

/-- `rightYonedaExtFunctor.map(preimage α) = α`:
the map-preimage roundtrip. For each P, T, x,
S, t, uses α's P-naturality and stage-naturality
to reduce to the canonical family. -/
theorem rightYonedaExtFunctor_map_preimage
    {F G : C ⥤ D}
    (α : rightYonedaExt F ⟶ rightYonedaExt G) :
    rightYonedaExtFunctor.map
      (rightYonedaExtFunctorPreimage C α) =
    α := by
  ext P T x
  apply RightYonedaExtFamily.ext'
  intro S t
  -- Goal: x.family S (σ.app S ≫ t) =
  --   (α.app P).app T x .family S t
  set σ := rightYonedaExtFunctorPreimage C α
  set P_S := F.op ⋙ yonedaULift (G.obj S)
  -- β : P_S ⟶ P sends
  -- ULift.up(h : F.obj S' ⟶ G.obj S) to
  -- x.family S' (h ≫ t).
  let β : P_S ⟶ P :=
    { app := fun c (z : P_S.obj c) =>
        x.family c.unop (z.down ≫ t)
      naturality := fun {c d} k => by
        funext ⟨h⟩
        dsimp [yonedaULift]
        exact ((congrArg (x.family d.unop)
            (Category.assoc _ _ _)).trans
          (x.naturality k.unop
            (h ≫ t)).symm) }
  -- P-naturality of α at β, evaluated at
  -- op(G.obj S) on the canonical family.
  have hα := congr_fun (congr_app
    (α.naturality β)
    (Opposite.op (G.obj S)))
    (@rightYonedaExtCanonicalFamily C _ D _ F G S)
  simp only [NatTrans.comp_app,
    types_comp_apply] at hα
  -- Stage-naturality of α.app P at t.op,
  -- applied to x.
  have hstage := congr_fun
    ((α.app P).naturality t.op) x
  simp only [types_comp_apply] at hstage
  -- hstage :
  -- (α P)(op GS)(F-transport(t.op)(x))
  --   = G-transport(t.op)((α P)(T)(x))
  -- The F-transport of x from T to
  -- op(G.obj S) equals the β-transport of
  -- the canonical family.
  have heq_x :
      ((rightYonedaExt F).obj P).map t.op x =
      ((rightYonedaExt F).map β).app
        (Opposite.op (G.obj S))
        (rightYonedaExtCanonicalFamily
          C S) := by
    apply RightYonedaExtFamily.ext'
    intro S' t'
    dsimp [rightYonedaExt, rightYonedaExtObj,
      rightYonedaExtFamilyMap,
      rightYonedaExtMap,
      rightYonedaExtFamilyMapNat,
      rightYonedaExtCanonicalFamily, β]
  rw [heq_x] at hstage
  rw [hα] at hstage
  -- hstage :
  -- G-β-transport(y_S) =
  --   G-stage-transport((α P)(T)(x))
  -- Extract .family S (𝟙) from both sides.
  have from_hstage :=
    congrArg
      (fun z => z.family S (𝟙 (G.obj S)))
      hstage
  dsimp [rightYonedaExt, rightYonedaExtObj,
    rightYonedaExtFamilyMap, rightYonedaExtMap,
    rightYonedaExtFamilyMapNat, β]
    at from_hstage
  simp only [Category.id_comp] at from_hstage
  -- from_hstage :
  -- x.family S (σ.app S ≫ t) =
  --   (α P)(T)(x).family S t
  dsimp [rightYonedaExtFunctor,
    rightYonedaExtFamilyAlpha]
  exact from_hstage

/-- `rightYonedaExtFunctor` is fully faithful:
natural transformations between functors
`F ⟶ G : C ⥤ D` biject with natural transformations
between their right Yoneda extensions
`rightYonedaExt F ⟶ rightYonedaExt G`. -/
def rightYonedaExtFunctorFullyFaithful :
    Functor.FullyFaithful
      (rightYonedaExtFunctor :
        (C ⥤ D) ⥤
        ((Cᵒᵖ ⥤ Type (max u v)) ⥤
          (Dᵒᵖ ⥤ Type (max u v)))) where
  preimage {_F _G} α :=
    rightYonedaExtFunctorPreimage C α
  map_preimage {F G} α :=
    @rightYonedaExtFunctor_map_preimage
      C _ D _ F G α
  preimage_map {_F _G} σ :=
    rightYonedaExtFunctor_preimage_map C σ

end RightYonedaExtFullFaithfulness

section SeparatedSpanEquivalence

/-! ### PshRelEdge ≌ FullSubcategory IsSeparatedSpan

The categorical equivalence between
`PshRelEdge C` and the full subcategory of
`WalkingSpan ⥤ PSh(C)` on separated spans.

The forward functor sends an edge to its
inclusion span (which is separated by
`pshRelEdge_isSeparatedSpan`). The backward
functor sends a separated span to its image
edge (via `separatedSpanToEdge`).

The roundtrip on the `PshRelEdge` side is
equality (by `separatedSpanToEdge_inclusion`).
The roundtrip on the full-subcategory side
uses the constructive inversion from
`WSubfunctor.fiber` to build the apex
isomorphism without `Classical.choice`.
-/

variable {C : Type u} [Category.{v} C]

/-- The forward functor: sends an edge to its
inclusion span in the full subcategory of
separated spans. -/
def edgeToSepSpan :
    PshRelEdge.{u, v, w} C ⥤
    ObjectProperty.FullSubcategory
      (IsSeparatedSpan (C := C)) where
  obj E := ⟨pshRelEdgeSpan E,
    pshRelEdge_isSeparatedSpan E⟩
  map f :=
    ⟨(pshRelEdgeInclusionFunctor
      (C := C)).map f⟩
  map_id E := by
    apply ObjectProperty.hom_ext
    exact (pshRelEdgeInclusionFunctor
      (C := C)).map_id E
  map_comp f g := by
    apply ObjectProperty.hom_ext
    exact (pshRelEdgeInclusionFunctor
      (C := C)).map_comp f g

/-- The backward functor: sends a separated
span to its image edge via
`pshRelEdgeSepFunctor`. -/
def sepSpanToEdge :
    ObjectProperty.FullSubcategory
      (IsSeparatedSpan (C := C)) ⥤
    PshRelEdge.{u, v, w} C :=
  ObjectProperty.ι
    (IsSeparatedSpan (C := C)) ⋙
    pshRelEdgeSepFunctor C

/-- The roundtrip on the `PshRelEdge` side
is equality: `pshRelEdgeSepObj(pshRelEdgeSpan E) = E`. -/
theorem edgeSepSpan_roundtrip
    (E : PshRelEdge.{u, v, w} C) :
    (edgeToSepSpan ⋙ sepSpanToEdge).obj E =
      E := by
  dsimp [edgeToSepSpan, sepSpanToEdge,
    pshRelEdgeSepFunctor]
  exact pshRelEdgeSepObj_inclusion E

end SeparatedSpanEquivalence

section EndofunctorCCC

/-! ### CCC structure on the endofunctor category

The endofunctor category
`PshRelEdge C ⥤ PshRelEdge C` inherits CCC
structure from `PshRelEdge C` being CCC and
complete. The internal hom `[F, G]` of two
endofunctors is the enriched hom (end)
`∫_X [F(X), G(X)]`, computed using the
internal hom in `PshRelEdge C`.

Mathlib provides this via
`MonoidalClosed` on functor categories,
given `MonoidalClosed C` and
`HasEnrichedHom C F₁ F₂` for all pairs.
-/

variable (C : Type u) [Category.{v} C]

/-- The endofunctor category of
`PshRelEdge C` inherits the cartesian
monoidal structure (pointwise products). -/
instance
    pshRelEdgeEndoCartesian :
    CartesianMonoidalCategory
      (PshRelEdge.{u, v, max u v} C ⥤
        PshRelEdge.{u, v, max u v} C) :=
  inferInstance

-- The exponential ideal instance
-- `ExponentialIdeal (pshRelEdgeInclusionFunctor C)`
-- is synthesized automatically from
-- `exponentialIdeal_of_preservesBinaryProducts`
-- and `pshRelEdgeSepPreservesFiniteProducts`.

end EndofunctorCCC

section Power

/-! ### Power (cotensor) in PshRelEdge

The `S`-indexed power `A^S` of an edge `A`
by a type `S` has:
- Source/target: the function presheaf
  `S → A.src/tgt` at each stage
- Relation: pointwise relatedness — a pair
  `(f, g)` is related when `(f s, g s) ∈ R`
  for all `s : S`
-/

variable {C : Type u} [Category.{v} C]

/-- The `S`-powered presheaf: given
`S : Type w` and a presheaf `P`, produce
the presheaf `S → P` (function type at
each stage, with restriction by
precomposition). -/
def pshPower
    (S : Type (max u v))
    (P : Cᵒᵖ ⥤ Type (max u v)) :
    Cᵒᵖ ⥤ Type (max u v) where
  obj c := S → P.obj c
  map f g s := P.map f (g s)
  map_id c := by
    ext g s
    exact congr_fun (P.map_id c) (g s)
  map_comp f₁ f₂ := by
    ext g s
    exact congr_fun (P.map_comp f₁ f₂) (g s)

/-- The `S`-powered relation: a pair of
functions `(f, g)` where `f : S → P.obj c`
and `g : S → Q.obj c` is related when
`(f s, g s) ∈ R` for all `s : S`. -/
def pshPowerRel
    {P Q : Cᵒᵖ ⥤ Type (max u v)}
    (S : Type (max u v))
    (R : PshRel P Q) :
    PshRel (pshPower S P) (pshPower S Q) where
  obj c fpq :=
    ∀ s : S, R.obj c (fpq.1 s, fpq.2 s)
  map {c d} f {fpq} h s := by
    have := R.map f (h s)
    dsimp [pshPower, pshProdPresheaf] at this ⊢
    exact this

/-- The power (cotensor) in `PshRelEdge C`:
given `S : Type (max u v)` and
`A : PshRelEdge C`, the `S`-indexed power
`A^S`. -/
def pshRelEdgePower
    (S : Type (max u v))
    (A : PshRelEdge.{u, v, max u v} C) :
    PshRelEdge.{u, v, max u v} C :=
  { src := pshPower S A.src
    tgt := pshPower S A.tgt
    edge := pshPowerRel S A.edge }

/-- The projection from the power `A^S` to
`A` at index `s : S`. Evaluates the function
at `s` for both source and target. -/
def pshRelEdgePowerProj
    (S : Type (max u v))
    (A : PshRelEdge.{u, v, max u v} C)
    (s : S) :
    pshRelEdgePower S A ⟶ A where
  srcMap :=
    { app := fun _ f => f s
      naturality := fun {_ _} _ =>
        funext fun _ => rfl }
  tgtMap :=
    { app := fun _ f => f s
      naturality := fun {_ _} _ =>
        funext fun _ => rfl }
  sq _ _ _ h := h s

/-- The lift into the power: given a family
of morphisms `f : S → (Y ⟶ A)`, produce a
morphism `Y ⟶ A^S` by collecting values. -/
def pshRelEdgePowerLift
    {S : Type (max u v)}
    {A Y : PshRelEdge.{u, v, max u v} C}
    (f : S → (Y ⟶ A)) :
    Y ⟶ pshRelEdgePower S A where
  srcMap :=
    { app := fun c y s => (f s).srcMap.app c y
      naturality := fun {c d} g => by
        ext y; funext s
        exact congr_fun
          ((f s).srcMap.naturality g) y }
  tgtMap :=
    { app := fun c y s => (f s).tgtMap.app c y
      naturality := fun {c d} g => by
        ext y; funext s
        exact congr_fun
          ((f s).tgtMap.naturality g) y }
  sq c y₁ y₂ h s := (f s).sq c y₁ y₂ h

/-- The projection factorization: the lift
composed with projection at `s` equals the
original morphism `f s`. -/
theorem pshRelEdgePowerFac
    {S : Type (max u v)}
    {A Y : PshRelEdge.{u, v, max u v} C}
    (f : S → (Y ⟶ A)) (s : S) :
    pshRelEdgePowerLift f ≫
      pshRelEdgePowerProj S A s = f s :=
  VertEdgeHom.ext rfl rfl

/-- Uniqueness of the power lift: any
morphism into the power that agrees with `f`
on all projections equals the lift. -/
theorem pshRelEdgePowerUniq
    {S : Type (max u v)}
    {A Y : PshRelEdge.{u, v, max u v} C}
    (f : S → (Y ⟶ A))
    (g : Y ⟶ pshRelEdgePower S A)
    (h : ∀ s, g ≫ pshRelEdgePowerProj S A s =
      f s) :
    g = pshRelEdgePowerLift f := by
  have hsrc : ∀ s, g.srcMap ≫
      (pshRelEdgePowerProj S A s).srcMap =
      (f s).srcMap :=
    fun s => congrArg VertEdgeHom.srcMap (h s)
  have htgt : ∀ s, g.tgtMap ≫
      (pshRelEdgePowerProj S A s).tgtMap =
      (f s).tgtMap :=
    fun s => congrArg VertEdgeHom.tgtMap (h s)
  apply VertEdgeHom.ext
  · ext c y; funext s
    exact congr_fun (congr_app (hsrc s) c) y
  · ext c y; funext s
    exact congr_fun (congr_app (htgt s) c) y

/-- `PshRelEdge C` has powers (cotensors):
the power `A ^. S` is the pointwise function
edge `pshRelEdgePower S A`. -/
instance pshRelEdgeHasPowers :
    HasPowers
      (PshRelEdge.{u, v, max u v} C) where
  power A S := pshRelEdgePower S A
  proj A S s := pshRelEdgePowerProj S A s
  lift f := pshRelEdgePowerLift f
  fac f s := pshRelEdgePowerFac f s
  uniq f g h := pshRelEdgePowerUniq f g h

/-- The `S`-copowered presheaf: given
`S : Type w` and a presheaf `P`, produce
the presheaf `S × P` (tagged elements at
each stage, with restriction on the second
component). -/
def pshCopower
    (S : Type (max u v))
    (P : Cᵒᵖ ⥤ Type (max u v)) :
    Cᵒᵖ ⥤ Type (max u v) where
  obj c := S × P.obj c
  map f sp := (sp.1, P.map f sp.2)
  map_id c := by
    ext ⟨s, p⟩ : 1
    simp only [types_id_apply]
    exact Prod.ext rfl (congr_fun
      (P.map_id c) p)
  map_comp f₁ f₂ := by
    ext ⟨s, p⟩ : 1
    simp only [types_comp_apply]
    exact Prod.ext rfl (congr_fun
      (P.map_comp f₁ f₂) p)

/-- The `S`-copowered relation: a pair
`((s₁, p), (s₂, q))` is related when
`s₁ = s₂` and `(p, q) ∈ R`. -/
def pshCopowerRel
    {P Q : Cᵒᵖ ⥤ Type (max u v)}
    (S : Type (max u v))
    (R : PshRel P Q) :
    PshRel (pshCopower S P)
      (pshCopower S Q) where
  obj c spq :=
    spq.1.1 = spq.2.1 ∧
      R.obj c (spq.1.2, spq.2.2)
  map {c d} f := by
    rintro ⟨⟨s₁, p⟩, ⟨s₂, q⟩⟩ ⟨heq, hr⟩
    exact ⟨heq, R.map f hr⟩

/-- The copower (tensor with a type) in
`PshRelEdge C`: given `S : Type (max u v)`
and `A : PshRelEdge C`, the `S`-indexed
copower `S ·. A`. Elements at stage `c` are
pairs `(s, a)` with `s : S` and
`a : A.src.obj c`, related when the tags
agree and the payloads are related. -/
def pshRelEdgeCopower
    (S : Type (max u v))
    (A : PshRelEdge.{u, v, max u v} C) :
    PshRelEdge.{u, v, max u v} C :=
  { src := pshCopower S A.src
    tgt := pshCopower S A.tgt
    edge := pshCopowerRel S A.edge }

/-- The injection into the copower at index
`s : S`. Tags the element with `s`. -/
def pshRelEdgeCopowerInj
    (S : Type (max u v))
    (A : PshRelEdge.{u, v, max u v} C)
    (s : S) :
    A ⟶ pshRelEdgeCopower S A where
  srcMap :=
    { app := fun _ a => (s, a)
      naturality := fun {_ _} _ =>
        funext fun _ => rfl }
  tgtMap :=
    { app := fun _ a => (s, a)
      naturality := fun {_ _} _ =>
        funext fun _ => rfl }
  sq _ _ _ h := ⟨rfl, h⟩

/-- The copower descent: given a family
`f : S → (A ⟶ Y)`, produce a morphism
`S ·. A ⟶ Y` by dispatching on the tag. -/
def pshRelEdgeCopowerDesc
    {S : Type (max u v)}
    {A Y : PshRelEdge.{u, v, max u v} C}
    (f : S → (A ⟶ Y)) :
    pshRelEdgeCopower S A ⟶ Y where
  srcMap :=
    { app := fun c sa =>
        (f sa.1).srcMap.app c sa.2
      naturality := fun {c d} g => by
        ext ⟨s, a⟩
        exact congr_fun
          ((f s).srcMap.naturality g) a }
  tgtMap :=
    { app := fun c sa =>
        (f sa.1).tgtMap.app c sa.2
      naturality := fun {c d} g => by
        ext ⟨s, a⟩
        exact congr_fun
          ((f s).tgtMap.naturality g) a }
  sq c sp₁ sp₂ h := by
    dsimp [pshRelEdgeCopower, pshCopowerRel]
      at h
    have heq : sp₁.1 = sp₂.1 := h.1
    have hr := h.2
    cases sp₁; cases sp₂
    dsimp at heq hr ⊢
    subst heq
    exact (f _).sq c _ _ hr

/-- The injection factorization: injection at
`s` composed with descent equals `f s`. -/
theorem pshRelEdgeCopowerFac
    {S : Type (max u v)}
    {A Y : PshRelEdge.{u, v, max u v} C}
    (f : S → (A ⟶ Y)) (s : S) :
    pshRelEdgeCopowerInj S A s ≫
      pshRelEdgeCopowerDesc f = f s :=
  VertEdgeHom.ext rfl rfl

/-- Uniqueness of the copower descent: any
morphism from the copower that agrees with
`f` on all injections equals the descent. -/
theorem pshRelEdgeCopowerUniq
    {S : Type (max u v)}
    {A Y : PshRelEdge.{u, v, max u v} C}
    (f : S → (A ⟶ Y))
    (g : pshRelEdgeCopower S A ⟶ Y)
    (h : ∀ s, pshRelEdgeCopowerInj S A s ≫ g =
      f s) :
    g = pshRelEdgeCopowerDesc f := by
  have hsrc : ∀ s, (pshRelEdgeCopowerInj
      S A s).srcMap ≫ g.srcMap =
      (f s).srcMap :=
    fun s => congrArg VertEdgeHom.srcMap (h s)
  have htgt : ∀ s, (pshRelEdgeCopowerInj
      S A s).tgtMap ≫ g.tgtMap =
      (f s).tgtMap :=
    fun s => congrArg VertEdgeHom.tgtMap (h s)
  apply VertEdgeHom.ext
  · ext c ⟨s, a⟩
    exact congr_fun (congr_app (hsrc s) c) a
  · ext c ⟨s, a⟩
    exact congr_fun (congr_app (htgt s) c) a

/-- `PshRelEdge C` has copowers (tensors
with types): the copower `S ·. A` is the
tagged-element edge `pshRelEdgeCopower S A`.
-/
instance pshRelEdgeHasCopowers :
    HasCopowers
      (PshRelEdge.{u, v, max u v} C) where
  copower S A := pshRelEdgeCopower S A
  inj S A s := pshRelEdgeCopowerInj S A s
  desc f := pshRelEdgeCopowerDesc f
  fac f s := pshRelEdgeCopowerFac f s
  uniq f g h := pshRelEdgeCopowerUniq f g h

end Power

section EndoIhom

/-! ### Endofunctor internal hom via powered ends

The internal hom `[F, G]` of two endofunctors
on `PshRelEdge C` is defined via the powered
end formula (Yoneda reduction):

`[F, G](E) = ∫_{(c,i)} [F(y(c,i)), G(y(c,i))]^{E(c,i)}`

where `(c, i)` ranges over `Cᵒᵖ × WalkingSpan`
(small), `y(c,i)` is the representable edge
(separation of the representable span), and
`E(c,i)` is the evaluation of the included
span at index `(c, i)`.
-/

variable {C : Type u} [Category.{v} C]

/-- The evaluation of an edge at a span-
presheaf index `(c, i)`: the type
`(pshRelEdgeSpan E).obj(i).obj(c)`. -/
abbrev pshRelEdgeSpanEval
    (E : PshRelEdge.{u, v, max u v} C)
    (c : Cᵒᵖ) (i : WalkingSpan) :
    Type (max u v) :=
  ((pshRelEdgeInclusionFunctor (C := C)).obj
    E).obj i |>.obj c

/-- The representable presheaf in the curried
span-presheaf category
`WalkingSpan ⥤ PSh(C)` at index
`(i₀, c₀) : WalkingSpan × Cᵒᵖ`.
At span node `i` and stage `c`, this is
`Hom_{WalkingSpan}(i₀, i) ×
 ULift(Hom_{C}(c.unop, c₀.unop))`,
using the coyoneda `Hom(i₀, -)` for the
covariant WalkingSpan direction and
the Yoneda `Hom(-, c₀.unop)` (ULift'd)
for the contravariant Cᵒᵖ direction. -/
def spanRepresentable
    (i₀ : WalkingSpan) (c₀ : Cᵒᵖ) :
    WalkingSpan ⥤ (Cᵒᵖ ⥤ Type (max u v)) where
  obj i :=
    { obj := fun c =>
        (i₀ ⟶ i) × ULift.{max u v}
          (c₀ ⟶ c)
      map := fun {c d} f sp =>
        (sp.1, ⟨sp.2.down ≫ f⟩)
      map_id _ := by
        funext ⟨_, ⟨_⟩⟩
        exact Prod.ext rfl
          (congrArg ULift.up
            (Category.comp_id _))
      map_comp _ _ := by
        funext ⟨_, ⟨_⟩⟩
        exact Prod.ext rfl
          (congrArg ULift.up
            (Category.assoc _ _ _).symm) }
  map {i j} φ :=
    { app := fun c sp => (sp.1 ≫ φ, sp.2)
      naturality := fun {c d} f => by
        funext ⟨_, ⟨_⟩⟩; rfl }
  map_id i := by
    apply NatTrans.ext; funext c
    funext ⟨h, ⟨g⟩⟩
    exact Prod.ext (Category.comp_id _) rfl
  map_comp φ ψ := by
    apply NatTrans.ext; funext c
    funext ⟨h, ⟨g⟩⟩
    exact Prod.ext
      (Category.assoc _ _ _).symm rfl

/-- The representable edge: the separation
of the representable span at `ic`. This is
the Yoneda embedding of the span-presheaf
base category `WalkingSpan × Cᵒᵖ` into
`PshRelEdge C`. -/
def pshRelEdgeRepresentable
    (i₀ : WalkingSpan) (c₀ : Cᵒᵖ) :
    PshRelEdge.{u, v, max u v} C :=
  pshRelEdgeSepObj
    (spanRepresentable (C := C) i₀ c₀)

end EndoIhom

end GebLean
