import GebLean.PshRelDouble
import Mathlib.CategoryTheory.Adjunction.Reflective

/-!
# Functionalization of Presheaf Relations

This file constructs a reflective adjunction from
the arrow category of presheaves into the edge
category of presheaf relations.

The right adjoint (inclusion) sends an arrow
`f : P ⟶ Q` to the edge `(P, Q, graph(f))`,
using the existing `pshRelEdgeGraphFunctor`.

The left adjoint (reflector) functionalizes a
relation `R : PshRel P Q` by forming the pushout
of `π₁ : R.toFunctor → P` and
`π₂ : R.toFunctor → Q`, equivalently the
coequalizer of `inl ∘ π₁` and `inr ∘ π₂`
from `R.toFunctor` to `P ⊕ Q`. This produces
an arrow `P → (P ⊕ Q) / ~` where `~` identifies
`inl(p)` with `inr(q)` for each related pair
`(p, q) ∈ R`.

## Main definitions

* `pshRelFunctionalizeRel`: the raw quotient
  relation on `P(c) ⊕ Q(c)`
* `pshRelFunctionalize`: the functionalized
  codomain presheaf
* `pshRelFunctionalizeHom`: the arrow
  `P ⟶ pshRelFunctionalize R`
* `pshRelEdgeFunctionalizeFunctor`: the
  reflector functor
  `PshRelEdge C ⥤ Arrow(PSh(C))`
* `pshRelEdgeFunctionalizeAdj`: the adjunction
  `functionalize ⊣ graph`
* `pshRelEdgeGraphReflective`: the reflective
  subcategory instance
-/

open CategoryTheory Limits

namespace GebLean

universe u v w

variable {C : Type u} [Category.{v} C]

/-- The raw relation on `P(c) ⊕ Q(c)` for the
functionalization quotient. For each related pair
`(p, q) ∈ R(c)`, identifies `Sum.inl p` with
`Sum.inr q`. `Quot` generates the equivalence
closure. -/
def pshRelFunctionalizeRel
    {P Q : Cᵒᵖ ⥤ Type w}
    (R : PshRel P Q) (c : Cᵒᵖ) :
    (P.obj c ⊕ Q.obj c) →
    (P.obj c ⊕ Q.obj c) → Prop :=
  fun x y => ∃ (p : P.obj c)
    (q : Q.obj c),
    (p, q) ∈ R.obj c ∧
    x = .inl p ∧ y = .inr q

/-- The presheaf action for the functionalized
codomain: maps via `Sum.map` on the coproduct
components and respects the quotient by the
subfunctor condition on `R`. -/
def pshRelFunctionalizeMap
    {P Q : Cᵒᵖ ⥤ Type w}
    (R : PshRel P Q) {c d : Cᵒᵖ}
    (f : c ⟶ d) :
    Quot (pshRelFunctionalizeRel R c) →
    Quot (pshRelFunctionalizeRel R d) :=
  Quot.lift
    (fun x => Quot.mk _ (Sum.map
      (P.map f) (Q.map f) x))
    (by
      rintro _ _ ⟨p, q, hR, rfl, rfl⟩
      exact Quot.sound
        ⟨P.map f p, Q.map f q,
         R.map f hR, rfl, rfl⟩)

@[simp]
theorem pshRelFunctionalizeMap_mk
    {P Q : Cᵒᵖ ⥤ Type w}
    (R : PshRel P Q) {c d : Cᵒᵖ}
    (f : c ⟶ d) (a : P.obj c ⊕ Q.obj c) :
    pshRelFunctionalizeMap R f
      (Quot.mk _ a) =
    Quot.mk _ (Sum.map
      (P.map f) (Q.map f) a) :=
  rfl

/-- The functionalized codomain presheaf. Given
a relation `R : PshRel P Q`, the presheaf at
stage `c` is the quotient of `P(c) ⊕ Q(c)` by
the equivalence relation generated by
`inl(p) ~ inr(q)` for each `(p, q) ∈ R(c)`. -/
def pshRelFunctionalize
    {P Q : Cᵒᵖ ⥤ Type w}
    (R : PshRel P Q) : Cᵒᵖ ⥤ Type w where
  obj c :=
    Quot (pshRelFunctionalizeRel R c)
  map f := pshRelFunctionalizeMap R f
  map_id c := funext (Quot.ind fun a => by
    simp only [pshRelFunctionalizeMap_mk,
      P.map_id, Q.map_id]
    cases a <;> rfl)
  map_comp f g := funext (Quot.ind fun a => by
    simp only [pshRelFunctionalizeMap_mk,
      P.map_comp, Q.map_comp]
    cases a <;> rfl)

/-- The functionalized arrow: `inl` followed by the
quotient map, giving `P ⟶ pshRelFunctionalize R`.
At stage `c`, sends `p : P(c)` to the equivalence
class `[inl(p)]` in `(P(c) ⊕ Q(c)) / ~`. -/
def pshRelFunctionalizeHom
    {P Q : Cᵒᵖ ⥤ Type w}
    (R : PshRel P Q) :
    P ⟶ pshRelFunctionalize R where
  app _ p := Quot.mk _ (.inl p)
  naturality _ _ f := funext fun p =>
    (pshRelFunctionalizeMap_mk R f
      (.inl p)).symm

/-- The pointwise map on functionalized codomains
induced by an edge morphism. Maps `[inl(p)]` to
`[inl(h.srcMap p)]` and `[inr(q)]` to
`[inr(h.tgtMap q)]`. -/
def pshRelFunctionalizeQuotMapApp
    {E E' : PshRelEdge.{u, v, w} C}
    (h : E ⟶ E') (c : Cᵒᵖ) :
    Quot (pshRelFunctionalizeRel E.edge c) →
    Quot (pshRelFunctionalizeRel
      E'.edge c) :=
  Quot.lift
    (fun x => Quot.mk _
      (Sum.map (h.srcMap.app c)
        (h.tgtMap.app c) x))
    (by
      rintro _ _ ⟨p, q, hR, rfl, rfl⟩
      exact Quot.sound
        ⟨h.srcMap.app c p,
         h.tgtMap.app c q,
         h.sq c p q hR, rfl, rfl⟩)

@[simp]
theorem pshRelFunctionalizeQuotMapApp_mk
    {E E' : PshRelEdge.{u, v, w} C}
    (h : E ⟶ E') (c : Cᵒᵖ)
    (a : E.src.obj c ⊕ E.tgt.obj c) :
    pshRelFunctionalizeQuotMapApp h c
      (Quot.mk _ a) =
    Quot.mk _ (Sum.map (h.srcMap.app c)
      (h.tgtMap.app c) a) :=
  rfl

/-- The map on functionalized codomains induced by
an edge morphism, as a natural transformation. -/
def pshRelFunctionalizeQuotMap
    {E E' : PshRelEdge.{u, v, w} C}
    (h : E ⟶ E') :
    pshRelFunctionalize E.edge ⟶
    pshRelFunctionalize E'.edge where
  app c := pshRelFunctionalizeQuotMapApp h c
  naturality _ _ f := funext
    (Quot.ind fun a => by
      simp only [
        pshRelFunctionalizeQuotMapApp_mk,
        types_comp_apply]
      cases a with
      | inl p =>
        simp only [Sum.map]
        exact congr_arg (Quot.mk _)
          (congr_arg Sum.inl (congr_fun
            (h.srcMap.naturality f) p))
      | inr q =>
        simp only [Sum.map]
        exact congr_arg (Quot.mk _)
          (congr_arg Sum.inr (congr_fun
            (h.tgtMap.naturality f) q)))

/-- The functorializer functor from `PshRelEdge C`
to `Arrow(PSh(C))`. Sends each edge `(P, Q, R)`
to the arrow `P → (P ⊕ Q)/~` obtained by
quotienting the coproduct by the relation. -/
def pshRelEdgeFunctionalizeFunctor
    (C : Type u) [Category.{v} C] :
    PshRelEdge.{u, v, w} C ⥤
    Arrow (Cᵒᵖ ⥤ Type w) where
  obj E := Arrow.mk
    (pshRelFunctionalizeHom E.edge)
  map h := Arrow.homMk h.srcMap
    (pshRelFunctionalizeQuotMap h)
    (by
      ext c p
      simp [pshRelFunctionalizeHom,
        pshRelFunctionalizeQuotMap,
        pshRelFunctionalizeQuotMapApp])
  map_id _ := CommaMorphism.ext rfl
    (NatTrans.ext (funext fun c =>
      funext (Quot.ind fun a => by
        simp [pshRelFunctionalizeQuotMap,
          pshRelFunctionalizeQuotMapApp]
        cases a <;> rfl)))
  map_comp _ _ := CommaMorphism.ext rfl
    (NatTrans.ext (funext fun c =>
      funext (Quot.ind fun a => by
        simp [pshRelFunctionalizeQuotMap,
          pshRelFunctionalizeQuotMapApp]
        cases a <;> rfl)))

/-- The unit component: given an edge `(P, Q, R)`,
the morphism `(P, Q, R) ⟶ graph(P → (P ⊕ Q)/~)`
in `PshRelEdge C`. The source map is the identity
on `P`. The target map sends `q ∈ Q(c)` to the
class `[inr(q)]` in the quotient. Relatedness
holds because for `(p, q) ∈ R(c)`, `[inl(p)]` and
`[inr(q)]` are identified by the quotient. -/
def pshRelEdgeFunctionalizeUnitComp
    (E : PshRelEdge.{u, v, w} C) :
    E ⟶ (pshRelEdgeGraphFunctor (C := C)).obj
      ((pshRelEdgeFunctionalizeFunctor C).obj
        E) where
  srcMap := 𝟙 _
  tgtMap :=
    { app := fun c q =>
        Quot.mk (pshRelFunctionalizeRel
          E.edge c) (.inr q)
      naturality := fun _ _ f =>
        funext fun q =>
          (pshRelFunctionalizeMap_mk E.edge f
            (.inr q)).symm }
  sq := fun _ p q hR =>
    Quot.sound ⟨p, q, hR, rfl, rfl⟩

/-- The counit component: given an arrow
`f : P ⟶ Q`, the morphism
`L(graph(f)) ⟶ f` in `Arrow(PSh(C))`.
The left component is the identity on `P`.
The right component maps `[inl(p)] ↦ f(p)` and
`[inr(q)] ↦ q` in the quotient of
`P ⊕ Q` by the graph relation. -/
def pshRelEdgeFunctionalizeCounitApp
    {P Q : Cᵒᵖ ⥤ Type w}
    (c : Cᵒᵖ) (f : P ⟶ Q) :
    Quot (pshRelFunctionalizeRel
      (pshRelGraph f) c) →
    Q.obj c :=
  Quot.lift
    (fun x => match x with
      | .inl p => f.app c p
      | .inr q => q)
    (by
      rintro _ _ ⟨p, q, hR, rfl, rfl⟩
      exact hR)

@[simp]
theorem pshRelEdgeFunctionalizeCounitApp_mk
    {P Q : Cᵒᵖ ⥤ Type w}
    (c : Cᵒᵖ) (f : P ⟶ Q)
    (a : P.obj c ⊕ Q.obj c) :
    pshRelEdgeFunctionalizeCounitApp c f
      (Quot.mk _ a) =
    match a with
      | .inl p => f.app c p
      | .inr q => q :=
  rfl

/-- The right component of the counit as a
natural transformation. -/
def pshRelEdgeFunctionalizeCounitRight
    (f : Arrow (Cᵒᵖ ⥤ Type w)) :
    pshRelFunctionalize
      (pshRelGraph f.hom) ⟶ f.right where
  app c :=
    pshRelEdgeFunctionalizeCounitApp c f.hom
  naturality _ _ g := funext
    (Quot.ind fun a => by
      cases a with
      | inl p =>
        simp only [Functor.id_obj,
          types_comp_apply,
          pshRelEdgeFunctionalizeCounitApp_mk]
        exact congr_fun
          (f.hom.naturality g) p
      | inr q => rfl)

/-- The counit of the adjunction:
`L(graph(f)) ⟶ f` in `Arrow(PSh(C))`. -/
def pshRelEdgeFunctionalizeCounitComp
    (f : Arrow (Cᵒᵖ ⥤ Type w)) :
    (pshRelEdgeFunctionalizeFunctor C).obj
      ((pshRelEdgeGraphFunctor (C := C)).obj
        f) ⟶ f :=
  Arrow.homMk (𝟙 _)
    (pshRelEdgeFunctionalizeCounitRight f)
    (by
      ext c p
      simp [pshRelEdgeFunctionalizeCounitRight,
        pshRelEdgeFunctionalizeCounitApp,
        pshRelEdgeFunctionalizeFunctor,
        pshRelFunctionalizeHom])

/-- The unit of the functionalize-graph adjunction
as a natural transformation. -/
def pshRelEdgeFunctionalizeAdjUnit
    (C : Type u) [Category.{v} C] :
    𝟭 (PshRelEdge.{u, v, w} C) ⟶
    pshRelEdgeFunctionalizeFunctor C ⋙
      pshRelEdgeGraphFunctor where
  app E := pshRelEdgeFunctionalizeUnitComp E
  naturality _ _ _ := by
    apply VertEdgeHom.ext <;>
    · ext c x; rfl

/-- The counit of the functionalize-graph
adjunction as a natural transformation. -/
def pshRelEdgeFunctionalizeAdjCounit
    (C : Type u) [Category.{v} C] :
    pshRelEdgeGraphFunctor ⋙
      pshRelEdgeFunctionalizeFunctor C ⟶
    𝟭 (Arrow (Cᵒᵖ ⥤ Type w)) where
  app f :=
    pshRelEdgeFunctionalizeCounitComp f
  naturality _ _ h := by
    apply CommaMorphism.ext
    · simp [pshRelEdgeFunctionalizeCounitComp,
        pshRelEdgeFunctionalizeFunctor,
        pshRelEdgeGraphFunctor]
    · apply NatTrans.ext; funext c
      exact funext (Quot.ind fun a => by
        simp only [Functor.id_obj,
          Functor.comp_obj,
          Functor.comp_map,
          Arrow.comp_right,
          FunctorToTypes.comp,
          Functor.id_map]
        cases a with
        | inl p =>
          exact congr_fun
            (congr_app h.w c) p
        | inr q => rfl)

private theorem left_triangle_right_mk
    (E : PshRelEdge.{u, v, w} C) (c : Cᵒᵖ)
    (a : E.src.obj c ⊕ E.tgt.obj c) :
    pshRelEdgeFunctionalizeCounitApp c
      (pshRelFunctionalizeHom E.edge)
      (pshRelFunctionalizeQuotMapApp
        (pshRelEdgeFunctionalizeUnitComp E) c
        (Quot.mk _ a)) =
    Quot.mk _ a := by
  simp only [
    pshRelFunctionalizeQuotMapApp_mk,
    pshRelEdgeFunctionalizeUnitComp,
    pshRelFunctionalizeHom, Sum.map]
  cases a <;> rfl

/-- The functionalize-graph adjunction:
`pshRelEdgeFunctionalizeFunctor ⊣
pshRelEdgeGraphFunctor`. -/
def pshRelEdgeFunctionalizeAdj
    (C : Type u) [Category.{v} C] :
    pshRelEdgeFunctionalizeFunctor.{u, v, w}
      C ⊣ pshRelEdgeGraphFunctor :=
  Adjunction.mkOfUnitCounit {
    unit :=
      pshRelEdgeFunctionalizeAdjUnit C
    counit :=
      pshRelEdgeFunctionalizeAdjCounit C
    left_triangle := by
      apply NatTrans.ext; funext E
      apply CommaMorphism.ext
      · rfl
      · apply NatTrans.ext; funext c
        exact funext (Quot.ind fun a =>
          left_triangle_right_mk E c a)
    right_triangle := by
      apply NatTrans.ext; funext f
      apply VertEdgeHom.ext
      · rfl
      · ext c q
        change
          pshRelEdgeFunctionalizeCounitApp c
            f.hom
            (Quot.mk _ (Sum.inr q)) = q
        simp only [
          pshRelEdgeFunctionalizeCounitApp_mk]
  }

/-- `Arrow(PSh(C))` is a reflective subcategory
of `PshRelEdge C` via the graph functor. The
reflector functionalizes relations by quotienting
`P ⊕ Q` by the relation. -/
instance pshRelEdgeGraphReflective
    (C : Type u) [Category.{v} C] :
    Reflective
      (pshRelEdgeGraphFunctor :
        Arrow (Cᵒᵖ ⥤ Type w) ⥤
          PshRelEdge.{u, v, w} C) where
  L := pshRelEdgeFunctionalizeFunctor C
  adj := pshRelEdgeFunctionalizeAdj C

end GebLean
