import GebLean.PshRelEdgeInclusion
import GebLean.PshRelEdgeExp
import Mathlib.CategoryTheory.Monoidal.Cartesian.Basic

/-!
# PshRelEdge C as separated presheaves

This file constructs the equivalence between
`PshRelEdge C` and the full subcategory of
`WalkingSpan ⥤ PSh(C)` on separated spans:
those where the pairing map
`F(.none) → F(.left) × F(.right)` is a
monomorphism (i.e., the two span projections
are jointly monic).

This is the separated-presheaf characterization
`PshRelEdge C ≅ Sep_J(C × I^op)` where `J` is
the Grothendieck topology on `C × I^op`
generated by covering each span apex with
its two projections.

## Main definitions

* `IsSeparatedSpan`: predicate on
  `WalkingSpan ⥤ PSh(C)` for joint monicity
  of span projections
* `pshRelEdge_isSeparatedSpan`: every edge
  in the image of the inclusion is separated
* `separatedSpanToEdge`: build an edge from a
  separated span
* `pshRelEdgeSepEquiv`: the category
  equivalence
-/

open CategoryTheory Limits

namespace GebLean

universe u v w

variable {C : Type u} [Category.{v} C]

/-- A span `F : WalkingSpan ⥤ PSh(C)` is
**separated** when the two span projections
`F.map fst` and `F.map snd` are jointly
injective at each stage: if two elements
`r₁, r₂ ∈ F(.none)(c)` have the same images
under both projections, then `r₁ = r₂`.

This is equivalent to the pairing map
`F(.none) → F(.left) × F(.right)` being a
monomorphism (in `Type`-valued presheaf
categories, monomorphisms are pointwise
injective). This is the separation condition
for the Grothendieck topology on `C × I^op`
generated by covering each span apex with its
two projections.

For edges in the image of
`pshRelEdgeInclusionFunctor`, this holds
because the relation `R` is a subfunctor of
`P × Q`, so the inclusion `R.ι` is monic. -/
def IsSeparatedSpan
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w)) :
    Prop :=
  ∀ (c : Cᵒᵖ)
    (r₁ r₂ : (F.obj .none).obj c),
    (F.map WalkingSpan.Hom.fst).app c r₁ =
      (F.map WalkingSpan.Hom.fst).app c r₂ →
    (F.map WalkingSpan.Hom.snd).app c r₁ =
      (F.map WalkingSpan.Hom.snd).app c r₂ →
    r₁ = r₂

/-- Every edge in the image of the inclusion
functor is separated. The pairing map is
`R.ι : R.toFunctor ⟶ pshProdPresheaf P Q`,
which is monic because `R` is a subfunctor. -/
theorem pshRelEdge_isSeparatedSpan
    (E : PshRelEdge.{u, v, w} C) :
    IsSeparatedSpan
      (pshRelEdgeSpan (C := C) E) := by
  intro c r₁ r₂ hfst hsnd
  dsimp [pshRelEdgeSpan, span,
    WidePushoutShape.mkCocone,
    pshRelFstProj,
    pshRelSndProj] at hfst hsnd
  exact Subtype.ext (Prod.ext hfst hsnd)

/-- Build a presheaf relation from a separated
span by taking the image of the pairing map
`(F.map fst, F.map snd) :
F(.none) → F(.left) × F(.right)`.

The relation at stage `c` consists of pairs
`(p, q) ∈ F(.left)(c) × F(.right)(c)` such
that there exists `r ∈ F(.none)(c)` with
`F.map(fst)(r) = p` and `F.map(snd)(r) = q`.

When the span is separated, the pairing map
is injective, so each pair `(p, q)` in the
relation has a unique witness `r`. -/
def separatedSpanRel
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w)) :
    PshRel (F.obj (.some .left))
      (F.obj (.some .right)) where
  obj c :=
    { pq |
      ∃ r : F.obj .none |>.obj c,
        (F.map WalkingSpan.Hom.fst).app c r =
          pq.1 ∧
        (F.map WalkingSpan.Hom.snd).app c r =
          pq.2 }
  map {c d} f := by
    rintro ⟨p, q⟩ ⟨r, hrp, hrq⟩
    refine ⟨F.obj .none |>.map f r, ?_, ?_⟩
    · have nat := congr_fun
        ((F.map WalkingSpan.Hom.fst).naturality
          f) r
      simp only [types_comp_apply] at nat
      rw [nat, hrp]; rfl
    · have nat := congr_fun
        ((F.map WalkingSpan.Hom.snd).naturality
          f) r
      simp only [types_comp_apply] at nat
      rw [nat, hrq]; rfl

/-- Build an edge from a span by taking
the image relation. -/
def separatedSpanToEdge
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w)) :
    PshRelEdge.{u, v, w} C :=
  { src := F.obj (.some .left)
    tgt := F.obj (.some .right)
    edge := separatedSpanRel (C := C) F }

/-- The image relation of the inclusion span
equals the original relation: the image of a
subfunctor inclusion `R.ι` is `R` itself. -/
theorem separatedSpanRel_of_inclusion
    (E : PshRelEdge.{u, v, w} C) :
    separatedSpanRel (pshRelEdgeSpan E) =
    E.edge := by
  apply Subfunctor.ext
  funext c
  ext ⟨p, q⟩
  simp only [separatedSpanRel,
    pshRelEdgeSpan, span,
    pshRelFstProj, pshRelSndProj,
    Set.mem_setOf_eq]
  constructor
  · rintro ⟨r, hrp, hrq⟩
    have : (p, q) = r.val := Prod.ext
      hrp.symm hrq.symm
    rw [this]
    exact r.prop
  · intro hpq
    exact ⟨⟨(p, q), hpq⟩, rfl, rfl⟩

/-- Round-trip: `separatedSpanToEdge` applied
to the inclusion span of an edge recovers the
original edge. -/
theorem separatedSpanToEdge_inclusion
    (E : PshRelEdge.{u, v, w} C) :
    separatedSpanToEdge
      (pshRelEdgeSpan (C := C) E) = E := by
  simp only [separatedSpanToEdge,
    pshRelEdgeSpan, span]
  exact congrArg (VertEdge.mk E.src E.tgt)
    (separatedSpanRel_of_inclusion E)

/-- The pairing map from the span apex to
the image relation's total presheaf. Sends
`r ∈ F(.none)(c)` to
`((F.map fst)(r), (F.map snd)(r))` with the
witness `r` itself. -/
def separatedSpanPairingMap
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w)) :
    F.obj .none ⟶
    (separatedSpanRel (C := C) F).toFunctor
    where
  app c r :=
    ⟨((F.map WalkingSpan.Hom.fst).app c r,
      (F.map WalkingSpan.Hom.snd).app c r),
     ⟨r, rfl, rfl⟩⟩
  naturality c d f := by
    ext r
    apply Subtype.ext
    apply Prod.ext
    · exact congr_fun
        ((F.map WalkingSpan.Hom.fst).naturality
          f) r
    · exact congr_fun
        ((F.map WalkingSpan.Hom.snd).naturality
          f) r

/-- For a separated span, the pairing map is
injective at each stage: if two elements have
the same image under both projections, they
are equal. -/
theorem separatedSpanPairingMap_injective
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w))
    (hF : IsSeparatedSpan (C := C) F)
    (c : Cᵒᵖ) :
    Function.Injective
      ((separatedSpanPairingMap F).app c) := by
  intro r₁ r₂ heq
  have heq' := congr_arg Subtype.val heq
  exact hF c r₁ r₂
    (congr_arg Prod.fst heq')
    (congr_arg Prod.snd heq')

/-- The pairing map is surjective: every element
of the image relation has a preimage in the
span apex (by definition of the image). -/
theorem separatedSpanPairingMap_surjective
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w))
    (c : Cᵒᵖ)
    (x : (separatedSpanRel (C := C) F).toFunctor.obj
      c) :
    ∃ r : (F.obj .none).obj c,
      (separatedSpanPairingMap F).app c r =
        x := by
  obtain ⟨⟨p, q⟩, ⟨r, hrp, hrq⟩⟩ := x
  exact ⟨r, Subtype.ext
    (Prod.ext hrp hrq)⟩

/-- The separation reflector `pshRelEdgeSepObj`
applied to an inclusion span gives back the
original edge: the image of a subfunctor
inclusion is the subfunctor itself. -/
theorem pshRelEdgeSepObj_inclusion
    (E : PshRelEdge.{u, v, w} C) :
    pshRelEdgeSepObj (C := C)
      (pshRelEdgeSpan E) = E := by
  simp only [pshRelEdgeSepObj,
    pshRelEdgeSpan, span]
  congr 1
  apply Subfunctor.ext; funext c; ext ⟨p, q⟩
  simp only [Subfunctor.range, Set.mem_range,
    pshProdLift, FunctorToTypes.prod.lift]
  constructor
  · rintro ⟨r, hr⟩
    have hp := congr_arg Prod.fst hr
    have hq := congr_arg Prod.snd hr
    dsimp at hp hq
    rw [← hp, ← hq]
    exact r.prop
  · intro hpq
    exact ⟨⟨(p, q), hpq⟩, rfl⟩

/-- Separated spans map to themselves under the
separation reflector: the reflector unit is a
pointwise injection at the apex, and every pair
in the image has a witness.

The separation condition is equivalent to the
pairing map `F(.none) → F(.left) × F(.right)`
being monic. The reflector replaces the apex
with the image of this map; when the map is
monic, the image is isomorphic to the original
apex (though constructing the inverse requires
extracting witnesses from `Set.range`, which
stores them propositionally).

The reflector `pshRelEdgeSepFunctor` together
with the fully faithful inclusion and
`pshRelEdgeSepObj_inclusion` establishes
`PshRelEdge C` as the reflective subcategory
of separated spans in `WalkingSpan ⥤ PSh(C)`.
-/
theorem separatedSpan_unit_injective
    (F : WalkingSpan ⥤ (Cᵒᵖ ⥤ Type w))
    (hF : IsSeparatedSpan (C := C) F)
    (c : Cᵒᵖ) :
    Function.Injective
      ((pshRelEdgeSepUnit F).app .none
        |>.app c) := by
  intro r₁ r₂ heq
  have heq' := congr_arg Subtype.val heq
  simp only [pshRelEdgeSepUnit, spanHomMk,
    pshProdLift,
    FunctorToTypes.prod.lift] at heq'
  exact hF c r₁ r₂
    (congr_arg Prod.fst heq')
    (congr_arg Prod.snd heq')

section BarrAdjunctionAgreement

/-- The functor `P ↦ P + B` for a fixed
presheaf `B`, as a covariant endofunctor. -/
def pshCoprodRightFunctor
    (B : Cᵒᵖ ⥤ Type w) :
    (Cᵒᵖ ⥤ Type w) ⥤ (Cᵒᵖ ⥤ Type w) where
  obj P := pshCoprodPresheaf P B
  map {P₁ P₂} f :=
    pshCoprodDesc
      (f ≫ pshCoprodInl P₂ B)
      (pshCoprodInr P₂ B)
  map_id P := by
    ext c x; match x with
    | Sum.inl _ => rfl
    | Sum.inr _ => rfl
  map_comp f g := by
    ext c x; match x with
    | Sum.inl _ => rfl
    | Sum.inr _ => rfl

/-- The Barr lift of the coproduct functor
`(- + B)` at a relation `R` equals the
coproduct relation `pshRelCoprod R (pshRelId B)`.

This shows that the Barr lift agrees with
the adjunction lift (which produces
`pshRelEdgeCoprod`) when the fixed argument
carries the identity relation. -/
theorem pshBarrLiftRel_coprodRight
    {P Q B : Cᵒᵖ ⥤ Type w}
    (R : PshRel P Q) :
    pshBarrLiftRel
      (pshCoprodRightFunctor (C := C) B)
      R =
    pshRelCoprod R (pshRelId B) := by
  apply Subfunctor.ext; funext c
  ext ⟨pq₁, pq₂⟩
  simp only [pshBarrLiftRel, pshBarrLift,
    pshProdOverToRel, Subfunctor.range,
    Set.mem_range, Over.mk_hom,
    FunctorToTypes.prod.lift,
    pshCoprodRightFunctor,
    pshRelCoprod, pshRelId,
    Set.mem_setOf_eq]
  constructor
  · rintro ⟨r, hr⟩
    have h₁ := congr_arg Prod.fst hr
    have h₂ := congr_arg Prod.snd hr
    dsimp [pshCoprodPresheaf] at h₁ h₂
    match r with
    | Sum.inl r' =>
      rw [← h₁, ← h₂]; exact r'.prop
    | Sum.inr b =>
      rw [← h₁, ← h₂]; rfl
  · intro h
    match pq₁, pq₂, h with
    | Sum.inl p, Sum.inl q, h =>
      exact ⟨Sum.inl ⟨(p, q), h⟩, rfl⟩
    | Sum.inr b₁, Sum.inr b₂, h =>
      exact ⟨Sum.inr b₁,
        congr_arg (fun x => (Sum.inr b₁,
          Sum.inr x)) h⟩

end BarrAdjunctionAgreement

section CartesianClosedInstances

variable {C : Type u} [Category.{v} C]

/-- The exponential right adjoint functor for
a fixed edge `A`: sends `B` to
`pshRelEdgeExp A B` and morphisms to the
appropriate induced maps via post-composition
currying. The universe `w = max u v` is
required for the exponential structure. -/
def pshRelEdgeIhom
    (A : PshRelEdge.{u, v, max u v} C) :
    PshRelEdge.{u, v, max u v} C ⥤
    PshRelEdge.{u, v, max u v} C where
  obj B := pshRelEdgeExp A B
  map f := pshRelEdgeCurry
    (pshRelEdgeEval A _ ≫ f)
  map_id B := by
    change pshRelEdgeCurry
      (pshRelEdgeEval A B ≫
        𝟙 (B : PshRelEdge.{u, v, max u v} C)) =
      𝟙 _
    rw [Category.comp_id]
    change pshRelEdgeCurry
      (pshRelEdgeUncurry
        (𝟙 (pshRelEdgeExp A B))) =
      𝟙 (pshRelEdgeExp A B)
    exact pshRelEdgeCurry_uncurry _
  map_comp {B₁ B₂ B₃} f g := by
    have inj : ∀ {X Y : PshRelEdge.{u, v,
        max u v} C}
        (a b : X ⟶ pshRelEdgeExp A Y),
        pshRelEdgeUncurry a =
          pshRelEdgeUncurry b → a = b :=
      fun a b h =>
        (pshRelEdgeCurry_uncurry a).symm.trans
          (congrArg pshRelEdgeCurry h
            |>.trans
            (pshRelEdgeCurry_uncurry b))
    apply inj
    rw [pshRelEdgeUncurry_curry,
      pshRelEdgeUncurry_curry_comp,
      Category.assoc]

instance pshRelEdgeBraided
    (C : Type u) [Category.{v} C] :
    BraidedCategory
      (PshRelEdge.{u, v, w} C) :=
  BraidedCategory.ofCartesianMonoidalCategory

instance pshRelEdgeSymmetric
    (C : Type u) [Category.{v} C] :
    SymmetricCategory
      (PshRelEdge.{u, v, w} C) :=
  CartesianMonoidalCategory.toSymmetricCategory

open MonoidalCategory in
/-- Each edge `A` in `PshRelEdge C` is closed:
`tensorLeft A` has `pshRelEdgeIhom A` as
right adjoint. The adjunction uses the
braiding `A ⊗ B ≅ B ⊗ A` to match the
`tensorLeft` convention with our curry
convention `pshRelEdgeProd B A ⟶ C ↔
B ⟶ pshRelEdgeExp A C`. -/
instance pshRelEdgeClosed
    (A : PshRelEdge.{u, v, max u v} C) :
    Closed A where
  rightAdj := pshRelEdgeIhom A
  adj := Adjunction.mkOfHomEquiv
    { homEquiv := fun B D =>
        { toFun := fun (f : A ⊗ B ⟶ D) =>
            pshRelEdgeCurry (C := C)
              ((β_ B A).hom ≫ f)
          invFun := fun g =>
            (β_ B A).inv ≫
              pshRelEdgeUncurry g
          left_inv := fun f => by
            simp only [Iso.inv_hom_id_assoc,
              pshRelEdgeUncurry_curry]
          right_inv := fun g => by
            dsimp only []
            rw [Iso.hom_inv_id_assoc]
            exact pshRelEdgeCurry_uncurry g }
      homEquiv_naturality_right := by
        intro X Y Y' f g
        simp only [Equiv.coe_fn_mk]
        symm
        have inj := fun
            (a b : X ⟶ pshRelEdgeExp A Y') =>
          fun (h : pshRelEdgeUncurry a =
            pshRelEdgeUncurry b) =>
          (pshRelEdgeCurry_uncurry a).symm.trans
            (congrArg pshRelEdgeCurry h
              |>.trans
              (pshRelEdgeCurry_uncurry b))
        apply inj
        change pshRelEdgeUncurry
          (pshRelEdgeCurry ((β_ X A).hom ≫ f) ≫
            pshRelEdgeCurry
              (pshRelEdgeEval A Y ≫ g)) = _
        rw [pshRelEdgeUncurry_curry_comp,
          pshRelEdgeUncurry_curry,
          Category.assoc] }

/-- `PshRelEdge C` is monoidal closed (at
universe `w = max u v`): every object is
closed. -/
instance pshRelEdgeMonoidalClosed
    (C : Type u) [Category.{v} C] :
    MonoidalClosed
      (PshRelEdge.{u, v, max u v} C) where
  closed A := pshRelEdgeClosed A

end CartesianClosedInstances

end GebLean
