import VersoManual
import GebLeanDocs.Bibliography
import GebLean.Ramified.AlgSig
import GebLean.Ramified.Algebras

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

/-! # Free algebras and recurrence

Part I chapter 1 of the ramified-recurrence manual. See
`docs/superpowers/specs/2026-07-22-verso-ramified-manual-design.md`
section 4.1.
-/

#doc (Manual) "Free algebras and recurrence" =>

Ramified recurrence restricts a schema that is unrestricted to begin with.
This chapter fixes the unrestricted schema: the signatures that generate
free algebras, the recurrence over such an algebra, the vocabulary for its
positions, the three fragments of the schema, and the classification of
algebras against which the complexity results of Part I chapter 6 are
stated. The presentation transcribes Leivant III section 2.1
{citep leivant3}[].

# Signatures and free algebras

A free algebra is generated by a finitary signature: a type of constructor
labels together with an arity for each label. {name GebLean.Ramified.AlgSig}`AlgSig`
records exactly that, as a field `B` of labels and a field `ar` assigning
each label a natural number.

{name GebLean.Ramified.FreeAlg}`FreeAlg A` is the algebra the signature `A`
generates: the finite terms built from the labels of `A`, each applied to as
many subterms as its arity states. {name GebLean.Ramified.FreeAlg.mk}`FreeAlg.mk`
is the generic constructor, taking a label `b` together with a function from
`Fin (A.ar b)` into the carrier.

Throughout the manual the generated algebra is assumed infinite: the
signature carries at least one label of arity zero and at least one of
positive arity. A signature without a nullary label generates the empty
algebra, and one without a positive-arity label generates a finite one, so
neither supports a recurrence with anything to recur on. Leivant III states
the assumption as a standing convention on the algebras considered; the Lean
development carries it as a hypothesis on the results that need it rather
than as a field of {name GebLean.Ramified.AlgSig}`AlgSig`, so that the type
of signatures stays free of proof obligations.

# The recurrence schema

Leivant III eq. (1) defines a function over a free algebra by one equation
per constructor label: the value at a term is given in terms of the term's
label, the parameters of the definition, the term's immediate subterms, and
the values already computed at those subterms. Its Lean form is
{name GebLean.Ramified.FreeAlg.recurse}`FreeAlg.recurse`.

The declaration names only the first of the four positions of its
step-function argument `g`, and two of the remaining three differ only in
codomain. The presentation below names all four; the names are internal to
`g`'s type, and the type is otherwise the declaration's own.

```signature
GebLean.Ramified.FreeAlg.recurse
    {A : GebLean.Ramified.AlgSig} {P C : Type}
    (g : (label : A.B) → (parameters : P) →
      (subterms : Fin (A.ar label) → GebLean.Ramified.FreeAlg A) →
      (results : Fin (A.ar label) → C) → C) :
    P → GebLean.Ramified.FreeAlg A → C
```

The argument `g` is the family of {deftech}[step functions], one per
constructor label; Leivant III writes the family as `g_{c_i}` and calls its
members the recurrence functions.

{margin}[First position of `g`: the label whose equation is being given.]
`label` ranges over the {deftech}[constructor labels] of `A`, Leivant III's
`c_i`. The schema supplies one equation for each.

{margin}[Second position of `g`: the data held fixed across the recursion.]
`parameters` carries the {deftech}[recurrence parameters], Leivant III's
vector `x`. They are passed unchanged to every recursive call, which is why
they occur to the left of the algebra argument in the result type
`P → FreeAlg A → C`.

{margin}[Third position of `g`: the immediate components of the recurrence
argument.]
`subterms` supplies the {deftech}[subterms] `a_1, …, a_{r_i}` of the
{deftech}[recurrence argument] — the value `FreeAlg.mk label subterms` at
which the equation applies. A step function that reads this position sees
the term it is destructing, not only what has been computed from it, which
makes the schema a paramorphism rather than a fold.

{margin}[Fourth position of `g`: the values already computed.]
`results` supplies the {deftech}[recursive results] `φ_1, …, φ_{r_i}`, the
value of the recurrence at each subterm. Leivant III calls them the critical
arguments.

The equation itself is
{name GebLean.Ramified.FreeAlg.recurse_mk}`FreeAlg.recurse_mk`, which states
that the recurrence at `FreeAlg.mk b sub` is the step function at `b`
applied to the parameters, the subterms `sub`, and the recurrence's own
values at the subterms. It holds definitionally.

# Three fragments

Leivant III section 2.1 names three fragments of the schema, each obtained
by withholding one of the positions from the {tech}[step functions].

A recurrence is {deftech}[monotonic] when its step functions do not read
`subterms`: the value at a term depends on the term only through the
{tech}[recursive results]. This is the fold fragment of the paramorphism.

It is {deftech}[closed] when there are no {tech}[recurrence parameters], so
`P` may be taken to be the unit type.

It is {deftech}[flat] when its step functions do not read `results`: nothing
computed at a subterm reaches the value at the term, so the schema performs
a case distinction on the outermost constructor rather than a recursion.

Part I chapter 4 gives the ramified schema in a monotonic form, Leivant III
eq. (4), and a flat form, eq. (5).

# Word algebras and tree algebras

The complexity readings of Part I chapter 6 turn on the arities a signature
admits, which govern how a term's size grows with its height.

A {deftech}[monadic word algebra] has one nullary label and exactly one
label of arity one. Its terms form a chain, so the algebra is a copy of the
natural numbers; {name GebLean.Ramified.natAlgSig}`natAlgSig`, the signature
`1 + X`, is the instance carried by the development.

A {deftech}[polyadic word algebra] has one nullary label and several labels
of arity one. Its terms are the words over the alphabet of unary labels;
{name GebLean.Ramified.binWordAlgSig}`binWordAlgSig`, the signature
`1 + 2X`, is the binary case. As with the monadic case, a term of height `h`
has exactly `h` proper subterms.

A {deftech}[tree algebra] admits a label of arity two or more, so its terms
branch: {name GebLean.Ramified.treeAlgSig}`treeAlgSig`, the signature
`1 + X²`, generates the binary trees, in which a term of height `h` may
carry exponentially many subterms in `h`. Part I chapter 6 states the
complexity results separately for the three cases, and records the
cost-model caveat that attaches to the third.
