import VersoManual
import GebLeanDocs.Bibliography
import GebLean.Ramified.AlgSig
import GebLean.Ramified.Algebras
import GebLean.Ramified.SortedSig
import GebLean.Ramified.RType

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

/-! # Signatures, free algebras, ramified types

Part II chapter 2 of the ramified-recurrence manual. See
`docs/superpowers/specs/2026-07-22-verso-ramified-manual-design.md`
section 4.2.
-/

#doc (Manual) "Signatures, free algebras, ramified types" =>

This chapter is the reference counterpart to Part I chapters 1 and 3: it
renders the declarations of `GebLean/Ramified/AlgSig.lean`,
`GebLean/Ramified/Algebras.lean`, `GebLean/Ramified/SortedSig.lean`, and
`GebLean/Ramified/RType.lean` underlying the vocabulary those chapters
introduce. Each declaration's own doc comment states its content; the prose
here places each in relation to its neighbours.

# Free-algebra signatures

A free-algebra signature names constructor labels with their arities; its
polynomial endofunctor presents that data as a `PolyEndo`, whose `PolyFix`
W-type is the free algebra generated by a single generic constructor.

{docstring GebLean.Ramified.AlgSig}

{docstring GebLean.Ramified.AlgSig.polyEndo}

{docstring GebLean.Ramified.FreeAlg}

{docstring GebLean.Ramified.FreeAlg.mk}

# The recurrence over a free algebra

The recurrence over a free algebra is a paramorphism: its step functions see
the parameters, the subterms of the recurrence argument, and the recursive
results; it reduces at each constructor node to the step function applied to
those three.

{docstring GebLean.Ramified.FreeAlg.recurse}

{docstring GebLean.Ramified.FreeAlg.recurse_mk}

# The monadic word algebra

{docstring GebLean.Ramified.natAlgSig}

{docstring GebLean.Ramified.natToFreeAlg}

{docstring GebLean.Ramified.freeAlgToNat}

Two theorems state that {name GebLean.Ramified.natToFreeAlg}`natToFreeAlg` and
{name GebLean.Ramified.freeAlgToNat}`freeAlgToNat` are mutually inverse.

{docstring GebLean.Ramified.freeAlgToNat_natToFreeAlg}

{docstring GebLean.Ramified.natToFreeAlg_freeAlgToNat}

The pair packages as a single equivalence, whose two directions unfold to the
functions above.

{docstring GebLean.Ramified.natFreeAlgEquiv}

{docstring GebLean.Ramified.natFreeAlgEquiv_apply}

{docstring GebLean.Ramified.natFreeAlgEquiv_symm_apply}

# The polyadic word algebra and the tree algebra

{name GebLean.Ramified.binWordAlgSig}`binWordAlgSig` and
{name GebLean.Ramified.treeAlgSig}`treeAlgSig` are instances of the
{tech}[polyadic word algebra] and {tech}[tree algebra] classes, alongside the
{tech}[monadic word algebra] instance
{name GebLean.Ramified.natAlgSig}`natAlgSig` above. Part I chapter 6 states
complexity readings against the monadic and polyadic classes and explicitly
declines one against the tree-algebra class, on cost-model grounds.

{docstring GebLean.Ramified.binWordAlgSig}

{docstring GebLean.Ramified.treeAlgSig}

Each signature's carrier has constructors that build `FreeAlg` values
directly, carrying no r-type sort of their own.

{docstring GebLean.Ramified.binEmpty}

{docstring GebLean.Ramified.binCons}

{docstring GebLean.Ramified.treeLeaf}

{docstring GebLean.Ramified.treeNode}

Each carrier also carries one {tech}[monotonic] recurrence and one
{tech}[flat] recurrence, built from
{name GebLean.Ramified.RIdent}`RIdent`, the schema-identifier type
{name GebLean.Ramified.RIdent.mrec}`RIdent.mrec` and
{name GebLean.Ramified.RIdent.frec}`RIdent.frec` construct — Part II
chapter 4's subject. {name GebLean.Ramified.binLength}`binLength` and
{name GebLean.Ramified.treeSize}`treeSize` are the {tech}[monotonic]
instances; {name GebLean.Ramified.binTail}`binTail` and
{name GebLean.Ramified.treeLeftChild}`treeLeftChild` are the {tech}[flat]
ones. Each is typed at {tech}[object type]s built from the base type: the
monotonic recurrences take their recurrence argument at
`RType.omega RType.o`, the flat ones at `RType.o`, and all four output
`RType.o`.

{docstring GebLean.Ramified.binLength}

{docstring GebLean.Ramified.binTail}

{docstring GebLean.Ramified.treeSize}

{docstring GebLean.Ramified.treeLeftChild}

# Morphisms of free-algebra signatures

A morphism of free-algebra signatures transports one carrier into another
along a {tech}[constructor label] map that preserves arities.

{docstring GebLean.Ramified.AlgSigHom}

{docstring GebLean.Ramified.freeAlgMap}

# Multi-sorted signatures

{name GebLean.Ramified.SortedSig}`SortedSig` moves from the single-sorted
free-algebra signatures above to signatures over an explicit sort type, the
format Part II chapter 3's Lawvere-theory layer builds on.
{name GebLean.Ramified.SortedSig.sum}`SortedSig.sum` assembles two
signatures over the same sorts by disjoint union of their operations.
{name GebLean.Ramified.constructorSig}`constructorSig` is the bridge between
the free-algebra and multi-sorted formats: it reads a free-algebra signature
back as a multi-sorted one, with one operation per {tech}[object type] and
{tech}[constructor label].

{docstring GebLean.Ramified.SortedSig}

{docstring GebLean.Ramified.SortedSig.sum}

{docstring GebLean.Ramified.constructorSig}

# Ramified types as a free algebra

The {tech}[r-type]s themselves are generated as a free algebra over a
three-label signature, reusing every declaration of the first two
sections at a new instance.

{docstring GebLean.Ramified.RTypeShape}

{docstring GebLean.Ramified.rTypeSig}

{docstring GebLean.Ramified.RType}

{docstring GebLean.Ramified.RType.o}

{docstring GebLean.Ramified.RType.arrow}

{docstring GebLean.Ramified.RType.omega}

# Object types, tower sorts, and the standard denotation

The object-type predicate marks the r-types eligible to serve as a recurrence
argument or output: the base type and every `Omega`-type.

{docstring GebLean.Ramified.RType.IsObj}

The tower sorts are the chain of {tech}[`Omega`-type]s built from
{name GebLean.Ramified.RType.o}`RType.o` alone; the {tech}[tier] of a tower
sort is the iteration count.

{docstring GebLean.Ramified.RType.tower}

{docstring GebLean.Ramified.RType.IsTower}

A further predicate classifies the {tech}[r-type]s with no `Omega` anywhere in
their structure, the simple types of Leivant III section 4.2.

{docstring GebLean.Ramified.RType.IsSimple}

The standard denotation sends every {tech}[object type] to a copy of a fixed
carrier and every function type to a function space; the theorem following it
states the object-type case.

{docstring GebLean.Ramified.RType.interp}

{docstring GebLean.Ramified.RType.interp_isObj}
