import GebLean.PolyAlg

/-!
# Free-algebra signatures and their recurrence

Finitary presentation data for the algebra axis of ramified recurrence.
A free-algebra signature `AlgSig` names its constructor labels and their
arities; its polynomial signature endofunctor `AlgSig.polyEndo` presents
that data over a single sort; and the free algebra `FreeAlg` it generates
is the `PolyFix` W-type, the initial algebra of that endofunctor.
`FreeAlg.recurse` is the recurrence over a free algebra: a paramorphism
whose step functions see the parameters, the subterms of the recurrence
argument, and the recursive results.

These definitions are novel packaging: they present the free-algebra
conventions of Leivant III section 2.1 through this development's
polynomial-endofunctor stack (decision 8: every recursive type is a
W-type of a `PolyEndo`), rather than through a Lean-native inductive.
The underlying conventions transcribe Leivant III section 2.1.

## Main definitions

* `AlgSig` — a free-algebra signature: constructor labels with arities.
* `AlgSig.polyEndo` — the polynomial signature endofunctor of a
  signature, over the one-sort domain `PUnit`.
* `FreeAlg` — the free algebra: the `PolyFix` W-type of `AlgSig.polyEndo`.
* `FreeAlg.mk` — the generic constructor: a label with its subterms.
* `FreeAlg.recurse` — the recurrence over a free algebra (Leivant III
  eq. (1)), realized as a paramorphism.
* `natAlgSig` — the `1 + X` word signature: one 0-ary and one unary
  constructor.
* `natToFreeAlg`, `freeAlgToNat` — the numeric reading of the standard
  carrier `FreeAlg natAlgSig`, a copy of the naturals.

## Main statements

* `freeAlgToNat_natToFreeAlg` — the numeric reading is a left inverse of
  the encoding; the full equivalence `FreeAlg natAlgSig ≃ ℕ` is packaged as
  `natFreeAlgEquiv` (`GebLean/Ramified/Algebras.lean`).

## References

The recurrence over a free algebra and the standing convention on
infinite algebras (a 0-ary and a positive-arity constructor) follow
D. Leivant, "Ramified recurrence and computational complexity III:
Higher type recurrence and elementary complexity", Annals of Pure and
Applied Logic 96 (1999) 209-229, DOI `10.1016/S0168-0072(98)00040-2`,
section 2.1.

## Tags

ramified recurrence, free algebra, signature, polynomial functor,
W-type, paramorphism
-/

namespace GebLean.Ramified

open CategoryTheory

/-- A free-algebra signature: constructor labels with arities
(Leivant III section 2.1; the paper's standing convention — an infinite
algebra has a 0-ary and a positive-arity constructor — is carried as
hypotheses on results that need it, not baked in). -/
structure AlgSig where
  /-- The type of constructor labels. -/
  B : Type
  /-- The arity of each constructor label: the number of subterms it
  takes. -/
  ar : B → Nat

/-- The polynomial signature endofunctor of a free-algebra signature:
constructor labels as shapes, arity positions as directions, over the
one-sort domain `PUnit` (decision 8: the algebra axis is presented by
its polynomial signature functor). At the single sort, the positions are
the constructor labels `A.B`, and each label `b` has `A.ar b` directions,
each pointing back to the single sort. Novel packaging of Leivant III
section 2.1's free-algebra conventions through this development's
polynomial-endofunctor stack. -/
def AlgSig.polyEndo (A : AlgSig) : PolyEndo PUnit.{1} :=
  fun _ => ccrObjMk fun b : A.B => Over.mk fun _ : Fin (A.ar b) => PUnit.unit

/-- The free algebra over `A`: the `PolyFix` W-type of `A.polyEndo`, its
initial algebra (`polyFixAlg_isInitial` in `GebLean/PolyAlg.lean`). Realizes
the free algebra generated by the signature (Leivant III section 2.1) as
a W-type (decision 8), not a Lean-native inductive. -/
def FreeAlg (A : AlgSig) : Type := PolyFix A.polyEndo PUnit.unit

/-- The generic constructor of the free algebra: a constructor label `b`
together with its subterms (the immediate components of the recurrence
argument). Derived from the `PolyFix` constructor. -/
def FreeAlg.mk {A : AlgSig} (b : A.B) (subterms : Fin (A.ar b) → FreeAlg A) :
    FreeAlg A :=
  PolyFix.mk PUnit.unit b subterms

/-- The recurrence over a free algebra (Leivant III section 2.1,
eq. (1)): one step function per constructor label, seeing the parameters,
the subterms of the recurrence argument, and the recursive results. A
paramorphism — the step functions see the subterms as well as the
recursive results — realized by the dependent eliminator `PolyFix.ind`
(`GebLean/PolyAlg.lean`) with the parameters threaded through the
`P → C` function carrier. -/
def FreeAlg.recurse {A : AlgSig} {P C : Type}
    (g : (b : A.B) → P → (Fin (A.ar b) → FreeAlg A) → (Fin (A.ar b) → C) → C) :
    P → FreeAlg A → C :=
  fun p t =>
    PolyFix.ind (P := A.polyEndo) (motive := fun {_} _ => P → C)
      (fun i children ih q => g i q children fun e => ih e q) t p

/-- The reduction rule of the free-algebra recurrence at a constructor node
(Leivant III section 2.1, eq. (1)): `FreeAlg.recurse g p (FreeAlg.mk b sub)`
unfolds to the step function `g` at `b` applied to the parameter `p`, the
subterms `sub`, and the recursive results on the subterms. The `PolyFix.ind`
iota rule at a `FreeAlg.mk` node; holds definitionally. -/
theorem FreeAlg.recurse_mk {A : AlgSig} {P C : Type}
    (g : (b : A.B) → P → (Fin (A.ar b) → FreeAlg A) → (Fin (A.ar b) → C) → C)
    (p : P) (b : A.B) (sub : Fin (A.ar b) → FreeAlg A) :
    FreeAlg.recurse g p (FreeAlg.mk b sub)
      = g b p sub (fun e => FreeAlg.recurse g p (sub e)) := rfl

/-- The `1 + X` signature (monadic word algebra): one 0-ary constructor
(`false`) and one unary constructor (`true`). Used from Phase 2 onward;
the other canonical instances arrive in Phase 3. -/
def natAlgSig : AlgSig := ⟨Bool, fun b => cond b 1 0⟩

/-- A natural number as an element of the standard carrier `FreeAlg natAlgSig`:
`0` is the nullary constructor and `n + 1` the unary constructor applied to `n`.
The `ofNat` direction of the equivalence `natFreeAlgEquiv : FreeAlg natAlgSig ≃
ℕ` (`GebLean/Ramified/Algebras.lean`). -/
def natToFreeAlg : Nat → FreeAlg natAlgSig
  | 0 => FreeAlg.mk false finZeroElim
  | n + 1 => FreeAlg.mk true (fun _ => natToFreeAlg n)

/-- An element of the standard carrier `FreeAlg natAlgSig` as the natural number
counting its unary constructors. The `toNat` direction of the equivalence
`natFreeAlgEquiv : FreeAlg natAlgSig ≃ ℕ` (`GebLean/Ramified/Algebras.lean`).
Realized by the free-algebra recurrence `FreeAlg.recurse`. -/
def freeAlgToNat (t : FreeAlg natAlgSig) : Nat :=
  FreeAlg.recurse (A := natAlgSig) (P := Unit)
    (fun b _ _sub rec => match b with
      | false => 0
      | true => rec ⟨0, Nat.zero_lt_one⟩ + 1) () t

/-- The numeric reading of the standard carrier `FreeAlg natAlgSig` is a left
inverse of the encoding: `freeAlgToNat (natToFreeAlg n) = n`. Together with
`natToFreeAlg_freeAlgToNat` (`GebLean/Ramified/Algebras.lean`) this makes the
numeric reading a two-sided inverse. -/
@[simp] theorem freeAlgToNat_natToFreeAlg (n : Nat) :
    freeAlgToNat (natToFreeAlg n) = n := by
  induction n with
  | zero => rfl
  | succ n ih => exact congrArg (· + 1) ih

end GebLean.Ramified
